### ISSUE TITLE
check_syntax:  Loop, not a table type

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1002]
In older releases (and in a lot of SAP code) tables are defined using "occurs". That they are a table-type is not mandatory.
`DATA: t_fbstab LIKE  tfkfbc OCCURS 0 WITH HEADER LINE.`

If that needs to be forced, then this should be done in a separate check.

**Comment by larshp** [comment]
I think its a bug in abaplint, OCCURS 0 should make it a table

**Comment by larshp** [comment]
try again, 2.37.1 released

**Comment by ed-holland** [comment]
![image](https://user-images.githubusercontent.com/53995991/85951601-6c1e1380-b964-11ea-8aa8-8e5ce5d5a2ee.png)

Issue is still there.

./src/xbp/#redwood#xbprsdbspva.prog.abap[200, 5]                         - Loop, not a table type (check_syntax)
 ./src/xbp/#redwood#xbprsdbspva.prog.abap[212, 5]                         - Read table, not a table type (check_syntax)
![image](https://user-images.githubusercontent.com/53995991/85951561-1fd2d380-b964-11ea-8cf9-4fb4647ba8b0.png)

**Comment by larshp** [comment]
reproduced,

```abap
FORM foo TABLES bar.
  READ TABLE bar INDEX 1 TRANSPORTING NO FIELDS.
ENDFORM.
```

![image](https://user-images.githubusercontent.com/5888506/85953465-c91fc680-b970-11ea-95ba-6d330a4ed7a0.png)

**Comment by ed-holland** [comment]
Might be a relation with #1004 .

**Comment by larshp** [comment]
nah, its a different example, see railroad https://syntax.abaplint.org/?filter=form#/expression/FormTables

**Comment by larshp** [comment]
try again, latest version

**Comment by ed-holland** [comment]
Still getting issues (maybe from other check parts):

 ./src/isu/#redwood#1isu.fugr.lfkkaktiv2f01.abap[2576, 3]                 - Read table, not a table type (check_syntax)
 ./src/isu/#redwood#1isu.fugr.lfkkaktiv2f01.abap[2578, 5]                 - Not a structure (check_syntax)
![image](https://user-images.githubusercontent.com/53995991/85999783-f8841100-ba0c-11ea-8711-6b7cdc9c89ec.png)

./src/isu/#redwood#1isu.fugr.lfkkaktiv2f01.abap[3010, 3]                 - Read table, not a table type (check_syntax)
 ./src/isu/#redwood#1isu.fugr.lfkkaktiv2f01.abap[3017, 3]                 - Loop, not a table type, Type error, could not resolve tfkfbc (check_syntax)
![image](https://user-images.githubusercontent.com/53995991/85999970-2ff2bd80-ba0d-11ea-81ac-27c2b1773c53.png)

**Comment by larshp** [comment]
yea, this is a "LIKE" scenario

**Comment by larshp** [comment]
try again, latest version

**Comment by ed-holland** [comment]
looks like the docker images are not being build (abaplint & backend)

**Comment by ed-holland** [comment]
Issue is fixed. Thx again.
