### ISSUE TITLE
Parser Errors on SAP original code (also our code)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1006]
We use SAP original includes in our code. This one is from IS-U. 
![image](https://user-images.githubusercontent.com/53995991/85945099-bc34b000-b93b-11ea-9d0d-0f52a14cea96.png)
The source:
![image](https://user-images.githubusercontent.com/53995991/85945107-cb1b6280-b93b-11ea-8327-63be8df1598b.png)
![image](https://user-images.githubusercontent.com/53995991/85945144-f8681080-b93b-11ea-975e-a66722774a7e.png)

 ./src/xbp/#redwood#1xbp.fugr.#redwood#xbp_event_def_get.abap[18, 5]       - Statement does not exist in ABAPv700(or a parser error), "lv_events_cnt" (parser_error)
![image](https://user-images.githubusercontent.com/53995991/85945373-a3c59500-b93d-11ea-9aa7-42620a394391.png)
![image](https://user-images.githubusercontent.com/53995991/85945395-c061cd00-b93d-11ea-8ef2-fdc4dd58fff4.png)

 ./src/xbp/#redwood#1xbp.fugr.#redwood#xbp_set_recipient.abap[25, 3]       - Statement does not exist in ABAPv700(or a parser error), "swc_container" (parser_error)
Macro is not recognized. As we extend SAP, there can be many of them.
![image](https://user-images.githubusercontent.com/53995991/85945402-c5bf1780-b93d-11ea-857a-0bd85716cf97.png)

**Comment by larshp** [comment]
`ok-code`: yea, this is really bad ABAP code, but fixable in abaplint

`data: : bar type c.`: double chaining does not work in abaplint currently, suggest removing one of the `:`s

`swc_container`: add to the abaplint configuration, like https://github.com/larshp/abapOpenChecks/blob/master/abaplint.json#L30

**Comment by ed-holland** [comment]
Are macro's currently not detected or is this because they are not part of the dependencies?

**Comment by larshp** [comment]
abaplint does not handle the scoping of the marcros properly, https://github.com/abaplint/abaplint/blob/master/docs/design/index.adoc#7-parsing-vs-standard-abap

the workaround is to add them to the configuration

**Comment by larshp** [comment]
dashes in variable names -> #1007 

double colon/chaining -> #1008

**Comment by ed-holland** [comment]
Macros added to config and are not showing up anymore

**Comment by larshp** [comment]
I think we can close this? remaining issues are covered by #1007 and #1008 

double colon will be fixed in https://github.com/abaplint/abaplint/pull/1005

**Comment by larshp** [comment]
EXPORT, try again, latest version

**Comment by ed-holland** [comment]
Tested with 2.37.2, Export issue is gone. 
Thanks.
