### ISSUE TITLE
SCI: Structures are not found although they exist

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1012]
Structures are not found although they exist.
`FUGR /JCS/BC > PROG /JCS/LBCTOP [ @33 ] 
"bapixmlogr" not found, #JCS#BC.FUGR.#JCS#LBCTOP.ABAP`
![image](https://user-images.githubusercontent.com/53995991/86012758-a77d1880-ba1e-11ea-9acb-b2fbfdbcafd1.png)

Same with Tables:
`FUGR /JCS/BC > PROG /JCS/LBCTOP [ @53 ] 
"tadir" not found, #JCS#BC.FUGR.#JCS#LBCTOP.ABAP`
![image](https://user-images.githubusercontent.com/53995991/86013083-0b074600-ba1f-11ea-91a5-29e4c03f7605.png)

**Comment by larshp** [comment]
try again, latest version

**Comment by ed-holland** [comment]
Better. This type still gives an error:
`FUGR /JCS/BC > PROG /JCS/LBCTOP [ @9 ] 
Include RSXMIBAPI not found, #JCS#BC.FUGR.#JCS#LBCTOP.ABAP`
![image](https://user-images.githubusercontent.com/53995991/86031000-8d026980-ba35-11ea-8f4f-d1eaf29607b9.png)
Not sure what is the difference with the line below that does not create an error.

`FUGR /JCS/BC > PROG /JCS/LBCF91 [ @16 ] 
"txmilograw" not found, #JCS#BC.FUGR.#JCS#LBCF91.ABAP`
![image](https://user-images.githubusercontent.com/53995991/86031088-b28f7300-ba35-11ea-9274-7167d92a66e9.png)

**Comment by larshp** [comment]
reproduced, 

![image](https://user-images.githubusercontent.com/5888506/86814996-6e7a1f00-c082-11ea-8d81-19d082ede11f.png)

![image](https://user-images.githubusercontent.com/5888506/86815011-74700000-c082-11ea-980e-e318f08c9d2a.png)

**Comment by larshp** [comment]
same issue on  2.37.5,

![image](https://user-images.githubusercontent.com/5888506/86815495-037d1800-c083-11ea-8fca-b1999f8c1a6e.png)

**Comment by larshp** [comment]
the table is a bit special with .INCLUDE fields, so the error might be misleading

**Comment by larshp** [comment]
TXMILOGRAW

**Comment by larshp** [comment]
now the right dependencies are found, https://github.com/abaplint/abaplint-sci-client/pull/73

![image](https://user-images.githubusercontent.com/5888506/87220594-70cfc800-c365-11ea-9b05-69fdd8a531aa.png)

**Comment by ed-holland** [comment]
yes, but it breaks the abaplint now. To many objects probably.

**Comment by larshp** [comment]
so far I have only seen it crash due to memory

I've not spent any time optimizing memory consumption

**Comment by ed-holland** [comment]
Using this already...
export NODE_OPTIONS="--max-old-space-size=4096"
![image](https://user-images.githubusercontent.com/53995991/87223938-51df2f00-c381-11ea-9b27-7626bd792a97.png)

It is stuck a long time on MSAGs. Is there more output to get?

**Comment by larshp** [comment]
I'm not exactly sure what "Killed" means, if its an out of memory error its quite misleading

anyhow https://github.com/abaplint/abaplint-sci-client/issues/59 is solved in https://github.com/abaplint/abaplint-sci-client/pull/73, which I guess will drastically reduce the size of the MSAG XML files

**Comment by ed-holland** [comment]
The size is caused by the long-texts (see other issue). They are not required for dependencies.

**Comment by ed-holland** [comment]
As to the abaplint "kill". it is not a memory issue (gives different error). I have the feeling that we are getting a timeout somewhere. Did you specify timeouts in the nodes?

**Comment by larshp** [comment]
try again, latest version 2.37.11

**Comment by ed-holland** [comment]
I've checked again with 2.38.4

SCI:
![image](https://user-images.githubusercontent.com/53995991/88475127-79133000-cf2d-11ea-88be-12a7e2b0759f.png)

Linter also shows this include not to be found, but it exists
`./src/idoc/#redwood#1idoc.fugr.#redwood#sapl1idoc.abap[4, 3]               - Include /REDWOOD/L1IDOCTOP not found (check_include)`

But it exists
![image](https://user-images.githubusercontent.com/53995991/88475103-39e4df00-cf2d-11ea-9e0e-883eb3b44b38.png)

**Comment by ed-holland** [comment]
I've checked again with 2.38.12
Issue is still there,

**Comment by ed-holland** [comment]
Closing issue and will create new one with more specific information
