### ISSUE TITLE
structure: Expected ENDFORM at the beginning of include

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1014]
Error:
`./src/isu/#redwood#2isu.fugr.#redwood#l2isuf02.abap[1, 1]               - Expected ENDFORM (structure)`

Code:
![image](https://user-images.githubusercontent.com/53995991/86046748-1160e680-ba4e-11ea-994f-093e92a009cd.png)

**Comment by larshp** [comment]
The "expected" something errors are not super helpful, there is some kind of error somewhere else in the include

**Comment by ed-holland** [comment]
The original issue mentioned above is gone with 2.38.4

The error is still part of my errors list. They are all in SAP original code.

Example:
MV45AFST_STATISTIK_UPDATE

It seems to be related to ENHANCEMENT-SECTION.

**Comment by larshp** [comment]
try again, 2.38.5

**Comment by ed-holland** [comment]
A number of cases of this error have disappeared :-) 

The following SAP original programs have this issues still:
`
 /tmp/abaplint-DjlEbj/src/fbas/rfbibl01.prog.abap[1, 1]                     - Expected ENDFORM (structure)
 /tmp/abaplint-DjlEbj/src/va/fith_j_1tpbupl.prog.abap[1, 1]                 - Expected ENDFORM (structure)
 /tmp/abaplint-DjlEbj/src/va/mv45a_msrf03.prog.abap[1, 1]                   - Expected ENDFORM (structure)
/tmp/abaplint-DjlEbj/src/va/mv45af0b_beleg_lesen_logic.prog.abap[1, 1]     - Expected ENDFORM (structure)
 /tmp/abaplint-DjlEbj/src/va/mv45af0v_vbkd_incov_check_item.prog.abap[1, 1] - Expected ENDFORM (structure)
/tmp/abaplint-DjlEbj/src/vz/incoterm_location_assignment.prog.abap[1, 1]   - Expected ENDFORM (structure)
`

There are more, but i can not find a common issue with them. The last tow sources are very small.

**Comment by larshp** [comment]
yea, the error message is not super helpful, need to improve the message in abaplint sometime

**Comment by larshp** [comment]
ref https://github.com/abaplint/abaplint/pull/1093/commits/ae7a73f5710f481a086263aff6394595bed73524 might solve some of it

**Comment by ed-holland** [comment]
Many of the error cases are gone now. The below are left.

This one has enhancement stuff.
```
/tmp/abaplint-bMgDiM/src/va/mv45af0t_tvak-trvog_pruefen.prog.abap[1, 1]    - Expected ENDFORM (structure)
```

These do not.
```
/tmp/abaplint-bMgDiM/src/fbas/rfbibl01.prog.abap[1, 1]                     - Expected ENDFORM (structure)
/tmp/abaplint-bMgDiM/src/va/mv45a_msrf03.prog.abap[1, 1]                   - Expected ENDFORM (structure)
/tmp/abaplint-bMgDiM/src/va/mv45af0b_beleg_lesen_logic.prog.abap[1, 1]     - Expected ENDFORM (structure)
/tmp/abaplint-bMgDiM/src/va/mv45af0i_incoterm_save_check.prog.abap[1, 1]   - Expected ENDFORM (structure)
/tmp/abaplint-bMgDiM/src/va/mv45af0v_vbkd_incov_check_item.prog.abap[1, 1] - Expected ENDFORM (structure)
/tmp/abaplint-bMgDiM/src/vz/incoterm_location_assignment.prog.abap[1, 1]   - Expected ENDFORM (structure)
```

**Comment by ed-holland** [comment]
I'm sorry but the issue is still reported for the above.

**Comment by larshp** [comment]
most of them are due to 
![image](https://user-images.githubusercontent.com/5888506/89007654-6cb21d00-d309-11ea-8156-c9504ade7e9c.png)

**Comment by ed-holland** [comment]
Closing this one to create more specific issues.
