### ISSUE TITLE
structure: Expected ENDFUNCTION at beginning of function module

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1015]
Error:
` ./src/isu/#redwood#2isu.fugr.#redwood#ma_structure_data.abap[1, 1]      - Expected ENDFUNCTION (structure)`

Code:
![image](https://user-images.githubusercontent.com/53995991/86046898-4d944700-ba4e-11ea-8064-6a56f80a4b70.png)

**Comment by larshp** [comment]
The "expected" something errors are not super helpful, there is typically some kind of error somewhere else in the include

**Comment by larshp** [comment]
the easiest way to find the right error is to copy paste the code into https://playground.abaplint.org, to find a smaller example reproducing the issue

**Comment by ed-holland** [comment]
Used 2.38.4

Issue is resolved. Thanks again.
