### ISSUE TITLE
Component "tfill" not found in structure

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1016]
`PROG /REDWOOD/XBPRSDBSPVA [ @199 ] 
Component "tfill" not found in structure, #REDWOOD#XBPRSDBSPVA.PROG.ABAP`
![image](https://user-images.githubusercontent.com/53995991/86046240-2ab56300-ba4d-11ea-9c3f-139323e35a79.png)

It finds the field in 197 but not in 199.

**Comment by larshp** [comment]
try again, latest abaplint version

**Comment by ed-holland** [comment]
Issue is fixed. Thanks
