### ISSUE TITLE
indentation: Expected 4 but have 6

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1019]
Error:
```
FUGR /JCS/BC > PROG /JCS/LBCU37 [ @143 ] 
Indentation problem, expected 4 spaces, #JCS#BC.FUGR.#JCS#BC_CURRENCY_CONVERSION.ABAP, indentation
```

Example (part of function): 
![image](https://user-images.githubusercontent.com/53995991/86155366-98709600-bb04-11ea-8df0-a35afca489ac.png)

**Comment by larshp** [comment]
reproduced,

```abap
CATCH SYSTEM-EXCEPTIONS arithmetic_errors = 4 OTHERS = 8.
  WRITE 'hello world'.
ENDCATCH.
```

![image](https://user-images.githubusercontent.com/5888506/86204209-3137fd80-bb67-11ea-98d6-59f8cb51f36e.png)

**Comment by larshp** [comment]
try again, latest abaplint version

**Comment by ed-holland** [comment]
Works. Thx

**Comment by ed-holland** [comment]
The issue changed. follow up issue?
![image](https://user-images.githubusercontent.com/53995991/86325104-d0302880-bc3f-11ea-906a-7df2c8ee88bf.png)
![image](https://user-images.githubusercontent.com/53995991/86325134-df16db00-bc3f-11ea-9501-488cd033efea.png)
