### ISSUE TITLE
Skip CDS generated class from CL_SADL_GTK_EXPOSURE_MPC

### ISSUE THREAD

**Issue by jrodriguez-rc** [abaplint/abaplint#1026]
Add an option to skip generated DPC classes generated for a published CDS, which inherits CL_SADL_GTK_EXPOSURE_MPC
https://github.com/jrodriguez-rc/abap-tasks-tracker/blob/master/src/zcl_ztt_c_projects.clas.abap
![image](https://user-images.githubusercontent.com/56556686/86444001-60d63980-bd10-11ea-914c-87b8f2a9703a.png)

**Comment by jrodriguez-rc** [comment]
Still fails
![image](https://user-images.githubusercontent.com/56556686/86946204-57066900-c14a-11ea-8952-0e7bc045beb5.png)

**Comment by larshp** [comment]
yea, it will be part of next release

**Comment by larshp** [comment]
try again, new version released

**Comment by jrodriguez-rc** [comment]
Fixed, thank you!
