### ISSUE TITLE
Skip BOPF generated constant interfaces

### ISSUE THREAD

**Issue by jrodriguez-rc** [abaplint/abaplint#1027]
https://github.com/jrodriguez-rc/abap-tasks-tracker/blob/master/src/zif_tt_i_projects_c.intf.abap
![image](https://user-images.githubusercontent.com/56556686/86447126-2a4eed80-bd15-11ea-9b3c-b374100c8b92.png)

I think that those interfaces can be detected by interface /BOBF/IF_LIB_CONSTANTS
![image](https://user-images.githubusercontent.com/56556686/86447189-43579e80-bd15-11ea-92be-c656077bad48.png)

**Comment by jrodriguez-rc** [comment]
Still fails:
https://github.com/jrodriguez-rc/abap-tasks-tracker/blob/master/src/zif_tt_i_tasks_c.intf.abap
![image](https://user-images.githubusercontent.com/56556686/86944581-3fc67c00-c148-11ea-8de1-bd18ea22db24.png)

**Comment by larshp** [comment]
yea, it will be part of next release

**Comment by larshp** [comment]
try again, new version released

**Comment by jrodriguez-rc** [comment]
Fixed, thank you!
