### ISSUE TITLE
keyword_case: selection screen title text-001 should be uppercase.

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1043]
![image](https://user-images.githubusercontent.com/53995991/87246600-b916e500-c44e-11ea-85e2-64eebfcbff53.png)

**Comment by larshp** [comment]
it should be upper case, from somewhere around 740~750 the pretty printer in SAP standard upper cases it

in case you want it lower case, use configure the `ignoreKeywords`,
https://rules.abaplint.org/keyword_case/

**Comment by ed-holland** [comment]
the pretty printer always makes it lowercase (740-SP23). This will become very annoying. As this issue comes from abaplint backend, the rules are set.

**Comment by larshp** [comment]
it is annoying that the SAP standard logic for pretty printing changed

the keyword "text" can be added to `ignoreKeywords` to allow either for this example

**Comment by ed-holland** [comment]
let keep it as for the moment.
