### ISSUE TITLE
XML parsing, memory usage and performance

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#1048]
currently https://www.npmjs.com/package/xml-js is used in abaplint

some of the XML files serialized by abapGit can get quite large, as everything is read into memory, and abaplint (currently) only uses very little information from the xml files

consider moving to raw
https://www.npmjs.com/package/sax
and stream the XML file contents

or one of the other ones,
https://www.npmjs.com/package/saxes

**Comment by sbcgua** [comment]
there is also https://www.npmjs.com/package/fast-xml-parser to mention. but I don't know how it compares to sax performance-wise

**Comment by larshp** [comment]
yea, it just seems like it can do much more than required

but anyhow, there is some basic research required, want low memory usage high speed(as always)

**Comment by larshp** [comment]
https://github.com/justinwilaby/sax-wasm

**Comment by larshp** [comment]
this is starting to come out as the slowest parts,

```
100% - 108.6s - Finding Issues
        48482ms check_text_elements
        25151ms xml_consistency
        24856ms check_ddic
        514ms   release_idoc

100% - 94.1s - Finding Issues
        79199ms xml_consistency
        5319ms  parser_missing_space
```

**Comment by larshp** [comment]
+ must work in browser
+ must have some typescript support

**Comment by larshp** [comment]
https://github.com/larshp/test-xml-performance

will move towards https://www.npmjs.com/package/fast-xml-parser
