### ISSUE TITLE
check_syntax: Table field not found although available in dependency repository

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1069]
The dependency project contains the table:
![image](https://user-images.githubusercontent.com/53995991/88150295-7f3d9f80-cc01-11ea-9d6c-5c2e65fac3b0.png)

Coding:
![image](https://user-images.githubusercontent.com/53995991/88150206-62a16780-cc01-11ea-8bc1-0ced1ef51938.png)

The table also shows up when running dependency list for this object.

abaplint version: 2.38.1

REF: PROG XBPTEMPVAR

**Comment by larshp** [comment]
thanks, what is the exact error message from abaplint?

**Comment by ed-holland** [comment]
![image](https://user-images.githubusercontent.com/53995991/88151057-7d281080-cc02-11ea-9a4a-8582f0fc4c41.png)
SCI also shows same message

**Comment by ed-holland** [comment]
The Issue might be more generic.
./src/ecc/#jcs#mm_lis_sel_versions_reorg.prog.abap[10, 1]                  - "rsparams" not found (check_syntax)

![image](https://user-images.githubusercontent.com/53995991/88289737-fe140480-ccf5-11ea-92c2-f7718d48262c.png)

It definitely exists in dependency project
![image](https://user-images.githubusercontent.com/53995991/88289955-50edbc00-ccf6-11ea-8a0c-64b89481b9dd.png)

**Comment by ed-holland** [comment]
I've checked again with 2.38.12
Issue resolved.
