### ISSUE TITLE
check_syntax: trdir not found

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1070]
In coding, a trdir field is referenced. The syntax check does not find the table.

![image](https://user-images.githubusercontent.com/53995991/88151170-a34db080-cc02-11ea-86c7-353a81fab64d.png)

The dependency report shows TRDIR as VIEW.

Does the linter only checks for TABLE?

abaplint version: 2.38.1

REF: PROG XBPTEMPVAR

**Comment by larshp** [comment]
yea, think it only looks for TABL right now

**Comment by ed-holland** [comment]
There are more tables not found (example)
![image](https://user-images.githubusercontent.com/53995991/88151872-82398f80-cc03-11ea-801f-d98c291a88be.png)

They also exist in dependency repository. Both are structures.

**Comment by larshp** [comment]
try again, 2.38.3

**Comment by ed-holland** [comment]
Used 2.38.4

The issue persists:
![image](https://user-images.githubusercontent.com/53995991/88474692-68f95180-cf29-11ea-9987-4b2a514db40c.png)

Rechecked the views/tables and they do exist in dependency repository

**Comment by larshp** [comment]
In the playground it does not know anything about a standard system, so the above errors are as expected

**Comment by ed-holland** [comment]
The question is why the linter does also although the dependencies are available.

**Comment by larshp** [comment]
yea

**Comment by larshp** [comment]
ref https://github.com/abaplint/abaplint/issues/1101

**Comment by larshp** [comment]
some of the above issues might have been solved?

**Comment by ed-holland** [comment]
Issue is resolved. Thx
