### ISSUE TITLE
check_syntax: Cannot read property '_text' of undefined

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1071]
Unclear what the issue is here.
SCI:
![image](https://user-images.githubusercontent.com/53995991/88156280-81a3f780-cc09-11ea-9a5e-2276ced881bd.png)
![image](https://user-images.githubusercontent.com/53995991/88156373-a0a28980-cc09-11ea-826c-4f6af050d59f.png)

![image](https://user-images.githubusercontent.com/53995991/88156522-d8a9cc80-cc09-11ea-9ce4-1f72e2975002.png)
![image](https://user-images.githubusercontent.com/53995991/88156424-b021d280-cc09-11ea-8290-4d56fff67667.png)

AbapLint:
![image](https://user-images.githubusercontent.com/53995991/88156133-47d2f100-cc09-11ea-943c-77bf2382d259.png)

**Comment by larshp** [comment]
thanks, its some internal abaplint error when reading the XMLs, should not occur looks like a bug in abaplint

**Comment by larshp** [comment]
might have been fixed

**Comment by ed-holland** [comment]
Used 2.38.4

Issue resolved. Thanks again.
