### ISSUE TITLE
SCI - unknown_types: todo

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1072]
![image](https://user-images.githubusercontent.com/53995991/88183322-9ac09e80-cc31-11ea-9c7f-ed69281d6e24.png)
![image](https://user-images.githubusercontent.com/53995991/88183342-a14f1600-cc31-11ea-9430-ba8d66f4853d.png)

The abaplint standalone run does not have this error.

The message also has a bad abap name as reference, resulting in the link not working.

**Comment by larshp** [comment]
thanks

**Comment by larshp** [comment]
STRUCTURES solved in 2.38.3

regarding DEC, the error message should be more helpful in 2.38.3

**Comment by larshp** [comment]
DEC, fixed in 2.38.4

**Comment by ed-holland** [comment]
Used 2.38.4

Issue resolved. Thanks again.
