### ISSUE TITLE
check_syntax: Not a structure, target (header lines)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1073]
![image](https://user-images.githubusercontent.com/53995991/88193607-23ddd280-cc3e-11ea-8e84-4a811a2ab45e.png)

The source:
![image](https://user-images.githubusercontent.com/53995991/88193785-5c7dac00-cc3e-11ea-8570-db0bae764b05.png)
![image](https://user-images.githubusercontent.com/53995991/88193852-6dc6b880-cc3e-11ea-9b79-7266b274342a.png)
![image](https://user-images.githubusercontent.com/53995991/88193680-3b1cc000-cc3e-11ea-9ca1-e05b9ee4e9a3.png)

Why does it not fit?

**Comment by larshp** [comment]
I think abaplint does not take the header line into account

**Comment by larshp** [comment]
think this one is fixed in  2.38.6

**Comment by ed-holland** [comment]
the above mentioned case is still there.

Another example:
`./src/ecc/#jcs#bc_dynamic_selections.prog.abap[104, 5]                     - Not a structure, target (check_syntax)`

Source:
![image](https://user-images.githubusercontent.com/53995991/88514393-4b3ff100-cfea-11ea-9739-b0e2a29970b0.png)

![image](https://user-images.githubusercontent.com/53995991/88514424-5b57d080-cfea-11ea-87ac-eaabe562d92a.png)

**Comment by larshp** [comment]
error messaging regarding INCLUDE STRUCTURE was improved yesterday, so this might give a different error message

**Comment by ed-holland** [comment]
Message is still the same.

**Comment by larshp** [comment]
reproduced as

```abap
TYPES: BEGIN OF bar,
         foo TYPE c,
       END OF bar.

DATA BEGIN OF tables_tab OCCURS 10.
INCLUDE TYPE bar.
DATA END OF tables_tab.

tables_tab-foo = 'A'.
```

**Comment by ed-holland** [comment]
Issue resolved. Thanks
