### ISSUE TITLE
check_ddic: Unknown/un-resolveable type "TTYP" kind L

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1074]
![image](https://user-images.githubusercontent.com/53995991/88196735-d2cfdd80-cc41-11ea-9014-df4685f84129.png)

![image](https://user-images.githubusercontent.com/53995991/88196978-217d7780-cc42-11ea-9c70-fc73f558046f.png)
![image](https://user-images.githubusercontent.com/53995991/88197028-322ded80-cc42-11ea-97ac-d90cff49d04d.png)

Can this type be supported?

**Comment by larshp** [comment]
oh, its a table type with a table type as the line type

![image](https://user-images.githubusercontent.com/5888506/88452589-5ebf5080-ce60-11ea-9df3-5bae0acb3231.png)

**Comment by larshp** [comment]
try again, 2.38.3

**Comment by ed-holland** [comment]
Used 2.38.4

Issue resolved. Thanks again.
