### ISSUE TITLE
structure: Expected ENDIF (incomplete IF structure)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1077]
The dependencies checked the include MV45AF0A_AUTOMATISCHE_SERIALNU (standard in ides).

It contains enhancement points / sections that contain incomplete if structures.

![image](https://user-images.githubusercontent.com/53995991/88258337-36005500-ccc0-11ea-85e1-988988cb0c8b.png)

Related #1010

[SCI issue 47](https://github.com/abaplint/abaplint-sci-client/issues/47)

**Comment by larshp** [comment]
:) sap sap sap

**Comment by ed-holland** [comment]
Similar case but with the message "Expected ENDFORM".
MV45AF0B_BELEG_INITIALISIEREN
MV45AF0B_BELEG_KOPIEREN
MV45AF0C_CUA_SETZEN_BUTTONS

![image](https://user-images.githubusercontent.com/53995991/88258596-cb9be480-ccc0-11ea-8afd-728d4511b605.png)

**Comment by ed-holland** [comment]
Expected ENDCASE (structure) from MV45AF0D_D301T_SELECT
![image](https://user-images.githubusercontent.com/53995991/88258679-fe45dd00-ccc0-11ea-9a21-51168d71c2c6.png)

**Comment by larshp** [comment]
I guess the two bottom cases have been fixed, and only the incomplete IF structure remains an issue?

**Comment by ed-holland** [comment]
Indeed the last 2 cases are gone. 
But also the first case is gone.

Many Thanks.
