### ISSUE TITLE
check_syntax: Structure does not contain any components

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1078]
![image](https://user-images.githubusercontent.com/53995991/88259407-8973a280-ccc2-11ea-9347-9a692b9ba9ca.png)

**Comment by larshp** [comment]
```abap
DATA BEGIN OF tables_tab OCCURS 10.
INCLUDE STRUCTURE something_void.
DATA END OF tables_tab.
```

**Comment by larshp** [comment]
try again, 2.38.3

**Comment by ed-holland** [comment]
Used 2.38.4

Found this variation:
![image](https://user-images.githubusercontent.com/53995991/88474455-d952a380-cf26-11ea-9ff5-66d121890549.png)

**Comment by ed-holland** [comment]
Issue is resolved. Thanks.
