### ISSUE TITLE
Linter errors not sorted

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1079]
Would it be possible to sort the results from a Linter run?

Currently the errors from one program are spread out throughout the errors list.
Fixing them would be easier if one has all the error for a program together.

Proposed Sort: File Name + Line number.

**Comment by larshp** [comment]
try again, 2.38.5

**Comment by ed-holland** [comment]
Sorting on file name is working nicely. Thx.

Sorting on error line seems to work only partly.
![image](https://user-images.githubusercontent.com/53995991/88479822-2e57df00-cf52-11ea-912d-3c084bfef023.png)

**Comment by larshp** [comment]
try again, 2.38.7

**Comment by ed-holland** [comment]
Sorting works nicely. Thanks
