### ISSUE TITLE
check_text_elements: Searching for the texts in the include

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1080]
![image](https://user-images.githubusercontent.com/53995991/88269413-46222f80-ccd4-11ea-9823-3ad0f764843e.png)

If an include uses TEXT-... elements then these need to be searched in the top-program that uses the include.
There can be several top programs.

If the check is already doing this, enhancing the message to show which top-program is missing the text would be of great help.

**Comment by larshp** [comment]
main program should now be output in 2.38.7

**Comment by ed-holland** [comment]
Thanks much easier now.
