### ISSUE TITLE
check_syntax: Method "numofchar" not found 

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1081]
function "numofchar" not recognized (sap original code).
![image](https://user-images.githubusercontent.com/53995991/88282450-e171cf80-cce9-11ea-80f4-79549eec472c.png)

![image](https://user-images.githubusercontent.com/53995991/88282534-0bc38d00-ccea-11ea-9be4-30f78547ab53.png)

**Comment by larshp** [comment]
https://help.sap.com/doc/abapdocu_752_index_htm/7.52/en-US/abenlength_functions.htm

**Comment by larshp** [comment]
try again, 2.38.3

**Comment by ed-holland** [comment]
Used 2.38.4

Issue resolved. Thanks again.
