### ISSUE TITLE
keyword_case: Identifiers should be lower case: "COL_HEADING"

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1082]
Source:
`FORMAT COLOR COL_HEADING.`

COL_HEADING is part of the syntax.
![image](https://user-images.githubusercontent.com/53995991/88284297-77f3c000-cced-11ea-9200-9d763d310a86.png)

**Comment by larshp** [comment]
try again, 2.38.3

**Comment by ed-holland** [comment]
Used 2.38.4

Issue resolved. Thanks again.
