### ISSUE TITLE
parser_error: Statement does not exist in ABAPv700(or a parser error), "FIELD"

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1084]
The error is on line 57.

![image](https://user-images.githubusercontent.com/53995991/88285957-44666500-ccf0-11ea-9a43-43db95e5e1ef.png)

**Comment by larshp** [comment]
```abap
TYPES ty_$ TYPE c LENGTH 1.
FIELD-SYMBOLS <sdf$> TYPE ty_$.
```

**Comment by larshp** [comment]
try again, 2.38.3

**Comment by ed-holland** [comment]
Used 2.38.4

Issue resolved. Thanks again.
