### ISSUE TITLE
Identifiers should be lower case: "PRIMARY" (keyword_case)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1086]
The error is on line 557.

![image](https://user-images.githubusercontent.com/53995991/88289186-28b18d80-ccf5-11ea-8a61-07716c334adc.png)

**Comment by larshp** [comment]
try again, 2.38.3

**Comment by ed-holland** [comment]
Used 2.38.4

Issue resolved. Thanks again.
