### ISSUE TITLE
Identifiers should be lower case: "FROM" (keyword_case)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1087]
Error is on line 271.

![image](https://user-images.githubusercontent.com/53995991/88290273-c9547d00-ccf6-11ea-85c7-abb15055a109.png)

![image](https://user-images.githubusercontent.com/53995991/88290300-d2dde500-ccf6-11ea-92f8-55e94fb9f519.png)

**Comment by larshp** [comment]
```abap
DATA val TYPE c LENGTH 1.
DATA var TYPE c LENGTH 1.
MODIFY LINE sy-index FIELD VALUE val FROM var.
```

**Comment by larshp** [comment]
try again, 2.38.3

**Comment by ed-holland** [comment]
Used 2.38.4

Issue resolved. Thanks again.
