### ISSUE TITLE
Indentation problem, expected 2 spaces (TOP-OF-PAGE)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1090]
The indentation should be 0.

`./src/ecc/#jcs#mm_lis_sel_versions_reorg.prog.abap[72, 1]                  - Indentation problem, expected 2 spaces (indentation)`

Source:
![image](https://user-images.githubusercontent.com/53995991/88475363-53872600-cf2f-11ea-8457-d68b9834832e.png)

**Comment by larshp** [comment]
try again, 2.38.5

**Comment by ed-holland** [comment]
Checked and issue is gone. Thanks.
