### ISSUE TITLE
Type error, not a structure type g_seltab_255-selname (unknown_types) (header line)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1091]
`./src/nw/#jcs#variant.fugr.#jcs#lvariantf02.abap[116, 8]                   - Unknown type: Type error, not a structure type g_seltab_255-selname (unknown_types)`

Source:
![image](https://user-images.githubusercontent.com/53995991/88475621-03f62980-cf32-11ea-90c2-4b335ac546aa.png)

![image](https://user-images.githubusercontent.com/53995991/88475632-0eb0be80-cf32-11ea-9c47-d259b3e1a03b.png)

**Comment by larshp** [comment]
reproduced,

```abap
TYPES: BEGIN OF ty_type,
         foo TYPE string,
       END OF ty_type.
DATA tab TYPE TABLE OF ty_type WITH HEADER LINE.
DATA moo LIKE tab-foo.
```

**Comment by larshp** [comment]
try again, 2.38.7

**Comment by ed-holland** [comment]
issue is gone. Thanks
