### ISSUE TITLE
Unexpected ENDFORM (structure) (dashes in names)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1094]
```
/tmp/abaplint-PAooJg/src/sldbv/rsdbspds.prog.abap[324, 1]                  - Unexpected ENDFORM (structure)
/tmp/abaplint-PAooJg/src/so/fssoae02.prog.abap[57, 1]                      - Unexpected ENDFORM (structure)
```

Source
![image](https://user-images.githubusercontent.com/53995991/88480115-56e0d880-cf54-11ea-827c-b2c094fc2ad8.png)

Not sure what is causing this. Maybe the "structure" in the forms interface.

**Comment by larshp** [comment]
dashes in parameters,

```abap
FORM sdf using var-dash type string.

ENDFORM.
```

**Comment by larshp** [comment]
try again, 2.38.9

**Comment by ed-holland** [comment]
The issue is gone. Thx.

Will create a new issue from the next ENDFORM case.
