### ISSUE TITLE
Not a structure, FieldChain (check_syntax) (header line)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1095]
It is the only message for this program, but there are several other programs with this issue.

`./src/ecc/#jcs#analitics_lis_output.prog.abap[45, 11]                      - Not a structure, FieldChain (check_syntax)`

Source
![image](https://user-images.githubusercontent.com/53995991/88480641-64e42880-cf57-11ea-97e1-b8770f8c56de.png)

![image](https://user-images.githubusercontent.com/53995991/88480650-72011780-cf57-11ea-8e56-db8f3436a805.png)

**Comment by larshp** [comment]
think this is the same kind of error as https://github.com/abaplint/abaplint/issues/1091 and https://github.com/abaplint/abaplint/issues/1073

**Comment by larshp** [comment]
think this one is fixed in  2.38.6

**Comment by ed-holland** [comment]
Tested with 2.38.6

Issue is still there.

**Comment by larshp** [comment]
```abap
TYPES: BEGIN OF ty_log,
         msgv1 TYPE string,
       END OF ty_log.
DATA joblog TYPE ty_log OCCURS 0 WITH HEADER LINE.
DATA foo TYPE string.
foo = joblog-msgv1.
```

**Comment by larshp** [comment]
try again, 2.38.7

**Comment by ed-holland** [comment]
The original issue is gone now. Thanks.

There are many more of this type, but they might be symptoms of a structure not found.
Example:
`./src/ecc/#jcs#bc_dynamic_selections.prog.abap[18, 1]                      - "rsdynsel" not found (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[66, 7]                      - Not a structure, target (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[104, 5]                     - Not a structure, target (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[111, 5]                     - "node" not found (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[112, 7]                     - Not a structure, target (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[217, 5]                     - Not a structure, FieldChain (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[227, 5]                     - Not a structure, FieldChain (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[227, 5]                     - Not a structure, FieldChain (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[237, 5]                     - Not a structure, FieldChain (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[237, 5]                     - Not a structure, FieldChain (check_syntax)`

I'll create a seperate issue for the "structure not found. Closing this one
