### ISSUE TITLE
"<structure>" not found (check_syntax)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1101]
There are quite a few of this error in my project. It probably also causes other dependent issues.
I'll try to add the different variations below.

Example:
`./src/ecc/#jcs#bc_dynamic_selections.prog.abap[18, 1]                      - "rsdynsel" not found (check_syntax)  1)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[66, 7]                      - Not a structure, target (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[104, 5]                     - Not a structure, target (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[111, 5]                     - "node" not found (check_syntax) 2)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[112, 7]                     - Not a structure, target (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[217, 5]                     - Not a structure, FieldChain (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[227, 5]                     - Not a structure, FieldChain (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[227, 5]                     - Not a structure, FieldChain (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[237, 5]                     - Not a structure, FieldChain (check_syntax)
 ./src/ecc/#jcs#bc_dynamic_selections.prog.abap[237, 5]                     - Not a structure, FieldChain (check_syntax)`

1) rsdynsel exist as TABL in dependency repository
![image](https://user-images.githubusercontent.com/53995991/88628544-6c6a1580-d0ae-11ea-9688-94ad47c362eb.png)

2) node is defined as RANGE
![image](https://user-images.githubusercontent.com/53995991/88628801-c10d9080-d0ae-11ea-8b50-3c29d92223cf.png)
![image](https://user-images.githubusercontent.com/53995991/88628862-d7b3e780-d0ae-11ea-8c17-c75a8ed9f119.png)

3) se16n_seltab exists as TABL in dependency repository
 `./src/ecc/#jcs#bc_se16n_batch.prog.abap[76, 1]                             - "se16n_seltab" not found (check_syntax)`
![image](https://user-images.githubusercontent.com/53995991/88629193-3b3e1500-d0af-11ea-87a7-be91c3f77147.png)

4) smpdyntext exists as TABL in dependency repository
` ./src/ecc/#jcs#bc_se16n_batch.prog.abap[280, 1]                            - "smp_dyntxt" not found (check_syntax)`
![image](https://user-images.githubusercontent.com/53995991/88629759-f6ff4480-d0af-11ea-9402-9a3ce04ae70e.png)

**Comment by larshp** [comment]
1: is data element DYNSELID and domain DYNSELID also in the dependencies?

**Comment by ed-holland** [comment]
Interesting... the DTEL is showing up in dependencies but is not generated as file. (used List Deps with zip).
No domain either.
![image](https://user-images.githubusercontent.com/53995991/88657386-21fa9000-d0d2-11ea-950c-cd9c08e371ed.png)

**Comment by larshp** [comment]
okay, there is a problem with `LIKE` typing in abaplint

**Comment by larshp** [comment]
try again, 2.38.10

**Comment by ed-holland** [comment]
Interesting... from example above, the "rsdynsel" issue is gone :-) but the "node" one is still there.
Many of the not found messages are gone.

There is now also trace information available. Including messages like this:
`* .INCLU--AP TYPE Unknown type: Table COBL, todo, group named INCLUDE`.

I'm attaching the complete run's information.
[x.txt](https://github.com/abaplint/abaplint/files/5005522/x.txt)

**Comment by larshp** [comment]
argh, the "trace information" should not be there, probably a `console.log` somewhere in the code

**Comment by larshp** [comment]
ahh, its just very long error descriptions :)

**Comment by ed-holland** [comment]
if it helps... is there a how-to-debug-abaplint guide?
As you can see, there are still a lot of strange messages in the log.

**Comment by larshp** [comment]
no, not really, 

first I typically try to reproduce the issue on the playground, https://playground.abaplint.org

if it doesnt work, or for reproducing the issue requires multiple files, I make an empty folder and copy the files there. Also recommend the https://marketplace.visualstudio.com/items?itemName=larshp.vscode-abaplint, but note it does not always run the latest version.

**Comment by ed-holland** [comment]
Verified.
Created seperate issue #1122 for the ranges issue.
