### ISSUE TITLE
Expected ENDCASE (structure)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1111]
Message
`/tmp/abaplint-MheNHn/src/vn/rsnast00.prog.abap[1, 1]                       - Expected ENDCASE (structure)`

Possible cause:
![image](https://user-images.githubusercontent.com/53995991/89009368-b2241980-d30c-11ea-9372-12a7a6599c4f.png)
or
![image](https://user-images.githubusercontent.com/53995991/89009428-cff17e80-d30c-11ea-8617-8ba7189af787.png)

**Comment by ed-holland** [comment]
tried both cases with the playground but the error does not show.

**Comment by larshp** [comment]
try pasting the full include source into the playground, and delete as many statements as possible while reproducing the issue

**Comment by ed-holland** [comment]
did a pretty printer on it and pasted it into visual code (no issue). Then in the playground (only showing 10 issues) and started deleting...(it has 1130 lines).
I stopped after 30 mins... SAP original code is not meant to be check with the current profile...
![image](https://user-images.githubusercontent.com/53995991/89013891-fa473a00-d314-11ea-8ff4-1dfab4c16161.png)

Can the playground be extended?
- show more errors
- allow customizing of the rules

**Comment by g-back** [comment]
You can customize the rules, click on the abaplint.json tab and modify as you wish:
![image](https://user-images.githubusercontent.com/27279305/89026652-5ddb6280-d329-11ea-8524-d664e2942386.png)

**Comment by ed-holland** [comment]
Thank, that helps a lot...

Can it be that this is caused by the insert statement?
![image](https://user-images.githubusercontent.com/53995991/89034520-6d62a780-d339-11ea-93de-071df734e6ba.png)

**Comment by larshp** [comment]
probably not, but 🤷‍♂️ 

Open the INSERT parser error as a separate issue please

**Comment by ed-holland** [comment]
Closing.
