### ISSUE TITLE
DATA parameters with dashes not supported

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1116]
name with a dash.
![image](https://user-images.githubusercontent.com/53995991/89034973-57091b80-d33a-11ea-9e17-4f6e6a82d803.png)

Ref: PROG THEADDAT

**Comment by ed-holland** [comment]
Fixed with 2.38.14 Thanks

**Comment by larshp** [comment]
nope, 

![image](https://user-images.githubusercontent.com/5888506/89129906-4eaf0d00-d501-11ea-9bf5-34d102e85e8c.png)

**Comment by ed-holland** [comment]
you are correct.
Found several more issues of the same type.

There is a dtel called dummy but it is not part of the dependencies.

**Comment by ed-holland** [comment]
Note that also multiple dashes are used in sap code:
![image](https://user-images.githubusercontent.com/53995991/89130786-2bd42700-d508-11ea-8538-5b71258f072f.png)

**Comment by ed-holland** [comment]
Not to forget also:
- Statics
- Common Area
- Constants

Like:
![image](https://user-images.githubusercontent.com/53995991/89155387-01668600-d569-11ea-925f-781c836cf0c7.png)

**Comment by larshp** [comment]
another example to be supported: `CHAR-`

**Comment by larshp** [comment]
and for some reason `TYPES foo-bar TYPE c.` is not valid ABAP syntax, while `DATA foo-bar TYPE c.` is valid

**Comment by larshp** [comment]
the parsing now allows dashes in names, but syntax wise there will be a lot of other issues with dashes, which might be okay for now

![image](https://user-images.githubusercontent.com/5888506/89704779-5b938c80-d957-11ea-9190-96e3252149d2.png)

**Comment by larshp** [comment]
try again, 2.38.17

**Comment by ed-holland** [comment]
Most of the dash issues are gone. Thanks.

`./src/isu/#redwood#1isu.fugr.lfkkaktiv2f01.abap[3506, 3]          - Not a structure, target (check_syntax)`

`  h-ok-code = 'DISP'.`

`./src/isu/#redwood#1isu.fugr.lfkkaktiv2f01.abap[3784, 3]          - Not a structure, FieldChain (check_syntax)`

```
FORM okcode_5200_canc.

  CASE ok-code.
    WHEN 'CANC'.
      sy-subrc = 4.
      LEAVE TO SCREEN 0.
  ENDCASE.

ENDFORM.                    " okcode_5200_canc
```
![image](https://user-images.githubusercontent.com/53995991/89733023-f2913f00-da52-11ea-85eb-52e2a85c7986.png)

![image](https://user-images.githubusercontent.com/53995991/89733072-42700600-da53-11ea-9daa-2b959debe4b8.png)

**Comment by larshp** [comment]
oh, did not think it was in custom code

**Comment by larshp** [comment]
try again, 2.38.19

**Comment by ed-holland** [comment]
It is not custom code. We use SAP original includes in some of our programs.

All Cases are gone except one. Thanks

This one is still an issue:
`h-ok-code = 'DISP'.`

**Comment by larshp** [comment]
```abap
DATA: hok-code TYPE string.
hok-code = 'DISP'.
```

**Comment by larshp** [comment]
try again, 2.38.21

**Comment by ed-holland** [comment]
Issue resolved. Thanks.
