### ISSUE TITLE
"node" not found, Target (check_syntax) - RANGES

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1122]
I've checked again with 2.38.12

`./src/ecc/#jcs#bc_dynamic_selections.prog.abap[111, 5]                     - "node" not found, Target (check_syntax)`

source:
![image](https://user-images.githubusercontent.com/53995991/89121970-d70ebd00-d4c3-11ea-8357-313a43c55d4a.png)

**Comment by larshp** [comment]
reproduced as

```abap
RANGES foo FOR sy-mandt.
foo-low = '123'.
```

**Comment by larshp** [comment]
try again, 2.38.14

**Comment by ed-holland** [comment]
Issue resolved. Thanks.
