### ISSUE TITLE
Expected ENDFORM (structure) - Cause Bracket without blank

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1125]
Issue:
`/tmp/abaplint-CfnPNm/src/va/mv45a_msrf03.prog.abap[1, 1]                - Expected ENDFORM (structure)`

Source (original SAP - mv45a_msrf03)
![image](https://user-images.githubusercontent.com/53995991/89129669-5968a280-d4ff-11ea-9cc2-1ce5804ceb3f.png)

Tested with 2.38.14

**Comment by ed-holland** [comment]
Issue also in SAPFF001 @ 2849.

**Comment by larshp** [comment]
try again 2.39.0

It should now parse okay, but note that the rule https://rules.abaplint.org/parser_missing_space/ will show an error(which will probably be ignored for dependencies)

**Comment by ed-holland** [comment]
Issues resolved. New rule did not show up. Thanks.

**Comment by larshp** [comment]
new rules are not enabled by default, you must adjust `abaplint.json` to enable it, if its a rule you'd like to have enabled
