### ISSUE TITLE
Statement does not exist in ABAPv740sp08(or a parser error) - SELECT

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1126]
Tested with 2.38.14

Source:
![image](https://user-images.githubusercontent.com/53995991/89129734-e3b10680-d4ff-11ea-84ad-d103b900dbf0.png)

Original SAP: mv45afdb_vapma_select

**Comment by larshp** [comment]
variable name `char-`

**Comment by larshp** [comment]
still an issue,

`SELECT SINGLE foo FROM bar WHERE column IN (sdf, char-).`

![image](https://user-images.githubusercontent.com/5888506/89731144-151c5b80-da45-11ea-82fa-86ccbe6c5668.png)

**Comment by ed-holland** [comment]
confirmed.

**Comment by ed-holland** [comment]
issue persists in 2.39.2

**Comment by larshp** [comment]
try again, 2.39.10

**Comment by ed-holland** [comment]
Issue Resolved. Thanks.
