### ISSUE TITLE
 Statement does not exist in ABAPv740sp08(or a parser error), "IF"(parser_error)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1128]
tested with 2.38.14

Source:
![image](https://user-images.githubusercontent.com/53995991/89129819-d0526b00-d500-11ea-98d7-037cbbe33453.png)

Original SAP: mv45afli

**Comment by larshp** [comment]
due to the variable name `CHAR-`

**Comment by larshp** [comment]
closing root cause is https://github.com/abaplint/abaplint/issues/1116
