### ISSUE TITLE
Unused variables

### ISSUE THREAD

**Issue by EduardoCopat** [abaplint/abaplint#113]
Maybe this is too difficult, but if abaplint could check if a variable is used throughout the code, it would be nice. 

Maybe start with the local ones first? (i.e. used withing a method)

**Comment by larshp** [comment]
yeah, this is quite difficult, but eventually it will be implemented

**Comment by larshp** [comment]
rule `check_variables` currently makes sure variables are defined, but does not check for unused yet

**Comment by larshp** [comment]
on deck

**Comment by larshp** [comment]
need https://github.com/abaplint/abaplint/issues/512 first to handle `##NEEDED`

**Comment by g-back** [comment]
now that we can get the `##NEEDED` pragmas, this could be attempted. Maybe only local variables in method implementations to start with?
How do we define a variable as "unused"? When it's never used as a `Source`?

**Comment by larshp** [comment]
right now the difficult part is handling `CHANGING` which is both a write and a read position

**Comment by larshp** [comment]
try latest version, 2.38.18, it contains lots of improvements wrt detecting unused variables

**Comment by larshp** [comment]
closing this, but feel free to open bug reports for the rule
