### ISSUE TITLE
Read table, not a table type (check_syntax) - OCCURS table

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1131]
Issue:
`./src/isu/#redwood#2isu.fugr.#redwood#l2isuf02.abap[361, 3]             - Read table, not a table type (check_syntax)`

Source:
![image](https://user-images.githubusercontent.com/53995991/89130844-aef57d00-d508-11ea-87f9-0c45f716aad8.png)

![image](https://user-images.githubusercontent.com/53995991/89130848-b61c8b00-d508-11ea-8951-e274da947194.png)

**Comment by larshp** [comment]
unable to reproduce,

```abap
DATA: BEGIN OF tab OCCURS 10,
        foo TYPE string,
      END OF tab.
READ TABLE tab INDEX 1.
```

**Comment by ed-holland** [comment]
It seems that it has to do with being inside a form with data from outside.

This example gives the error in playground:
```
data:
* path stack
  begin of tb_path occurs 10,
    stru like dd03v-fieldname,
    path TYPE scrfname,
  end of tb_path.

FORM pop_path.

  DELETE TABLE tb_path.
  READ TABLE tb_path INDEX g_depth.
  SUBTRACT 1 FROM g_depth.

ENDFORM.
```

**Comment by larshp** [comment]
identified bug, its actually a upper case lower case problem, if `OCCURS` is upper then it works, if `occurs` is lower then bug

**Comment by larshp** [comment]
try again, 2.38.17

**Comment by ed-holland** [comment]
Issue resolved. Thanks.
