### ISSUE TITLE
Not a structure, target (check_syntax) - TYPE TABLE OF with Local structure

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1132]
Issue:
`./src/xbp/#redwood#1xbp.fugr.#redwood#l1xbpf01.abap[89, 9]              - Not a structure, target (check_syntax)`

Source:
![image](https://user-images.githubusercontent.com/53995991/89130951-b5382900-d509-11ea-8ba6-925fb3cccfcf.png)

![image](https://user-images.githubusercontent.com/53995991/89130954-be28fa80-d509-11ea-9c2f-275fb8b8c452.png)

![image](https://user-images.githubusercontent.com/53995991/89130963-caad5300-d509-11ea-8e50-acbc3d357adc.png)

**Comment by larshp** [comment]
what does `where_line` look like?

following does **not** reproduce the error,
```abap
DATA: BEGIN OF stru,
        foo TYPE string,
      END OF stru.
DATA tab LIKE TABLE OF stru WITH HEADER LINE.
tab-foo = 'sdf'.
```

**Comment by ed-holland** [comment]
see last screenshot... it is a local definition.

**Comment by ed-holland** [comment]
![image](https://user-images.githubusercontent.com/53995991/89154137-9d42c280-d566-11ea-8df0-07a6bd63f0a4.png)

This way it does:

> 
> types:
>    where_type(255) TYPE c.
> 
> DATA p_where_tab TYPE TABLE OF where_type.
> 
> DATA: BEGIN OF where_line,
>    line TYPE where_type,
> END OF where_line.
> 
> DATA:
>     p_new_where like table of where_line with header line.
> 
> p_new_where-line = '('.

**Comment by larshp** [comment]
upper/lower case problem in abaplint

**Comment by larshp** [comment]
try again, 2.38.17

**Comment by ed-holland** [comment]
Issue resolved. Thanks.
