### ISSUE TITLE
Not a structure, FieldChain (check_syntax) - reference to a TABLES field in a header line

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1133]
issue:
`./src/xbp/#redwood#xbplsbdf11.prog.abap[192, 7]                         - Not a structure, FieldChain (check_syntax)`

Source:
![image](https://user-images.githubusercontent.com/53995991/89131170-08f74200-d50b-11ea-98c2-a0d570544eed.png)

**Comment by ed-holland** [comment]
is this the same as #1073 ?

**Comment by larshp** [comment]
reproduced as

```abap
DATA: BEGIN OF stru,
        foo TYPE string,
      END OF stru.
FORM bar TABLES tab STRUCTURE stru.
  WRITE tab-foo.
ENDFORM.
```

**Comment by ed-holland** [comment]
Checked with 2.38.16
Issue resolved. Thanks.
