### ISSUE TITLE
Config: Request for a separate version to be specified for code that is checked from dependency code

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1134]
Even though code needs to be checked as such to work in a specific version syntax wise (syntax->version)
the dependency code generated in a separate repository can be from a different version.
This causes problems when abaplint tries to verify dependency code that uses newer syntax.

Example; The use of DATA(temp) is not supported in 702.

If the dependency code can be checked using the version it is generated from, these issues will not occur.

**Comment by ed-holland** [comment]
Would this be feasible at all?

We need to check for the v700 release to be compatible with some of our customers (yes they are still at this release, even with lower SP).

The only other option would be:
- Exclude the content with issues
- Generate Dependencies for older releases (is this feasible?)

**Comment by larshp** [comment]
its difficult to implement

do you have an example of where this is a problem? if possible the easiest fix is to not have that code in the dependencies, eg code inside FORMS/methods/function modules are not needed

**Comment by ed-holland** [comment]
I got these issues when i switch from 740sp8 to 700:
```
/tmp/abaplint-AhcAcG/src/va/mv45af0b_beleg_lesen_logic.prog.abap[1, 1]     - Expected ENDFORM (structure)
/tmp/abaplint-AhcAcG/src/va/mv45af0b_beleg_sichern.prog.abap[1, 1]         - Expected ENDDO (structure)
/tmp/abaplint-AhcAcG/src/va/mv45af0i_incoterm_save_check.prog.abap[1, 1]   - Expected ENDFORM (structure)
/tmp/abaplint-AhcAcG/src/va/mv45af0v_vbkd_incov_check_item.prog.abap[1, 1] - Expected ENDFORM (structure)
/tmp/abaplint-AhcAcG/src/va/sd_dpp_mv45af0a_ag_pruefen.prog.abap[30, 2]    - Unexpected ENDIF (structure)
/tmp/abaplint-AhcAcG/src/vz/incoterm_location_assignment.prog.abap[1, 1]   - Expected ENDFORM (structure)
```

Due to code like DATA(value) etc...

**Comment by larshp** [comment]
for these includes, what if we delete all code between FORM and ENDFORM, I guess it will be better?

**Comment by ed-holland** [comment]
Worth a try.

**Comment by larshp** [comment]
ref https://github.com/abaplint/abaplint-sci-client/issues/97

**Comment by ed-holland** [comment]
Ref [sci-client #97](https://github.com/abaplint/abaplint-sci-client/pull/128)

**Comment by ed-holland** [comment]
This request is not required anymore due to squashing the FORMS and Functions in the dependency repository.

Thanks.
