### ISSUE TITLE
t001w (unknown_types)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1135]
Issue:
`./src/ecc/#jcs#ckml.fugr.#jcs#lckmltop.abap[11, 9]                       - t001w (unknown_types)`

Source:
![image](https://user-images.githubusercontent.com/53995991/89155822-e1839200-d569-11ea-8076-376950c54aaa.png)

Not reproducible in playground. Dependency Repo contains table.

Similar issue:
`./src/ecc/#jcs#bdc_erp.fugr.#jcs#lbcf90.abap[103, 35]                    - msgtype (unknown_types)`

Source:
![image](https://user-images.githubusercontent.com/53995991/89156054-50f98180-d56a-11ea-9c59-1efb41e5dd00.png)

**Comment by ed-holland** [comment]
tested with 2.38.15

**Comment by larshp** [comment]
part regarding `sy-msgty` fixed in 2.38.17

**Comment by larshp** [comment]
for `t001w`: try opening the project in vscode with the abaplint extension installed, https://marketplace.visualstudio.com/items?itemName=larshp.vscode-abaplint, and hover the mouse on T001W, then it should better show what is missing, 

![image](https://user-images.githubusercontent.com/5888506/89705822-a1a11e00-d960-11ea-8218-79ab4d96238c.png)

**Comment by ed-holland** [comment]
I've opened /jcs/lckmltop in vcode. 
![image](https://user-images.githubusercontent.com/53995991/89733810-5407dc80-da58-11ea-8e07-3c192f314da3.png)

It has these errors:
Object name does not match pattern ^Z: /JCS/CKMLabaplint(object_naming)
Include /JCS/LBCMAC not foundabaplint(check_include)

Both errors seem to be wrong (first upper/lower maybe).

**Comment by ed-holland** [comment]
Could it be that not all types are retrieved by the dependency collection?

`./src/ecc/#jcs#co_internal_order_balance.prog.abap[11, 9]                - Type of "coas" contains unknown types (unknown_types)`

![image](https://user-images.githubusercontent.com/53995991/89986580-091ade80-dc7d-11ea-81ac-8c6a414fbbde.png)

the table COAS has a strange field (also saw it in COVP) :
![image](https://user-images.githubusercontent.com/53995991/89986757-4da67a00-dc7d-11ea-8b16-e260facbd37c.png)

**Comment by ed-holland** [comment]
issue persists in 2.39.2

**Comment by ed-holland** [comment]
Can the message be improved to show which field is causing the problem?

**Comment by larshp** [comment]
yea, good idea

**Comment by larshp** [comment]
COAS star fixed in 2.39.4

error message improved in 2.39.4

**Comment by ed-holland** [comment]
COAS releated issues are gone.

the new error message produced this:
```
./src/ecc/#jcs#bdc_erp.fugr.#jcs#lbdc_erptop.abap[7, 12]                 - Type of "fb02_rec" contains unknown: Table BSEG, todo, group named INCLUDE (unknown_types)
./src/ecc/#jcs#ckml.fugr.#jcs#lckmltop.abap[11, 9]                       - Type of "t001w" contains unknown: Table T001W, todo, group named INCLUDE (unknown_types)
./src/ecc/#jcs#co_internal_order_balance.prog.abap[11, 21]               - Type of "ionra" contains unknown: Table IONRA, todo, group named INCLUDE (unknown_types)
./src/ecc/#jcs#fi_copa_bdc_fields.prog.abap[15, 6]                       - Type of "in_cobl" contains unknown: Table COBL, todo, group named INCLUDE (unknown_types)
```

Something goes wrong with the type assesment. The first error is from this code:
![image](https://user-images.githubusercontent.com/53995991/90255140-251cac80-de44-11ea-8f84-652866171add.png)

there is no BSEG there (tpit references are from a type-pool).

The 2nd one is just referencing itself.
The 3rd is a structure with appends
The 4th is a structure with includes and appends

**Comment by larshp** [comment]
ahh, okay `.APPEND` is actually `.INCLU--AP` after serialization

**Comment by larshp** [comment]
try again, 2.39.5

**Comment by ed-holland** [comment]
Several cases of this error are gone. Thanks

Issue:
`./src/ecc/#jcs#fi_copa_bdc_fields.prog.abap[15, 6]                       - Type of "in_cobl" contains unknown: Type error, could not resolve cobl (unknown_types)`

Source:
`DATA in_cobl LIKE cobl.`

COBL has multiple includes in include and also appends with includes.
Other cases also have includes with appends and appends with includes (like LFB1, WITH_ITEM).

**Comment by larshp** [comment]
try again, 2.39.6

**Comment by ed-holland** [comment]
They are all gone. Thanks
