### ISSUE TITLE
resolving TYPE pool data, icon_fencing not found, findTop (check_syntax)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1148]
Issue:
`./src/#redwood#xbp_parameters.prog.abap[300, 3]                   - icon_fencing not found, findTop (check_syntax)`

icon_fencing is part of the type pool icon.

**Comment by larshp** [comment]
workaround is adding it as a global constant, https://github.com/larshp/abapGit/blob/master/abaplint.json#L18

resolving data/constants from type pools doesn't work right now

**Comment by ed-holland** [comment]
added the constants to the json. Workaround working fine. Thanks.

**Comment by larshp** [comment]
its still a problem, so I'd like to fix it sometime

**Comment by larshp** [comment]
starting this 🎉

**Comment by larshp** [comment]
@ed-holland try again, note that I've added some icons in https://github.com/abaplint/deps/blob/main/src/icon.type.abap

**Comment by ed-holland** [comment]
Resolved.
