### ISSUE TITLE
sy-spono not found

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1149]
Issue:
```
./src/#redwood#xbp_submit.prog.abap[33, 1]                        - Component "spono" not found in structure (check_syntax)
./src/#redwood#xbp_submit.prog.abap[35, 1]                        - Component "spono" not found in structure (check_syntax)
```

Code:
![image](https://user-images.githubusercontent.com/53995991/89758131-5feeaf80-dae7-11ea-85f9-32829418d391.png)

![image](https://user-images.githubusercontent.com/53995991/89758229-96c4c580-dae7-11ea-818a-4e9b941f72c5.png)

**Comment by larshp** [comment]
try again, 2.38.21

**Comment by ed-holland** [comment]
Issue resolved. Thanks.
