### ISSUE TITLE
Identifiers should be lower case: "INTO"(keyword_case)

### ISSUE THREAD

**Issue by jrodriguez-rc** [abaplint/abaplint#1155]
Linter doesn't determine correctly "INTO TABLE" as keywords when the statement has more additions, like REFERENCE INTO:
![image](https://user-images.githubusercontent.com/56556686/89880648-c39ada80-dbc4-11ea-8084-f774a6be60d6.png)

Without REFERENCE INTO works correctly
![image](https://user-images.githubusercontent.com/56556686/89880713-d4e3e700-dbc4-11ea-98d7-501751a81637.png)

**Comment by larshp** [comment]
thanks will be fixed via https://github.com/abaplint/abaplint/commit/85eaf3e24134c6a6b4f456f09ed5557b5c961705

**Comment by larshp** [comment]
try again, 2.38.21
