### ISSUE TITLE
Expected ENDCASE(structure) - due to INCLUDE

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1156]
This issue was fixed in the past and has resurfaced in 2.38.21
![image](https://user-images.githubusercontent.com/53995991/89913625-396a6a80-dbf4-11ea-9f90-d3faf54bd3b1.png)

**Comment by larshp** [comment]
I've moved the INSERT into field group to a separate statement, https://syntax.abaplint.org/?filter=insert#/statement/InsertFieldGroup

which is currently not allowed in any structures => bug

**Comment by larshp** [comment]
try again, 2.38.22

**Comment by ed-holland** [comment]
Issue Resolved. Thanks.
