### ISSUE TITLE
Chain mainly declarations (chain_mainly_declarations) - LOCAL

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1157]
Issue:
`./src/ecc/#jcs#hr_pa03.prog.abap[476, 3]                                 - Chain mainly declarations (chain_mainly_declarations)`

Source:
![image](https://user-images.githubusercontent.com/53995991/89914775-c95ce400-dbf5-11ea-8120-16ae136398e4.png)

Playground:
![image](https://user-images.githubusercontent.com/53995991/89915112-3f614b00-dbf6-11ea-8120-6be12ab7c474.png)

**Comment by larshp** [comment]
try again, 2.38.22

**Comment by ed-holland** [comment]
Issue Resolved. Thanks.
