### ISSUE TITLE
Component "slset" not found in structure (check_syntax)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1158]
Issue:
`./src/ecc/#jcs#hr_pa03.prog.abap[1218, 3]                                - Component "slset" not found in structure (check_syntax)`

Source:
![image](https://user-images.githubusercontent.com/53995991/89915510-bd255680-dbf6-11ea-85f4-dd60dc8e9894.png)

Playground:
![image](https://user-images.githubusercontent.com/53995991/89915555-cb737280-dbf6-11ea-8608-fbbb39cdb512.png)

**Comment by larshp** [comment]
try again, 2.38.22

**Comment by ed-holland** [comment]
Issue Resolved. Thanks.
