### ISSUE TITLE
Indentation problem, expected 2 spaces (indentation) - AT USER-COMMAND

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1159]
Issue:
`./src/ecc/#jcs#mm_lis_sel_versions_reorg.prog.abap[76, 1]                - Indentation problem, expected 2 spaces (indentation)`

Source:
![image](https://user-images.githubusercontent.com/53995991/89916046-69ffd380-dbf7-11ea-849b-a10b995b2aba.png)

Playground:
![image](https://user-images.githubusercontent.com/53995991/89916174-9c113580-dbf7-11ea-83ce-2a7187d54780.png)

**Comment by larshp** [comment]
try again, 2.38.22

**Comment by ed-holland** [comment]
Issue Resolved. Thanks.
