### ISSUE TITLE
syst not found, findTop (check_syntax)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1164]
Issue:
`./src/ecc/#jcs#fi_gd13_check_compare.prog.abap[101, 3]                   - syst not found, findTop (check_syntax)`

Source:
![image](https://user-images.githubusercontent.com/53995991/90223409-45317900-de0e-11ea-97a8-807a2785092a.png)

Playground:
![image](https://user-images.githubusercontent.com/53995991/90223526-7d38bc00-de0e-11ea-9941-3f4e37f365eb.png)

**Comment by larshp** [comment]
hmm, thought SYST was just a ddic structure, not a global variable 😄 always something new in ABAP

**Comment by larshp** [comment]
try again, 2.39.1

**Comment by ed-holland** [comment]
Issue resolved. Thanks.
