### ISSUE TITLE
t_tabmsg not found, findTop (check_syntax) - Fuba Tables parameter not found in include

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1165]
Issue:
`./src/ecc/#jcs#fipi.fugr.#jcs#lfipif01.abap[73, 9]                       - t_tabmsg not found, findTop (check_syntax)`

Source:
![image](https://user-images.githubusercontent.com/53995991/90223671-c721a200-de0e-11ea-83dc-0f3063dc3719.png)

![image](https://user-images.githubusercontent.com/53995991/90223854-1b2c8680-de0f-11ea-8c8d-6ca5e3e86f21.png)

**Comment by larshp** [comment]
there is a bit more to this story? if its a F01 include, it does not automatically have access to the function module parameters?

**Comment by ed-holland** [comment]
That was what i thought also until i found this one.

The FUGR is a copy of the SAP original FIPI with some extended handling of BDC QIDs.

The object Jump in the GUI is doing magic...

Call of the form contains the table in the tables part.
![image](https://user-images.githubusercontent.com/53995991/90244668-80916f00-de31-11ea-8cd2-ba1692569392.png)

The Form start:
![image](https://user-images.githubusercontent.com/53995991/90244785-bdf5fc80-de31-11ea-8bb1-99d1e1ae3c72.png)

For me, the loop should have been on tab_msg instead. SAP still makes it work somehow.
It also does not get a syntax error... any idea why?

**Comment by larshp** [comment]
hmm, no

**Comment by ed-holland** [comment]
I've changed it to tab_msg (as it should be) and now the checks are fine.
