### ISSUE TITLE
st_txttab not found, findTop (check_syntax) - STATICS with Include

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1166]
Issue:
```
./src/ecc/#jcs#fipi.fugr.lfipif00.abap[3483, 3]                          - Chain mainly declarations (chain_mainly_declarations)
./src/ecc/#jcs#fipi.fugr.lfipif00.abap[3483, 3]                          - Structure does not contain any components (check_syntax)
./src/ecc/#jcs#fipi.fugr.lfipif00.abap[3484, 10]                         - Start statement at tab position (start_at_tab)
./src/ecc/#jcs#fipi.fugr.lfipif00.abap[3516, 9]                          - "ST_TXTTAB" not found, Target (check_syntax)
./src/ecc/#jcs#fipi.fugr.lfipif00.abap[3517, 9]                          - "ST_TXTTAB" not found, Target (check_syntax)
./src/ecc/#jcs#fipi.fugr.lfipif00.abap[3518, 9]                          - st_txttab not found, findTop (check_syntax)
```

Source (part of FORM):
![image](https://user-images.githubusercontent.com/53995991/90224101-752d4c00-de0f-11ea-881e-647abe67352e.png)

Definition:
![image](https://user-images.githubusercontent.com/53995991/90224145-84ac9500-de0f-11ea-9e41-8be393ad0d29.png)

The table THEADVB is part of the dependency repository

**Comment by larshp** [comment]
added STATICS BEGIN as ok for `chain_mainly_declarations`, https://github.com/abaplint/abaplint/pull/1167/commits/abb19a0cb21c94ba7db2392514ae1b6dbf9c8986#diff-575f03430b4e5637378c73ad27ab0937

**Comment by larshp** [comment]
try again, 2.39.1

**Comment by ed-holland** [comment]
Issue Resolved. Thanks
