### ISSUE TITLE
Component "lilli" not found in structure (check_syntax) - SY-LILLI

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1170]
Issue:
`./src/ecc/#jcs#mm_lis_sel_versions_reorg.prog.abap[197, 3]               - Component "lilli" not found in structure (check_syntax)`

Source:
![image](https://user-images.githubusercontent.com/53995991/90247255-82a9fc80-de36-11ea-9ccd-cbf0594ada30.png)

Playground:
![image](https://user-images.githubusercontent.com/53995991/90247354-acfbba00-de36-11ea-98ef-827adf35de6e.png)

**Comment by larshp** [comment]
try again, 2.39.4

**Comment by ed-holland** [comment]
issue resolved. Thanks
