### ISSUE TITLE
Question regarding abaplint.json and the globalConstants attribute

### ISSUE THREAD

**Issue by habrahams** [abaplint/abaplint#1172]
@larshp, I'm busy configuring a abaplint.json file for use. I am looking at your abapgit configuration and I have a question about the globalConstants attribute. What is it used for and what does it reference?
![image](https://user-images.githubusercontent.com/16045067/90257452-7b3f1f00-de47-11ea-85bb-990686e12231.png)
 
I looked in the docs folder at the design doc but the section on configuration still needs to be completed.
Do you perhaps have any other documentation on how to configure the abaplint.json?
Thanks!

**Comment by larshp** [comment]
the approach is:
1: run abaplint, with no globalConstants configured
2: if there is an error involving a global constant, add it, and goto 1, else done

**Comment by habrahams** [comment]
Thanks @larshp

**Comment by larshp** [comment]
its not a perfect approach, but its ABAP 😁
