### ISSUE TITLE
functional_writing, add quickfix

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#1185]
add quickfix for rule https://rules.abaplint.org/functional_writing/

**Comment by g-back** [comment]
can be either or:
```abap
CALL METHOD foo=>bar.
CALL METHOD foo=>bar( ).
```
which, including eventual line breaks in the statement, makes this not so easy

**Comment by larshp** [comment]
suggest ignoring the line breaks in this quick fix, leave it to a different rule to fix line breaks
