### ISSUE TITLE
pragma outside of statement / pragma_placement

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#119]
`foo = 'bar'. ##NO_TEXT`

**Comment by larshp** [comment]
this can be done, pragmas are now part of the statement

StatementNode->getEnd
StatementNode->getTerminator
StatementNode->getColon

**Comment by bigld** [comment]
@larshp I will do this

**Comment by larshp** [comment]
right now, this actually gives a parser errror

```abap
DATA foo TYPE string.
foo = 'bar'. ##NO_TEXT
```
