### ISSUE TITLE
MESSAGE + string template not supported in 702

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1190]
`MESSAGE |{ mo_repo->get_name( ) }: settings saved successfully.| TYPE 'S'.`

![image](https://user-images.githubusercontent.com/59966492/90422320-b5e3ca00-e088-11ea-8e68-7d8151bf4ee6.png)

**Comment by mbtools** [comment]
Duplicate https://github.com/abaplint/abaplint/issues/286

**Comment by larshp** [comment]
thanks, I'll add https://github.com/abaplint/abaplint/issues/286 to the list of stuff to do tomorrow
