### ISSUE TITLE
Notification of rule changes

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1216]
We all have a bunch of abaplint.json files in our projects and want to keep them up-to-date with the latest abaplint rules. It would be nice to have some kind of notification or method to identify which rules are new and which have changed. 

Maybe add a "last update" date to the metadata of each rule and surface it on rules.abaplint.org so we can filter the rules by it.

**Comment by larshp** [comment]
hi,
the best solution right now is to open `abaplint.json` in vscode, it will help entering new rules and add new configuration options, according to the json schema

**Comment by larshp** [comment]
but did something break, I'm trying to add more stuff without directly breaking existing

however might do changes, where eg. rules are renamed, and thus not run on old configurations

**Comment by mbtools** [comment]
It was a couple renames that threw me off. No worry

**Comment by larshp** [comment]
currently, I'm prioritizing functionality over stability for abaplint
