### ISSUE TITLE
Macro call rp-init-buffer not recognised by abaplint as valid statement

### ISSUE THREAD

**Issue by habrahams** [abaplint/abaplint#1222]
Macro call rp-init-buffer not recognised in abaplint (vscode).
![image](https://user-images.githubusercontent.com/16045067/91140084-d1198f80-e6af-11ea-91e2-b6ecd0e52184.png)
SM30->TRMAC
![image](https://user-images.githubusercontent.com/16045067/91140656-fc9c7a00-e6af-11ea-84f3-53d00d46b85c.png)

**Comment by larshp** [comment]
thanks for the bug report

two problems:
a: global macros are not really handled in abaplint, workaround is to add them in abaplint.json, example: https://github.com/larshp/abapOpenChecks/blob/master/abaplint.json#L30
b: this macro contains dashes, so I'm guessing the workaround doesn't work in this case

**Comment by habrahams** [comment]
Thanks @larshp , I'll add it to the abaplint.json.

**Comment by larshp** [comment]
I'll publish a new version with the changes from https://github.com/abaplint/abaplint/pull/1223, sometime later today

**Comment by larshp** [comment]
try again, 2.39.19 published

**Comment by habrahams** [comment]
Thanks @larshp ,
The issue is resolved, after the vscode extension updated I was able to exclude the macro via the abaplint.json config.
