### ISSUE TITLE
abaplint.json "skipGeneratedFunctionGroups": true, not ignoring Function group with namespace

### ISSUE THREAD

**Issue by habrahams** [abaplint/abaplint#1227]
I have an issue where a generated function group is checked and various syntax issues are picked up.
The function group is not in the z namespace.

![image](https://user-images.githubusercontent.com/16045067/91172214-16ec4d00-e6dc-11ea-9311-ebda81204af4.png)
![image](https://user-images.githubusercontent.com/16045067/91175666-713bdc80-e6e1-11ea-96b6-9f679260091b.png)

Is there a way to exclude a function group from any abaplint checks? or do you have to specify all the *.prog.abap files under each individual check?

**Comment by larshp** [comment]
currently, the logic looks for a TOBJ object corresponding to the function module, do you have this in the repository?

or which kind of generated function group is it?

**Comment by habrahams** [comment]
The generated function groups is for view maintenance. The TOBJ xml does exist in the repository and is serialised.
![image](https://user-images.githubusercontent.com/16045067/91176324-6cc3f380-e6e2-11ea-9b35-a880249c67c4.png)
![image](https://user-images.githubusercontent.com/16045067/91176573-c1676e80-e6e2-11ea-9301-489553ad8fed.png)

**Comment by larshp** [comment]
thanks, I think there is a bug in the regex when getting the AREA from the TOBJ object, the "/" should be escaped(https://github.com/abaplint/abaplint/issues/1226#issuecomment-679926949)

https://github.com/abaplint/abaplint/blob/master/packages/core/src/objects/maintenance_and_transport_object.ts#L24

**Comment by larshp** [comment]
also, can you try running `abaplint` on command line, to check that the results are the same? do `npm install @abaplint/cli -g` to install/upgrade and then run abaplint in the directory

note that I dont always keep the vscode extension up to date

**Comment by habrahams** [comment]
Thanks @larshp ,
I'll test this and the macro dash(-) issue via the command line first thing in the morning.

W.r.t the vscode extension, you have mentioned this to me previously, but I thought I would give it a go anyway seeing as there was an update available. If the update didn't address the issue I would have defaulted to the cli. 

Thanks again for all your assistance!

**Comment by habrahams** [comment]
The issue is not present in the cli, thus this is only a vscode extension issue.

**Comment by larshp** [comment]
the fix will be inside abaplint, as I will be moving everything to URIs sometime

reopening

**Comment by larshp** [comment]
issue might be the same as https://github.com/abaplint/abaplint/issues/1230

**Comment by larshp** [comment]
@habrahams can you help trying again? might have been the same issue as https://github.com/abaplint/abaplint/issues/1230

**Comment by habrahams** [comment]
Issue resolved, thanks! Do you still want to keep the issue open or can it be closed now?

**Comment by larshp** [comment]
closing
