### ISSUE TITLE
Parse Error for "field-symbols:" statement in abap program

### ISSUE THREAD

**Issue by habrahams** [abaplint/abaplint#1228]
The "field-symbols" statement picked up as a parse error in infotype program include.

![image](https://user-images.githubusercontent.com/16045067/91174052-07bace80-e6df-11ea-94b3-b1202d583274.png)

**Comment by larshp** [comment]
thanks, I'll add the obsolete syntax to the statement

https://syntax.abaplint.org/?filter=fields#/statement/FieldSymbol

**Comment by larshp** [comment]
try again, 2.39.20 published

**Comment by habrahams** [comment]
Issue resolved, thanks!
