### ISSUE TITLE
abaplint.json class methods implementations of interface not identified when using namespace (implement_methods, check_syntax))

### ISSUE THREAD

**Issue by habrahams** [abaplint/abaplint#1230]
I have another namespace issue with regard to the class checks:
![image](https://user-images.githubusercontent.com/16045067/91188926-224a7300-e6f2-11ea-9433-cfcf4a8f5894.png)

**Comment by larshp** [comment]
any dashes or non `\w` characters in the namespace? https://github.com/abaplint/abaplint/blob/master/packages/core/src/files/_abstract_file.ts#L28

**Comment by habrahams** [comment]
No there are no not. [A-Z] only.

**Comment by habrahams** [comment]
This is has also been resolved.
