### ISSUE TITLE
Data begin of - Data end of, parse error (valid between ... and ...)

### ISSUE THREAD

**Issue by habrahams** [abaplint/abaplint#1234]
A parse issue picked up for "data begin of" and "data end of". I believe the addition of "valid between begda and endda" causes the issue.

![image](https://user-images.githubusercontent.com/16045067/91285808-eebd2680-e78d-11ea-8198-753308972cd6.png)

Confirmed in vscode and abaplint cli.

**Comment by larshp** [comment]
yea, https://syntax.abaplint.org/?filter=dataend#/statement/DataEnd

**Comment by larshp** [comment]
try again, 2.39.20 published

**Comment by habrahams** [comment]
Issue resolved, thank you!
