### ISSUE TITLE
Parser_error on "Export to memory" Statement

### ISSUE THREAD

**Issue by habrahams** [abaplint/abaplint#1238]
Parse error on statement "Export to memory id".
`EXPORT var TO MEMORY ID id.`

Statement does not exist in ABAPv700(or a parser error), "EXPORT" (parser_error)

**Comment by larshp** [comment]
I'm unable to reproduce this issue,

![image](https://user-images.githubusercontent.com/5888506/91449541-877da000-e87b-11ea-9ca7-69c1139d6e27.png)

**Comment by habrahams** [comment]
Apologies, the issue is caused by a special character and my example dit not take this into account.
`EXPORT $hcat1 TO MEMORY ID sy-uname.`

![image](https://user-images.githubusercontent.com/16045067/91538049-7d10e400-e917-11ea-9897-5b1cf01d313d.png)

**Comment by larshp** [comment]
try again, 2.39.22 published

**Comment by habrahams** [comment]
Issue resolved, thank you!
