### ISSUE TITLE
Parse_error on "Form" statement when parameter name has special character "&"

### ISSUE THREAD

**Issue by habrahams** [abaplint/abaplint#1242]
```
FORM re549r USING &permo.

  CHECK: &permo NE t549r-permo.

  SELECT SINGLE * FROM t549r WHERE permo EQ &permo.

  CHECK sy-subrc NE 0.
  CLEAR t549r.
  MESSAGE e301(rp) WITH 'T549R' &permo.

ENDFORM. 
```

Statement does not exist in ABAPv700(or a parser error), "FORM" (parser_error)

Confirmed "&" is causing the parse error on the abaplint playground.

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/pull/1235/commits/24b9b66b8a99fef9e50e50bba06ada0fe07821bc

**Comment by larshp** [comment]
try again, 2.39.21 published

**Comment by habrahams** [comment]
Resolved, thank you!
