### ISSUE TITLE
Question Regarding Statement "ULINE" and NW compatibility

### ISSUE THREAD

**Issue by habrahams** [abaplint/abaplint#1244]
I have a question regarding statement "ULINE". The statement is picked up as not being backward compatible with the abapOpenChecks that is run via ATC.
I am currently testing with code compatibility for NW 7.00 via abaplint, and I am getting a parse error, but I'm not sure if it is a parse error or the statement just doesn't exist in NW 7.00.

Do you perhaps know in which NW version the "ULINE" statement was introduced?

**Comment by larshp** [comment]
https://help.sap.com/viewer/10a002cd6c531014b5e1cb16d2455072/7.0.37/en-US/c95472f6787f11d194c90000e8353423.html has references to ULINE, so I assume ULINE will work on 700, but I don't have access to systems to check it

something might be missing in the syntax that abaplint knows about uline,
https://syntax.abaplint.org/?filter=uline#/statement/Uline

**Comment by ed-holland** [comment]
I can confirm that uline works in 700 SP35. I remember using it already in 3.1i / 4.0b.

**Comment by larshp** [comment]
@habrahams can you help adding information regarding the statement that causes the parser error?

**Comment by habrahams** [comment]
The statement that causes the parse error:
   
`ULINE AT  p_offset(131).`

All the occurrences of code that cause the parse error look like the above example.
I do not have another variant that I have picked up yet.

**Comment by larshp** [comment]
try again, 2.39.22 published

**Comment by habrahams** [comment]
Issue resolved, thank you!
