### ISSUE TITLE
Not a structure, ComponentName (check_syntax) - ComponentName does not exist

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1248]
Issues:
```
./src/ecc/#jcs#fi_gd13_check_compare.prog.abap[122, 7]                     - Not a structure, ComponentName (check_syntax)
./src/ecc/#jcs#fi_gd13_check_compare.prog.abap[425, 5]                     - Not a structure, ComponentName (check_syntax)
./src/ecc/#jcs#fi_gd13_check_export.prog.abap[85, 5]                       - Not a structure, ComponentName (check_syntax)
```

Source:
1:
![image](https://user-images.githubusercontent.com/53995991/91586830-3a223100-e956-11ea-8007-b8a34a0f4cce.png)
![image](https://user-images.githubusercontent.com/53995991/91586866-473f2000-e956-11ea-8502-877790d71fdd.png)
2:
![image](https://user-images.githubusercontent.com/53995991/91586944-62aa2b00-e956-11ea-9f0c-a43a264851c8.png)
3:
![image](https://user-images.githubusercontent.com/53995991/91587157-af8e0180-e956-11ea-887c-d786f9bd7adc.png)
![image](https://user-images.githubusercontent.com/53995991/91587179-b61c7900-e956-11ea-88f5-e7ca740f58aa.png)

**Comment by larshp** [comment]
issue 2 reproduced as following, is issue 1 and 3 also FORM TABLES parameters using LIKE typing?

```abap
TYPES: BEGIN OF ty_type,
         field TYPE string,
       END OF ty_type.

DATA tab TYPE STANDARD TABLE OF ty_type.

FORM foo TABLES bar LIKE tab.
  WRITE bar-field.
ENDFORM.
```

**Comment by ed-holland** [comment]
For 1. it is `DATA: gt_outtab1  LIKE gt_comp_fields OCCURS 0 WITH HEADER LINE.`

For 3. it is `DATA: gt_outtab  LIKE gt_table_fields OCCURS 0 WITH HEADER LINE.`

**Comment by larshp** [comment]
reproduced, it seems that when doing LIKE a table with header line it becomes the structure type,

```abap
TYPES: BEGIN OF ty_type,
         field TYPE c LENGTH 1,
       END OF ty_type.

DATA tab1 TYPE ty_type OCCURS 0 WITH HEADER LINE.

DATA tab2 LIKE tab1 OCCURS 0 WITH HEADER LINE.

LOOP AT tab2.
  WRITE tab2-field.
ENDLOOP.
```

**Comment by larshp** [comment]
try again, 2.39.23 published

**Comment by ed-holland** [comment]
Issue resolved. Thanks
