### ISSUE TITLE
Not a structure, ComponentName (check_syntax) - Select-Option values

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1249]
Issue:
```
./src/nw/#jcs#bc_insert_table_content.prog.abap[24, 3]                     - Not a structure, ComponentName (check_syntax)
```

Source:
![image](https://user-images.githubusercontent.com/53995991/91587603-48bd1800-e957-11ea-9918-40111b963af3.png)

Structure:
![image](https://user-images.githubusercontent.com/53995991/91587761-815cf180-e957-11ea-91c6-efa63a8692fc.png)

**Comment by larshp** [comment]
reproduced as

```abap
TYPES: BEGIN OF ty_type,
         fieldname TYPE c LENGTH 10,
       END OF ty_type.

DATA bar TYPE STANDARD TABLE OF ty_type WITH HEADER LINE.

SELECT-OPTIONS foo FOR bar NO INTERVALS LOWER CASE.

LOOP AT foo.
  WRITE foo-low.
ENDLOOP.
```

**Comment by larshp** [comment]
try again, 2.39.23 published

**Comment by ed-holland** [comment]
The message changed:
`./src/nw/#jcs#bc_insert_table_content.prog.abap[24, 3]                     - Component "low" not found in structure (check_syntax)`

Looks like he does not see the select-option as a range.

**Comment by larshp** [comment]
try again, 2.39.25 published

**Comment by ed-holland** [comment]
Issue resolved. Thanks.
