### ISSUE TITLE
Type of "lt_file" contains unknown: Type error, not a table type lt_char_file (unknown_types)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1254]
Issue:
`./src/ecc/#jcs#fi_gd13_check_compare.prog.abap[752, 18]                    - Type of "lt_file" contains unknown: Type error, not a table type lt_char_file (unknown_types)`

Source:
![image](https://user-images.githubusercontent.com/53995991/91653734-92b31480-eaa3-11ea-9c9a-3e03342393e9.png)

**Comment by larshp** [comment]
I cannot reproduce it, how is `lt_char_file` defined?

```
DATA: lt_char_file TYPE STANDARD TABLE OF i.

DATA BEGIN OF lt_file OCCURS 0.
DATA: line LIKE LINE OF lt_char_file,
     END OF lt_file.
```

**Comment by ed-holland** [comment]
Quite basic. It is inside a Form though.
![image](https://user-images.githubusercontent.com/53995991/91690876-f5211900-eb66-11ea-874f-1b542423b295.png)

**Comment by larshp** [comment]
reproduced as

```abap
DATA: BEGIN OF lt_char_file OCCURS 0,
        zstring(72),
      END OF lt_char_file.

DATA BEGIN OF lt_file OCCURS 0.
DATA: line LIKE LINE OF lt_char_file,
      END OF lt_file.
```

**Comment by larshp** [comment]
try again, 2.39.25 published

**Comment by ed-holland** [comment]
Issue resolved. Thanks.
