### ISSUE TITLE
Bad LENGTH (check_syntax) - On Select-Option

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1257]
Issue:
`./src/ecc/#jcs#bc_se16n_batch.prog.abap[51, 1]                             - Bad LENGTH (check_syntax)`

Source:
![image](https://user-images.githubusercontent.com/53995991/91696380-c2c7e980-eb6f-11ea-9866-8e6fb2e51291.png)

**Comment by larshp** [comment]
It looks like some of the typing of KABA00 is missing?

anyhow I'll add a fallback

**Comment by larshp** [comment]
try again, 2.39.26 published

**Comment by ed-holland** [comment]
issue resolved. Thanks.
