### ISSUE TITLE
Unexpected ENDFORM (structure)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1273]
Playground:
![image](https://user-images.githubusercontent.com/53995991/92223769-33894180-eea1-11ea-87a9-c6c2b01aa919.png)

source: 
MV45AFOI_TSW_UPDATE_WORKLIST_N

**Comment by larshp** [comment]
what happens if you delete the first 19 lines in the example above?

**Comment by ed-holland** [comment]
The same. It seems he has problems with the tabs though...
![image](https://user-images.githubusercontent.com/53995991/92261089-2be58f00-eed9-11ea-8a0a-5d201d2438a5.png)

**Comment by ed-holland** [comment]
Interestingly, when i remove all the tabs, the issue is gone... left one tab
![image](https://user-images.githubusercontent.com/53995991/92261357-9696ca80-eed9-11ea-8587-c3b0ab8fb862.png)
Removed last tab...
![image](https://user-images.githubusercontent.com/53995991/92261414-aadac780-eed9-11ea-9c97-bf60d2f1ab75.png)

Note that this source comes from a SAP program so it can not be changed.

**Comment by larshp** [comment]
```abap
form moo using value(bar)	type c.
endform.
```

**Comment by larshp** [comment]
try again, 2.41.2 published

**Comment by ed-holland** [comment]
Issue resolved. Thanks
