### ISSUE TITLE
new rule: prefer pragmas, over pseudo comments

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#1275]
example

`"#EC NO_HANDLER`

should be replaced with the corresponding pragma

**Comment by FreHu** [comment]
useful resource: https://blogs.sap.com/2019/09/11/what-are-pragmas-and-pseudo-comments-in-abap/

**Comment by larshp** [comment]
duplicate, see https://github.com/abaplint/abaplint/issues/3022
