### ISSUE TITLE
Unexpected ENDIF(structure) - parameters/name using &

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1276]
Playground:
![image](https://user-images.githubusercontent.com/53995991/92321365-a1f90b80-f029-11ea-94f4-dc2d633a52e6.png)

It might be two different issues. When removing the surrounding def/end-def the issue is still there.

**Comment by larshp** [comment]
try again, 2.41.3

**Comment by ed-holland** [comment]
Issue resolved. Thanks
