### ISSUE TITLE
Unexpected ENDIF (structure) - class method call

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1282]
Issue:
`/tmp/abaplint-EFnfbA/src/va/sd_dpp_mv45af0a_ag_pruefen.prog.abap[30, 2]   - Unexpected ENDIF (structure)`

Source (SD_DPP_MV45AF0A_AG_PRUEFEN):
![image](https://user-images.githubusercontent.com/53995991/92359028-d254ae80-f0ea-11ea-9713-b4c1e8fa7f49.png)

**Comment by larshp** [comment]
I think this is as expected, this kind of IF is not possible in 700

**Comment by ed-holland** [comment]
This is valid in 700...(did not find a boolean method)

![image](https://user-images.githubusercontent.com/53995991/92363990-ab01df80-f0f2-11ea-9fac-91733054c5fd.png)

**Comment by ed-holland** [comment]
Indeed the method only expression is a 740SP8 feature.

As the dependencies are generated in this release, the code is correct.
This creates an issue though as the linter was instructed to use 700. The executable parts are squashed to avoid this.

This include is used as follows (inside a form):
![image](https://user-images.githubusercontent.com/53995991/92367284-814ab780-f0f6-11ea-80b7-8b0b1f9a46e1.png)

Would it be possible to check if the include is inside a form and in this case not add it to dependency?

**Comment by ed-holland** [comment]
To be handled using [SCI Issue 147](https://github.com/abaplint/abaplint-sci-client/issues/147)
