### ISSUE TITLE
Errors in macro's report caller location/line and not macro location

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1285]
Issue:
`./src/ecc/#jcs#fi.fugr.#jcs#bapi_acc_document_check.abap[27, 3]  - Statement does not exist in ABAPv700(or a parser error), "fbgenmac" (parser_error)`

It is unclear where the error is coming from.

**Comment by larshp** [comment]
can you add an example?

this error is in line 7, as I would expect, the macro can be called multiple times

![image](https://user-images.githubusercontent.com/5888506/92395749-2039d880-f124-11ea-94c4-f34a6b04be5f.png)

**Comment by ed-holland** [comment]
Issues:
![image](https://user-images.githubusercontent.com/53995991/92395903-67c06480-f124-11ea-9af2-2807e4444d5e.png)

Macro is called like this:
![image](https://user-images.githubusercontent.com/53995991/92396002-8e7e9b00-f124-11ea-9e37-4201bcd53200.png)

**Comment by ed-holland** [comment]
Playground is showing the real error after including the source directly. 
Macro is called in Macro.

To identify the problem, one needs to know where in the macro it fails. Even if it means that this error is repeated for every call of the macro.

**Comment by larshp** [comment]
is it a nested macro, `fbgenmac` is called from inside another macro definition?

**Comment by ed-holland** [comment]
No, fbgenmac is calling read_fbgendat.

**Comment by larshp** [comment]
can you help building an example in the playground?

**Comment by ed-holland** [comment]
Tried reproducing in Playground but was not able to.
fbgenmac is used to debug function modules (from SAP and stores the call input). It is in an include and called at the start of a function module.

**Comment by ed-holland** [comment]
closing until it happens again ;-)
