### ISSUE TITLE
unused_variables: LOG-POINT

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1287]
`
REPORT zfoobar.
CONSTANT foo TYPE c VALUE 'FOO'.
CONSTANT bar TYPE c VALUE 'BAR'.
LOG-POINT ID baz SUBKEY foo FIELDS bar.
`

+minor code coloring issue

![image](https://user-images.githubusercontent.com/59966492/92430714-9447a100-f163-11ea-82d2-603f9a2cb8c3.png)

**Comment by larshp** [comment]
code highlighting, we've collected issues in https://github.com/abaplint/abaplint/issues/554, for now we are awaiting new release of https://github.com/microsoft/monaco-languages, and will after that start collecting issues again
