### ISSUE TITLE
Playground: Monarch bugs / highlighting #2

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#1292]
add issues below, note that some bugs have been fixed, currently awaiting new release of monaco-editor

**Comment by mbtools** [comment]
- Terms with hyphen 
AT... VALUE-**REQUEST**
AT **SELECTION**-SCREEN ... 
DATA ... READ-**ONLY**
LOG-**POINT**
**AUTHORITY**-CHECK ...
FIELD-**SYMBOL**
TYPE-**POOLS**

- Selection screen
**COMMENT**
**PUSHBUTTON**
RADIOBUTTON **GROUP**
**MEMORY** ID
**TABBED**
**USER-COMMAND**
**SUBSCREEN**

- Operators
IF ... **CA** ... **CP** ... **BETWEEN** (+other C/Nx operators)
IF ... **NOT** / **OR** / **AND**

- Class/Interface
METHOD ... **PREFERRED PARAMETER**
INTERFACES ... **PARTIALLY IMPLEMENTED**

- Others
**CONSTANT**
SUBMIT ... **VIA** ... **AND** RETURN
SORT ... AS **TEXT**
WRITE ... AS **ICON**
SPLIT ... IN CHARACTER **MODE**
**FORM** foo. ... ENDFORM

- Red characters which look like they are invalid 
**@, #, \`** (backtick)
SELECT foo,bar FROM tab INTO TABLE @lt_tab.
WRITE foo ##foobar.
moo = VALUE #( ... ).
foo = \`  \`.

**Comment by larshp** [comment]
this can be started now, but @mbtools it looks like some of the above bugs were already fixed in https://github.com/microsoft/monaco-languages/pull/87, so the above list needs to be updated with to reflect bugs in monaco-editor 0.21.0

**Comment by mbtools** [comment]
this cost me a day... there were over 500 hundred missing keywords, data types, and operators! the highlighting should be fixed with this. we will have to see if this also takes care of the red characters mentioned above. 

https://github.com/microsoft/monaco-languages/pull/112
unfortunately, some build issue which I can't figure out

I will send you my XLS with all ~1000 keywords. if you have nothing else to do, you could check if they all exist in abaplint ;-)

**Comment by larshp** [comment]
think most of the red characters from above was fixed in the previous release(released yesterday)

**Comment by larshp** [comment]
also note when https://github.com/abaplint/abaplint/issues/682 is implemented, all this will be fixed, the editor highlighting will do the first fast highlighting, and the slow will kick in later

that way something like `DATA DATA TYPE TYPE.` will highlight correctly

**Comment by mbtools** [comment]
all checks passed https://github.com/microsoft/monaco-languages/pull/112 :-)

**Comment by larshp** [comment]
its merged now, so awaiting next release of monaco-languages and monaco-editor

**Comment by larshp** [comment]
https://github.com/microsoft/monaco-editor/blob/master/CHANGELOG.md#0211-24092020

**Comment by larshp** [comment]
closing, open new issue for new issues
