### ISSUE TITLE
SCI result: Unexpected ENDOFDEFINITION

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1293]
![image](https://user-images.githubusercontent.com/59966492/92553103-27e6a380-f230-11ea-9e7b-cab23127ca12.png)

Unexpected ENDOFDEFINITION, %3CCONTRO%3E.PROG.ABAP

There are no macros in this code. Any idea what it's related to?

**Comment by larshp** [comment]
does it `INCLUDE <CONTRO>` somewhere?

are you running the latest version? <CONTRO> was fixed sometime last week as far as I remember

**Comment by mbtools** [comment]
After lint server got the bump from 2.40 to 2.42.1 the issue was gone (not sure why it skipped some). The <contro> include is one of those hidden things SAP adds to the byte code when you use for example tabs on the selection screen
