### ISSUE TITLE
Macros and line_break_multiple_parameters

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1298]
```
REPORT zfoobar.
DEFINE my_macro.
  cl_msg=>print(
    msgv1 = &1
    msgv2 = &2
    msgv3 = &3
    msgv4 = &4 ).
END-OF-DEFINITION.
my_macro 'This' 'is' 'test' 'message'.
my_macro 'This'
  'is'
  'test'
  'message'.
```

/zfoobar.prog.abap[11, 1]: Line break multiple parameters(line_break_multiple_parameters)
/zfoobar.prog.abap[11, 1]: Line break multiple parameters(line_break_multiple_parameters)
/zfoobar.prog.abap[11, 1]: Line break multiple parameters(line_break_multiple_parameters)
/zfoobar.prog.abap[13, 1]: Line break multiple parameters(line_break_multiple_parameters)
/zfoobar.prog.abap[13, 1]: Line break multiple parameters(line_break_multiple_parameters)
/zfoobar.prog.abap[13, 1]: Line break multiple parameters(line_break_multiple_parameters)

Expanding macro might be missing the line-breaks.

**Comment by larshp** [comment]
the rule will now be skipped for macro contents

**Comment by larshp** [comment]
try again, 2.42.4 published

**Comment by larshp** [comment]
closing
