### ISSUE TITLE
indentation: Ignore generated FUGR

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1300]
Add "ignoreGeneratedFunctionGroup" option to avoid issues with generated table maintenance code

**Comment by larshp** [comment]
right now the function group is considered generated if there is a TOBJ object for it, https://github.com/abaplint/abaplint/blob/3c7e2dafb285a63d90f6b70d75d5bbd41148966c/packages/core/src/skip_logic.ts#L76

can you help making an public repository with an example which causes the error?

**Comment by larshp** [comment]
the new top level exclude might work for you, https://github.com/abaplint/abaplint/issues/1309

**Comment by mbtools** [comment]
closing this in favor of https://github.com/abaplint/abaplint-sci-client/issues/155#issuecomment-696086309
