### ISSUE TITLE
Errors in config comments

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1315]
abaplint can now handle jsonc, but the comments still show up as errors:

![](https://user-images.githubusercontent.com/5097067/93177019-6b5e7780-f732-11ea-8c16-b2b21944b6ec.png)

By default abaplint will look for an abaplint.json, so you can't rename it to jsonc. I think abaplint should also look for an abaplint.jsonc.

**Comment by larshp** [comment]
yea, and/or `.json5`

**Comment by larshp** [comment]
try again, 2.44.0 published

**Comment by larshp** [comment]
the jsonc and json5 extensions was also added in the vscode extension, so it should recognize/use the schema

**Comment by FreHu** [comment]
i was just going to submit the autocompletion issue :)

**Comment by larshp** [comment]
it should work in the latest version, published ~1 hour ago
