### ISSUE TITLE
Missing predefined type int8

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1317]
![](https://user-images.githubusercontent.com/5097067/93190620-df554b80-f743-11ea-90ff-312b5711857a.png)

abaplint reports `Type of "iv_operand1" contains unknown: INT8 not found, lookup (unknown_types)`

**Comment by larshp** [comment]
heh, thats funny, INT4 is a DDIC object, but INT8 is built-in 😄

**Comment by larshp** [comment]
try again, 2.44.0 published
