### ISSUE TITLE
New rule: use xsdbool

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1341]
https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#use-xsdbool-to-set-boolean-variables

Should not be hard to detect.

Whenever there is
```abap
if cond_expr.
  var = abap_true.
else.
  var = abap_false.
endif.
```
it can be replaced with `var = xsdbool( cond_expr )`.

**Comment by larshp** [comment]
👍  

similar to https://github.com/abaplint/abaplint/issues/545

**Comment by FreHu** [comment]
there are some releases where you have boolc and not xsdbool, the message/fix could be adapted based on version

**Comment by larshp** [comment]
agree

**Comment by larshp** [comment]
starting this now
