### ISSUE TITLE
use_bool_expression - improvements

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1346]
`Use boolc instead of IF (use_bool_expression)`

- Should underline `if` not first assignment
- Mention expression from `if` statement in message
- In case the condition is supposed to be reversed, the message should also mention it
```
IF lv_state IS INITIAL.
  rv_bool = abap_false.
ELSE.
  rv_bool = abap_true.
ENDIF.
```

**Comment by larshp** [comment]
yea, should add the quick fix sometime

**Comment by larshp** [comment]
try again, 2.48.4 published

**Comment by FreHu** [comment]
quickfix seems to work, also with negated expressions :+1:
