### ISSUE TITLE
prefer_is_not - exclude method calls

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1348]
Example: `if not is_valid( ).`

**Comment by larshp** [comment]
just method calls? I'd suggest it to exclude all short form IFs, supposed we move in this direction,

example
`IF NOT lv_bool.`

**Comment by FreHu** [comment]
`IF NOT lv_bool` does not compile.

**Comment by larshp** [comment]
oh, okay 😄

**Comment by larshp** [comment]
try again, 2.48.4 published
