### ISSUE TITLE
Idoc in customer namespace not allowed

### ISSUE THREAD

**Issue by DennisLybecker-INVIXO** [abaplint/abaplint#1354]
An error occurs when creating idocs in customer namespace.

This is ok in SAP. 

I have had a look at #850 and note 104010. 

Should Idocs be allowed ìn customer namespace by abaplint?

**Comment by larshp** [comment]
@DennisLybecker-INVIXO thanks, try again, 2.48.2 published

**Comment by DennisLybecker-INVIXO** [comment]
> @DennisLybecker-INVIXO thanks, try again, 2.48.2 published

Perfect, thanks.

**Comment by larshp** [comment]
I'm assuming it worked? closing

**Comment by DennisLybecker-INVIXO** [comment]
Yes, it works.
