### ISSUE TITLE
Select for customer namespace tables

### ISSUE THREAD

**Issue by DennisLybecker-INVIXO** [abaplint/abaplint#1356]
The following select statement is OK for table ZTEST in the linter playground, but fails when using namespace. 

`SELECT DISTINCT roosourcet~oltpsource,
        roosourcet~txtsh,
        roosourcet~txtmd,
        roosourcet~txtlg INTO TABLE @DATA(lt_roosourcet)
        FROM roosourcet JOIN /xyz/ztest ON /xyz/ztest~oltpsource = roosourcet~oltpsource
        FOR ALL ENTRIES IN @lt_active
        WHERE roosourcet~oltpsource = @lt_active-oltpsource
        AND roosourcet~objvers = 'A'
        AND roosourcet~langu = 'E'.`

Error:"Statement does not exist in ABAPv754(or a parser error), "SELECT""

**Comment by larshp** [comment]
```abap
SELECT DISTINCT roosourcet~oltpsource,
        roosourcet~txtsh,
        roosourcet~txtmd,
        roosourcet~txtlg INTO TABLE @DATA(lt_roosourcet)
        FROM roosourcet JOIN /xyz/ztest ON /xyz/ztest~oltpsource = roosourcet~oltpsource
        FOR ALL ENTRIES IN @lt_active
        WHERE roosourcet~oltpsource = @lt_active-oltpsource
        AND roosourcet~objvers = 'A'
        AND roosourcet~langu = 'E'.
```

**Comment by larshp** [comment]
@DennisLybecker-INVIXO try again, 2.48.3 published

**Comment by DennisLybecker-INVIXO** [comment]
> @DennisLybecker-INVIXO try again, 2.48.3 published

Yes, it works. Thanks for the help .
