### ISSUE TITLE
Idea: allow dependency classes have definition only [discussion]

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint#1364]
Continued from here: https://github.com/abaplint/abaplint-sci-client/pull/181#issuecomment-696630174

>>>> P.S. BTW, does the dependency classes serialized completely ? Or just definition ? It could speed up things

>>>dependencies are reduced, so something like method definitions are removed, among other things

>>I guess it makes sense to remove whole implementation. Well, anyway, just an idea

> it removes as much as possible, while still keeping abaplint happy, ie global classes must have an IMPLEMENTATION

theoretically abaplint may ignore complete class implementation if it knows that the class is not a check subject but a dependency

Advantages:
- less data to send in e.g. abaplint-server
- less data to store in dependency repos (e.g. if it is sap code)
- less parsing power required (?)

**Comment by larshp** [comment]
Below is a screenshot of how it looks today, via method [BUILD_CLAS_CODE](https://github.com/abaplint/abaplint-sci-client/blob/662bdffe1be2f532c694fd7753b840ea8165b7f2/src/deps/zcl_abaplint_deps_serializer.clas.abap#L81)

If removing IMPLEMENTATION it will require core changes in abaplint to allow this special kind of syntax error(IMPLEMENTATION missing).

I'll also claim/guess that deleting from row 259 and down in the screenshot, will gain only few overall percentages

![image](https://user-images.githubusercontent.com/5888506/93872112-f78f1280-fccf-11ea-94ec-d6f0d8a4d627.png)

**Comment by sbcgua** [comment]
Ah, so method code is actually stripped. I didn't know it. Then this makes sense, I agree the impact is minimal.

**Comment by sbcgua** [comment]
closing then, thanks for the example

**Comment by larshp** [comment]
function module bodies, FORM bodies, dynpro XMLs are also stripped

perhaps more, don't exactly remember
