### ISSUE TITLE
Change message "Unknown object type, add/change filename eg zclass.clas.abap or zprogram.prog.abap"

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1376]
If you have an unsupported object, you get the message

`Unknown object type, add/change filename eg zclass.clas.abap or zprogram.prog.abap`

It's more likely that this is an object abaplint can't handle than a naming error. The message should instead suggest to put the file in the global exclude (or add support for it).

**Comment by larshp** [comment]
I added the message in case the user opens a file "foobar.abap", so suggest the above if there are at least two "."'s in the filename

**Comment by larshp** [comment]
I've changed the error message in 2.49.2, turned out that "foobar.abap" files are ignored, closing
