### ISSUE TITLE
Select using package size result in ENDTRY error in class

### ISSUE THREAD

**Issue by DennisLybecker-INVIXO** [abaplint/abaplint#1382]
For the code below I get an Endtry error. 

I belive its because of the ENDSELECT. 
The endselect is needed for selecting with package size.

![image](https://user-images.githubusercontent.com/46812361/94235536-08c46300-ff0c-11ea-86cc-0a10ea1b4992.png)

`CLASS cl_read DEFINITION
  PUBLIC
  CREATE PUBLIC .

  PROTECTED SECTION.

    METHODS read_table.
ENDCLASS.

CLASS CL_READ IMPLEMENTATION.

* <SIGNATURE>---------------------------------------------------------------------------------------+
* | Instance Protected Method cl_read->READ_TABLE_INIT
* +-------------------------------------------------------------------------------------------------+
* +--------------------------------------------------------------------------------------</SIGNATURE>
    METHOD read_table.
    DATA(lv_pack) = 10.

    TRY.
        SELECT * from mara
          INTO TABLE @<lt_mara> PACKAGE SIZE @lv_pack.
       "Do something
       endselect.

      CATCH cx_root INTO DATA(lx__error).
       "Do something
    ENDTRY.
ENDMETHOD.

ENDCLASS.`

**Comment by larshp** [comment]
reproduced as
![image](https://user-images.githubusercontent.com/5888506/94236422-7b820e00-ff0d-11ea-96e8-55edeebf67a8.png)

**Comment by larshp** [comment]
@DennisLybecker-INVIXO try again, 2.49.3 published

**Comment by DennisLybecker-INVIXO** [comment]
> @DennisLybecker-INVIXO try again, 2.49.3 published

The endtry error is solved. Thanks
Still get the "Avoid use of ENDSELECT" should I create a separate issue for this one?

**Comment by larshp** [comment]
I'll add ENDSELECT as okay when there is a corresponding PACKAGE SIZE 

until its fixed, suggest changing the configuration for the rule to not report ENDSELECTS, https://rules.abaplint.org/avoid_use/

**Comment by larshp** [comment]
@DennisLybecker-INVIXO try again, 2.50.0 published

**Comment by larshp** [comment]
@DennisLybecker-INVIXO did it work out?

**Comment by DennisLybecker-INVIXO** [comment]
@larshp  Yes, thanks. I'll close
