### ISSUE TITLE
Fix in-statement indentation error for select statement with endselect.

### ISSUE THREAD

**Issue by DennisLybecker-INVIXO** [abaplint/abaplint#1384]
First select no errors. Second one indentation error. Possible due to "Package size/end select" ?

Which is the correct indentation? 

        SELECT (ls_dynamic-fields)
          FROM (ls_dynamic-from)
          UP TO @ls_dynamic-count ROWS
          INTO TABLE @<lt_data>
          WHERE (ls_dynamic-where)
          ORDER BY (ls_dynamic-sort).

        SELECT (ls_dynamic-fields)
          FROM (ls_dynamic-from)
          UP TO @is_init_read-max_rec ROWS
          INTO TABLE @<lt_data>
          PACKAGE SIZE @is_init_read-pack_size
          WHERE (ls_dynamic-where).

**Comment by larshp** [comment]
the first statement is not a SELECT loop? ie. without ENDSELECT?

The second is a loop? Its difficult to tell looking at above

**Comment by larshp** [comment]
yea, the second statement does not syntax check,

![image](https://user-images.githubusercontent.com/5888506/94256486-299bb100-ff2a-11ea-9521-a80154ff8667.png)

**Comment by larshp** [comment]
I guess the rule causing the problem is https://rules.abaplint.org/in_statement_indentation/ ?

following works, and syntax checks,

```abap
DATA lv_str TYPE string.
FIELD-SYMBOLS <lt_data> TYPE ANY TABLE.

SELECT (lv_str)
  FROM (lv_str)
  UP TO 100 ROWS
  INTO TABLE @<lt_data>
  WHERE (lv_str)
  ORDER BY (lv_str).

SELECT (lv_str)
    FROM (lv_str)
    UP TO 100 ROWS
    INTO TABLE @<lt_data>
    PACKAGE SIZE 10
    WHERE (lv_str).
  WRITE 'hello world'.
ENDSELECT.
```

**Comment by DennisLybecker-INVIXO** [comment]
Yes, thanks
