### ISSUE TITLE
Playground: Monaco coloring of operators/identifiers

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1391]
The recent update has fixed most issues. However, operators and identifiers have the same color (white) and the color for numbers is only slightly different.

![image](https://user-images.githubusercontent.com/59966492/94299941-50f87b00-ff36-11ea-8e39-bb639fffb9cd.png)

Can the colors be adjusted? Where is the setting for that?

**Comment by FreHu** [comment]
In tmlanguage, you can't change the colors, only provide a list of scopes. In monaco tmlanguage is not used, but these look like scope names so maybe it is a similar mechanism:
https://github.com/microsoft/monaco-languages/pull/112/files#diff-1e2d055105af4ff62911f2f32d94aeb8R1095

In vscode, the scope 'keyword.operator.abap' does not have a default color either, you have to add it in the settings manually
```
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "keyword.operator.abap",
                "settings": {
                    "foreground": "#d456b9"
                }
            }
      ]
}
```
Of course in monaco you don't have settings.

You can always misuse scope names to get better default colors :). There are some "standard" scope names, but editors choose what to color kind of arbitrarily.

Or maybe this is really a question for why operators don't have a color by default in vscode.

**Comment by mbtools** [comment]
I found a snippet that shows how to define a custom theme with different colors:
https://github.com/microsoft/monaco-editor/issues/1815
with a color from here:
https://github.com/fabiospampinato/khroma/blob/fa81639c242fdcf6492c36e2fb85f04664e042da/src/color/keyword.ts#L13-L161

```
monaco.editor.defineTheme('myCustomTheme', {
	base: 'vs',
	inherit: true,
	rules: [
		{ token: 'operator', foreground: '<color>' }
	]
});
```

I'm not sure where this would need to go

**Comment by FreHu** [comment]
This would have to be part of the playground code and not the core monaco grammar. I guess it would at least fix the problem somewhere, but currently I like my solution to mislabel operators as keywords more :)

**Comment by larshp** [comment]
fixed, and/or out of scope for this repo?

**Comment by mbtools** [comment]
Fixed 👍
