### ISSUE TITLE
Parser error for  "APPEND" expression

### ISSUE THREAD

**Issue by pawelwiejkut** [abaplint/abaplint#1395]
Hello team,

`APPEND VALUE #( tabname = to_upper('rsddstatdtp') fieldname = to_upper('requid')  ) TO lt_fields.`

https://github.com/pawelwiejkut/bw_toolbox/runs/1170240477
https://travis-ci.com/github/pawelwiejkut/bw_toolbox/builds/186820773

Can you please check?

**Comment by larshp** [comment]
add the proper spacing, and it will work

```abap
APPEND VALUE #( tabname = to_upper( 'rsddstatdtp' ) fieldname = to_upper( 'requid' ) ) TO lt_fields.
```

**Comment by pawelwiejkut** [comment]
It works, thank you!
