### ISSUE TITLE
cast, todo, infer type

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1409]
the type is the type of the importing parameter, which is resolved

![](https://user-images.githubusercontent.com/5097067/94611837-97393b80-02a2-11eb-844d-3cd5071a914c.png)

**Comment by larshp** [comment]
yea, lots of stuff still missing for parameters 👍

**Comment by larshp** [comment]
this might have been fixed, but need to reproduce the scenario in the playground

**Comment by larshp** [comment]
@FreHu try again in the latest, I think this works

**Comment by FreHu** [comment]
i think so
