### ISSUE TITLE
indentation - SELECTION-SCREEN BEGIN OF BLOCK

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1413]
```abap
SELECTION-SCREEN BEGIN OF BLOCK table_compare WITH FRAME TITLE TEXT-006.
PARAMETERS:
      p_diff AS CHECKBOX DEFAULT abap_true MODIF ID exl,
      p_tech AS CHECKBOX DEFAULT abap_true MODIF ID exl,
      p_obsl AS CHECKBOX DEFAULT abap_true MODIF ID exl.
SELECTION-SCREEN END OF BLOCK table_compare.
```

**Comment by larshp** [comment]
which errors do you expect for above? or should the code be changed when triggering pretty printer?

**Comment by FreHu** [comment]
I expect this to be counted as a block for indentation purposes. I mean, it's literally a block :). Also you can nest them so it makes sense visually.

So in my example `parameters` should be indented
```
SELECTION-SCREEN BEGIN OF BLOCK table_compare WITH FRAME TITLE TEXT-006.
  PARAMETERS:
        p_diff AS CHECKBOX DEFAULT abap_true MODIF ID exl,
        p_tech AS CHECKBOX DEFAULT abap_true MODIF ID exl,
        p_obsl AS CHECKBOX DEFAULT abap_true MODIF ID exl.
SELECTION-SCREEN END OF BLOCK table_compare.
```

**Comment by g-back** [comment]
Note that the SAP pretty printer will NOT indent this (and will also remove indentations at least in 740sp20)

**Comment by FreHu** [comment]
On my basis 781 it does indent them, showcasing the power of S4/HANA.

![](https://user-images.githubusercontent.com/5097067/94833549-8b1ebc80-040f-11eb-83e5-a596949e19ac.png)

**Comment by FreHu** [comment]
well i guess it can be parametrized

**Comment by mbtools** [comment]
+1 for parameter 

The PP already indents the selection screen blocks in 754.

**Comment by larshp** [comment]
@FreHu try again, 2.74.46
