### ISSUE TITLE
keyword_case: SYSTEM-CALL OBJMGR CLONE 

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1426]
`SYSTEM-CALL OBJMGR CLONE me TO result`

OBJMGR CLONE is treated incorrectly like identifiers, not as keywords. (standard pretty printer will uppercase them)

**Comment by larshp** [comment]
ugh, there is a lot of different SYSTEM-CALL, I'll try adding just the above

**Comment by larshp** [comment]
try again, 2.56.0
