### ISSUE TITLE
Rule: unknown_types does not recognise predefined numeric types DECFLOAT16 and DECFLOAT34

### ISSUE THREAD

**Issue by d023604** [abaplint/abaplint#1434]
The rule unknown_types does not recognise predefined numeric types DECFLOAT16 and DECFLOAT34 available in release 740/750
![image](https://user-images.githubusercontent.com/12813491/95693153-975c1280-0c76-11eb-8a17-0263c784f25e.png)

**Comment by larshp** [comment]
thanks for the bug report 👍 

```abap
DATA my_decfloat34 TYPE decfloat34.
DATA my_decfloat16 TYPE decfloat16.
```

**Comment by larshp** [comment]
try again, 2.57.2

**Comment by d023604** [comment]
Tested OK.  No unknown_types errors reported.

`REPORT zreport.`

`DATA mydecfloat34 TYPE decfloat34.`
`DATA mydecfloat16 TYPE decfloat16.`

`FORM abc.`
  `mydecfloat16 = 1.`
  `mydecfloat34 = 2.`
`ENDFORM.`

`PERFORM abc.`
