### ISSUE TITLE
indentation: Rule expects different indentation then before - SELECT

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1435]
abaplint 2.57.1

Issue:
```
./src/ecc/#jcs#ext_run_erp.fugr.#jcs#ddr_reports_import.abap[23, 5] - Indentation problem, expected 2 spaces (indentation) [E]
./src/ecc/#jcs#ext_run_erp.fugr.#jcs#rw_groups_import.abap[97, 7]   - Indentation problem, expected 4 spaces (indentation) [E]
```

Code Examples:
![image](https://user-images.githubusercontent.com/53995991/95738088-f9257800-0c88-11eb-9548-f2d91bbf3b56.png)

![image](https://user-images.githubusercontent.com/53995991/95738267-3b4eb980-0c89-11eb-9338-0934a813767d.png)

Note:
all found occurrences of the select statement contain a comment at the end of the select line

**Comment by larshp** [comment]
can it be reproduced in the playground?

**Comment by ed-holland** [comment]
Yes.
![image](https://user-images.githubusercontent.com/53995991/95740710-4f94b580-0c8d-11eb-9098-71b5d3161ec3.png)

Removing the comment resolves the issue:
![image](https://user-images.githubusercontent.com/53995991/95740767-66d3a300-0c8d-11eb-8b0c-21d92471a45e.png)

**Comment by ed-holland** [comment]
Cause of Issue might be the same also for #1436 and #1437

**Comment by larshp** [comment]
thanks, reproduced as

```abap
SELECT * FROM bar "sdfsd
    WHERE moo = 2.
  WRITE 'sdf'.
ENDSELECT.
```

![image](https://user-images.githubusercontent.com/5888506/95743053-6210ee00-0c91-11eb-8780-380b14901f1f.png)

**Comment by larshp** [comment]
try again, 2.57.2

**Comment by ed-holland** [comment]
Issue resolved. Thanks.
