### ISSUE TITLE
indentation: Rule expects different indentation then before - CASE

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1436]
abaplint 2.57.1

Issue:
```
./src/ecc/#jcs#fi.fugr.#jcs#fi_check_tcode_lock.abap[43, 7]         - Indentation problem, expected 4 spaces (indentation) [E]
```

Code:
![image](https://user-images.githubusercontent.com/53995991/95738611-cb8cfe80-0c89-11eb-8327-adeba4c55cb9.png)

**Comment by ed-holland** [comment]
Playground:
![image](https://user-images.githubusercontent.com/53995991/95742950-2ece5f00-0c91-11eb-8272-f011603ca619.png)

**Comment by larshp** [comment]
try again, 2.57.2

**Comment by ed-holland** [comment]
Issue resolved. Thanks.
