### ISSUE TITLE
indentation: Rule expects different indentation then before - IF

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1437]
abaplint 2.57.1

Issue:
```
./src/ecc/#jcs#fipi.fugr.#jcs#fi_posting_intf_clearing.abap[81, 7]  - Indentation problem, expected 4 spaces (indentation) [E]
```

Code:
![image](https://user-images.githubusercontent.com/53995991/95738878-39d1c100-0c8a-11eb-8c47-8d6f9ebd5a5b.png)

**Comment by ed-holland** [comment]
Playground
![image](https://user-images.githubusercontent.com/53995991/95743066-6806cf00-0c91-11eb-9d8e-59148d147092.png)

Removing the comment on line 5 resolves the issue.

**Comment by larshp** [comment]
try again, 2.57.2

**Comment by ed-holland** [comment]
Issue resolved. Thanks.
