### ISSUE TITLE
check_syntax: FUGR top include fields not found anymore

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1438]
abaplint 2.57.1

Issue:
```
./src/ecc/#jcs#fipi.fugr.#jcs#lfipif01.abap[19, 3]                  - sgfunct not found, findTop (check_syntax) [E]
./src/ecc/#jcs#fipi.fugr.#jcs#lfipif01.abap[28, 7]                  - tcode not found, findTop (check_syntax) [E]
```

Top Source:
![image](https://user-images.githubusercontent.com/53995991/95739179-b5cc0900-0c8a-11eb-9726-5d8aef38e091.png)

Fugr Include Source:
![image](https://user-images.githubusercontent.com/53995991/95739234-cf6d5080-0c8a-11eb-8dad-01069ee1d474.png)

**Comment by larshp** [comment]
ok in https://github.com/larshp/FUGR4/blob/main/src/zfugr4.fugr.lzfugr4f01.abap

**Comment by ed-holland** [comment]
Namespace issue?

VC shows no attributes of the fields.

**Comment by larshp** [comment]
Line 253, its part of a chain, are there any other errors in that chain? 

Are there any other rules disabled like the unknown_types? 

Are there any other issues for this object, except for the two mentioned above?

**Comment by ed-holland** [comment]
After debugging together with @larshp we identified the source of the problem. The Top file was part of the global exclude. This caused the fields not to be found.

Global Excludes where used to remove rule errors from SAP original code. The excludes need to be moved back to the rules.
Alternative could be a global setting to ignore errors from SAP original code.
