### ISSUE TITLE
check_syntax: form in include not found

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1439]
abaplint 2.57.1

Issue:
```
./src/nw/#jcs#parameter_maintenance_fca.prog.abap[39, 3]            - FORM definition "f4_file_name" not found (check_syntax) [E]
```

Source:
![image](https://user-images.githubusercontent.com/53995991/95741373-6ee01280-0c8e-11eb-971a-503da225fcb7.png)

The form is in the include mentioned in the screenshot.

**Comment by larshp** [comment]
Can not reproduce, see https://github.com/larshp/FUGR4/tree/main/src

**Comment by ed-holland** [comment]
The form has a CHANGING parameter. Could that be the cause?
![image](https://user-images.githubusercontent.com/53995991/95746969-ea928d00-0c97-11eb-8071-b716d29d0c1f.png)

VC says that it can not find the include (although it is in the same folder). A possible cause?

**Comment by larshp** [comment]
best to trust the command line 😄 

but while in vscode, try removing the CHANGING part, save the files, run the command line again

**Comment by larshp** [comment]
CHANGING seems okay, https://github.com/larshp/FUGR4/commit/c5bf64e142e8335c5d0e35673e4c767550b80c23

**Comment by ed-holland** [comment]
Reduces test-set which still has the issue.
[nw.zip](https://github.com/abaplint/abaplint/files/5369805/nw.zip)

**Comment by ed-holland** [comment]
After debugging together with @larshp we identified the source of the problem. The F01 file was part of the global exclude. This caused the forms not to be found.

Global Excludes where used to remove rule errors from SAP original code. The excludes need to be moved back to the rules.
Alternative could be a global setting to ignore errors from SAP original code.
