### ISSUE TITLE
unknown_types: TYPE LINE OF not recognized

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1440]
abaplint 2.57.1

Issue:
`./src/nw/#jcs#sql.fugr.#jcs#lsqlf01.abap[757, 9]                    - Type of "l_field" contains unknown: TYPE LINE OF, could not resolve type (unknown_types) [E]`

Source:
![image](https://user-images.githubusercontent.com/53995991/95741608-d1d1a980-0c8e-11eb-93f0-3c80092eeedf.png)

**Comment by larshp** [comment]
I've improved the error message in 2.57.2, try again?

**Comment by ed-holland** [comment]
Still there.

**Comment by larshp** [comment]
what does the error message say now?

**Comment by ed-holland** [comment]
subtle difference

`./src/nw/#jcs#sql.fugr.#jcs#lsqlf01.abap[757, 9]         - Type of "l_field" contains unknown: TYPE LINE OF, unexpected type (unknown_types) [E]`

**Comment by larshp** [comment]
got it, fixing

**Comment by larshp** [comment]
try again with 2.57.3, did some changes, but not sure its fixed

**Comment by ed-holland** [comment]
Issue is resolved. Thanks
