### ISSUE TITLE
check_syntax: component not found in table where field is in include structure

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1441]
abaplint 2.57.1

Issue:
`./src/ecc/#jcs#hr_pa03.prog.abap[1022, 7]                           - Component "abrdt" not found in structure (check_syntax) [E]`

DDIC Table:
![image](https://user-images.githubusercontent.com/53995991/95742241-f9754180-0c8f-11eb-8a4b-f51c5e6d4932.png)

The Deps repository contains both the table PA0003 (containing the include structure) and PS0003 (containing the field).

**Comment by larshp** [comment]
whats the statement with the issue?

Does
```abap
DATA foo1 TYPE ps0003.
DATA foo2 TYPE ps0003-abrdt.
DATA foo3 TYPE pa0003-grpvl.
```
work?

**Comment by larshp** [comment]
try again with 2.57.3, did some changes, but not sure its fixed

**Comment by ed-holland** [comment]
Issue Resolved. Thanks
