### ISSUE TITLE
check_syntax: Cannot read property 'DD03P_TABLE' of undefined

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1444]
abaplint 2.57.3

Issue:

`./src/isu/#redwood#1isu.fugr.lfkkaktiv2dat.abap[144, 1] - Cannot read property 'DD03P_TABLE' of undefined (check_syntax) [E]`

Source:
![image](https://user-images.githubusercontent.com/53995991/95825494-3c3b2600-0d31-11eb-964e-4afdd8f09dcd.png)

Note: Issue occurs with AbapLint and SCI.

**Comment by ed-holland** [comment]
Table Details:
![image](https://user-images.githubusercontent.com/53995991/95826173-37c33d00-0d32-11eb-875e-e424e8ddea84.png)

**Comment by larshp** [comment]
also try running ZABAPLINT_DEBUG and check the contents of the XML files

**Comment by larshp** [comment]
try with 2.57.4, it might give a different error

**Comment by ed-holland** [comment]
After checking the DFKKOP table and it's includes, i found these includes:
![image](https://user-images.githubusercontent.com/53995991/95838873-98f30c80-0d42-11eb-8f4f-6b6d45147585.png)

These includes exist in the dictionary but are switched off
![image](https://user-images.githubusercontent.com/53995991/95838954-b3c58100-0d42-11eb-8015-c045c0c65d3e.png)

The dependency generate does not generate any fields for these includes, ergo causing the error.

I've reran abaplint with the new version and we now have a more clear message:
`./src/isu/#redwood#1isu.fugr.lfkkaktiv2dat.abap[144, 1] - Structure does not contain any components (check_syntax) [E]`

Could the include/table causing this be added to the message?

**Comment by larshp** [comment]
try again, 2.57.5

**Comment by ed-holland** [comment]
Message is improved. Thx.
`./src/isu/#redwood#1isu.fugr.lfkkaktiv2dat.abap[144, 1] - Table/Structure SI_FKKOPR does not contain any components (check_syntax) [E]`

List Dependencies for FKKOP:
![image](https://user-images.githubusercontent.com/53995991/95980327-49cdda00-0e1d-11eb-897a-b1343534000a.png)

Should this dependency be removed if the switch is not active?

**Comment by larshp** [comment]
hmm, that might be difficult and/or slow to determine

**Comment by ed-holland** [comment]
When running dependency with log/download...
![image](https://user-images.githubusercontent.com/53995991/95984917-32461f80-0e24-11eb-9383-438e1f3566ab.png)

The include structures are generated without fields. The alternative would be to generated the fields (they exist in DD03L).
It would anyway be good if these fields are generated as they could be referenced in switched-code.

By using state=M (call to DDIF_TABL_GET) the fields are retrieved.

Would that cause other issues?

**Comment by larshp** [comment]
having too many fields would be okay

**Comment by ed-holland** [comment]
[Pull Request](https://github.com/ed-holland/abapgit/pull/1)

**Comment by ed-holland** [comment]
The change works well for the Linter, but SCI still shows the issue.
![image](https://user-images.githubusercontent.com/53995991/96224814-6fc7bb80-0f90-11eb-833f-07c5cf951a15.png)

**Comment by ed-holland** [comment]
The SCI error comes from the cache. After disabling the cache, the error is gone.
is there a way to force the cache to be rebuild?

**Comment by ed-holland** [comment]
Created issue [SCI #212](https://github.com/abaplint/abaplint-sci-client/issues/212) for the clear cache.
