### ISSUE TITLE
RAISE EXCEPTION NEW, only 752 and up

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1446]
Atually not just new, but any kind of expression in this position.

From 752 release notes:

**Exception Object After RAISE EXCEPTION**

The operand position for the reference variable **oref** of the statement [**RAISE EXCEPTION oref**](javascript:call_link('abapraise_exception_class.htm')) is now a [general expression position](javascript:call_link('abengeneral_expr_position_glosry.htm')).

**Comment by larshp** [comment]
try again, 2.57.5

**Comment by FreHu** [comment]
Still doesn't seem to work, reproducible in playground.

**Comment by larshp** [comment]
https://syntax.abaplint.org/?filter=raise#/statement/Raise

did you change the configuration? its v754 by default in the playground

![image](https://user-images.githubusercontent.com/5888506/95984926-35d9a680-0e24-11eb-90a4-01142f007005.png)

**Comment by FreHu** [comment]
![](https://user-images.githubusercontent.com/5097067/95985916-830a4800-0e25-11eb-8a48-223bc200f112.png)

**Comment by FreHu** [comment]
I get the error for 702 and below

**Comment by larshp** [comment]
yea, https://syntax.abaplint.org/?filter=raise#/expression/MethodCallChain which is part of SimpleSource allows New

**Comment by larshp** [comment]
try again, 2.57.10
