### ISSUE TITLE
downport, 700

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#147]
also see https://github.com/larshp/abaplint/issues/91

@thesourav123 can you add a list of the typical issues/statements when downporting a 702 program to 700?

**Comment by thesourav123** [comment]
The major issues that arise in NW7.0 are th
a) String Processing Extensions( &&, | | etc are not recognized )
b) Chained Method Calls Not Allowed( e.g fn1( fn1( ) ), fn1()-var1 ) 
c) Custom Functions( boolc(), to_upper(), to_lower() etc) Not Supported
d) Pragma Statements Not Supported( e.g ##NO_TEXT etc )
e) Various Standard Classes are not available( e.g CL_ABAP_UNIT_ASSERT )

**Comment by gregorwolf** [comment]
to_lower is also missing in 701

**Comment by larshp** [comment]
nah, closing
