### ISSUE TITLE
Return parameter seen as non existing statement

### ISSUE THREAD

**Issue by DennisLybecker-INVIXO** [abaplint/abaplint#1502]
Error by linter: "Statement does not exist in ABAPv740sp08(or a parser error), "rv_inbound_fm" "
(code has been ok seen by the linter earlier)
For the following method definition/implementation. 

`    METHODS get_inbound_conversion_fm
      IMPORTING
        !iv_table            TYPE tabname
        !iv_field            TYPE fieldname
      RETURNING
        VALUE(rv_inbound_fm) TYPE rs38l_fnam
      RAISING
        zcx_exception .

  METHOD get_inbound_conversion_fm.

    rv_inbound_fm = 'CONVERSION_EXIT_' && get_field_ref( iv_table = iv_table
                                                         iv_field = iv_field )->edit_mask+2 && '_INPUT'.

  ENDMETHOD.`

**Comment by larshp** [comment]
@DennisLybecker-INVIXO thanks

try again, 2.58.19 published

**Comment by DennisLybecker-INVIXO** [comment]
Perfect, thanks, works again.
