### ISSUE TITLE
definitions_top quick fix, does not work on BEGIN OF

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#1505]
for now, just skip quick fixing these,

![image](https://user-images.githubusercontent.com/5888506/97334340-eca24180-187c-11eb-88dc-94d7605d255d.png)

**Comment by larshp** [comment]
fixed, closing

no quick fix currently suggested for this scenario

**Comment by mbtools** [comment]
hmm... I'm trying to quick fix string-map after mirror & rename and it errors here:

https://github.com/sbcgua/abap-string-map/blob/master/src/zcl_abap_string_map.clas.testclasses.abap#L84

no worry. i will check with Alexander to move the defs to the top in the original
