### ISSUE TITLE
parser_error in xsdbool sentence

### ISSUE THREAD

**Issue by jrodriguez-rc** [abaplint/abaplint#1515]
There is a parser error with this sentence:
```
    result =
        xsdbool(
            FILTER #( messages USING KEY type IN message_error_types WHERE type = table_line ) IS NOT INITIAL ).
```

https://github.com/jrodriguez-rc/abap-dev-utilities/blob/248fe396d48765474e14f12215a4c0a2f421a3a3/src/zcl_adu_messages.clas.abap#L363

./src/zcl_adu_messages.clas.abap[363, 5] - Statement does not exist in ABAPv754(or a parser error), "result" (parser_error) [E]

**Comment by larshp** [comment]
thanks, fixed in https://github.com/abaplint/abaplint/pull/1513/commits/3b4e6817971113d2fec08bd63af1b545c75770fd

I'll publish a new version tomorrow

**Comment by larshp** [comment]
workaround is doing below instead, I think it should work

```abap
 result =
        xsdbool(
            FILTER #( messages IN message_error_types USING KEY type WHERE type = table_line ) IS NOT INITIAL ).
```

**Comment by larshp** [comment]
@jrodriguez-rc try again, 2.58.27

**Comment by jrodriguez-rc** [comment]
Fixed, thank you!
