### ISSUE TITLE
Type Groups are not identified

### ISSUE THREAD

**Issue by pokrakam** [abaplint/abaplint#1518]
Type groups are treated as undeclared variables.

**Comment by pokrakam** [comment]
OK, I figured it out, they need to be hardcoded as constants in abaplint. PR to follow.

**Comment by larshp** [comment]
yea, its a workaround for now

**Comment by pokrakam** [comment]
Any preference whether to add SAP ones to abapLint or avoid them and create constants instead?
The ABAP doc says to not create new ones but use of existing ones are fine. I suppose since _everyone_ uses abap_true they can't make it obsolete just yet :-)

**Comment by larshp** [comment]
scope for abaplint is to know only the things that are built into the language, more or less `abap_*` and built-in types

ie. it will itself not know anything about workflow

Everyone can roll their own https://github.com/abaplint/deps, with type groups(when its supported by abaplint)

**Comment by pokrakam** [comment]
OK, but in this case the context is abapGit, which points to this repo's deps. Therefore my question whether to add some of the WF ones in here or just create constants for abapGit.

**Comment by larshp** [comment]
for now: add constants to the abapGit abaplint.json

**Comment by pokrakam** [comment]
Sounds good, thanks.
