### ISSUE TITLE
SCI: Table Enhancement category check not performed (tabl_enhancement_category)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1524]
The Linter finds the below issue but SCI does not.

We use SCI before we commit to verify that all is correct. Would be great if this check is also performed.

`/src/nw/#jcs#bc_job_control.tabl.xml[1, 1]              - TABL enhancement category not classified in /JCS/BC_JOB_CONTROL (tabl_enhancement_category) [E]`

**Comment by larshp** [comment]
@ed-holland did the fix in https://github.com/abaplint/abaplint-sci-client/pull/226 work?

**Comment by ed-holland** [comment]
Yes, it worked nicely. Thanks.
![image](https://user-images.githubusercontent.com/53995991/99263369-5e87fe00-281f-11eb-8216-46ae4a7d3a32.png)
