### ISSUE TITLE
Question: abaplint.app Statement Compatibility

### ISSUE THREAD

**Issue by jrodriguez-rc** [abaplint/abaplint#1538]
Just a question, there is an option to see what statements are [not] compatible in the different versions?
https://abaplint.app/stats/jrodriguez-rc/abap-dev-utilities/statement_compatibility

**Comment by larshp** [comment]
hi,
not right now, but there will be, sometime

as a workaround, you can clone the files to your local PC, then change the version in abaplint.json, and run `abaplint`

**Comment by jrodriguez-rc** [comment]
I imported the project into a 750 system and fix 3 syntax errors (abaplint only shows 2)
https://github.com/jrodriguez-rc/abap-dev-utilities/commit/ec549128e0ca516712f95a8a3efc6edf806dcd9d

After I updated the code, I have the same result, with 2 statements incompatible from 740sp8 to 751, but I didn't find any other error in 750.

Also, in the abaplint config, I specified version 740sp8, but no errors are raised.
https://github.com/jrodriguez-rc/abap-dev-utilities/blob/master/abaplint.json#L10

**Comment by larshp** [comment]
that sounds like bugs, please raise an issue for each of the findings

**Comment by larshp** [comment]
the value in the config is wrong, try opening the config in vscode, assuming you have the abaplint extension installed,

![image](https://user-images.githubusercontent.com/5888506/98797796-57bb4e80-240d-11eb-934f-8d491161219f.png)

**Comment by larshp** [comment]
issue https://github.com/abaplint/abaplint/issues/1540 created

**Comment by jrodriguez-rc** [comment]
Thank you @larshp, I could open them yesterday, but I saw almost all problems are fixed (I'll need to check the version in others abaplint configs).

I open a new issue for pending error #1545
