### ISSUE TITLE
Parser error - select from cds with association usage

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1566]
```abap
SELECT aaa, \_association-shortText AS ShortText FROM cds_view INTO @DATA(var).
snip, hvam
```

Reproducible in playground

**Comment by larshp** [comment]
any problem with the "AUTHORITY-CHECK" part?

**Comment by FreHu** [comment]
oh, i mistook it for part of the select. Just the following then:

\`SELECT aaa, \\\_association-shortText AS ShortText FROM cds\_view INTO @DATA(var).\`

**Comment by larshp** [comment]
path expressoin, https://help.sap.com/doc/abapdocu_753_index_htm/7.53/en-US/abenopen_sql_path.htm

**Comment by larshp** [comment]
@FreHu try again, 2.61.5
