### ISSUE TITLE
Statement ended with '..'

### ISSUE THREAD

**Issue by lucasborin** [abaplint/abaplint#1586]
![image](https://user-images.githubusercontent.com/5233413/100928025-766cac80-34c4-11eb-9fdc-4c934aace602.png)

Pull-Request:
https://github.com/SAP/code-pal-for-abap/pull/262/files

Both checks raised because of double `.` at the end of the file.
False-positives? New check for it?

**Comment by larshp** [comment]
should probably change `max_one_statement` so that it does not report anything for empty statements

**Comment by larshp** [comment]
@lucasborin try again, latest version

note that I'm not always updating [abaplint.app](https://abaplint.app/) with every release, but I update it often, and always when there are big bugs

**Comment by lucasborin** [comment]
![image](https://user-images.githubusercontent.com/5233413/101939473-c97ce880-3bc3-11eb-9d81-873f70805ef6.png)

https://github.com/SAP/code-pal-for-abap/pull/284/files

**Comment by larshp** [comment]
so its working, right? we can close the issue?
