### ISSUE TITLE
Parser_error for TYPES ... LIKE ... OCCURS 

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1601]
```abap
TYPES: ty_streenode_1 LIKE streenode.
TYPES: ty_streenode_2 LIKE streenode OCCURS 10.
TYPES: ty_streenode_3 TYPE streenode.
TYPES: ty_streenode_4 TYPE streenode OCCURS 10.
```

All lines activate without errors. Unfortunately, LIKE <ddic> OCCURS <n> is valid in ABAP. 

Second line gives "Statement does not exist in ABAPv754(or a parser error), "TYPES"(parser_error)"

**Comment by larshp** [comment]
@mbtools try again, 2.62.2
