### ISSUE TITLE
unknown_type: TypedConstantIdentifier

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1603]
```abap
CLASS lcl_class DEFINITION.
  PUBLIC SECTION.
    CONSTANTS:
      gc_value TYPE c LENGTH 1 VALUE 'X',
      BEGIN OF gc_struct,
        val_a TYPE c LENGTH 1 VALUE 'A',
        val_b TYPE c LENGTH 1 VALUE 'B',
      END OF gc_struct.
ENDCLASS.
CLASS lcl_class IMPLEMENTATION.
ENDCLASS.

CONSTANTS:
  gc_1 TYPE c LENGTH 1 VALUE lcl_class=>gc_value,    " ok when refering to single value
  gc_2 TYPE c LENGTH 1 VALUE lcl_class=>gc_struct-val_a.  " error when referring to structure
```

Type of "gc_2" contains unknown: todo, TypedConstantIdentifier(unknown_types)

Also, public class constants are not marked as used:

Variable "gc_value" not used(unused_variables)
Variable "gc_struct" not used(unused_variables)

**Comment by larshp** [comment]
thanks, yea, this scenario is a bit difficult

the unused part can be reproduced with below,

```abap
CLASS lcl_class DEFINITION.
  PUBLIC SECTION.
    CONSTANTS: gc_value TYPE c LENGTH 1 VALUE 'X'.
ENDCLASS.
CLASS lcl_class IMPLEMENTATION.
ENDCLASS.

CONSTANTS gc_1 TYPE c LENGTH 1 VALUE lcl_class=>gc_value.
WRITE gc_1.
```

![image](https://user-images.githubusercontent.com/5888506/101595938-815b9b80-39f4-11eb-97b6-ee3ad3a27f16.png)

**Comment by larshp** [comment]
it is a bug

but I'm trying to think of a scenario where it helps to "rename" the constants, I'd personally prefer to use the original constant directly

**Comment by mbtools** [comment]
it's just shorter than referring multiple times to class+struct+field.

CONSTANTS:
  c_title TYPE string VALUE /mbtools/cl_tool_bc_cts_req=>c_tool-title.

**Comment by nesl9** [comment]
This issue also appears to come up in the inherited attributes of a gateway service MPC_EXT class.

`Type of "CARDINALITY_FEED" contains unknown: todo, TypedConstantIdentifier, /IWBEP/CL_MGW_ABS_MODEL.CLAS.ABAP (unknown_t`

for value
`/IWBEP/IF_MGW_MED_ODATA_TYPES=>GCS_CARDINALITY-CARDINALITY_0_N`

**Comment by larshp** [comment]
@nesl9 thanks, what's the full statement that gives the error?

**Comment by nesl9** [comment]
I believe this is causing the issue. In  CLASS /IWBEP/CL_MGW_ABS_MODEL

```
  constants CARDINALITY_ENTITY type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_CARDINALITY value /IWBEP/IF_MGW_MED_ODATA_TYPES=>GCS_CARDINALITY-CARDINALITY_1_1. "#EC NOTEXT  "EC NO_TEXT
  constants CARDINALITY_ENTITY_0 type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_CARDINALITY value /IWBEP/IF_MGW_MED_ODATA_TYPES=>GCS_CARDINALITY-CARDINALITY_0_1. "#EC NOTEXT  "EC NO_TEXT
  constants CARDINALITY_FEED type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_CARDINALITY value /IWBEP/IF_MGW_MED_ODATA_TYPES=>GCS_CARDINALITY-CARDINALITY_0_N. "#EC NOTEXT  "EC NO_TEXT

```

**Comment by larshp** [comment]
try again, 2.69.3 published

**Comment by nesl9** [comment]
Yes, this is working now with 2.69.3. Thanks!
