### ISSUE TITLE
Running abaplint repeatedly can fail with an error

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1646]
Sometimes you get

```
generic[1, 1] - Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\xyz\AppData\Local\Temp\abaplint-OOSmmZ\src' at Object.rmdirSync (fs.js:850:3) (error) [E]
```

when running abaplint from cli multiple times in a row.

**Comment by FreHu** [comment]
I'm using the vscode terminal on windows, nothing special. But maybe it could be the abaplint extension and cli running at the same time and interfering with each other.

What should I be recording with screentogif?

**Comment by FreHu** [comment]
Not very high priority, you can just run it again

**Comment by larshp** [comment]
hmm, dont really have any ideas

but try updating node?

**Comment by larshp** [comment]
I cannot reproduce it, suggest closing issue
