### ISSUE TITLE
Object not found - (findtop - check syntax)

### ISSUE THREAD

**Issue by DennisLybecker-INVIXO** [abaplint/abaplint#1650]
The following code result in the error: "/zfoobar.prog.abap[13, 1]: lo_document not found, findTop(check_syntax)"

`DATA: lv_subject   TYPE so_obj_des,
      lr_recipient TYPE REF TO if_recipient_bcs.

DATA(lo_send_request) = cl_bcs=>create_persistent( ).

DATA(lo_document) = cl_document_bcs=>create_document(
                                             i_type    = 'RAW'
                                             i_text    = VALUE #( ( line = 'ERROR' ) )
                                             i_length  = '12'
                                             i_subject = lv_subject ).
lo_send_request->set_document( lo_document ).`

**Comment by larshp** [comment]
guessing this is caused by https://github.com/abaplint/abaplint/issues/1649, as lo_document is defined in the line with syntax error

**Comment by DennisLybecker-INVIXO** [comment]
> guessing this is caused by #1649, as lo_document is defined in the line with syntax error

Could be related, lets put it on hold until #1649 is fixed. Then we can see if it solved this way (Y)

**Comment by larshp** [comment]
try again, 

![image](https://user-images.githubusercontent.com/5888506/104009284-1516b800-51ab-11eb-81e7-24d9bcdb5d19.png)

**Comment by larshp** [comment]
@DennisLybecker-INVIXO did this issue solve itself?

**Comment by DennisLybecker-INVIXO** [comment]
> @DennisLybecker-INVIXO did this issue solve itself?

Yes, was related to the other issue
