### ISSUE TITLE
Indentation problem TRY-ENDTRY in local classes

### ISSUE THREAD

**Issue by jrodriguez-rc** [abaplint/abaplint#1652]
In local classes, the indentation is not calculating correctly between TRY-ENDTRY
https://github.com/sbcgua/ajson/pull/41/checks?check_run_id=1668657001

**Comment by larshp** [comment]
@sbcgua uses https://github.com/sbcgua/ajson/blob/master/abaplint.json#L121

**Comment by jrodriguez-rc** [comment]
Ok, I didn't see that.

I'll close the issue then. Sorry.
