### ISSUE TITLE
Append |...| to table should not work in 702

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint#1657]
ref https://github.com/abapGit/abapGit/pull/4392

```abap
APPEND |MANDT = '{ sy-mandt }'| TO ls_config-where.
```

**Comment by larshp** [comment]
hmm, there is a unit test with a string template, https://github.com/abaplint/abaplint/blob/master/packages/core/test/abap/statements/append.ts#L56

can you help testing if `APPEND |foo| && |bar| TO mt_code.` works on 702?

**Comment by sbcgua** [comment]
it is 731 in fact. But no, it doesn't
![image](https://user-images.githubusercontent.com/15635498/104235972-74e8b980-545e-11eb-9b4d-05e12598bd5d.png)

**Comment by larshp** [comment]
@sbcgua try again, 2.64.3

**Comment by sbcgua** [comment]
Cool, it works now. :+1:
