### ISSUE TITLE
Check_Syntax: Message statement not recognized after macro call

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1664]
abaplint 2.63.16

issue:
`./src/nw/#jcs#bc_job_abap_debugging.prog.abap[504, 3]    - Not a structure, FieldChain (check_syntax) [E]`

Source:
![image](https://user-images.githubusercontent.com/53995991/104162927-cb6ddd80-53f5-11eb-94a9-8a1780c409c4.png)
![image](https://user-images.githubusercontent.com/53995991/104162807-9792b800-53f5-11eb-882f-b487c787eff1.png)

Playground does not reproduce the error:
![image](https://user-images.githubusercontent.com/53995991/104163189-459e6200-53f6-11eb-8dbb-3f224fb7ea2a.png)

**Comment by larshp** [comment]
thanks, I think this is a regression after fixing https://github.com/abaplint/abaplint/issues/1656

**Comment by larshp** [comment]
tho, I dont think its related to the macro call

**Comment by larshp** [comment]
try again, 2.64.0 published

**Comment by ed-holland** [comment]
issue resolved. Thx
