### ISSUE TITLE
CheckSyntax: Message statement does not recognize TEXT parameters

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1665]
abaplint 2.63.16

Issue:
`./src/nw/#jcs#bc_rsbdcsub_list.prog.abap[68, 5]          - TEXT not found, findTop (check_syntax) [E]`

Source:
![image](https://user-images.githubusercontent.com/53995991/104163663-0f151700-53f7-11eb-8a38-6479e0b11262.png)

Playground:
![image](https://user-images.githubusercontent.com/53995991/104163614-fdcc0a80-53f6-11eb-8537-1bcc87e4d230.png)

**Comment by larshp** [comment]
thanks, I think this is a regression after fixing https://github.com/abaplint/abaplint/issues/1656

**Comment by larshp** [comment]
try again, 2.64.0 published

**Comment by ed-holland** [comment]
issue resolved. Thx
