### ISSUE TITLE
Check_Syntax: Loop over standard table does not recognize table parameter

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1666]
abaplint 2.63.16

issue:
`./src/nw/#jcs#bc_rsbdcsub_status.prog.abap[188, 5]       - Loop, not a table type (check_syntax) [E]`

source:
![image](https://user-images.githubusercontent.com/53995991/104163996-8ea2e600-53f7-11eb-979d-1664020ac440.png)
![image](https://user-images.githubusercontent.com/53995991/104164026-98c4e480-53f7-11eb-808a-6ef108decbd9.png)

playground:
![image](https://user-images.githubusercontent.com/53995991/104164151-cc077380-53f7-11eb-9306-990b55635fa1.png)

**Comment by ed-holland** [comment]
Related issues:
```
./src/nw/#jcs#bc_rsbdcsub_status.prog.abap[410, 5]       - Append, target not a table type (check_syntax) [E]
./src/nw/#jcs#bc_rsbdcsub_status.prog.abap[473, 5]       - Append, target not a table type (check_syntax) [E]
```

Source:
![image](https://user-images.githubusercontent.com/53995991/104164324-0bce5b00-53f8-11eb-9452-5bcac1b07030.png)
![image](https://user-images.githubusercontent.com/53995991/104164362-1852b380-53f8-11eb-9d5e-5de36dd15128.png)

**Comment by larshp** [comment]
heh, thanks, dont think this case is covered, defining a table without `TYPE`

ABAP is evil...

**Comment by larshp** [comment]
workaround is changing the code to `DATA list TYPE c LENGTH 250 OCCURS 0 WITH HEADER LINE.`

**Comment by larshp** [comment]
```abap
DATA list(250) OCCURS 0 WITH HEADER LINE.

LOOP AT list.
  WRITE / list.
ENDLOOP.
```

**Comment by larshp** [comment]
try again, 2.64.0 published

**Comment by ed-holland** [comment]
issue resolved. Thx
