### ISSUE TITLE
check_syntax: WITH HEADER LINE can only be used with internal table

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1667]
abaplint 2.64.0

Issue:
`/tmp/abaplint-NFCmkk/src/kalc/kgaldtyp.prog.abap[335, 1] - WITH HEADER LINE can only be used with internal table (check_syntax)`

Source (from original SAP as part of dependency repo)
```abap
DATA: fieldtab TYPE rkea1_fieldtab WITH HEADER LINE.
```

Playground:
```abap
REPORT zfoobar.

TYPES: BEGIN OF rkea1_fieldtab_entry.
        INCLUDE STRUCTURE dd03p.
        INCLUDE STRUCTURE cefld.
TYPES: END OF rkea1_fieldtab_entry.

TYPES: rkea1_fieldtab TYPE rkea1_fieldtab_entry OCCURS 150.

DATA: fieldtab TYPE rkea1_fieldtab WITH HEADER LINE.
```

**Comment by larshp** [comment]
```abap
TYPES tab TYPE i OCCURS 150.
DATA fieldtab TYPE tab WITH HEADER LINE.
```

**Comment by larshp** [comment]
@ed-holland try again, 2.64.1 published

**Comment by ed-holland** [comment]
abaplint 2.64.1

Issue is still there in abaplint. It is gone in playground. Also VC does not see the problem.

Source code numbers in deps are different so using vc on the deps-repo.
![image](https://user-images.githubusercontent.com/53995991/104288856-a5f5d800-54b8-11eb-89db-9fe5f5d4fe6b.png)

**Comment by ed-holland** [comment]
Closing as the issue is resolved.
