### ISSUE TITLE
keep_single_parameter_on_one_line - multiple fields in structure

### ISSUE THREAD

**Issue by DennisLybecker-INVIXO** [abaplint/abaplint#1680]
The following code gives the error "keep_single_parameter_on_one_line"
I would assume that it should be ok to split into multiple lines to make it more readable.

`      data(lv_xyz) = get_something( VALUE #( field1 = 'X'
                                             field2 = 'Y' ) ).`

![image](https://user-images.githubusercontent.com/46812361/104837227-6c0b4400-58b3-11eb-922f-73fb1293b4c5.png)

**Comment by larshp** [comment]
@DennisLybecker-INVIXO try again, 2.64.6 published

**Comment by DennisLybecker-INVIXO** [comment]
> @DennisLybecker-INVIXO try again, 2.64.6 published

Works, thanks
