### ISSUE TITLE
instanceof Statements.Raise is incomplete

### ISSUE THREAD

**Issue by jan-jezek** [abaplint/abaplint#1683]
```
RAISE EXCEPTION TYPE cx_generation_error
  EXPORTING
    previous = exception
  MESSAGE e136(messages).
```
Statement is not recognised as instanceof Statements.Raise (it is Unknown).

```
RAISE EXCEPTION TYPE cx_generation_error
  EXPORTING
    previous = exception.
```
This statement works fine.

**Comment by larshp** [comment]
yea, its a syntax error, at least on 751,

![image](https://user-images.githubusercontent.com/5888506/105019984-051e9400-5a47-11eb-8ad0-ef5d2132bb02.png)

but following works,

![image](https://user-images.githubusercontent.com/5888506/105020041-17003700-5a47-11eb-9baf-d96c29f1fcc4.png)

**Comment by jan-jezek** [comment]
I took it from styleguide:
https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#prefer-raise-exception-new-to-raise-exception-type

**Comment by larshp** [comment]
hmm, then I guess there is a syntax error in the styleguide? at least on 751

maybe it works on higher releases?

**Comment by larshp** [comment]
latest doc, https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abapraise_exception_class.htm also has the EXPORTING part after MESSAGE

**Comment by jan-jezek** [comment]
Will be fixed in styleguide. PR SAP/styleguides#175.
