### ISSUE TITLE
RAISE EXCEPTION - SimpleSource2

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1688]
This allows invalid syntax like `RAISE EXCEPTION 'A'`.

![](https://user-images.githubusercontent.com/5097067/105071391-ce676e80-5a84-11eb-8487-e40e4ae1ce9d.png)

![](https://user-images.githubusercontent.com/5097067/105071435-e3440200-5a84-11eb-922f-56ad48b29ee7.png)

**Comment by larshp** [comment]
yea, thanks, it should probably just be "FieldChain" instead of "SimpleSource2"

**Comment by larshp** [comment]
https://syntax.abaplint.org/?filter=raise#/statement/Raise

**Comment by larshp** [comment]
note that this will be covered in the type/syntax check, and not by the parser

**Comment by larshp** [comment]
@FreHu try again, 2.65.1

**Comment by larshp** [comment]
@FreHu
