### ISSUE TITLE
`DESCRIBE TABLE moo( ) LINES bar.` is not valid, but accepted by abaplint

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1689]
`DESCRIBE TABLE moo( ) LINES bar.` is not valid, but accepted by abaplint

according to keyword documentation only `itab` is supported in this position

![](https://user-images.githubusercontent.com/5097067/105071271-a37d1a80-5a84-11eb-8403-73e9c3fbf1b2.png)

_Originally posted by @FreHu in https://github.com/abaplint/abaplint/issues/1686#issuecomment-762999778_

**Comment by larshp** [comment]
https://syntax.abaplint.org/?filter=describe#/statement/Describe

**Comment by larshp** [comment]
@FreHu try again, 2.65.1
