### ISSUE TITLE
Add support for NSPC 

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1700]
![image](https://user-images.githubusercontent.com/59966492/105636442-6cb55480-5e36-11eb-894c-e52d1f5712b1.png)

https://github.com/abaplint/abaplint/blob/master/packages/core/src/rules/allowed_object_naming.ts#L42

**Comment by larshp** [comment]
@mbtools try again, 2.66.0 published

**Comment by mbtools** [comment]
The error is still there with  2.66.4.  I think it's because there's no additional character after the namespace `#mbtools#`.

**Comment by larshp** [comment]
@mbtools try again, 2.66.5

https://abaplint.app doesnt always run the latest abaplint, but just ping me if you need it updated

**Comment by mbtools** [comment]
👍
