### ISSUE TITLE
unused_variable: usage of constants

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1703]
```abap
REPORT zfoobar.

CONSTANTS lc_tabname TYPE tabname VALUE 'ZTEST'.
DATA lv_test TYPE i.
SELECT SINGLE * INTO @lv_test FROM (lc_tabname).
ASSERT sy-subrc = 0.

CONSTANTS lc_length TYPE i VALUE 10.
TYPES ty_name TYPE c LENGTH lc_length.
```

/zfoobar.prog.abap[3, 11]: Variable "lc_tabname" not used(unused_variables)
/zfoobar.prog.abap[8, 11]: Variable "lc_length" not used(unused_variables)

**Comment by larshp** [comment]
thanks 👍

**Comment by larshp** [comment]
@mbtools try again, 2.66.0 published

**Comment by mbtools** [comment]
The examples above are fixed but I still get the error when the constant is in a *class*.

/zfoobar.prog.abap[4, 15]: Variable "c_name_length" not used(unused_variables)

```abap
REPORT zfoobar.
CLASS lcl_test DEFINITION FINAL.
  PUBLIC SECTION.
    CONSTANTS c_name_length TYPE i VALUE 90 ##NO_TEXT.
    TYPES ty_name TYPE c LENGTH c_name_length.
ENDCLASS.
CLASS lcl_test IMPLEMENTATION.
ENDCLASS.
```

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/106773029-ed4b3080-6640-11eb-9c07-e36bdc37a034.png)

**Comment by larshp** [comment]
@mbtools try again, 2.66.6

**Comment by mbtools** [comment]
👍
