### ISSUE TITLE
functional_writing - methods with non class exceptions

### ISSUE THREAD

**Issue by DennisLybecker-INVIXO** [abaplint/abaplint#1709]
I need to call a standard method which has a non class exception. 
In order to handle this,  I belive the only way is to use 'CALL METHOD'?
Resulting in these errors:
![image](https://user-images.githubusercontent.com/46812361/105815924-e4f55480-5fb3-11eb-8520-34cf20bb3414.png)

`DATA: lr_typedescr TYPE REF TO cl_abap_typedescr.

CALL METHOD cl_abap_typedescr=>describe_by_name
    EXPORTING
      p_name         = 'NAME'
    RECEIVING
      p_descr_ref    = lr_typedescr
    EXCEPTIONS
      type_not_found = 1
      OTHERS         = 2.`

**Comment by larshp** [comment]
following will avoid the issue, and make it a functional call,

```abap
DATA: lr_typedescr TYPE REF TO cl_abap_typedescr.

cl_abap_typedescr=>describe_by_name(
  EXPORTING
    p_name         = 'NAME'
  RECEIVING
    p_descr_ref    = lr_typedescr
  EXCEPTIONS
    type_not_found = 1
    OTHERS         = 2 ).
```

**Comment by larshp** [comment]
I'll update the documentation to include it as an example

**Comment by DennisLybecker-INVIXO** [comment]
Perfect. Thanks just had the idea that the CALL METHOD was needed. This issue can be closed. Left it open if you needed for the documentation update reminder.

**Comment by larshp** [comment]
documentation updated in https://github.com/abaplint/abaplint/pull/1710

and https://github.com/abaplint/abaplint/issues/1711 opened

closing
