### ISSUE TITLE
Duplicate issues

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1722]
2.66.4
some issues are reported twice (see http... in rules name)

example 1:

![image](https://user-images.githubusercontent.com/59966492/106672196-ae07db80-657d-11eb-80af-d30d8b4d2eb6.png)

example 2:

![image](https://user-images.githubusercontent.com/59966492/106672339-e3acc480-657d-11eb-9023-aad7985dd4dc.png)

**Comment by larshp** [comment]
It looks like abaplint is setup to run via both github actions and via the abaplint app, suggest disabling the github action. In this case, both runs independently

![image](https://user-images.githubusercontent.com/5888506/106700433-205fd680-65e5-11eb-91b5-c4fa3c8d2b50.png)
![image](https://user-images.githubusercontent.com/5888506/106700436-23f35d80-65e5-11eb-9f65-3d2fb41b54a8.png)

**Comment by mbtools** [comment]
Of course! I didn't think about that when adding the app. 

My private repos show in the overview

![image](https://user-images.githubusercontent.com/59966492/106778241-bf9bc280-6613-11eb-9385-2976e6f26432.png)

but the dashboards don't work

![image](https://user-images.githubusercontent.com/59966492/106778294-d0e4cf00-6613-11eb-9dd2-85f96411d6c4.png)

Is there some config I'm missing? BTW, happy to pay for this if there are costs associated with it.

**Comment by larshp** [comment]
the dashboard doesnt work for private repos yet, it will be added sometime 😄 

I'll remove the dashboard link for now, its misleading

**Comment by mbtools** [comment]
👍
