### ISSUE TITLE
keyword_case does not recognise SCREEN as keyword

### ISSUE THREAD

**Issue by jan-jezek** [abaplint/abaplint#1730]
![screen1](https://user-images.githubusercontent.com/17530797/106886806-9bf47d00-66e4-11eb-9436-a20e003c38a1.PNG)
![screen2](https://user-images.githubusercontent.com/17530797/106886804-9bf47d00-66e4-11eb-9ed9-d3b6be0410b3.PNG)

Statement should be "MODIFY SCREEN FROM wa".
Abaplint is suggesting "MODIFY screen FROM wa".

Pretty print correctly sets SCREEN to upper case.

**Comment by larshp** [comment]
yea.., its release dependent, below screenshot is from 751 after pretty printing, might have to add some target version logic in the pretty printer

workaround is to add a `ignoreKeywords` in the configuration, https://rules.abaplint.org/keyword_case/

![image](https://user-images.githubusercontent.com/5888506/106887120-01e10480-66e5-11eb-8d6c-ca5b95fa16df.png)

**Comment by jan-jezek** [comment]
Actually your workaround cannot be used, because the code doesn't recognise SCREEN as keyword, so ignoreKeywords in configuration is not used. It would have to be something like ignoreIdentifiers.

The problem is most probably not in keyword_case rule, but in parser.
![image](https://user-images.githubusercontent.com/17530797/106890664-f17f5880-66e9-11eb-826e-2538bec7c7dd.png)

**Comment by larshp** [comment]
hmm, yea

suggest that `ignoreKeywords` is changed to `ignoreWord`

and yea, the parser should probably recognize MODIFY SCREEN as a separate statement

**Comment by larshp** [comment]
hmm, there is already some hacks for this scenario in the code,
https://github.com/abaplint/abaplint/blob/657b9019b2d3043ba28b9ffed82ed3dd6b652261/packages/core/src/rules/keyword_case.ts#L229

**Comment by larshp** [comment]
@jan-jezek try again 2.66.6

plus I have opened https://github.com/abaplint/abaplint/issues/1732

**Comment by jan-jezek** [comment]
Works fine 👍🏻
