### ISSUE TITLE
rules.abaplint.org: add some kind of easy search

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#1740]
eg, search for "kernel" and find rule https://rules.abaplint.org/avoid_use/

https://gomakethings.com/how-to-create-a-vanilla-js-search-page-for-a-static-website/

https://scrapy.org/

https://www.henriksommerfeld.se/search-static-website-without-external-service/

https://lunrjs.com/

https://github.com/nextapps-de/flexsearch

https://github.com/krisk/fuse

https://docsearch.algolia.com/

**Comment by larshp** [comment]
adding https://docsearch.algolia.com in progress, currently awaiting api keys

**Comment by larshp** [comment]
configuration: https://github.com/algolia/docsearch-configs/blob/master/configs/abaplint.json

**Comment by mbtools** [comment]
works well. thanks! 

is it possible to pass the query string via url? something like:

https://rules.abaplint.org/?search=test

**Comment by mbtools** [comment]
maybe overwrite the width of the dropdown. here it is with `width:800px;`

![image](https://user-images.githubusercontent.com/59966492/108576775-d23d1980-72ec-11eb-8707-557fd46abbb5.png)

**Comment by larshp** [comment]
query string: nah, not currently, what would be use-case scenario?

width: I'll adjust the titles to be shorter

still messing with it, but its starting to come together

**Comment by mbtools** [comment]
with a query string option, you can add the search to the browser address bar, for example. but we can always google it anyway with https://www.google.com/search?q=site%3Arules.abaplint.org+test

**Comment by larshp** [comment]
done, seems okay, closing
