### ISSUE TITLE
FIND FIRST OCCURRENCE .... "IGNORING" Statement

### ISSUE THREAD

**Issue by smardcode** [abaplint/abaplint#1742]
The linter cannot identify the statement "IGNORING" in the "FIND FIRST OCCURRENCE" Statement

FIND FIRST OCCURRENCE OF REGEX '^/Date((-?\d+)([+-]\d{1,4})?)/' IN sdummy SUBMATCHES lv_ticks lv_offset IGNORING CASE. "#EC NOTEXT

![image](https://user-images.githubusercontent.com/60311033/107079760-971cef80-67f0-11eb-9821-bec914d13705.png)

**Comment by larshp** [comment]
reprodued as below, related issue = https://github.com/abaplint/abaplint/issues/1592

```abap
DATA sdummy TYPE string.
DATA lv_ticks TYPE string.
DATA lv_offset TYPE string.
FIND FIRST OCCURRENCE OF REGEX 'sdf' IN sdummy SUBMATCHES lv_ticks lv_offset IGNORING CASE.
```

![image](https://user-images.githubusercontent.com/5888506/107113767-51e4d600-6861-11eb-8f53-64a0fa91a91a.png)

**Comment by larshp** [comment]
@smardcode try again, 2.66.7 published

**Comment by smardcode** [comment]
Excellent, solved - thx.

**Comment by larshp** [comment]
https://abaplint.app is updated every now and then, check the version number in the details if needed
