### ISSUE TITLE
View abaplint.app run details

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1758]
Approx 130 ABAP objects in my repo. Almost all abaplint rules are active.

How it started: 516 issues
How it's going: 0 issues  💯 😄 

In case of issues, there's a little red X for the commit that will link to the abaplint run:

![image](https://user-images.githubusercontent.com/59966492/107394225-a094a900-6ac9-11eb-81ba-0952249f95fc.png)

If there's no issue, there does not seem to be a way to view the abaplint run details. It would be helpful to see which abaplint version was used and that it actually ran successfully. 

I wish there was a green checkmark next to the commit to link to the run.

**Comment by larshp** [comment]
hmm, yea, I guess its because you are not using pull requests?

eg all commits for https://github.com/abapGit/abapGit/commits/master have status checks

**Comment by mbtools** [comment]
I had removed the GH actions to avoid issues showing twice. Maybe I need some dummy action.

**Comment by larshp** [comment]
I'll have a look sometime, I've not really tested this scenario where pushes are directly to the default branch

**Comment by larshp** [comment]
I did some testing, it seems to work, just github had some trouble ealier today

**Comment by mbtools** [comment]
Added a "hello world" workflow and now abaplint shows again... 

![image](https://user-images.githubusercontent.com/59966492/107399723-0cc5db80-6acf-11eb-87a0-15e97295fb3b.png)

Interestingly, it found 1 issue although nothing changed (except adding hello.yml):

![image](https://user-images.githubusercontent.com/59966492/107399846-35e66c00-6acf-11eb-9166-32df93cc1cf1.png)

After fixing this, I get the checkmark but not related to abaplint

![image](https://user-images.githubusercontent.com/59966492/107405260-1fdbaa00-6ad5-11eb-92ca-c432a08d8213.png)

![image](https://user-images.githubusercontent.com/59966492/107405244-1ce0b980-6ad5-11eb-90c6-72b51d46127f.png)

**Comment by larshp** [comment]
@mbtools this issue can be closed?
