### ISSUE TITLE
Missing methods found in include although they are defined in main program

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1759]
abaplint 2.66.9 (SAP 7.40)

Issues:
```
./src/nw/#jcs#bc_rtts.prog.abap[54, 7]          - Method "get_table_line_type" not found, methodCallChain (check_syntax) [E]
./src/nw/#jcs#bc_rtts.prog.abap[54, 7]          - Method "get_table_line_type" not found, methodCallChain (check_syntax) [E]
./src/nw/#jcs#bc_rtts.prog.abap[59, 7]          - Method "get_components" not found, methodCallChain (check_syntax) [E]
./src/nw/#jcs#bc_rtts.prog.abap[59, 7]          - Method "get_components" not found, methodCallChain (check_syntax) [E]
```

Code:
```
DATA:     lr_tabledescr          TYPE REF TO cl_abap_tabledescr.

  CASE lr_typedescr->kind.
    WHEN cl_abap_typedescr=>kind_table.
      lr_tabledescr ?= lr_typedescr.
      lr_datadescr = lr_tabledescr->get_table_line_type( ).
      lr_typedescr = lr_datadescr.
      PERFORM get_fields_of_ref TABLES otb_components USING lr_typedescr.
    WHEN cl_abap_typedescr=>kind_struct.
      lr_structdescr ?= lr_typedescr.
      lt_component_org = lr_structdescr->get_components( ).
```

Methods are all from CL_ABAP_DATADESCR.

**Comment by larshp** [comment]
can this be reproduced in a public repo? in the issue, is `cl_abap_tabledescr` part of deps?

**Comment by ed-holland** [comment]
The class is part of the deps repository.

Playground gets stuck on the "not Found".
![image](https://user-images.githubusercontent.com/53995991/107479847-f75abb00-6b7b-11eb-8536-d412b7824b75.png)

I've also checked with VC but it finds no issues (uses the same deps repo).

**Comment by larshp** [comment]
did you change the configuration in the playground? `lr_tabledescr` gets voided in the default configuration,

![image](https://user-images.githubusercontent.com/5888506/109184066-e40c3a00-778e-11eb-88d4-007fee401e27.png)

**Comment by ed-holland** [comment]
I used my config for it. It might be missing newer options though. Which rule is voiding these methods?

**Comment by ed-holland** [comment]
@larshp found the cause. The super class CL_ABAP_COMPLEXDESCR is not part of the dependency repository.

**Comment by larshp** [comment]
closing
