### ISSUE TITLE
field not identified in standard table when using for all entries in

### ISSUE THREAD

**Issue by DennisLybecker-INVIXO** [abaplint/abaplint#1766]
This used to work. 

Now results in error: /zfoobar.prog.abap[5, 1]: Component "tabname" not found in structure(check_syntax)

`DATA: lt_sort TYPE TABLE OF dd03l.

SELECT tabname
  INTO TABLE @DATA(lt_dd02l)
      FROM dd02l
      FOR ALL ENTRIES IN @lt_sort
      WHERE
        tabname = @lt_sort-tabname.`

Error does not occur for :
`REPORT zfoobar.

SELECT tabname
  INTO TABLE @DATA(lt_dd02l)
      FROM dd02l
      WHERE
        tabname = 'Hello World'.

SORT lt_dd02l BY tabname.`

**Comment by larshp** [comment]
fae scoping changed in https://github.com/abaplint/abaplint/pull/1750, regression...

**Comment by larshp** [comment]
@DennisLybecker-INVIXO try again, 2.66.11 published

**Comment by DennisLybecker-INVIXO** [comment]
Works. Thanks.
