### ISSUE TITLE
builtin functions nmin and nmax missing parameter val8

### ISSUE THREAD

**Issue by joltdx** [abaplint/abaplint#1768]
```
REPORT zfoobar.
DATA(nmin) = nmin( val1 = 1
                   val2 = 2
                   val3 = 3
                   val4 = 4
                   val5 = 5
                   val6 = 6
                   val7 = 7
                   val8 = 8
                   val9 = 9 ).
WRITE / nmin.
```
/zfoobar.prog.abap[2, 1]: Method importing parameter "VAL8" does not exist(check_syntax)

The same applies for nmax. I doubt anybody will miss it, but yea... 😁

**Comment by larshp** [comment]
heh, yea

https://github.com/abaplint/abaplint/blob/28a9c060b3bd09439dfec9b3d397d5d6a426f5c0/packages/core/src/abap/5_syntax/_builtin.ts#L169
