### ISSUE TITLE
avoid_use: Extend with "Insert Report" and "Generate Subroutine Pool"

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1791]
The Abap code allows for code to be created dynamically and used for execution.

This should be avoided. Can the "avoid_use" be extended accordingly?

**Comment by larshp** [comment]
maybe time to split some of `avoid_use` into a new `dangerous_statements` rule

**Comment by larshp** [comment]
@ed-holland try again, latest version, note the new rule is https://rules.abaplint.org/dangerous_statement/

**Comment by ed-holland** [comment]
It is working nicely. Thanks.
