### ISSUE TITLE
Truncate dataset statement not recognized

### ISSUE THREAD

**Issue by stefan-riedel-seifert** [abaplint/abaplint#1792]
Statement does not exist in ABAPv755(or parser error).
Statement exist even in 755.

data:
  i_filename type c length 255 value '/user/sap/data/....'.

truncate dataset i_filename at current position.

**Comment by larshp** [comment]
```abap
data i_filename type c length 255 value '/user/sap/data/....'.
truncate dataset i_filename at current position.
```

**Comment by larshp** [comment]
heh, there are always more ABAP statements :)
