### ISSUE TITLE
Set dataset statement not recognized

### ISSUE THREAD

**Issue by stefan-riedel-seifert** [abaplint/abaplint#1793]
Statement does not exist in ABAPv755(or parser error).
Statement exist even in 755.

data:
  i_filename type c length 255 value '/user/sap/data/....'.

set dataset i_filename position end of file.

**Comment by larshp** [comment]
```abap
DATA i_filename TYPE c LENGTH 255 VALUE '/user/sap/data/....'.
SET DATASET i_filename POSITION END OF FILE.
```
