### ISSUE TITLE
Create object ... type (.. ) statement not recognized

### ISSUE THREAD

**Issue by stefan-riedel-seifert** [abaplint/abaplint#1794]
Statement does not exist in ABAPv755(or parser error).
Statement exist even in 755.

In my opinion in some situations obvious indispensable: 

create object lo_object type (l_imp) parameter-table l_tab_parmbind
                                                              exception-table l_tab_excpbind.

The content of (i_imp) actually cannot be specified dynamically here.

**Comment by larshp** [comment]
```abap
CREATE OBJECT lo_object TYPE (l_imp) 
  PARAMETER-TABLE l_tab_parmbind
  EXCEPTION-TABLE l_tab_excpbind.
```

**Comment by larshp** [comment]
its the EXCEPTION-TABLE part that is currently unknown to abaplint, https://syntax.abaplint.org/?filter=create#/statement/CreateObject
