### ISSUE TITLE
syntax_check: Definition for "CL_ABAP_TABLEDESCR" not found in scope

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1800]
abaplint version: 2.69.3

issue:
`/src/nw/#jcs#sql.fugr.#jcs#lsqlf01.abap[71, 7]                       - Definition for "CL_ABAP_TABLEDESCR" not found in scope (check_syntax) [E]`

The code (see below) is in a form include of a fugr. I've created a test fugr / function with this inside and it caused no problems.
Any idea?

Code used in playground (no issue there):
```
FIELD-SYMBOLS:
  <table_rec> type any,
  <table> TYPE any.

DATA:
    l_oref   TYPE REF TO cx_root,
    ltb_table_fields     TYPE cl_abap_structdescr=>component_table,
    ltb_table_fields_new TYPE cl_abap_structdescr=>component_table,
    lr_table    TYPE REF TO data,
    lr_rec      TYPE REF TO data,
    o_ref_struc TYPE REF TO cl_abap_structdescr,
    o_ref_table TYPE REF TO cl_abap_tabledescr.

TRY.
    o_ref_struc = cl_abap_structdescr=>create( p_components = ltb_table_fields ).
    CREATE DATA lr_rec TYPE HANDLE o_ref_struc.
    ASSIGN lr_rec->* TO <table_rec>.

    o_ref_table = cl_abap_tabledescr=>create( p_line_type = o_ref_struc
        p_table_kind = cl_abap_tabledescr=>tablekind_std ).
    CREATE DATA lr_table TYPE HANDLE o_ref_table.
    ASSIGN lr_table->* TO <table>.

  CATCH cx_root INTO l_oref.
    EXIT.
ENDTRY.
```

**Comment by larshp** [comment]
are you running this via the SCI client? if so, it depends on the configuration

**Comment by ed-holland** [comment]
This error is comming from abaplint. Also having forms not being found anymore. Collecting data for a ticket...

**Comment by ed-holland** [comment]
might be related to #1759.

**Comment by larshp** [comment]
in the example which line is line 71?

**Comment by ed-holland** [comment]
This one:

`  o_ref_table = cl_abap_tabledescr=>create( p_line_type = o_ref_struc
        p_table_kind = cl_abap_tabledescr=>tablekind_std ).`

**Comment by larshp** [comment]
I cannot easily reproduce the error,

![image](https://user-images.githubusercontent.com/5888506/109259544-b2ca5300-77fc-11eb-9769-db312733f979.png)

**Comment by ed-holland** [comment]
The cause is the same as from issue #1759.
