### ISSUE TITLE
check_syntax: form in shared include not found

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1801]
Created using gitlab runner - abaplint 2.69.3

Issue:
`./src/nw/#jcs#bc.fugr.#jcs#lbcf81.abap[35, 7]                         - FORM definition "update_bapiret2" not found (check_syntax) [E]
./src/nw/#jcs#bc.fugr.#jcs#lbcf81.abap[85, 9]                         - FORM definition "update_bapiret2" not found (check_syntax) [E]
`
The form is in a shared form include /JCS/NW_SHARED_F95. It is defined in the main program of a function group (not in the TOP include).

Code Inspector finds no issues.

Added the include in the same way to a test-fugr and no issue was raised. As if the number of objects is causing the fault.

**Comment by larshp** [comment]
can this be reproduced in a public repo?

**Comment by larshp** [comment]
might be reproduceable in these public repos, but need to investigate if its false positives,
![image](https://user-images.githubusercontent.com/5888506/109197925-e5912e80-779d-11eb-9f2e-6b688817ddd3.png)

**Comment by larshp** [comment]
so, below gives a false positive, not sure if its the same scenario, but I'll fix this one first,

![image](https://user-images.githubusercontent.com/5888506/109257845-4c900100-77f9-11eb-8785-faa5b3da188c.png)

**Comment by larshp** [comment]
@ed-holland would this look like your example? where is the include defined that calls the form from `zshared`?

![image](https://user-images.githubusercontent.com/5888506/109258957-9b3e9a80-77fb-11eb-9cfa-bf6b415a6a41.png)

**Comment by ed-holland** [comment]
It looks the same. More includes. The new version did not fix the issue.

![image](https://user-images.githubusercontent.com/53995991/109267328-ac8ea380-7809-11eb-934f-52926b480b36.png)

**Comment by ed-holland** [comment]
Issue was caused by the FUGR xml being updated in the repo but the abap side not (one containing the shared include and the other not).

This should not happen. Can this be enforced in the UI?

**Comment by larshp** [comment]
I'm not sure I understand the scenario, can you add a short example?

**Comment by ed-holland** [comment]
Those xml files which contain information of related objects (line in fugr.xml).
If the related object is changed and the fugr.xml then both must be committed to be consistent.
