### ISSUE TITLE
New rule: Avoid offensive or profane words

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1817]
I swear at the computer but not in my code (usually). But a rule would make sure of it 😉 

Suggest putting a list like on https://www.cs.cmu.edu/~biglou/resources/ into abaplint with an option in the rule to add other words.

**Comment by larshp** [comment]
this could probably be solved via a simple `grep`, but it would not become a real annotation that way

I would like to avoid defining what is considered bad words, so perhaps a feature like

https://docs.abapopenchecks.org/checks/70/

which searches the code for different regex'es, I think it would have multiple usecases including looking for bad words

**Comment by mbtools** [comment]
Or be able to provide a link to a word list in abaplint.json?

I guess the linter would be faster checking a word list than ABAP

**Comment by mbtools** [comment]
https://github.com/marketplace/actions/profanity-filter or custom ATC check will do
