### ISSUE TITLE
Avoid use of SELECT *, false positive

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#1834]
skip when using INTO CORRESPONDING FIELDS ?

https://rules.abaplint.org/select_performance/

**Comment by mbtools** [comment]
It's about performance so the number of selected fields is what makes the difference. I use 10 as a threshold but maybe it's a setting. So if either the table or the corresponding structure have more then 10 fields, it should raise an issue.

**Comment by larshp** [comment]
yea, agree, there are just multiple things to consider, I'd like to get rid of the false positives first, then extend the logic

above moved to #1837
