### ISSUE TITLE
type can not be determined as its structure is not determined

### ISSUE THREAD

**Issue by DennisLybecker-INVIXO** [abaplint/abaplint#1843]
### Got this error when comparing a field symbol (structure) field with a field in a class constant.

"Not a structure, type unknown, FieldChain"

### Description of where the error occur:

> Class has table as an attribute

attribute : 'mt_data' has field 'name'.

> Insert some data into attribute assigning field symbol.

INSERT VALUE #( name = 'XYZ' ) INTO TABLE mt_data ASSIGNING FIELD-SYMBOL(<ls_data>).

> Check if the value in field NAME is the same at a constant - **This is where the error occur**

**IF <ls_data>-name = zcl_some_class=>gs_data-name.**  

> Definition of the constants that is compared to if this was any role in the error?.

      BEGIN OF gs_data,
        name TYPE ty_someother_st-name VALUE 'foobar'
      END OF gs_data.

**Comment by larshp** [comment]
sooo, something like the below?

```abap
DATA: BEGIN OF gs_data,
    name TYPE string,
  END OF gs_data.
DATA mt_data LIKE STANDARD TABLE OF gs_data WITH EMPTY KEY.
INSERT VALUE #( name = 'XYZ' ) INTO TABLE mt_data ASSIGNING FIELD-SYMBOL(<ls_data>).
IF <ls_data>-name = 'sdf'.
  WRITE 'sdfs'.
ENDIF.
```

![image](https://user-images.githubusercontent.com/5888506/110649933-60a10e80-81ba-11eb-85d3-9fbe2464bced.png)

**Comment by DennisLybecker-INVIXO** [comment]
Yup. Thank. 
Yes I should have build it in the playground to test.

**Comment by larshp** [comment]
@DennisLybecker-INVIXO try again, 2.70.2 published

**Comment by DennisLybecker-INVIXO** [comment]
Works, thanks.
