### ISSUE TITLE
new rule: objects have the same description

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1846]
For objects of the same type, it's unlikely that you should have the exact same description. It often happens that people duplicate objects and forget to edit the description on the new one.

**Comment by larshp** [comment]
yea, good one 👍

**Comment by larshp** [comment]
@FreHu any specific object types in mind? currently CLAS + INTF implemented in https://github.com/abaplint/abaplint/pull/1866

**Comment by FreHu** [comment]
Often happens with basic ddic stuff. For  domain and data element, it might be ok having the same descriptions, which is why I wanted to group by object type first.

**Comment by mbtools** [comment]
also includes. in a similar way one could check if the description matches the default text i.e. the developer didn't bother to add a proper description.

**Comment by larshp** [comment]
@FreHu try again, https://rules.abaplint.org/identical_descriptions/ latest version

**Comment by FreHu** [comment]
Amazing rule, found 139 identical descriptions in 900 objects.
