### ISSUE TITLE
Raise exception new false positive

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1852]
Prefer raise exception new is reported in this case:
`RAISE EXCEPTION TYPE cx_blah MESSAGE e003.`

But there is no valid syntax for RAISE EXCEPTION NEW + MESSAGE.
This should be a syntax error, but abaplint does not detect it:
`RAISE EXCEPTION NEW cx_blah( ) MESSAGE e003.`

**Comment by larshp** [comment]
thanks 👍

**Comment by larshp** [comment]
second part moved to https://github.com/abaplint/abaplint/issues/1854

false positive to be fixed by https://github.com/abaplint/abaplint/pull/1853

**Comment by larshp** [comment]
@FreHu try again, false positive fixed in latest version, 2.71.2
