### ISSUE TITLE
abaplint run hangs if abaplint.json is not valid

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1856]
I had a few times where a `,` was missing in an array. run didn't complete. I think 54106 was an example

**Comment by larshp** [comment]
yeap, it seems hanging, an error is shown on https://abaplint.app/jobs if the repo is public

but true, it should revert the error to the repo

**Comment by larshp** [comment]
@mbtools try again

**Comment by mbtools** [comment]
fails with error now 👍 

![image](https://user-images.githubusercontent.com/59966492/113475866-138e2080-9478-11eb-8a78-2ce69bfc5056.png)
