### ISSUE TITLE
Jump to code based on abaplint issue

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1871]
Not sure where else to put this little helper. Turn into a new repo, add to some repo, or just leave it here? 

Takes location of abaplint issue and displays corresponding ABAP code or directly jumps to code

https://gist.github.com/mbtools/1d67bd896b395b4cc98b171ce606a17c

![image](https://user-images.githubusercontent.com/59966492/112203468-da9db280-8c12-11eb-87be-b259f567d80f.png)

Cut&paste issue location into the helper and run:

![image](https://user-images.githubusercontent.com/59966492/112203602-0325ac80-8c13-11eb-8075-8042775f2311.png)

![image](https://user-images.githubusercontent.com/59966492/112203814-36683b80-8c13-11eb-95bc-db049630459d.png)

![image](https://user-images.githubusercontent.com/59966492/112203898-526bdd00-8c13-11eb-8695-6476d0e73446.png)

**Comment by larshp** [comment]
cool

**Comment by larshp** [comment]
closing...
