### ISSUE TITLE
--rename breaks on inferred type

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#1874]
![image](https://user-images.githubusercontent.com/5097067/112488451-d510ab80-8d7d-11eb-85af-25be02dcb39f.png)

**Comment by larshp** [comment]
heh, thanks

**Comment by FreHu** [comment]
I'm trying to rename the materials from the opensap unit testing course, because they are including some custom rename utility:
[openSAP_wtc1_abapGit_20180403.zip](https://github.com/abaplint/abaplint/files/6206295/openSAP_wtc1_abapGit_20180403.zip)

![image](https://user-images.githubusercontent.com/5097067/112507248-c4b4fc80-8d8e-11eb-82dc-407664deaeae.png)

**Comment by larshp** [comment]
@FreHu try again, 2.73.3

**Comment by FreHu** [comment]
works, although the package can't be renamed yet as only `clas` and `intf` are supported.

(para, tran, dtel, fugr, doma, ttyp, tabl, prog are missing for this case)
