### ISSUE TITLE
[False-Positive] A line should not contain only "." or ")."

### ISSUE THREAD

**Issue by lucasborin** [abaplint/abaplint#1888]
False-positive:

![image](https://user-images.githubusercontent.com/5233413/113758755-a9c97d00-96ea-11eb-9775-c56d4b06c625.png)

Run:
https://github.com/SAP/code-pal-for-abap/pull/304/checks?check_run_id=2280852190

**Comment by larshp** [comment]
is the left part of the screenshot from the `.testclasses.abap` file? it could look as if its the constructor of the global class

**Comment by lucasborin** [comment]
Oh, gosh! My bad. I have not seen the `.testclass.abap` at the end. 

![image](https://user-images.githubusercontent.com/5233413/113759588-9bc82c00-96eb-11eb-9837-8bd9e54f9a96.png)

The rule is correct. I'll turn it off in such a case.
