### ISSUE TITLE
Remove double space

### ISSUE THREAD

**Issue by lucasborin** [abaplint/abaplint#1890]
![image](https://user-images.githubusercontent.com/5233413/113759843-f06ba700-96eb-11eb-9f41-9ee005e75158.png)

I will turn the rule off as I prefer the code aligned here instead of removing the double space:
![image](https://user-images.githubusercontent.com/5233413/113759897-ff525980-96eb-11eb-904f-d5ebfb271430.png)

However, I would prefer the rule finding these cases:
![image](https://user-images.githubusercontent.com/5233413/113759876-fa8da580-96eb-11eb-855e-1e8cbd6af0e7.png)
Ps: They were not reported.

**Comment by larshp** [comment]
For after paren, there is a configuration option, https://rules.abaplint.org/double_space/

Before "=", yea, its not implemented yet

**Comment by larshp** [comment]
before "=" will probably be done in https://github.com/abaplint/abaplint/issues/929
