### ISSUE TITLE
[False-Positive] No Yoda conditions

### ISSUE THREAD

**Issue by lucasborin** [abaplint/abaplint#1891]
![image](https://user-images.githubusercontent.com/5233413/113760776-06c63280-96ed-11eb-8978-2cc836ebbad2.png)

![image](https://user-images.githubusercontent.com/5233413/113760740-fb730700-96ec-11eb-83eb-43e82e783dda.png)

**Comment by larshp** [comment]
see #1954

**Comment by larshp** [comment]
use new setting `onlyConstants`

https://rules.abaplint.org/no_yoda_conditions/

**Comment by lucasborin** [comment]
It looks like there are more false positives:

- https://github.com/SAP/code-pal-for-abap/pull/405/files

Or, am I understanding the Yoda conditions wrongly?

**Comment by larshp** [comment]
@lucasborin can this issue be closed?
