### ISSUE TITLE
Prefer Inline Declarations, PERCENTAGE

### ISSUE THREAD

**Issue by lucasborin** [abaplint/abaplint#1892]
![image](https://user-images.githubusercontent.com/5233413/113761702-23af3580-96ee-11eb-9403-2e795ada0893.png)

![image](https://user-images.githubusercontent.com/5233413/113761682-1e51eb00-96ee-11eb-8f2c-7d068c925cee.png)

Can we declare an in-line formula? 
If not, false-positive?

**Comment by larshp** [comment]
yea, the prefer_inline rule has some issues, its still experimental 😄

**Comment by larshp** [comment]
`DATA(percentage) = VALUE decfloat16( ).` is possible, but it doesnt bring any value in this example IMHO

perhaps the rule should only report for structures and internal tables

**Comment by g-back** [comment]
`DATA(percentage) = CONV decfloat34( comment_number / abs_statement_number ) * 100.`

**Comment by larshp** [comment]
ahh, yea 👍

**Comment by larshp** [comment]
@lucasborin I've added the example in https://rules.abaplint.org/prefer_inline/, does this help?

**Comment by larshp** [comment]
@lucasborin close this issue? feel free to open new issues
