### ISSUE TITLE
[False-Positive] Escape SQL host variables

### ISSUE THREAD

**Issue by lucasborin** [abaplint/abaplint#1896]
![image](https://user-images.githubusercontent.com/5233413/113900993-cb873a80-97a4-11eb-9b29-ebc86fe91d6e.png)

![image](https://user-images.githubusercontent.com/5233413/113901021-d215b200-97a4-11eb-9707-fc7bad0addcf.png)

`MODIFY SCREEN` variables cannot be escaped.

Run: https://github.com/SAP/code-pal-for-abap/pull/304/checks?check_run_id=2289307670

**Comment by larshp** [comment]
thanks

related = https://github.com/abaplint/abaplint/issues/1732

**Comment by larshp** [comment]
@lucasborin try again, latest version

**Comment by lucasborin** [comment]
Fixed!
