### ISSUE TITLE
[False-Positive] Uncaught exception YCX_OBJECT_NOT_PROCESSED

### ISSUE THREAD

**Issue by lucasborin** [abaplint/abaplint#1897]
![image](https://user-images.githubusercontent.com/5233413/113901477-42bcce80-97a5-11eb-9580-a1348a5860b8.png)

![image](https://user-images.githubusercontent.com/5233413/113901523-4e0ffa00-97a5-11eb-9e72-28b6183091f1.png)

It is being forward to the caller:
![image](https://user-images.githubusercontent.com/5233413/113901557-58ca8f00-97a5-11eb-9152-68890979dd6a.png)

Run: https://github.com/SAP/code-pal-for-abap/pull/304/checks?check_run_id=2289307670

**Comment by larshp** [comment]
thanks, I'm not really sure what causes this in abaplint, so I suggest disabling the rule for now

**Comment by larshp** [comment]
it currently traverses the statement structure without the include, and the spaghetti syntax is with the include

**Comment by larshp** [comment]
@lucasborin try again

**Comment by lucasborin** [comment]
Fine:

- https://github.com/SAP/code-pal-for-abap/pull/405/checks?check_run_id=2685557650
- https://github.com/SAP/code-pal-for-abap/pull/405/checks?check_run_id=2685560392
