### ISSUE TITLE
[False-Positive] Variable "function" not used

### ISSUE THREAD

**Issue by lucasborin** [abaplint/abaplint#1900]
![image](https://user-images.githubusercontent.com/5233413/113913249-7a7e4300-97b2-11eb-9c9d-addf43722fa6.png)

![image](https://user-images.githubusercontent.com/5233413/113913119-528edf80-97b2-11eb-97c6-a5bdfcb023f2.png)

Run: https://github.com/SAP/code-pal-for-abap/pull/304/checks?check_run_id=2290014389

**Comment by larshp** [comment]
I think the underlaying problem is the same as #1901

**Comment by lucasborin** [comment]
I ran it today, and the issue is not there anymore. Have you changed something?

Run: https://github.com/SAP/code-pal-for-abap/pull/304/checks?check_run_id=2296641852

**Comment by larshp** [comment]
yes, it now finds the usages :)

**Comment by lucasborin** [comment]
So, fixed. :)
