### ISSUE TITLE
[False-Positive] Variable "structure" not used

### ISSUE THREAD

**Issue by lucasborin** [abaplint/abaplint#1901]
![image](https://user-images.githubusercontent.com/5233413/113904559-8e24ac00-97a8-11eb-9798-e0fb5e3e0198.png)

![image](https://user-images.githubusercontent.com/5233413/113904537-87963480-97a8-11eb-9405-5f67ba64e0b1.png)

Abstract methods are not relevant.

Run: https://github.com/SAP/code-pal-for-abap/pull/304/checks?check_run_id=2289434137

**Comment by larshp** [comment]
@lucasborin I think this is also fixed in the latest version?
