### ISSUE TITLE
check_syntax: Constants (defined in include) not found in class

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1930]
Issue:
```
abaplint 2.74.8
./src/ma/#redwood#cl_ma_aktyp_mapping.clas.abap[30, 13] - c_target_addons not found, findTop (check_syntax) [E]
./src/ma/#redwood#cl_ma_aktyp_mapping.clas.abap[36, 13] - c_target_addons not found, findTop (check_syntax) [E]
./src/ma/#redwood#cl_ma_aktyp_mapping.clas.abap[39, 13] - c_target_addons not found, findTop (check_syntax) [E]
./src/ma/#redwood#cl_ma_aktyp_mapping.clas.abap[42, 13] - c_target_basics not found, findTop (check_syntax) [E]
./src/ma/#redwood#cl_ma_aktyp_mapping.clas.abap[43, 13] - c_basics_status not found, findTop (check_syntax) [E]
```
![image](https://user-images.githubusercontent.com/53995991/116036602-3cfd2f00-a667-11eb-9701-31954a85be6a.png)

Created a test case with two includes defined in different sections of the class.
https://github.com/ed-holland/AG_Tests.git
Although the case is as close as i can create it, it has no issues to be found.

Maybe a namespace issue with classes?

**Comment by ed-holland** [comment]
Could the reason why the include is not found is that it is part of a FUGR. The file naming is #redwood#ma.fugr.#redwood#lmad11.abap

**Comment by ed-holland** [comment]
I can confirm the previous comment. The public case now has this implemented and the error is there ;-)

**Comment by larshp** [comment]
@ed-holland try again, 2.74.9 published

**Comment by ed-holland** [comment]
YES. Both my issues are now resolved.
Thanks again.

**Comment by larshp** [comment]
🥳
