### ISSUE TITLE
unused_variables: check does not respect pragma in includes

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#1967]
If the variable is defined in an include, the ##NEEDED pragma does not suppress the check.

https://github.com/mbtools/TEST_UNUSED

![image](https://user-images.githubusercontent.com/59966492/118639314-0f278800-b7d8-11eb-98b6-9caf63fba585.png)

**Comment by larshp** [comment]
thanks 👍

**Comment by larshp** [comment]
@mbtools try again, 2.74.22

**Comment by mbtools** [comment]
👍
