### ISSUE TITLE
parse_error: Macro defined not recognized in function module

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#1994]
Issue:
```
./src/bsc/#jcs#bsc.fugr.#jcs#acc_doc_create_atta.abap[11, 3]                     - Statement does not exist in ABAPv700(or a parser error), "check_authorization_exc" (parser_error) [E]
```
The macro is defined in an include which is included into the TOP include of the function group.

Source:
![image](https://user-images.githubusercontent.com/53995991/119950560-439b0100-bf9b-11eb-99ad-44d7472614ea.png)

**Comment by larshp** [comment]
workaround is adding it as a `globalMacros` in `abaplint.json`

**Comment by ed-holland** [comment]
Added to globalmacros as workaround
