### ISSUE TITLE
Select distinct into corresponding fields fails

### ISSUE THREAD

**Issue by DennisLybecker-INVIXO** [abaplint/abaplint#2008]
The following error occurs with the sample code:
/zfoobar.prog.abap[4, 1]: Statement does not exist in ABAPv755(or a parser error), "SELECT"(parser_error)

`REPORT zfoobar.
DATA lt_edimsg TYPE STANDARD TABLE OF edimsg WITH EMPTY KEY.

SELECT DISTINCT ( mestyp ) INTO CORRESPONDING FIELDS OF TABLE @lt_edimsg
FROM edimsg.
`

**Comment by larshp** [comment]
thanks, reproduced

![image](https://user-images.githubusercontent.com/5888506/120602894-bdbfff80-c44b-11eb-8bae-7a46b55c2fd2.png)

**Comment by larshp** [comment]
same error with `SELECT ( mestyp ) INTO CORRESPONDING FIELDS OF TABLE @lt_edimsg FROM edimsg.`

**Comment by larshp** [comment]
`SELECT ( ( mestyp ) ) INTO CORRESPONDING FIELDS OF TABLE @lt_edimsg FROM edimsg.`

**Comment by larshp** [comment]
@DennisLybecker-INVIXO try again, 2.74.37

**Comment by DennisLybecker-INVIXO** [comment]
Works, thanks.
