### ISSUE TITLE
rename: %23 in filename for namespaces

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2023]
My config:

```json
"rename": { 
  "output": "output",    
  "patterns": [{"type": "CLAS|INTF", "oldName": "Z(.*)_AJSON", "newName": "/MBTOOLS/$1_AJSON"}]  
},
```

Output:

![image](https://user-images.githubusercontent.com/59966492/122038269-b5fe4480-cdd5-11eb-8d54-95a9316c4d7b.png)

Should be # instead of %23 in filename

**Comment by larshp** [comment]
thanks, I'm planning to do a release later today, this should be an easy fix

**Comment by larshp** [comment]
@mbtools  try again, 2.74.46

**Comment by mbtools** [comment]
👍 

![image](https://user-images.githubusercontent.com/59966492/122185888-c2de6f00-ce8d-11eb-9749-268b9eb15f10.png)
