### ISSUE TITLE
rename: indentation

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2026]
rename removes indentation of some code (on multi-line statements)

Original:

![image](https://user-images.githubusercontent.com/59966492/122218047-4c059e00-ceae-11eb-8c1a-8cdb33d10576.png)

Example (red = expected, green = rename output):

![image](https://user-images.githubusercontent.com/59966492/122217851-19f43c00-ceae-11eb-95b9-e192206741c6.png)

**Comment by larshp** [comment]
thanks, looks like a bug

note you can also run the quickfix for indentation, `--fix` as a temporary workaround after renaming

**Comment by mbtools** [comment]
I'm using the same config as in AG, which includes the `--fix`:
https://github.com/Marc-Bernard-Tools/Mirror-AJSON/blob/main/package.json

**Comment by mbtools** [comment]
it was missing `in_statement_indentation` rule
