### ISSUE TITLE
rename: pretty print exception classes

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2027]
Renamed exception class is not pretty printed (expected keyword = upper case, vars = lower). Am I missing some config? 

![image](https://user-images.githubusercontent.com/59966492/122218647-ef56b300-ceae-11eb-815b-3a6a5bbe8e7d.png)

**Comment by larshp** [comment]
https://rules.abaplint.org/keyword_case/, set `"ignoreExceptions": false,`

note there is a similar setting in https://rules.abaplint.org/indentation/

**Comment by mbtools** [comment]
👍
