### ISSUE TITLE
rename: mapping for object description

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2028]
It would be nice, if we could change the object description in some way. For example, adding a prefix:

Example (red = my version, green = renamed output):

![image](https://user-images.githubusercontent.com/59966492/122219091-61c79300-ceaf-11eb-8f40-861200e5d4da.png)

**Comment by larshp** [comment]
also `sed`, this can be a simple regex

**Comment by mbtools** [comment]
I have it's nicely scripted with sed now
