### ISSUE TITLE
rename: add "credit" comment block

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2029]
When reusing code, I like to give credit to the original author and link to the license. For example:

![image](https://user-images.githubusercontent.com/59966492/122219506-c97dde00-ceaf-11eb-9576-806b0b36c921.png)

It would be nice to be able to insert some thing like this automatically.

**Comment by larshp** [comment]
suggest using https://en.wikipedia.org/wiki/Sed

**Comment by mbtools** [comment]
It took a bit of learning `sed` but it works nicely with something like this (assuming there's a blank line after the `CLASS` statement):

```sh
sed '0,/^$/ s/^$/\n*** CREDITS ***\n/' test.clas.abap
```

**Comment by larshp** [comment]
yea, but when its done, it should keep working forever

then we can let abaplint handle the complex renaming
