### ISSUE TITLE
git pipeline abaplint only changed files

### ISSUE THREAD

**Issue by heikobr** [abaplint/abaplint#2057]
Hello.

We use ABAPLINT in a GITLAB pipeline.
We would like to only check changed files of a merge request via ABAPLINT.

Which settings are necessary for this?

Thanks and regards, 
Heiko

**Comment by larshp** [comment]
well, as a starting point I recommend establishing development guidelines, and following these

it might be a challenge if there is a lot of old code, but you can also choose to only run the linter for some packages

you can start out with a small set of rules, and then enable more over time for more files

**Comment by heikobr** [comment]
How can we restrict the packages?

**Comment by larshp** [comment]
you can organize the different packages into different repositories in abapGit

or, in the top of `abaplint.json`
```
{
  "global": {
    "files": "/src/**/*.*",
    "exclude": [],
```
set the files, it uses a [glob pattern](https://www.npmjs.com/package/glob)

**Comment by larshp** [comment]
@heikobr did above help?

**Comment by larshp** [comment]
closing, no reply
