### ISSUE TITLE
Use functional writing style for method calls

### ISSUE THREAD

**Issue by lucasborin** [abaplint/abaplint#2103]
Source: https://github.com/SAP/code-pal-for-abap/pull/442/files

Code:
![image](https://user-images.githubusercontent.com/5233413/130813995-10c895ca-d1ae-49cb-bda6-928b96383555.png)

Functional writing style:
![image](https://user-images.githubusercontent.com/5233413/130814657-1008d348-7724-4385-bbf3-b4cff08076f0.png)

Syntax error message:
![image](https://user-images.githubusercontent.com/5233413/130814693-6ca8dcdd-3946-43f4-aedd-51f84554c547.png)

False-positive? It looks like `exceptions` (classic) can only be used with the `CALL METHOD` statement.

Btw, that's strange. The eclipse auto-complete (shift+enter) created the functional writing style, but it looks like it is no longer accepted.

**Comment by larshp** [comment]
try this,

![image](https://user-images.githubusercontent.com/5888506/130818560-d44df4a7-d9e6-4274-9d53-dd99d3c1e300.png)

**Comment by lucasborin** [comment]
Yah, you are right. Problem solved. Thanks, Lars!

![image](https://user-images.githubusercontent.com/5233413/130827043-2f0931a0-348f-40b6-a5c0-44692d0201da.png)
