### ISSUE TITLE
unused_ddic: DDIC used in other DDIC

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2110]
DDIC objects are often used in the definition of other DDIC objects. For example, DTEL used in TABL. Those should count as usage for DTEL. There are obviously quite a few of those combinations.

PS: Is there a way to reproduce scenarios with multiple objects (like code + a ddic XML) in the playground?

**Comment by larshp** [comment]
playground: no, it can only handle one abap file

suggest making a public repository with some dummy objects for an example

**Comment by mbtools** [comment]
Works 👍

**Comment by mbtools** [comment]
can't reproduce
