### ISSUE TITLE
Wrong error title in eclipse

### ISSUE THREAD

**Issue by OberstVonGatow** [abaplint/abaplint#2117]
Maybe someone has a hint what the problem is or has the same issue. Otherwise i think i just have to reinstall eclipse.

Since yesterday i get wrong error titles for all atc errors in eclipse:
For example wrong type naming tys_... instead of ty_...

`     TYPES: BEGIN OF tys_vhart_vhilm,
             vhart TYPE vhart,
             vhilm TYPE vhilm,
           END OF tys_vhart_vhilm.`

I get the error "Uncaught Exception".
![image](https://user-images.githubusercontent.com/6384996/131637460-70f41b33-ec8b-4a6b-90d2-5d10a06ac0b6.png)
and in the Editor tool tip
![image](https://user-images.githubusercontent.com/6384996/131637616-9f5caabd-0d22-4f8e-9816-34432505e94b.png)

But only the error title is wrong the details are correct.
This happens in every class/report... i tried and every error is wrong.
If i check in SE80 everything is correct
![image](https://user-images.githubusercontent.com/6384996/131637988-91e52846-fde2-49e2-8711-8abc56b1ec22.png)

Does anyone know if there is a cache in eclipse i could reset?

**Comment by larshp** [comment]
I guess you are using https://github.com/abaplint/abaplint-sci-client ?

**Comment by OberstVonGatow** [comment]
> I guess you are using https://github.com/abaplint/abaplint-sci-client ?

Yes

**Comment by OberstVonGatow** [comment]
Closed because wrong repo -> new issue https://github.com/abaplint/abaplint-sci-client/issues/256
