### ISSUE TITLE
Exit code does not distinguish between findings and execution issues

### ISSUE THREAD

**Issue by agoeb** [abaplint/abaplint#2118]
I just came across a situation in which abapLint (cli) was run on a system that did not have git installed. There, the `git clone` command for retrieving the default dependencies failed, and no checks were executed at all.

It would be great to have a way of programmatically distinguishing between the "we found issues" and "we couldn't even check" cases. This way the caller (build script) could decide on whether to report the number of found issues into a trend database. If something goes wrong during execution, you would not want the number of found issues drop to 1.

Would it be possible to return with another exit code (different from 1) in case of generic execution issues like a failed `git clone` invocation?

**Comment by larshp** [comment]
I assume you are using command line abaplint?

**Comment by larshp** [comment]
hmm, but it will give some other trouble

**Comment by agoeb** [comment]
> I assume you are using command line abaplint?

Yes, using abaplint-cli - updated the description.

> hmm, but it will give some other trouble

That's what I was a bit nervous about. So if you have any suggestion that you think would not break things elsewhere, that would be awesome.

**Comment by larshp** [comment]
@agoeb try again, 2.78.0
