### ISSUE TITLE
PCRE syntax is not yet recognized

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#2131]
https://blogs.sap.com/2020/12/10/modern-regular-expressions-in-abap-part-1-introducing-pcre/

- find/replace statements now have the `PCRE` keyword as an option
- builtin functions find, replace, count, matches now have a `pcre` parameter
  - both `pcre` and `regex` cannot be specified at the same time
- in ADT i also now get syntax check warnings that the POSIX regexes are deprecated, this could be a separate check

**Comment by larshp** [comment]
builtin functions = `find`, `replace`, `count`, `match`

from 7.55, https://help.sap.com/doc/abapdocu_755_index_htm/7.55/en-US/index.htm?file=abennews-755-strings.htm

**Comment by larshp** [comment]
starting this

move the last point regarding the warning to a new issue?

**Comment by larshp** [comment]
first 2 parts to be solved via https://github.com/abaplint/abaplint/pull/2128

not perfectly solved, but it should not give false positives for allowed syntax

**Comment by larshp** [comment]
@FreHu try again, 2.78.7, move remaining parts to new issue and close this one?

**Comment by FreHu** [comment]
#2132
