### ISSUE TITLE
False-Positive: Omit default parameter name "P_LEVEL"

### ISSUE THREAD

**Issue by lucasborin** [abaplint/abaplint#2136]
Issue: 
![image](https://user-images.githubusercontent.com/5233413/132903163-ce3519ac-d1a6-410b-9549-24aa64e3efd8.png)

Signature:
![image](https://user-images.githubusercontent.com/5233413/132903192-c3634edc-02f3-4bef-8c7c-22e2aa0cb764.png)

Problem:
![image](https://user-images.githubusercontent.com/5233413/132903347-498811dd-9fe2-46e4-86fa-46d0fc82dfee.png)

![image](https://user-images.githubusercontent.com/5233413/132903328-2584cb5e-46fd-44c2-bf68-14b37ce185e3.png)

**Comment by larshp** [comment]
its a problem in deps, https://github.com/abaplint/deps/blob/88814236d57de96097e38a3a9f5733f54c9da51d/src/ci/cl_ci_test_scan.clas.abap#L7

there is only one parameter specified, ie. the finding is correct, deps is wrong

**Comment by larshp** [comment]
@lucasborin try again, https://github.com/abaplint/deps/pull/98 merged

**Comment by lucasborin** [comment]
solved.
