### ISSUE TITLE
check_syntax: SHIFT with CSEQUENCE

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2144]
```abap
REPORT zfoobar.
CLASS lcl_foobar DEFINITION.
  PUBLIC SECTION.
    METHODS test EXPORTING ev_foo TYPE csequence.
ENDCLASS.
CLASS lcl_foobar IMPLEMENTATION.
  METHOD test.
    SHIFT ev_foo LEFT DELETING LEADING space.
  ENDMETHOD.
ENDCLASS.
```

/zfoobar.prog.abap[8, 5]: Shift, Target not char like(check_syntax)

PS: Highlighting for `CLASS` doesn't work properly

![image](https://user-images.githubusercontent.com/59966492/133290386-b3c10db8-5222-4ef0-aa62-a10b282b7b8f.png)

**Comment by larshp** [comment]
highlighting: yea, I'm messing with the semantic highlighting feature, it has issues on the playground

**Comment by larshp** [comment]
@mbtools try again, 2.79.0

**Comment by mbtools** [comment]
👍
