### ISSUE TITLE
check_syntax: change of severity does not change the output

### ISSUE THREAD

**Issue by gregorwolf** [abaplint/abaplint#2151]
I've reduced the severity for check_syntax to Info in the Project [gregorwolf/abapGitTestSEGWservice](https://github.com/gregorwolf/abapGitTestSEGWservice). But I still get the following errors:

```
./src/zcl_zepm_bp_dpc_ext.clas.abap[26, 3] - Method definition "/iwbep/if_mgw_appl_srv_runtime~get_stream" not found (check_syntax) [E]
./src/zcl_zepm_bp_dpc_ext.clas.abap[41, 3] - Method definition "/iwbep/if_mgw_appl_srv_runtime~update_stream" not found (check_syntax) [E]
```

My abaplint/cli version according to the output of `abaplint -v` is 2.79.2.

**Comment by larshp** [comment]
@gregorwolf thanks, try again, 2.79.3 published

**Comment by gregorwolf** [comment]
Works. Thank you.
