### ISSUE TITLE
rename fails even if they are only abaplint warnings

### ISSUE THREAD

**Issue by gregorwolf** [abaplint/abaplint#2158]
I've added an empty block in the source project [abapGitTestSEGWservice](https://github.com/gregorwolf/abapGitTestSEGWservice) when I now run `npm run mirror` in the project [abapGitTestSEGWserviceRename](https://github.com/gregorwolf/abapGitTestSEGWserviceRename) the rename fails with this error message:

```
./src/zcl_zepm_bp_dpc_ext.clas.abap[90, 5] - Empty block, add code: If (empty_structure) [W]
abaplint: 1 issue(s) found, 13 file(s) analyzed
Renames NOT applied, issues foundnpm ERR! code ELIFECYCLE
```

Is there an option that the rename is executed as long as no errors occur?

**Comment by larshp** [comment]
not as is

workaround: have multiple abaplint configuration files

**Comment by larshp** [comment]
just disable the rule in the renaming configuration file

**Comment by larshp** [comment]
@gregorwolf did above help?
