### ISSUE TITLE
abaplint.app: Re-running check action does not work as expected

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2161]
I'm triggering a re-run of the abaplint check via Github:

![image](https://user-images.githubusercontent.com/59966492/134231064-ea9d0be7-169f-4b0a-a743-8a9082fb6e58.png)

Original check had 8 issues. However, if you scroll down after the re-run, there are now 16 issues in the list (the count still says 8). Click re-run again and it shows 24 issues. 

Also, the repo has changed and the issues that were in files unrelated to this PR have been fixed. Should it still show issues or would it take the newer files into consideration?

**Comment by larshp** [comment]
thanks, its a bug

each github check suite is associated with a commit, ie rerunning reruns for that commit
![image](https://user-images.githubusercontent.com/5888506/134277783-278143d3-fe26-4caa-86e1-86e6afa7ff16.png)

**Comment by larshp** [comment]
hmm, seems to be a "feature" of the GitHub API,

![image](https://user-images.githubusercontent.com/5888506/134278874-35166ffa-b1d1-4655-b99f-bc3a52b58a0e.png)

**Comment by mbtools** [comment]
The append makes no sense to me. Oh well.

btw, the API supports getting up to 100 per page:
https://docs.github.com/en/rest/reference/checks#list-check-run-annotations

**Comment by larshp** [comment]
yea, abaplint.app only shows 50, 100's or 1000's of errors would be impossible to navigate anyhow IMHO
