### ISSUE TITLE
Lint 2.79.4 shows new error "Structure, duplicate field name - at new StructureType"

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#2163]
Since monday, we get this error
```
node version:     v12.22.6
abaplint version: 2.79.4

generic[1, 1] - Error: Structure, duplicate field name - at new StructureType (webpack://@abaplint/cli/./node_modules/@abaplint/core/build/src/abap/types/basic/structure_type.js?:15:23) (generic_error) [E]
```

The issue was caused in the dependencies repository. It was last changed on Sep. 10.
The change only deleted one DTEL (`src/wusl/tswpos.dtel.xml`)

**Comment by larshp** [comment]
will give a better error message with https://github.com/abaplint/abaplint/commit/2ae03ec7d90445dd0719f65b06823ffb4f0ac18b

the docker image build had been stuck for a while, https://hub.docker.com/r/abaplint/abaplint/tags?page=1&ordering=last_updated

**Comment by larshp** [comment]
@ed-holland try again with 2.79.5, it might provide a better error message

**Comment by ed-holland** [comment]
Issue is much clearer
`Error: Structure, duplicate field name "-", VIAUFKST at new StructureType (webpack://@abaplint/cli/./node_modules/@abaplint/core/build/src/abap/types/basic/structure_type.js?:15:23) (generic_error) [E]`

The View in SE11 has several entries like this:
![image](https://user-images.githubusercontent.com/53995991/134377924-f7a75183-5d87-475e-a005-d56e29c11745.png)
The xml of the view was change 8 months ago.

It contains entries like this
```
   <DD27P_TABLE>
    <DD27P>
     <VIEWFIELD>MANDT</VIEWFIELD>
     <TABNAME>AFIH</TABNAME>
     <FIELDNAME>MANDT</FIELDNAME>
     <KEYFLAG>X</KEYFLAG>
     <CHECKTABLE>T000</CHECKTABLE>
     <SHLPORIGIN>P</SHLPORIGIN>
    </DD27P>
    <DD27P>
     <VIEWFIELD>AUFNR</VIEWFIELD>
     <TABNAME>AFIH</TABNAME>
     <FIELDNAME>AUFNR</FIELDNAME>
     <KEYFLAG>X</KEYFLAG>
     <CHECKTABLE>AUFK</CHECKTABLE>
     <SHLPORIGIN>X</SHLPORIGIN>
     <LOGFLAG>X</LOGFLAG>
    </DD27P>
    <DD27P>
     <VIEWFIELD>*</VIEWFIELD>
     <TABNAME>AFIH</TABNAME>
     <FIELDNAME>*</FIELDNAME>
    </DD27P>
    <DD27P>
     <VIEWFIELD>-</VIEWFIELD>
     <TABNAME>AFIH</TABNAME>
     <FIELDNAME>MANDT</FIELDNAME>
     <CHECKTABLE>T000</CHECKTABLE>
     <SHLPORIGIN>P</SHLPORIGIN>
    </DD27P>
    <DD27P>
     <VIEWFIELD>-</VIEWFIELD>
     <TABNAME>AFIH</TABNAME>
     <FIELDNAME>AUFNR</FIELDNAME>
     <CHECKTABLE>AUFK</CHECKTABLE>
     <SHLPORIGIN>X</SHLPORIGIN>
     <LOGFLAG>X</LOGFLAG>
    </DD27P>
    <DD27P>
     <VIEWFIELD>ARTPR</VIEWFIELD>
     <TABNAME>AFIH</TABNAME>
     <FIELDNAME>ARTPR</FIELDNAME>
     <EFORM>*</EFORM>
     <CHECKTABLE>T356A</CHECKTABLE>
     <SHLPORIGIN>P</SHLPORIGIN>
    </DD27P>
```

**Comment by larshp** [comment]
heh, I'll have a look tomorrow

wonder what "-" does, new SAP feature of the day 😄

**Comment by ed-holland** [comment]
> wonder what "-" does, new SAP feature of the day

First Time i see this in over 25 Years of SAP

**Comment by ed-holland** [comment]
Nope, is not the view relation...
![image](https://user-images.githubusercontent.com/53995991/134384135-5fa240f0-d102-4ca0-b3ce-748f493ce984.png)
Maybe just fields not being used in the view...

**Comment by larshp** [comment]
@ed-holland try again, 2.79.7

**Comment by ed-holland** [comment]
Thx, this issue is gone.

Another came up. Will create a new issue for it.
