### ISSUE TITLE
unused_ddic: add skipNames config

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2165]
Should work the same way as for `unused_types`/`unused_variables`

**Comment by larshp** [comment]
can the existing `exclude` field be used? https://rules.abaplint.org/unused_ddic/ it supports regex patterns

eg if domain FOO is reported unused, set `exclude: ["foo.doma"]`

**Comment by mbtools** [comment]
it works! (note: refer to the file `#mbtools#mytab.tabl` and not the object `/mbtools/mytab`).
