### ISSUE TITLE
Lint 2.79.7: Structure, duplicate field name ".APPEND"

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#2167]
Issue occurred in the dependency Repository.
```
generic[1, 1] - Error: Structure, duplicate field name ".APPEND", RBKP_V at new StructureType (webpack://@abaplint/cli/./node_modules/@abaplint/core/build/src/abap/types/basic/structure_type.js?:15:23) (generic_error) [E]
```
This table has multiple append structures.

**Comment by larshp** [comment]
TABL seems to work https://github.com/abaplint/abaplint/commit/6ef6851ec266ad88d51589f7840ebb41606b4e9c

guess the issue is only for VIEWs

**Comment by larshp** [comment]
@ed-holland try again, 2.79.8

**Comment by ed-holland** [comment]
with this change, suddenly the linter is using `Using default config` which then generates thousands of errors.

**Comment by larshp** [comment]
not necessarily this change, but somewhere between 2.74.49 and 2.79.8

I restarted the build of docker containers some days ago, https://hub.docker.com/r/abaplint/abaplint/tags?page=1&ordering=last_updated

**Comment by larshp** [comment]
whats the exact message?

"Using default config"
"ERROR: Specified abaplint configuration file does not exist, using default config"
"Supply filename, not directory, using default config"

**Comment by ed-holland** [comment]
This is the messaging:
```
node version:     v12.22.6
abaplint version: 2.79.8
$ git config --global http.sslVerify false
$ export NODE_OPTIONS="--max-old-space-size=10240"
$ abaplint $CI_ABAPLINT -c
abaplint 2.79.8
Using default config
Clone: https://github.com/abaplint/deps
```
It runs now since 4 hours and is not finished...

With 2.79.7 this was not happening

**Comment by larshp** [comment]
2.79.7 failed before getting so far

whats in `$CI_ABAPLINT` ?

![image](https://user-images.githubusercontent.com/5888506/134650279-fe8aa821-f713-4eb3-ae99-59db9a9936e7.png)

**Comment by ed-holland** [comment]
I've restartet the wrong process. The dependency repository we do not lint as it is just to much.
The reason for the default is that there is not abaplint.json (name is in the variable).

The original issue of this ticket is resolved. Thx
