### ISSUE TITLE
Definitions and References on GitHub

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2172]
I was wondering what is needed to make this feature available for ABAP sources?

![image](https://user-images.githubusercontent.com/59966492/135304648-cd1579ab-df3c-45c1-b276-0ff81a21afb1.png)

For the long winter days...

It's based on [`tree-sitter`](https://docs.github.com/en/repositories/working-with-files/using-files/navigating-code-on-github). The parser will need a `grammar.js` as defined [here](https://tree-sitter.github.io/tree-sitter/creating-parsers). 

One might be able to generate this...

**Comment by larshp** [comment]
abaplint can find the references, there is just not a way AFAIK to upload it to github

creating a tree-sitter parser is out of scope for this project

puls I think its really difficult to do a LR(1) single pass grammar for ABAP, if possible at all
