### ISSUE TITLE
check_systax: SY-PDEST component not found in structure

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#2174]
The SY field PDEST is not recognized.
Dependency repository contains SYST table and also the Field PDEST.

```
abaplint 2.79.8
Using config: abaplint.json

./src/nw/variant/#jcs#variant_submit.prog.abap[32, 5] - Component "pdest" not found in structure (check_syntax) [E]
abaplint: 1 issue(s) found, 905 file(s) analyzed
```

Source:
![image](https://user-images.githubusercontent.com/53995991/135457618-ddaee814-1ee2-4ab7-aaf2-737c0f37ba7e.png)

**Comment by larshp** [comment]
@ed-holland try again, 2.79.9

**Comment by ed-holland** [comment]
Issue resolved. Thx
