### ISSUE TITLE
Package prefixes for object naming

### ISSUE THREAD

**Issue by cavabap** [abaplint/abaplint#2180]
Hello ABAP Lint Team,

Using ATC I have in the past created checks that package prefixes  (I'm not a big fan of them myself) of coding guidelines are being followed.

Usually it looks something like this,
IF the Package is ZSD, then all developments should start with ZSD.
E.g. 
Classes: ZCL_SD_MY_CLASS. (although I've enough customers who then even use use ZSD_CL_MY_CLASS )
Tables: ZSD_MY_TABLE
etc for data elements, structures, etc.

The prefix itself is selected either via a customizing table or from the first letters of the package that the development object.

I'm curious if there is a chance to generalize this for various systems using ABAP LInt?
Or would I need to have one ABAP Lint defintion per package/repository?

**Comment by FreHu** [comment]
You can accomplish this using object_naming, although it has to be configured in each repository separately.
```abap
"object_naming": {
      "clas": "^ZC(L|X)\\_ABAPGIT\\_",
      "intf": "^ZIF\\_ABAPGIT\\_",
      "prog": "^ZABAPGIT",
      "fugr": "^ZABAPGIT",
      "tabl": "^Z",
      "ttyp": "^Z",
      "dtel": "^Z",
      "doma": "^Z",
      "msag": "^Z",
      "tran": "^Z",
      "enqu": "^EZ",
      "auth": "^Z",
      "pinf": "^Z",
      "idoc": "^Z",
      "ssfo": "^Z",
      "ssst": "^Z",
      "shlp": "^Z",
      "xslt": "^Z"
    },
```

**Comment by larshp** [comment]
thinking, perhaps add the possibility to have multiple configs under object_naming, being matched by a filename regex

alternatively as a general thing for all rules, hmm

**Comment by FreHu** [comment]
i think this one is cleaner per object type as often the desired prefix has to be in a special position anyway or there is some extra convention or exception for a particular object type. 
So if you generalize it weakens the validation, e.g. uniting `zcl_prefix` and `zif_prefix` to `z(cl|if)_prefix` means i can now have a class with `zif`

**Comment by cavabap** [comment]
Okay. I've got this. To check it in abaplint would require the repository definition to match to the package prefix that is required, as illustrated by `"clas": "^ZC(L|X)\\_ABAPGIT\\_",`
