### ISSUE TITLE
Question: check if class/method exists

### ISSUE THREAD

**Issue by jan-jezek** [abaplint/abaplint#2181]
Hi,

Can I somehow check if called class/method exists in my repo (or is in deps)?
Eg. I have class "cl_foo" with method "bar" in repo1.
From repo2 I will call this method.

I want this check to fire until I either move class "cl_foo" into repo2 or I link repo1 as deps.

**Comment by larshp** [comment]
if CL_FOO is in the `errorNamespace` (configured in abaplint.json) it will be checked and errors reported as part of the `syntax_check` rule
