### ISSUE TITLE
allowed_object_naming: false positive for SOTS

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2213]
![image](https://user-images.githubusercontent.com/59966492/138730890-60be3109-bce3-4b07-81f5-aa77bada9e21.png)

DEVC, SOTS, SOTR can have `-` in the object name. 

Not sure if you want to change the regex or implement something object specific. 
https://github.com/abaplint/abaplint/blob/main/packages/core/src/rules/allowed_object_naming.ts#L46

**Comment by larshp** [comment]
similar = https://github.com/abaplint/abaplint/issues/2283
