### ISSUE TITLE
SAP Type Pool - Unexpected TYPEEND

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#2254]
![image](https://user-images.githubusercontent.com/53995991/143006368-e0513ab9-6eaf-4268-ad29-8f7fbdca2555.png)

Type Pool: 
![image](https://user-images.githubusercontent.com/53995991/143006622-c0dd8aca-3631-4d90-bf6d-35367ce92df2.png)

Issue
`/tmp/abaplint-NmJIbn/src/scpr/scpr.type.abap[34, 1] - Unexpected TYPEEND (structure) [E]`

**Comment by larshp** [comment]
try deleting the `%_FINAL` and see if that works

**Comment by ed-holland** [comment]
This is a SAP type group. No delete possible ;-(

**Comment by larshp** [comment]
copy the code to the playground and check there

**Comment by larshp** [comment]
reproduced as

```abap
TYPES: BEGIN OF foobar %_FINAL,
         sdfs  TYPE i,
       END OF foobar.
```

**Comment by larshp** [comment]
@ed-holland try again, 2.81.4

**Comment by ed-holland** [comment]
It seems that docker image build is stuck. Still on a older version. Can you push it?
![image](https://user-images.githubusercontent.com/53995991/143196117-263b7405-b927-480f-a803-e11c66c45bbf.png)

**Comment by larshp** [comment]
try again

**Comment by ed-holland** [comment]
Issue is resolved. Thanks
