### ISSUE TITLE
Structure: Expected TYPEEND

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#2255]
![image](https://user-images.githubusercontent.com/53995991/143232625-3e4854f7-9670-4aab-bed8-5aa3a1a45b4f.png)

Error:
/tmp/abaplint-IjJCFl/src/mrm/mmcr.type.abap[1, 1] - Expected TYPEEND (structure) [E]

Source (SAP Original)
![image](https://user-images.githubusercontent.com/53995991/143232524-c001a446-5f71-419a-b4d7-e1abac066e70.png)

Could it be that the blank before the colon is causing the issue?

**Comment by larshp** [comment]
reproduced as

```abap
TYPES: BEGIN OF foobar,
foo TYPE i,
INCLUDE zsdfsd.
TYPES: bar TYPE i.
TYPES: END OF foobar.
```

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/pull/2256/commits/9016c3a77ec3a599209ef9ad5dd862312972336c

**Comment by larshp** [comment]
@ed-holland try again, 2.82.0

**Comment by ed-holland** [comment]
Issue has been resolved. Thanks again.
