### ISSUE TITLE
Separate rules for mirrored objects in subpackages

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2263]
Imagining a solution using many mirrored repos (so far I'm using 3). The mirrored parts often use different rules (like different prefixes). Currently, you will have to add exceptions to your own abaplint.json. Globally excluding the mirrored objects doesn't work since your code depends on them.

A solution could be a different type of excluding that still parses the objects but doesn't raise issues or a mirrored abaplint.json that is located in the subfolder.

**Comment by larshp** [comment]
#2299 new global "noIssues" setting

**Comment by larshp** [comment]
@mbtools did the `noIssues` setting solve your issue?

**Comment by mbtools** [comment]
Yes 👍
