### ISSUE TITLE
allowed_object_naming: false positive for W3MI

### ISSUE THREAD

**Issue by sandraros** [abaplint/abaplint#2283]
Object named `ZDEMO_EXCEL15/1` is technically possible but rejected by abaplint.

Happens in abaplint for project abap2xlsx.

I think there's no check by SAP about the characters used, except the namespace at the beginning, like Y, Z for customers, /namespc/...

Name not allowed
https://rules.abaplint.org/allowed_object_naming

**Comment by larshp** [comment]
@sandraros thanks, try again, latest version

**Comment by sandraros** [comment]
Thank you very much, it works perfectly!
