### ISSUE TITLE
Method not found, methodCallChain

### ISSUE THREAD

**Issue by sandraros** [abaplint/abaplint#2284]
I don't get why I get this message (https://github.com/sapmentors/abap2xlsx/pull/902/files#annotation_2344214827):
![image](https://user-images.githubusercontent.com/34005250/144727686-d6623c60-bb71-48dc-9b46-2cb20cf2b66c.png)

(text: Method "create_filter_name_ns" not found, methodCallChain https://rules.abaplint.org/check_syntax)

Thank you!

**Comment by larshp** [comment]
try again, https://github.com/abaplint/deps/pull/130 merged

**Comment by sandraros** [comment]
Thank you very much, it works perfectly! 👍

**Comment by sandraros** [comment]
Now that I understand how it works, I guess I could directly provide a PR in the future, but is it possible to provide more information in the [abaplint "check syntax" link](https://rules.abaplint.org/check_syntax)?

**Comment by larshp** [comment]
yea, well, there might be multiple dependencies, or it might be a real syntax error
