### ISSUE TITLE
Prefer corresponding( ) to MOVE-CORRESPONDING

### ISSUE THREAD

**Issue by pokrakam** [abaplint/abaplint#2295]
Or a more general issue if functional writing should be enforced where all 'classic' syntax is available in the checked version.

**Comment by larshp** [comment]
its upport relevant, currently have these upport rules,

![image](https://user-images.githubusercontent.com/5888506/145803095-d8379e50-a981-4df2-8948-31fee0696ac4.png)

**Comment by larshp** [comment]
note, there are some forms of MOVE-CORRESPONDING which probably wont work with corresponding(), https://syntax.abaplint.org/?filter=move#/statement/MoveCorresponding

**Comment by pokrakam** [comment]
Yes, I know SAP added stuff to `corresponding( )` over several versions, so it's very much dependent on the version the linter is running against. 
That's what I meant by my utopian comment of "where all 'classic' syntax is available in the checked version.".
