### ISSUE TITLE
Enhancement to permit CLASS <ZCL_ALLUPPERCASE> IMPLEMENTATION with "keyword_case": true

### ISSUE THREAD

**Issue by sandraros** [abaplint/abaplint#2323]
When using the Class Builder (SE24/SE80), SAP automatically converts the class name to all upper case in `CLASS <classname> IMPLEMENTATION` while activating (for unknown reason, tested in ABAP 7.52). Example for my "ZZSRO" class pool:
```abap
CLASS zzsro DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    METHODS a .
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZZSRO IMPLEMENTATION.


* <SIGNATURE>---------------------------------------------------------------------------------------+
* | Instance Public Method ZZSRO->A
* +-------------------------------------------------------------------------------------------------+
* +--------------------------------------------------------------------------------------</SIGNATURE>
  METHOD a.
    " test
  ENDMETHOD.
ENDCLASS.
```

As far as I understand, the abaplint rule `"keyword_case": true` would indicate an error for `CLASS ZZSRO IMPLEMENTATION`, because `ZZSRO` should be in lower case. I don't have a repository setup with abaplint to verify that.

The problem is that the only solution to get the class name in lower case is to use Eclipse ADT or use Git editor/commands to fix it manually but many developers know neither Eclipse ADT nor Git, they only know the Class Builder.

Is it possible to make abaplint accept this error when there is `"keyword_case": true`?

Thanks.

Related discussion: https://github.com/abap2xlsx/abap2xlsx/issues/941

**Comment by larshp** [comment]
see configuration options in https://rules.abaplint.org/keyword_case/

The abapgit configuration ignores the case, https://github.com/abapGit/abapGit/blob/main/abaplint.json#L255

**Comment by sandraros** [comment]
OK, so I'm wrong, thanks for clarifying 👍. Closing.
