### ISSUE TITLE
align_parameters: create object

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2326]
```abap
REPORT zfoobar.
CREATE OBJECT go_test
  EXPORTING
    i_parent          = abap_false
    i_appl_events     = abap_true
  EXCEPTIONS
    error_cntl_create = 1
    error_cntl_init   = 2
    error_cntl_link   = 3
    error_dp_create   = 4
    OTHERS            = 5.
```

/zfoobar.prog.abap[4, 23]: Align parameters to column 19(align_parameters)

Looks aligned to me

**Comment by larshp** [comment]
the exceptions are not taken into account, its a bug

![image](https://user-images.githubusercontent.com/5888506/147885963-2bdbd09e-6600-43de-a9d0-6a3f16847fbe.png)

**Comment by larshp** [comment]
@mbtools try again, 2.83.18

**Comment by mbtools** [comment]
works 👍
