### ISSUE TITLE
SCI vs Git CI - different behavior

### ISSUE THREAD

**Issue by Zeatynis** [abaplint/abaplint#2327]
It seems that SCI treats files differently than CI or local abaplint run from command line.
I did:
`"global": {
    "exclude": ["/ws/"],
    "files": "/src/**/*.*"
    },`
    CI and command line runs work but SCI keeps returning errors for these files.
    

It seems like SCI doesn't look on file path but only on filename.

Am I doing something wrong? Maybe any repo setting is wrong? I use prefix folder logic.

**Comment by larshp** [comment]
SCI? are you using https://github.com/abaplint/abaplint-sci-server ? which version?

**Comment by Zeatynis** [comment]
Yes, abaplint-server, version: 2.83.13

**Comment by Zeatynis** [comment]
Yes, abaplint-server 
![obraz](https://user-images.githubusercontent.com/9119187/147912272-9e3a68fe-cc29-4591-abd6-c5d5e6f219d2.png)

**Comment by Zeatynis** [comment]
I see that newest abaplint version is 2.83.13. I think I will start with upgrade of abaplint server 😄 Thanks for poiting the right way.

**Comment by larshp** [comment]
closing

**Comment by Zeatynis** [comment]
I didn't forget about it. I'm waiting for my IT to upgrade abaplint... It's on company's machine that I don't have access to...

**Comment by larshp** [comment]
okay, reopening

**Comment by Zeatynis** [comment]
Finally, I have a 2.85.14 version. Unfortunately the issue still occurs.

**Comment by larshp** [comment]
update to the latest 2.85.17 😁 nah, probably also an issue with that version

anyhow, it depends a lot on the settings, I of cause recommend pushing everything to github and using https://github.com/marketplace/abaplint

**Comment by Zeatynis** [comment]
I confirm that 2.85.17 still has this issue

**Comment by larshp** [comment]
well, I cannot reproduce it

need to know the design and configuration of your setup

**Comment by Zeatynis** [comment]
Let's drop this topic. I have no idea how to prepare an easy to use script/repo/setup for playback. I can describe how I have it set up, but I've already stopped using this approach (running SCI with abaplint) because it's very slow compared to running abaplint in the pipeline after commits.

**Comment by larshp** [comment]
ok

yea, I also dont SCI with abaplint, due to the same reason

however, I have some plans to make it faster and easier, but reducing the scope of rules when running on SCI

**Comment by Zeatynis** [comment]
Sure :)
