### ISSUE TITLE
Should abaplint report a missing type definition?

### ISSUE THREAD

**Issue by schneidermic0** [abaplint/abaplint#2354]
Hi,

Did abaplint miss the type declaration is missing in the following commit?
https://github.com/SAP/abap-file-formats/pull/274/commits/087acac4f8ce63bdafc09ad3ba9b2401a2f03577

Here the local type `ty_length` is used, but the interface does not contain this type.
https://github.com/drakth/abap-file-formats/blob/087acac4f8ce63bdafc09ad3ba9b2401a2f03577/file-formats/doma/type/zif_aff_doma_v1.abap#L94

abaplint did not report a finding, but maybe there is also something in our configuration:
https://github.com/SAP/abap-file-formats/blob/main/abaplint.jsonc

Let me know if you need more details.

Thanks,
Michael

**Comment by larshp** [comment]
in this case, the error is not reported, as the filename is `file-formats/doma/type/zif_aff_doma_v1.abap`

abaplint ignores files that are not in abapgit format, eg must end with ".<type>.xml" or ".<type>.abap"

**Comment by schneidermic0** [comment]
Ok, I see. This is fine for me. Thanks for checking it.

Do you want to follow-up anything on this topic? Otherwise, I'll close the issue.

**Comment by larshp** [comment]
closing
