### ISSUE TITLE
max_one_statement - include type

### ISSUE THREAD

**Issue by Zeatynis** [abaplint/abaplint#2389]
Hey, I'm not sure if I don't know the right way to attach the type or the 'max_one_statement' rule doesn't know it.
![obraz](https://user-images.githubusercontent.com/9119187/152494296-4ccbbeef-19f7-4c16-adf0-07882f1f4135.png)

**Comment by larshp** [comment]
use ".INCLUDE" when defining TABLs in DDIC

in ABAP, ".INCLUDE TYPE something." is the same as

```abap
  .
  INCLUDE TYPE something.
```

ie. its an empty statement, ie. remove the first "."

**Comment by Zeatynis** [comment]
It worked. Thanks! I don't know why I didn't figure it out by myself... Now that I know it, it seems obvious...
