### ISSUE TITLE
Source not character like (check_syntax)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#2398]
A strange error with this version. 
I've check the source file in git and it does not contain any special characters...

![image](https://user-images.githubusercontent.com/53995991/152960240-7fe971aa-de09-48e4-9f7b-34722714c291.png)

node version:     v16.13.2
abaplint version: 2.85.12

Error
`./src/ecc/#jcs#fi_document_list.prog.abap[77, 7] - Source not character like (check_syntax) [E]`

Source
![image](https://user-images.githubusercontent.com/53995991/152959868-23f14903-163f-4811-b42a-7568951ccd4c.png)

**Comment by larshp** [comment]
what is the type of `error` ?

**Comment by larshp** [comment]
reproduced as

```abap
DATA tab TYPE STANDARD TABLE OF string WITH HEADER LINE.
WRITE tab.
```

![image](https://user-images.githubusercontent.com/5888506/152961833-3a21b0bb-781a-4845-8aeb-ffd2dae86e3d.png)

**Comment by larshp** [comment]
@ed-holland try again, 2.85.13

**Comment by ed-holland** [comment]
Issue is resolved.

Also the issue #2340 is now resolved. 

Many Thanks
