### ISSUE TITLE
Method parameter type not compatible(check_syntax)

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#2403]
node version:     v16.14.0
abaplint version: 2.85.16

Reproduced using Playground:
```abap
REPORT zfoobar.
WRITE 'Hello World'.

DATA:
  p_new_where      LIKE TABLE OF where_line WITH HEADER LINE,
  p_paranth_set(1) TYPE c,
  p_last_length    TYPE i,
  p_length         TYPE i,
  p_last_tabix     LIKE sy-tabix.


p_length = p_last_length + 1 + strlen( p_new_where ).
```

The error is on p_length. New functionality?

**Comment by larshp** [comment]
yea, I'm adding more strict type checks

**Comment by larshp** [comment]
@ed-holland try again, 2.85.17

**Comment by ed-holland** [comment]
Reran the test with the new version and the problem is gone.
Thanks again and have a great weekend.
