### ISSUE TITLE
main_file_contents: Main file must have specific contents: REPORT or PROGRAM name should match filename

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#2413]
Der abap hat ein REPORT statement aber dieses wird nicht erkannt.
Removing the comments, results in the same error.

node version:     v16.14.0
abaplint version: 2.85.18

Issue:
`./src/ecc/#jcs#fi_bapi_user_journal_exec.prog.abap[5, 8] - Main file must have specific contents: REPORT or PROGRAM name should match filename (main_file_contents)`

Source:
![image](https://user-images.githubusercontent.com/53995991/154279984-391d2683-530c-4d02-afcd-5ad0706b65f3.png)

**Comment by larshp** [comment]
looks like the finding is correct? The object name and the REPORT does not match,

![image](https://user-images.githubusercontent.com/5888506/154288134-3e5f9081-9f85-471a-aa0f-8303298fcf83.png)

**Comment by larshp** [comment]
yea ABAP doesnt care as such

I do care however, it helps that it matches if the code is shared or screenshotted, just disable the rule if it is not important in your team 😄
