### ISSUE TITLE
"SWITCH" Statement Downport V702

### ISSUE THREAD

**Issue by thorsten-wolf-neptune** [abaplint/abaplint#2416]
When downporting to 702 the SWITCH Statement is not considered.
I tried downporting https://github.com/abapinho/abapTimeMachine.git to V702.
SWITCH Syntax Error:
![image](https://user-images.githubusercontent.com/83953375/154937684-357ca761-ffee-4246-a7ee-0d6556fb7966.png)

resolved manually like this:
![image](https://user-images.githubusercontent.com/83953375/154938150-9bb84099-1fa5-4803-a881-32704bc98bae.png)
```abap
    case asset_type.
      when 'CSS'.
        result = temp1.
      when 'HTML'.
        case options->mode.
          when zcl_timem_consts=>mode-blame.
            result = temp2.
          when zcl_timem_consts=>mode-time_machine.
            result = temp3.
        endcase.
    endcase.
*    result = SWITCH #(
*      asset_type
*      WHEN 'CSS' THEN temp1
*      WHEN 'HTML' THEN
*        SWITCH #(
*          options->mode
*          WHEN zcl_timem_consts=>mode-blame THEN temp2
*          WHEN zcl_timem_consts=>mode-time_machine THEN temp3 ) ).
```

**Comment by larshp** [comment]
yeap, thanks, another thing to add in https://rules.abaplint.org/downport/

**Comment by larshp** [comment]
@thorsten-wolf-neptune try again, latest version

**Comment by larshp** [comment]
closing, no reply
