### ISSUE TITLE
No downport for inline declaration of FIELD-SYMBOL

### ISSUE THREAD

**Issue by timbolski** [abaplint/abaplint#2424]
APPEND INITIAL LINE TO gr_notif_wo_type ASSIGNING FIELD-SYMBOL(<lfs_notif_wo_type>).

There is no quick fix available for this in the playground.

**Comment by larshp** [comment]
make sure that there are no syntax errors in the code, plus set the version to 702,

![image](https://user-images.githubusercontent.com/5888506/155874670-d5528071-f1d2-4c12-a130-eacbb6e43178.png)

**Comment by timbolski** [comment]
Tested successfully
