### ISSUE TITLE
Structure Check: Linter expects complete If/Endif to be in one member

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#2431]
Environment:
node version:     v16.14.0
abaplint version: 2.85.30

Issue did not exist with previous version (Linter runs every day with latests docker version).

Issue:
/tmp/abaplint-ilALfL/src/fvvi/ifre_begin_of_pr_addon.prog.abap[1, 1] - Expected ENDIF (structure) [E]
/tmp/abaplint-ilALfL/src/fvvi/ifre_end_of_pr_addon.prog.abap[1, 1]   - Unexpected ENDIF (structure) [E]

Dependency REPO code (Original SAP which can not be changed):
![image](https://user-images.githubusercontent.com/53995991/155954103-414362a0-52a6-40d6-9d00-4e0e440ba632.png)
![image](https://user-images.githubusercontent.com/53995991/155954092-659e27f0-b793-4475-bf0b-13e274504877.png)

**Comment by larshp** [comment]
are there any other issues in the list of issues?

suggest trying to reproduce in a public repository, one main program and two includes should reproduce it?

**Comment by ed-holland** [comment]
These are the only issues in the list.

This issue is not a new one. It was fixed before.

It is caused by not including all includes to the source of an executable object before checking.

Will try to create a public test-set.

**Comment by ed-holland** [comment]
Issue is fixed with the current version.
