### ISSUE TITLE
Empty when should fire error

### ISSUE THREAD

**Issue by jan-jezek** [abaplint/abaplint#2433]
![image](https://user-images.githubusercontent.com/17530797/155961030-ac4cb0f0-abca-4681-93fb-87cfebff39e1.png)
I would expect a check (probably [empty structure](https://rules.abaplint.org/empty_structure/)) to fire here.
Empty when is pointless, if you really want to do nothing the RETURN or EXIT would be better.

Developer can make the mistake of linking two or more WHENs together (as shown in the picture). This is not valid syntax as developer must use OR to link whens.

**Comment by larshp** [comment]
yea, I agree, add to https://rules.abaplint.org/empty_structure/
