### ISSUE TITLE
QuickFix Loop when using all rules

### ISSUE THREAD

**Issue by marianfoo** [abaplint/abaplint#2437]
Hi Heliconia Labs Team,

![image](https://user-images.githubusercontent.com/13335743/156139141-6e71eaed-2cd6-4628-838e-8622b6728443.png)
Running in PR https://github.com/marianfoo/ztoad/pull/1

If have following line:
`DATA:ls_visibility LIKE LINE OF lt_visibility.`
https://github.com/marianfoo/ztoad/blob/e9b5d96c9b0fea3708c694e88467b4776431bcdd/src/ztoad.prog.abap#L2930

There are two problems:

- Missing space after the colonabaplint[colon_missing_space](https://rules.abaplint.org/colon_missing_space/)
- Remove double spaceabaplint[double_space](https://rules.abaplint.org/double_space/)

When i fix one, the other problem is display.
![QuickFixLoop](https://user-images.githubusercontent.com/13335743/156139261-470665e5-7fb5-4fa9-ba04-5fc25caacc5c.gif)

Is that the way it's intended?

**Comment by larshp** [comment]
try in the playground, are you leaving it enough time to update/recalculate?

![works](https://user-images.githubusercontent.com/5888506/156141976-08488159-2a06-490d-ba9a-3a76d55a3c58.gif)

**Comment by larshp** [comment]
Fix the syntax errors in your example first,
https://github.com/marianfoo/ztoad/blob/e9b5d96c9b0fea3708c694e88467b4776431bcdd/src/ztoad.prog.abap#L2928-L2929

if there are syntax errors dont expect anything to work

**Comment by marianfoo** [comment]
oh, sorry, i used the quick fixes blindly and they wrote it like that
it was like this before
https://github.com/marianfoo/ztoad/blob/cc2ff8cf2e48e0a50b53b754d3dc83019e6f5649/src/ztoad.prog.abap#L3145
need to do quick fixes on by one

**Comment by marianfoo** [comment]
is this a issue, abaplint rewrote this with invalid syntax?
https://github.com/marianfoo/ztoad/pull/1/files#diff-2b7365fa0411c16897cf90290a1cfcd6f42a3dbd99b028e7d09a4924691a728fL3145
![image](https://user-images.githubusercontent.com/13335743/156145116-3cb293cc-7091-4e9e-9b30-1f1b2fefa95c.png)

**Comment by larshp** [comment]
this single suggestion looks okay

need an isolated example
