### ISSUE TITLE
Statement does not exist in ABAPv756(or a parser error), "DATA" parser_error

### ISSUE THREAD

**Issue by marianfoo** [abaplint/abaplint#2438]
Hi Heliconia Labs Team,

i get the error `DATA` is not in 7.56.
https://github.com/marianfoo/ztoad/blob/e9b5d96c9b0fea3708c694e88467b4776431bcdd/src/ztoad.prog.abap#L2928

![image](https://user-images.githubusercontent.com/13335743/156141036-ffeab2f8-4899-4041-a539-9afcf96edd40.png)

**Comment by larshp** [comment]
correct finding, this is a syntax error, comma without preceding colon,

```abap
  DATA lt_visibility TYPE vrm_values,

  DATA:ls_visibility LIKE LINE OF lt_visibility.
```

**Comment by marianfoo** [comment]
sorry, same as #2437
