### ISSUE TITLE
Expected CONSTANTEND (structure) - Include in constant (TYPE-POOL)

### ISSUE THREAD

**Issue by markstuppacher** [abaplint/abaplint#2446]
![image](https://user-images.githubusercontent.com/14176548/157001364-01d5d909-9c5e-47be-86b3-c1225239fc03.png)
![image](https://user-images.githubusercontent.com/14176548/157001429-49cf9041-65a8-4aae-b6f5-709623294251.png)
![image](https://user-images.githubusercontent.com/14176548/157001532-571e38cd-4b80-4d8f-97a0-4233639fe1d6.png)

See public repo https://github.com/markstuppacher/abaplint_bug_2022-03-07

**Comment by larshp** [comment]
thanks, https://syntax.abaplint.org/?filter=constant#/abap/structure/Constants to be updated

**Comment by larshp** [comment]
@markstuppacher try again, 2.85.40

**Comment by markstuppacher** [comment]
@larshp Expected CONSTANTEND fixed. Thanks!
Still getting INCLUDE not used anywhere.
![image](https://user-images.githubusercontent.com/14176548/157096005-80cb0ddb-4e8c-4c78-8029-102154c6c685.png)

**Comment by markstuppacher** [comment]
Getting INCLUDE not used anywhere only with type-pool.
No issues when used in report. See branch https://github.com/markstuppacher/abaplint_bug_2022-03-07/tree/constant-include-in-report

**Comment by larshp** [comment]
heh, always another bug :) I've not tested very much with type pools

(btw, dont create type pools 😄 )

**Comment by larshp** [comment]
@markstuppacher try again, 2.85.41

**Comment by markstuppacher** [comment]
everything working now! thanks!

> (btw, dont create type pools 😄 )
standard code from dependencies 😃
