### ISSUE TITLE
Downport: FOR loop variable not assigned in REDUCE

### ISSUE THREAD

**Issue by pokrakam** [abaplint/abaplint#2477]
In a FOR inside a REDUCE (maybe other scenarios too) the initial value is not assigned. 

Example at https://github.com/pokrakam/exercism-test/blob/7d3e8dfd3ac85ffadfdd14c092125c0afbebd0da/src/zcl_minesweeper.clas.abap#L67
Passes unit tests on SAP, but raises `cx_sy_itab_line_not_found` in exercism-test

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/25539927/161078931-a73c8326-5769-455d-8caf-0f4144322cb4.png">

And BTW: why does linter complain about a Yoda condition?

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/pull/2475/commits/c50bc42fa2f4535ec0f2d33d5b048c07c63e23a6 might fix it, part of https://github.com/abaplint/abaplint/pull/2475

**Comment by larshp** [comment]
@pokrakam try again, locally, the exercism runner is not updated yet

**Comment by pokrakam** [comment]
2.86.3 still has same issue. `i` is unassigned, therefore zero, therefore exception. The original code's `nmax` ensures it starts with minimum `i = 1`
Clone my fork, minesweeper branch if you need to debug. It hits a problem with unit test 3 `no_mines`

**Comment by larshp** [comment]
@pokrakam try again

**Comment by pokrakam** [comment]
Yay! Works, thanks :)
