### ISSUE TITLE
Table expression with specified secondary key is not downported

### ISSUE THREAD

**Issue by s7oev** [abaplint/abaplint#2481]
Reduced example using Atbash Cipher exercise in [exercism/abap](https://github.com/exercism/abap):

```abap
class zcl_atbash_cipher definition public.
  public section.
    methods:
      decode
        importing cipher_text       type string
        returning value(plain_text) type string,

      encode
        importing plain_text         type string
        returning value(cipher_text) type string.
endclass.


class zcl_atbash_cipher implementation.
  method decode.
    types:
      begin of cipher_dict_struct,
        plain  type c length 1,
        cipher type c length 1,
      end of cipher_dict_struct.

    data:
      cipher_dict type hashed table of cipher_dict_struct
        with unique key plain
        with unique hashed key cipher_key components cipher.

    data(foo) = cipher_dict[ key cipher_key cipher = '' ]-plain.
  endmethod.


  method encode.
  endmethod.
endclass.
```

output:
```
./zcl_atbash_cipher.clas.abap[29, 5] - Statement does not exist in ABAPopen-abap(or a parser error), "READ" (parser_error) [E]
abaplint: 1 issue(s) found
```

**Comment by larshp** [comment]
@s7oev try again, 2.86.8 published

exercsim runner not updated yet

**Comment by s7oev** [comment]
I've pasted the code in the playground with the config from [exercism/abap/abaplint_exercises.json](https://github.com/exercism/abap/blob/main/abaplint_exercises.json), and applied all fixes (which were unrelated: use uppercase, change name of class from `zcl...` to `lcl...`, remove `public` from class definition), after which there were no extra errors reported, so I think it's all good 👍 


![image](https://user-images.githubusercontent.com/47610738/162007781-5d4f1592-bd6e-4a1f-a313-03ec1536f8c9.png)
