### ISSUE TITLE
double_space - false positive for EVENTS

### ISSUE THREAD

**Issue by jan-jezek** [abaplint/abaplint#2484]
![image](https://user-images.githubusercontent.com/17530797/161578555-82e1e237-15d7-40de-afe8-d72470071fcd.png)
This gives error for foo - remove double_space.
It should not be reported here as pretty print on latest abap version does this automatically.

**Comment by larshp** [comment]
@jan-jezek try again, latest version

**Comment by larshp** [comment]
closing
