### ISSUE TITLE
Job artifacts - distinguish warnings from errors

### ISSUE THREAD

**Issue by Zeatynis** [abaplint/abaplint#2497]
Is there a way to distinguish warnings from errors for abaplint output in junit format? Or is this issue only Gitlab related?

![obraz](https://user-images.githubusercontent.com/9119187/162801736-acc8e377-9b31-4fb6-a405-9ac03d0b3eaa.png)
![obraz](https://user-images.githubusercontent.com/9119187/162802030-b3566978-6aa5-49ef-92a4-353d1e768814.png)

**Comment by larshp** [comment]
1: how can the issue be reproduced?
2: are you using the latest version?
3: consider adding your name and affiliation in your github profile

**Comment by Zeatynis** [comment]
Sorry for a late response...

1. Just configure abaplint.json with mixed severity of rules (few rules as warnings, else as errors). I configured my abaplint.json with severity of most rules as error and for abapdoc I used warning. Then I run pipeline on gitlab for some objects. The screenshot is a result of abaplint check.
I did a repo with an example https://github.com/Zeatynis/abaplint-issue. As you can see the rule abapdoc has a severity as Warning and it is displayed in results as red one (don't know if github has warnings support there).
https://github.com/Zeatynis/abaplint-issue/runs/6537222950?check_suite_focus=true
2. Yes, I use always the latest version. 
3. I did.

**Comment by larshp** [comment]
@Zeatynis close?

**Comment by Zeatynis** [comment]
Yes.
Little explanation for future readers: I decided to change warnings to errors in my abaplint config. Warning gives a false feeling that one can ignore the check result.
