### ISSUE TITLE
false positive in unused variable

### ISSUE THREAD

**Issue by eduardohfnascimento** [abaplint/abaplint#2504]
I'm receving a false positive for a variable that I'm using in a DELETE. I tried to call it with and whitout @, also tried to make an attribuition to an auxiliar variable.

The only way that I solve it was using skipNames parameter. Is this normal with delete macro on ABAP?

**Comment by larshp** [comment]
thanks, how can the issue be reproduced, what is the exact statement?

**Comment by larshp** [comment]
these two examples does not reproduce the error,

![image](https://user-images.githubusercontent.com/5888506/163923677-459b3651-7140-4c7a-9161-0fd54e3cb217.png)

**Comment by larshp** [comment]
@eduardohfnascimento
