### ISSUE TITLE
change to jest?

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#251]
can run tests in parallel? 

https://jestjs.io/

also has built in coverage and watch features

**Comment by larshp** [comment]
seems that mocha is actually faster right now, closing

**Comment by larshp** [comment]
still slower, am I doing something wrong?

https://medium.com/dailyjs/javascript-test-runners-benchmark-3a78d4117b4

**Comment by sbcgua** [comment]
Hi Lars, why do you want to switch ? do abaplint tests take so long ?
I'm using jest for some of my own projects - it is very convenient. One package and you have runner, mocks, assets and async tests. And coverage. All in one (although inside there are a lot of packages. 
But ... most probably abaplint tests will require some adjustments to run on jest. And also having that it is type script ... it may have complications. Not sure, don't use typescript except minor tweaks for AL :)

**Comment by larshp** [comment]
just want something that runs faster

but looking at above links jest might be slower

**Comment by larshp** [comment]
looks like mocha 8 supports parallel execution, https://developer.ibm.com/articles/parallel-tests-mocha-v8/

**Comment by larshp** [comment]
adding a `npm run test:parallel`

**Comment by larshp** [comment]
nah
