### ISSUE TITLE
Rule <double_space>

### ISSUE THREAD

**Issue by albertmink** [abaplint/abaplint#2512]
Spaces after `=` are not taken into account, see
https://github.com/SAP/abap-file-formats-tools/pull/77#discussion_r855242265

**Comment by larshp** [comment]
works as expected

the file was excluded, removing exclusion in https://github.com/SAP/abap-file-formats-tools/pull/80

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/164645109-aa6e0079-7088-441c-beda-1666af3cc26f.png)

**Comment by albertmink** [comment]
That is good news. I will close the issue
