### ISSUE TITLE
Avoid_use - missing config option for test-seam

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#2524]
Here, the wrong thing is checked:
https://github.com/abaplint/abaplint/blob/787db3f82600707d11eceadad6e8e2b54ce283d3/packages/core/src/rules/avoid_use.ts#L80

**Comment by larshp** [comment]
too much copy pasta 🍝

**Comment by larshp** [comment]
@FreHu try again, 2.89.15

**Comment by larshp** [comment]
closing
