### ISSUE TITLE
new rule `no_external_form_calls`

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#2525]
issue errors for

like "PERFORM foo IN PROGRAM bar."

and "PERFORM foo(bar)."

no matter what the value of "bar" is

**Comment by ed-holland** [comment]
Optional exception handling would be helpfull as certification allows own written code to be call remotely.

**Comment by larshp** [comment]
@ed-holland try again, 2.90.0

**Comment by ed-holland** [comment]
Works great. 

Both cases of external perform are detected. No issues found

Thx

**Comment by larshp** [comment]
I did not add the exception handling part, can add it later if needed
