### ISSUE TITLE
7.02 select in list of values does not check for blanks in list. 

### ISSUE THREAD

**Issue by DennisLybecker-INVIXO** [abaplint/abaplint#2530]
If there are leading ending blanks in the IN list this is not identified by 7.02 linter check. But is error in 7.31.

```abap
DATA: lt_but000 TYPE STANDARD TABLE OF but000 WITH DEFAULT KEY.

SELECT * INTO TABLE lt_but000
  FROM but000
  WHERE  but000~partner IN ( '1000' , '2000' , '3000' ).
```

7.02 require 
```abap
DATA: lt_but000 TYPE STANDARD TABLE OF but000 WITH DEFAULT KEY.

SELECT * INTO TABLE lt_but000
  FROM but000
  WHERE  but000~partner IN ('1000' , '2000' , '3000').
```

**Comment by larshp** [comment]
thanks

I wonder which version starts allowing the spaces, I cannot find anything in the ABAP release specific changes

**Comment by larshp** [comment]
@DennisLybecker-INVIXO try again, 2.90.1

**Comment by DennisLybecker-INVIXO** [comment]
> @DennisLybecker-INVIXO try again, 2.90.1

Yes, works. Thanks.
