### ISSUE TITLE
insert |string| into ... syntax does not raise for 702 version (but should)

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint#2531]
https://github.com/sbcgua/ajson/pull/100#discussion_r866059192

`insert |string| into ...` is 740 syntax, yet [ajson abalint config](https://github.com/sbcgua/ajson/blob/master/abaplint.json) suggest 702

**Comment by larshp** [comment]
@sbcgua try again, 2.90.1

**Comment by sbcgua** [comment]
Cannot repeat the original case, but the reconstruction works. Thanks ! :+1:

![image](https://user-images.githubusercontent.com/15635498/167263454-64eef824-bbff-43e3-99e9-ff6448741d48.png)
