### ISSUE TITLE
abaplint scrip return status

### ISSUE THREAD

**Issue by hillbun** [abaplint/abaplint#2538]
It always return status of 1
```

./src/zcx_test_exception.clas.abap[13, 39]                    - Remove space before "," or "." (space_before_dot) [E]
./src/zcx_test_exception.clas.xml[1, 1]                       - Remove description for CONSTRUCTOR (remove_descriptions) [E]
./src/zspara_control.tabl.xml[1, 1]                           - TABL enhancement category not classified in ZSPARA_CONTROL (tabl_enhancement_category) [E]
./src/zspara_data_tab_s.tabl.xml[1, 1]                        - TABL enhancement category not classified in ZSPARA_DATA_TAB_S (tabl_enhancement_category) [E]
./src/zspara_data.tabl.xml[1, 1]                              - TABL enhancement category not classified in ZSPARA_DATA (tabl_enhancement_category) [E]
./src/zspara_return.tabl.xml[1, 1]                            - TABL enhancement category not classified in ZSPARA_RETURN (tabl_enhancement_category) [E]
./src/ztabline.tabl.xml[1, 1]                                 - TABL enhancement category not classified in ZTABLINE (tabl_enhancement_category) [E]
./src/ztpara_log.tabl.xml[1, 1]                               - TABL enhancement category not classified in ZTPARA_LOG (tabl_enhancement_category) [E]
abaplint: 875 issue(s) found, 55 file(s) analyzed
/builds/isit_projects/abap/official/zabap # echo $?
1

```

How to return 0?

**Comment by hillbun** [comment]
abaplint scrip always return 1 when I run pipeline do not pass

**Comment by larshp** [comment]
when there are zero issues found it will return `0`

fix the issues by fixing the code, or adjust the configuration to be less strict

**Comment by hillbun** [comment]
Is it possible to config the numbers of issues to make it return 0?

**Comment by larshp** [comment]
below configuration will disable all rules, with all rules disables it returns zero

```
{
  "global": {
    "files": "/src/**/*.*",
    "exclude": [],
    "noIssues": [],
    "skipGeneratedGatewayClasses": true,
    "skipGeneratedPersistentClasses": true,
    "skipGeneratedFunctionGroups": true,
    "useApackDependencies": false,
    "skipIncludesWithoutMain": false
  },
  "dependencies": [
    {
      "url": "https://github.com/abaplint/deps",
      "folder": "/deps",
      "files": "/src/**/*.*"
    }
  ],
  "syntax": {
    "version": "v756",
    "errorNamespace": "^(Z|Y|LCL_|TY_|LIF_)",
    "globalConstants": [],
    "globalMacros": []
  },
  "rules": {
  }
}
```

**Comment by hillbun** [comment]
I mean config the number of issues to 20, if result is below 20, it return 0?

**Comment by larshp** [comment]
Nothing currently built in to change the status based on the number of findings

IMHO it goes against the ideas of CI
https://www.petrikainulainen.net/programming/unit-testing/why-you-should-keep-your-build-green/
you want to keep the build clean/green, so that each developer knows which issues to fix and the issues were caused only by the changes that developer did

**Comment by hillbun** [comment]
Yes, I agree with this.

But as sonarqube, it can show new codes and whole codes scan status, and setup gates to adjust.

is it possible to integrate into sonarqube?

**Comment by larshp** [comment]
thats a different topic

and again, if some errors are hidden, how can the developer determine which are issues and which are not? Plus it will never get you to a good state.

I recommend actively working with your full codebase, moving the full codebase forward. There are multiple ways to approach this.

Sonarcube is a commerical offering, for abaplint there is https://github.com/marketplace/abaplint

**Comment by fuzolan** [comment]
It should give exit 1 when there is an error. It makes no sense for type information or warning.
