### ISSUE TITLE
Dependencies - unknown_types

### ISSUE THREAD

**Issue by Zeatynis** [abaplint/abaplint#2546]
Hi. Either I don't understand how dependecies work or there is an issue. I bet on the first one 😝 
I ran SAPRSEUB and SAPRSEUC reports in the background and when they completed I ran ZABAPLINT_DEPENDENCIES providing a seperate repository.
Then I added to my abaplint.json these lines:
```
"dependencies": [
        {
            "files": "/src/**/*.*",
            "folder": "/lint_deps",
            "url": "https://github.com/abaplint/deps"
        },
        {
            "files": "/src/**/*.*",
            "folder": "/lint_deps2",
            "url": "https://git.hicron.com/abap/ksef/ksef-deps"
        }
    ],
```
I don't understand the folder meaning. I modeled it after configs in some issues and the one in abapgit repo.

Here is my problem. When I run pipeline it checks my primary repository AND dependencies repo. Why?
If it is correct behaviour then why ZABAPLINT_DEPENDENCIES didn't also extracted /HCR/TRE_RESTCLS if it is used by /hcr/cl_rest_base?

![obraz](https://user-images.githubusercontent.com/9119187/169652676-f270bb70-6f0f-4e3b-9263-e3b7605f13e8.png)

**Comment by larshp** [comment]
folder: if folder is specified, the code will look for the folder locally, if it does not exist, it clones the url

this is very useful for testing locally, or if some dependencies are only local to the repository

the combinations are:
* only folder
* only url
* folder and url

**Comment by Zeatynis** [comment]
Ok, thank you for folder meaning explanation. What about the second part? Is this an expected behaviour? Dependencies should also be checked by abaplint?

**Comment by larshp** [comment]
closing
