### ISSUE TITLE
Allow loading dependencies from folders that don't contain configuration file

### ISSUE THREAD

**Issue by elijah-ezaga** [abaplint/abaplint#2547]
Currently at

https://github.com/abaplint/abaplint/blob/main/packages/cli/src/index.ts#L105, 

ABAP dependencies to be loaded are expected to reside relative to the _base_ folder, which in turn is expected to be where the configuration file resides according to 

https://github.com/abaplint/abaplint/blob/main/packages/cli/src/index.ts#L81.

**Comment by larshp** [comment]
yes, can you elaborate on if/how this is an issue? in which case would something reside outside?

I would like it to not be able to read outside of the base folder, due to security

you can always git clone, or .gitignore something, add a local symlink

**Comment by elijah-ezaga** [comment]
We use ABAPLint in a scenario where we analyze thousands (even more) of commits that can contain many ABAP files. By having to git clone for every commit will affect performance. Also places requirement of the need for internet access which is sometimes not available for our software. To circumvent the internet requirement, we currently have the dependencies repository cloned at first but now need to copy it during analysis of each commit into the base folder, something which still affects performance. The size of the dependencies repo is small ATM but it may grow in the future.

I can understand the need for security as you explained. I think users of ABAPlint will each need to keep this in mind nevertheless.

**Comment by larshp** [comment]
@elijah-ezaga what is your affiliation? are you building this for open source?

**Comment by elijah-ezaga** [comment]
We found a workaround for and thus I shall be closing this issue.
