### ISSUE TITLE
Add renaming packages to the rename functionality

### ISSUE THREAD

**Issue by steve192** [abaplint/abaplint#2549]
My target is to rename / migrate Z objects to a custom namespace /XXX/. 
This works fine for classes, interfaces etc. 
Unfortunately SAP requires objects with a namespace to be in packages with the same namespace. This requires renaming the packages in the same step.

Am I correct for the steps that need to be done?
- Add new renaming type in src/objects/rename (and add to renamer.ts)
- Packages are defined by the folder names the files are in (FULL_PACKAGE and PREFIX package logic must be handled differently, don't know how yet)
- Move objects to new package (is this even needed or is a RenameFile operation of vscode-languageserver-types on the package's directory sufficient?)
    - Find all files contained in this package and subpackage (loop through all objects of the IRegistry and get their files)
    - Move these files to a new directory using RenameFile opreation of vscode-languageserver-types
- No XMLs or references must be updated

**Comment by steve192** [comment]
Hmm it may be easier for me to just rename the packages by hand by renaming the directories.

**Comment by larshp** [comment]
yea, depends on how many packages  you have 😅
