### ISSUE TITLE
Expected endmethod (structure)

### ISSUE THREAD

**Issue by Zeatynis** [abaplint/abaplint#2550]
This error is displayed when you do a loop with using assigning field-symbol.
![obraz](https://user-images.githubusercontent.com/9119187/170143169-d63349e7-4c5d-4887-8582-9857e7423c52.png)

**Comment by larshp** [comment]
what language version is configured? inline loops works from v740sp02

 can you help pasting the text/raw code here?

**Comment by Zeatynis** [comment]
I missed very important detail: It's a screenshot from a transpiler app 😄

**Comment by larshp** [comment]
the transpiler only works with 702 syntax, use https://rules.abaplint.org/downport/ to downport first

**Comment by Zeatynis** [comment]
Downport doesn't seem to make sense here. Issue started with Abaplint reporting the same error _Expected endmethod (structure)_. Transpiler helped to aim the line with the real issue. The initial class that had this error had 1500 lines of code XD
So if you say that transpiler only works for 702 and I set abaplint to check syntax for 702 then how newer syntax keywords are caught and reported?

**Comment by larshp** [comment]
downport it before passing it to the transpiler, keep developing your code in the high syntax, 702 downport is just an intermediate step to transpiling,

![downport](https://user-images.githubusercontent.com/5888506/170205474-fefc80ec-7501-4bae-a881-0ccbf55a0461.gif)

**Comment by Zeatynis** [comment]
I rather would like to develop in 702 and have abaplint check if I didn't do any mistakes. I don't like the auto downport.

**Comment by Zeatynis** [comment]
btw. what do you use to make such recordings?

**Comment by larshp** [comment]
set the syntax version in `abaplint.json` to what your target version, eg. 702

I typically use https://www.screentogif.com to do gifs

**Comment by Zeatynis** [comment]
> set the syntax version in `abaplint.json` to what your target version, eg. 702
Yes. I did that. That's why I have this issue :D I get "_Expected endmethod (structure)_" instead of something like "Inline declaration of field-symbols is not supported in 702"

**Comment by larshp** [comment]
yea, need some better error messages -> there is https://github.com/abaplint/abaplint/issues/2267 already open for similar problem

**Comment by larshp** [comment]
closing -> #2267
