### ISSUE TITLE
check_syntax: constant not found, findtop / Pragma not allowed without pragma defined

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#2554]
With the new lint version, the below errors show up.

```
node version:     v16.15.0
abaplint version: 2.90.7

./src/nw/#jcs#bc.fugr.#jcs#lbcf91.abap[141, 5] - "c_char_unknown" not found, findTop (check_syntax) [E]
./src/nw/#jcs#bc.fugr.#jcs#lbcf91.abap[146, 5] - "c_char_unknown" not found, findTop (check_syntax) [E]
./src/nw/#jcs#bc.fugr.#jcs#lbcf91.abap[182, 9] - Pragmas not allowed in v700 (parser_error) [E]
./src/nw/#jcs#bc.fugr.#jcs#lbcf91.abap[[28](https://vdocker.sap.internal:8929/abap/abap-fca/-/jobs/103585#L28)7, 5] - "c_char_unknown" not found, findTop (check_syntax) [E]
./src/nw/#jcs#bc.fugr.#jcs#lbcf91.abap[288, 3] - "c_char_space" not found, findTop (check_syntax) [E]
```

The constants not found are part of a SAP original include referenced in the FUGR top include
![image](https://user-images.githubusercontent.com/53995991/170652858-b9073a3c-b84a-4324-b939-cd38cbebc1fc.png)

**Comment by larshp** [comment]
is `LBTCHDEF` in your repository/deps, without syntax errors?

**Comment by ed-holland** [comment]
yes, it is in deps. I've ran SCI_DEPS and it did not find any issues.
We use the same include also in some abaps and there it also has no issue.

**Comment by ed-holland** [comment]
Issue does not exist anymore. Closing
