### ISSUE TITLE
false "EXIT is not allowed outside of loops" - loop at screen in initialization

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint#2559]
![image](https://user-images.githubusercontent.com/15635498/171596994-c8ad9a6e-ef99-476a-bb87-531035925c25.png)

```abap
initialization.

  loop at screen.
    if screen-name = 'P_USNAM'.
      p_usnam = sy-uname.
      screen-input = '0'.
      modify screen.
      exit.
    endif.
  endloop.
```

```
$abaplint -v
2.90.9
```

**Comment by larshp** [comment]
@sbcgua try again, 2.90.10

**Comment by sbcgua** [comment]
Nice, works as desired, thanks ! :+1:
![image](https://user-images.githubusercontent.com/15635498/171872588-c288ca63-3296-4c20-b901-d225ea26e86c.png)
