### ISSUE TITLE
FORM ... DEFINITION and FORM ... IMPLEMENTATION

### ISSUE THREAD

**Issue by fabianlupa** [abaplint/abaplint#2561]
... lead to a parser error.

![image](https://user-images.githubusercontent.com/5270359/171908014-4d920a6a-a7a1-4545-a83a-faa82d5db9cc.png)

https://help.sap.com/doc/abapdocu_756_index_htm/7.56/en-US/index.htm?file=abapform_definition.htm

Seems like this form of the form syntax is even more obsolete, not sure why it exists. Possibly for some generated code somewhere where  definition and implementation are required to be split. I had a look at the internal function module syntax you can jump to in SE37 but that's not it.

**Comment by flaiker** [comment]
I haven't either, the ADT autocomplete sometimes yields unexpected results ;)

So not even sure if you should support it but I thought you might be interested in knowing about this anyway.

**Comment by larshp** [comment]
well, I'll add anything that is part of the language

but probably something to add to rule https://rules.abaplint.org/obsolete_statement/

**Comment by flaiker** [comment]
Just had a look if there's anything in the 7.54 Dev Edition.

`CL_ABAP_TEST_QUALIFY=>CLASS_CONSTRUCTOR` seems equally weirded out by this (the list goes on and is actually quite funny)
![image](https://user-images.githubusercontent.com/5270359/171914389-737fc661-11be-4666-99c2-1a02ee6ae601.png)

**Comment by larshp** [comment]
@fabianlupa try again, 2.93.8 published

**Comment by fabianlupa** [comment]
It works, thanks!
