### ISSUE TITLE
2.91.1 - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Zeatynis** [abaplint/abaplint#2568]
On all my repos today at version 2.91.1 the following error occurs. It's ok on 2.91.0.

`generic[1, 1] - RangeError: Maximum call stack size exceeded at DDIC.lookupTableOrView (webpack://@abaplint/cli/./node_modules/@abaplint/core/build/src/ddic.js?:219:13) (generic_error) [E]`

**Comment by larshp** [comment]
@Zeatynis try again, 2.91.2

**Comment by Zeatynis** [comment]
![obraz](https://user-images.githubusercontent.com/9119187/172181965-a4625805-b5e4-45fc-8647-56c0ce1aec16.png)
