### ISSUE TITLE
obsolete_statement: add select/insert/update... client specified

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2579]
Add 'client_specified' as option to https://rules.abaplint.org/obsolete_statement/

Ref:

https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abapselect_client_obsolete.htm

https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abapselect_client.htm

https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abapiumd_client.htm

**Comment by larshp** [comment]
any idea when "USING CLIENT" was added, does it exist in 702?

**Comment by mbtools** [comment]
see https://github.com/abaplint/abaplint/issues/2580

**Comment by larshp** [comment]
@mbtools try again, 2.91.5

**Comment by mbtools** [comment]
👍
