### ISSUE TITLE
Update syntax for `using client`

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2580]
Update syntax for `using client` since https://syntax.abaplint.org/?filter=client#/abap/expression/SQLClient is currently used only for `delete` and `update`.

However, it's also relevant for `select`, `insert`, and `modify`. 

In addition to `USING CLIENT clnt`, there are a few more options:

```abap
 | { USING { CLIENT clnt }
          | { CLIENTS IN @client_range_tab }
          | { CLIENTS IN T000 }
          | { ALL CLIENTS } } ...
```

Releases:

`USING CLIENT` as of [740sp5](https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abennews-740_sp05-abap_sql.htm#!ABAP_MODIFICATION_4@4@)

`USING CLIENTS IN` and `USING ALL CLIENTS` as of [754](https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abennews-754-abap_sql.htm#!ABAP_MODIFICATION_10@10@)

Ref:

https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abapselect_client.htm

https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abapiumd_client.htm

**Comment by larshp** [comment]
@mbtools try again, 2.91.5

**Comment by mbtools** [comment]
👍
