### ISSUE TITLE
Expected CLASSDEFINITION (structure) - RAP

### ISSUE THREAD

**Issue by BHeldens** [abaplint/abaplint#2596]
Dear,

During execution of abaplint we are presented with the following issue. We would like to mitigate it in order to prevent false positives.
![Screenshot 2022-07-15 155453](https://user-images.githubusercontent.com/97093535/179237550-0a973c60-c45a-4767-92e3-b2314fb4c81c.png)

This is standard generated syntax when we make use of RAP (abap RESTful programming model).
We are currently using abaplint v756 and the latest version of the abaplint npm module.
![image](https://user-images.githubusercontent.com/97093535/179237925-c9573fcd-0cba-4018-8948-2f16a488dbaf.png)

I have tested this in the playground version where I copied the abaplint config and the code. But it seems like I cannot reproduce it over there.
![image](https://user-images.githubusercontent.com/97093535/179239303-a804c7bc-0eee-4bb8-a716-18b829e512c7.png)

Could you validate if this is a false positive?
Thank you in advance!
KR

**Comment by larshp** [comment]
are you running the latest abaplint version?

**Comment by BHeldens** [comment]
Yes we do, this is a pipeline log:
![image](https://user-images.githubusercontent.com/97093535/179245312-81427630-fd99-4ddf-acfe-93646a832cb1.png)

**Comment by larshp** [comment]
This error message is sometimes misleading, try copying the full class source to the playground, and then remove code until the error disappears

**Comment by BHeldens** [comment]
I have played around with the code. The error changed once I changed the entity name at the end of line 3.
![image](https://user-images.githubusercontent.com/97093535/179248296-9c08658c-c3e4-4300-92a8-5be8d6b822ad.png)

I have also tried with below code and both the custom abaplint config and the default config from the playground.
![image](https://user-images.githubusercontent.com/97093535/179248768-5472b17f-1184-4d96-8e11-1789817f0a0b.png)

Thanks for the help so far! 😊

**Comment by larshp** [comment]
add the code inside the DEFINITION and IMPLEMENTATION to the playground, if there is something unrecognized inside, it might show this error message(which is misleading (https://github.com/abaplint/abaplint/issues/2267)

**Comment by BHeldens** [comment]
Thank you for your response!
The thing is, there is no code inside those classes. An RAP behavior implementation class has the practice of having no code in the "Global Class" section in the eclipse class view. The actual implementation is performed under the "Local Types" section.

Global Class tab:
![image](https://user-images.githubusercontent.com/97093535/179251440-3be366d9-252d-4486-a7c0-ff7ec383fb64.png)

Local Types tab:
![image](https://user-images.githubusercontent.com/97093535/179251784-039959d7-bfb7-41ac-9909-01e855a9dd9b.png)

In case you want more info about behavior implementation classes (bottom of page 270): https://help.sap.com/doc/3750bcdf7b8045e18f1b759e6d2b000b/Cloud/en-US/ABAP_RESTful_Programming_Model_EN.pdf

**Comment by larshp** [comment]
hmm, can you try making a dummy class and push it to github? then we can have a reproducibly example

**Comment by larshp** [comment]
reproduces error

"Statement does not exist in ABAPv756(or a parser error), "METHODS" (parser_error) [E]"

some syntax is missing in https://syntax.abaplint.org/?filter=method#/abap/statement/MethodDef

![image](https://user-images.githubusercontent.com/5888506/180011867-cb01fd31-f13a-4461-9379-ff20cbc35e77.png)

**Comment by larshp** [comment]
@BHeldens try again, 2.91.11 published

![image](https://user-images.githubusercontent.com/5888506/180135983-be2c2c5c-3e4c-46cd-99e8-f9158a25f6be.png)

**Comment by BHeldens** [comment]
Thanks for the update!
However I still cannot seem to reproduce the issue on the abaplint playground. I ran the pipeline again and checked for the ABAPLint version but I am still faced with the same issue that it expects CLASSDEFINITION for this class in the Global Class section.

Executing the pipeline without our custom ABAPLint configuration also triggers this issue

**Comment by larshp** [comment]
no progress, closing
