### ISSUE TITLE
Rename command doesn't rename

### ISSUE THREAD

**Issue by ConjuringCoffee** [abaplint/abaplint#2600]
When I execute `abaplint --rename`, nothing is renamed. Executing `abaplint -rename` prints a long list, but does nothing as well.

I'm running abaplint version 2.29.0.
I've set up a very minimal example project with class `zcl_bgi_abaplint` containing a single method. 
I then created the configuration file using `abaplint -d > abaplint.json` and added the renaming configuration parameters.

```
"rename": {
    "output": "renamed",
    "skip": [],
    "patterns": [
      {
        "type": "CLAS|INTF",
        "oldName": "z(.*)",
        "newName": "y$1"
      }
    ]
  }
```

When executing `abaplint --rename`, the following is printed to the terminal. 

```
Using config: /home/username/abaplint-test/test-abaplint-1/abaplint.json                                               
100% - 0.0s - Reading files - zcl_bgi_abaplint.clas.xml                                                                 
Clone: https://github.com/abaplint/deps                                                                                 
100% - 0.0s - Reading files - cl_workflow_general_task_def.clas.xml                                                     
100% - 0.7s - Lexing and parsing(v754) - CLAS CL_WORKFLOW_GENERAL_TASK_DEF                                              
100% - 0.0s - Finding Issues - CLAS CL_WORKFLOW_GENERAL_TASK_DEF                                                        
./src/zcl_bgi_abaplint.clas.abap[7, 13] - Missing ABAP Doc for method main (abapdoc)                                    
./src/zcl_bgi_abaplint.clas.abap[7, 5]  - Keyword should be upper case: "methods" (keyword_case)                        
abaplint: 2 issue(s) found, 3 file(s) analyzed 
```

I suspect this is a user error on my side. I hope you can help me out. Please let me know if you need additional information.

**Comment by ConjuringCoffee** [comment]
I've fixed the 2 issues that were found previously, but the behavior doesn't change.

```
Using config: /home/username/abaplint-test/test-abaplint-1/abaplint.json                                               
100% - 0.0s - Reading files - zcl_bgi_abaplint.clas.xml                                                                 
Clone: https://github.com/abaplint/deps                                                                                 
100% - 0.0s - Reading files - cl_workflow_general_task_def.clas.xml                                                     
100% - 0.7s - Lexing and parsing(v754) - CLAS CL_WORKFLOW_GENERAL_TASK_DEF                                              
100% - 0.0s - Finding Issues - CLAS CL_WORKFLOW_GENERAL_TASK_DEF                                                        
abaplint: 0 issue(s) found, 3 file(s) analyzed 
```

**Comment by larshp** [comment]
renaming CLAS objects was added in https://github.com/abaplint/abaplint/pull/1450, try updating to latest version instead of 2.29.0

**Comment by ConjuringCoffee** [comment]
The latest version available on npm is 2.29.0. How can I update to the latest version?

```
npm view abaplint version                                      
2.29.0  
```

**Comment by larshp** [comment]
```
npm uninstall abaplint -g
npm install @abaplint/cli -g
```

use https://www.npmjs.com/package/@abaplint/cli not https://www.npmjs.com/package/abaplint

note the message
![image](https://user-images.githubusercontent.com/5888506/180424919-f200b283-c206-4700-b96c-17e3ee034dd0.png)

**Comment by ConjuringCoffee** [comment]
Well, that explains it - thanks. This old package still has 430 downloads per week, so it looks like I'm not the only one. Maybe something for the README? Either way, issue is resolved.

**Comment by larshp** [comment]
yea, well, I would like to unpublish it alltogether, but I cannot do that as there is a dependency

I've pinged @pascalerni again

**Comment by larshp** [comment]
gone, https://www.npmjs.com/package/abaplint
