### ISSUE TITLE
IF contains( val = '/folder/' end = '/' ) syntax rejected in 7.02

### ISSUE THREAD

**Issue by sandraros** [abaplint/abaplint#2642]
I got [lint errors in abap2xlsx](https://github.com/abap2xlsx/demos/pull/16/commits/d0acd4cd9b314f62d4595f0acbab43592f10406d) on these 2 pieces of code concerning the function `contains`, one about `end`, one about `start`, I think they are both valid in 7.02 but I don't have 7.02 to verify:
- ![image](https://user-images.githubusercontent.com/34005250/184495523-e9f4e7fd-62f3-4cd7-b651-553486effd58.png)
- ![image](https://user-images.githubusercontent.com/34005250/184495477-6b4f2c6c-d6c3-45f2-ac6d-2f329c12d8ed.png)

Code to reproduce:
```
IF contains( val = '/folder/' end = '/' ).
ENDIF.
IF contains( val = '/folder/' start = '/' ).
ENDIF.
```

**Comment by larshp** [comment]
they are not valid 702 syntax, 702 accepts

`IF value1 COMARATOR value2`

not

`IF method( )`

workaround for you example is

```abap
IF boolc( contains( val = '/folder/' end = '/' ) ) = abap_true.
ENDIF.
```

**Comment by sandraros** [comment]
Are you sure? I don't have the ABAP 7.02 documentation but it used to work at least in [7.31](https://help.sap.com/doc/abapdocu_731_index_htm/7.31/en-US/index.htm?url=abencontains_functions.htm):
```abap
DATA html TYPE string.

html = '<body>Text</body>'.

IF contains_any_not_of( val = to_upper( html ) start = sy-abcde ) AND
   contains_any_not_of( val = to_upper( html ) end   = sy-abcde ).
  ...
ENDIF.
```

**Comment by larshp** [comment]
well, I dont have access to any 702, same as you

so we can keep guessing

**Comment by sandraros** [comment]
It was just in case, to discuss the point. I thought maybe it was due to the presence of `start` and `end`, and that `contains` was accepted as a predicate function with the classic `sub` word.

The predicate function `contains` seems to exist since 7.02 according to this [blog post in 2010 about 7.02](https://blogs.sap.com/2010/04/14/what-is-new-in-abap-language-abap-workbench-and-enhancement-framework-with-sap-netweaver-70-ehp2/):
> There are also new predicate functions for strings such as 
> ```
> contains, contains_any_of, contains_any_not_of
> ```

Anyway, I let you close the issue if you wish.
