### ISSUE TITLE
Change IF to CASE (change_if_to_case)

### ISSUE THREAD

**Issue by lucasborin** [abaplint/abaplint#2682]
Given this example:
![image](https://user-images.githubusercontent.com/5233413/190187873-0409d57e-17e3-4653-90a0-4b3dddba4893.png)

```abap
  IF raises_exception = abap_true.
    configuration->raise_exception( ).
  ELSEIF never_called = abap_true.
    configuration->ignore_all_parameters( )->and_expect( )->is_never_called( ).
  ELSE.
    configuration->and_expect( )->is_called_once( ).
  ENDIF.
```

It expects:
![image](https://user-images.githubusercontent.com/5233413/190187717-a6743af9-8ffc-43fc-b89a-a46dcddb2c61.png)

```abap
  CASE abap_true.
    WHEN raises_exception.
       configuration->raise_exception( ).
    WHEN never_called.
       configuration->ignore_all_parameters( )->and_expect( )->is_never_called( ).
    WHEN OTHERS.
       configuration->and_expect( )->is_called_once( ).
  ENDCASE.
```

If it is a boolean, it looks quite strange. Should we disable this check for boolean?

**Comment by larshp** [comment]
hmm, well, personally I think its easier to read in the CASE statement, but it does require some getting used to

we can add a list of regex `skipNames`

so you can add

`skipNames: ["abap_true", "abap_false"]`

if the team prefers not having these in the CASE part

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/pull/2683

**Comment by larshp** [comment]
@lucasborin try 2.93.16
