### ISSUE TITLE
Table type not seen as a table type

### ISSUE THREAD

**Issue by DennisLybecker-INVIXO** [abaplint/abaplint#2736]
As I cannot simply recreate this in the linter playground I will try to describe the issue.

This has been working until lately (a few weeks since last pull request). We are working with syntax version 7.02.

Data has been simplified and renamed for use in this issue.

Table definition in a class.
```abap
    TYPES:
      BEGIN OF ty_data_st,
        path         TYPE string,
        output_data  TYPE string,
      END OF ty_data_st .
    TYPES:
      ty_data_tt TYPE STANDARD TABLE OF ty_data_st WITH DEFAULT KEY .
```

Table type is used in a function module export parameter.
```abap
*"  EXPORTING
*"     REFERENCE(ET_DATA) TYPE
*"        ZCL_READ=>TY_DATA_TT
```

Function module code:

```abap
data: ls_data        LIKE LINE OF ZCL_READ=>TY_DATA_TT.

    ls_data-output_data = 'FOO'.
    APPEND ls_data TO et_data.
```

--------------------
Linter result:
![image](https://user-images.githubusercontent.com/46812361/196642977-362332ad-89a3-4755-9f89-c1524400a074.png)

Please reach out if additional information is needed.

**Comment by larshp** [comment]
@DennisLybecker-INVIXO try again, it might be solved with 2.93.48

**Comment by larshp** [comment]
@DennisLybecker-INVIXO did it work out?

**Comment by DennisLybecker-INVIXO** [comment]
> @DennisLybecker-INVIXO did it work out?

Yes, thanks.
