### ISSUE TITLE
rules json from url

### ISSUE THREAD

**Issue by OberstVonGatow** [abaplint/abaplint#2787]
Hi,

it would be awesome if we could use an https url as abaplint rules file.
For example
`abaplint -f https://raw.githubusercontent.com/abaplint/abaplint-sci-client/main/abaplint.json`

We now have 8 Repositories with abaplint (and more to come). If we change rules we want all Pipelines get the same rules.
Would be nice and easy with a https link/request.

**Comment by larshp** [comment]
hmm, well, you want/need to manage all changes through pull requests to stay in control

say one central place is changed, and it could potentially impact the status for `main` in 8 other repositories

suggest setting up a process where changes to a central configuration can be automatically incrementally adopted by each repository

**Comment by OberstVonGatow** [comment]
Don't know if that would be too complex. Just a single URL would be enough. I would want to affect every branch of the repos.

If I could set a rules url I could make a own repo for abaplint rules. With a main branch (link in every abap repo pipeline). If I would want to test a new ruleset I would make a new branch in my rules repo and get a new link because of the branch. Then I could update the rules pipeline in single ABAP branches as I like.

**Comment by OberstVonGatow** [comment]
Okay forget about it. Can't believe how stupid i was 🙈
I can already do my requirement just in my pipeline itself:

```
- wget -O globalrules.json https://raw.githubusercontent.com/abaplint/abaplint-sci-client/main/abaplint.json
- abaplint globalrules.json --outformat junit --outfile report.xml
```
