### ISSUE TITLE
Syntax check - Errors related to unknown typ group constants

### ISSUE THREAD

**Issue by dpuerner** [abaplint/abaplint#2810]
Hello.

I am using ABAPLINT via CI/CD job running on GitHub. After committing software changes to GitHub the ABAPLINT job will be executed automatically. I used ABAPLINT to make a syntax check on our namespace development (> 1.000 objects ; all kind of objects like classes, interface, DDIC, etc.).
Here you can find my abaplint config file (json). 
![abaplint_syntax_json](https://user-images.githubusercontent.com/83902129/208933332-e281f70c-88da-417e-8918-2cde1fce8605.png)

The namespace was already imported into customer SAP EWM systems w/o any issues. Here my abaplint check, using the config file above, will return > 1.000 errors. I just checked the first 100 and identified different issues, one of these issues is, that constants are unknown in the abaplint check which are related to a function group. Constants from the following type groups are not identified correctly (maybe more groups are affected in further errors):

1. SLIS
2. SEOX
3. ICON
4. SOI
5. WMEGC

1-4 are available in ERP systems as well. 5 is a EWM related type group. But normally this shouldn't be a reason for an error because according to my abaplint config file, only the following namespaces should be check only.

**"^(Z|Y|LCL_|TY_|LIF_|/MYCOMP/|/D4C/)"**

All of the type groups (constants in it) are not related to such a namespace.

Here you can find syntax error from abaplint for 2 examples.
![Syntax_error_SLIS_SEOX](https://user-images.githubusercontent.com/83902129/208935088-c448c706-96d9-41c6-a790-ce3cc3e8e2d6.jpg)

Is that an error which can be fixed?

Thanks in advance.

Best regards,
Dominik Pürner

P.S. Is it a realistic scenario to go out with no syntax error at the end of a syntax check on a complete namespace with several thousands of objects as result or is abaplint not intended for syntax checking on such a scale at the end?

**Comment by larshp** [comment]
easiest workaround is to add the type group constants as in https://github.com/abapGit/abapGit/blob/main/abaplint.json#L22

it will all work out, dont worry :) tho its a bit of work

**Comment by dpuerner** [comment]
First thank you for the very quick answer :-)
Is it may possible to work with wildcards in the constant list? Then I can easily add a entry like "SLIS*" and all constants from that type group are covered?!

**Comment by larshp** [comment]
no, its not possible to use regex values for `globalConstants`, they are added to the scope for variable resolution, ie. it needs full names

**Comment by larshp** [comment]
note that icons are defined in https://github.com/abaplint/deps/blob/main/src/icons/icon.type.abap

clarification about regex added in https://github.com/abaplint/abaplint/pull/2815/commits/9f21adb4b7e8e21f787905c7594c25f98d6222e5

**Comment by dpuerner** [comment]
Looks better now by adding the constants to the "globalConstants"-list. Thank you a lot!
