### ISSUE TITLE
Syntax check - Interface IF_IXML_NODE unknown

### ISSUE THREAD

**Issue by dpuerner** [abaplint/abaplint#2811]
Hello.

I am using ABAPLINT via CI/CD job running on GitHub. After committing software changes to GitHub the ABAPLINT job will be executed automatically. I used ABAPLINT to make a syntax check on our namespace development (> 1.000 objects ; all kind of objects like classes, interface, DDIC, etc.).
Here you can find my abaplint config file (json).
![abaplint_syntax_json](https://user-images.githubusercontent.com/83902129/208936196-18b213bd-f994-4b21-80ce-3a185d52ed73.png)

One of the syntax issues I am receiving is related to interface IF_IXML_NODE (method CREATE_ITERATOR) which seems to be unknown.
![image](https://user-images.githubusercontent.com/83902129/208936780-fc08a7bf-c1cd-4841-ba73-bf8e7e3afbb8.png)
![Syntax_error_IF_IXML_NODE_II](https://user-images.githubusercontent.com/83902129/208936971-a5b492cf-86c9-4fb5-ac55-934ada23c757.jpg)

Thanks.

Best regards,
Dominik Pürner

**Comment by larshp** [comment]
with the configuration it checks dependencies against abaplint/deps, so

add the method `create_iterator` to https://github.com/abaplint/deps/blob/main/src/ixml/if_ixml_node.intf.abap

**Comment by dpuerner** [comment]
Issue solved by adding the method (temporary to my fork - Will solve other issues and finally do pull-request to org. repository). Thanks a lot for your help :-)
