### ISSUE TITLE
Syntax check - Interface IF_EX_CTS_REQUEST_CHECK unknown

### ISSUE THREAD

**Issue by dpuerner** [abaplint/abaplint#2812]
Hello.

I am using ABAPLINT via CI/CD job running on GitHub. After committing software changes to GitHub the ABAPLINT job will be executed automatically. I used ABAPLINT to make a syntax check on our namespace development (> 1.000 objects ; all kind of objects like classes, interface, DDIC, etc.).
Here you can find my abaplint config file (json).
![abaplint_syntax_json](https://user-images.githubusercontent.com/83902129/208937495-adf3e835-fa0c-43e8-bad5-0a9205517711.png)

One of the syntax issues I am receiving is related to interface IF_EX_CTS_REQUEST_CHECK which seems to be unknown. I am receiving a lot of errors coming from an class which is implementing methods of that interface.
![Syntax_error_IF_EX_CTS_REQUEST_CHECK](https://user-images.githubusercontent.com/83902129/208939022-757fcabb-23d3-4a4e-b34c-d0e08bf203be.jpg)

This is an example of an interface parameter unknown.
![Syntax_error_IF_EX_CTS_REQUEST_CHECK_II](https://user-images.githubusercontent.com/83902129/208939191-70efb639-4e64-4775-9c0d-0fc811f2cac4.jpg)

Thanks.

Best regards,
Dominik Pürner

**Comment by larshp** [comment]
add missing definitions to https://github.com/abaplint/deps/blob/main/src/badi/if_ex_cts_request_check.intf.abap

**Comment by dpuerner** [comment]
Issue solved by adding missing definitions to interface  (temporary to my fork - Will solve other issues and finally do pull-request to org. repository). Thanks a lot for your help :-)
