### ISSUE TITLE
Syntax check - Structure which is part of the repository is unkown

### ISSUE THREAD

**Issue by dpuerner** [abaplint/abaplint#2813]
Hello.

I am using ABAPLINT via CI/CD job running on GitHub. After committing software changes to GitHub via ABAPGit the ABAPLINT job will be executed automatically. I used ABAPLINT to make a syntax check on our namespace development (> 1.000 objects ; all kind of objects like classes, interface, DDIC, etc.).
Here you can find my abaplint config file (json).
![abaplint_syntax_json](https://user-images.githubusercontent.com/83902129/208940853-26cfa2f8-cb4f-4eb6-a740-0bb11ccfec15.png)

One of the syntax issues I am receiving is related to structure /mycomp/ci_item which seems to be unknown. This structure is part of the repository and not part of an syntax issues himself (means /mycomp/ci_item is not part of the ABAPLINT syntax issue list)

![Syntax_error_MYCOMP_ci_item_II](https://user-images.githubusercontent.com/83902129/208943405-d613d318-afc7-48e0-a210-6c68c887d172.jpg)
![Syntax_error_MYCOMP_ci_item](https://user-images.githubusercontent.com/83902129/208941384-e656c601-6555-498c-b7a9-3bc4191ff73c.jpg)

Taking a look to the structure where you can see that include exists, which is may the problem ...
![Syntax_error_MYCOMP_ci_item_III](https://user-images.githubusercontent.com/83902129/208942085-8c246825-1429-46f3-97e7-625e5411f0e6.jpg)

... because within the ddic file for the structure the single include fields are missing.
![Syntax_error_MYCOMP_ci_item_V](https://user-images.githubusercontent.com/83902129/208942332-07bf4184-bb81-415c-9366-a4ce7284747c.jpg)

So may ABAPGit issue?

Thanks.

Best regards,
Dominik Pürner

**Comment by larshp** [comment]
I've reproduced the issue

**Comment by larshp** [comment]
-> https://github.com/abaplint/abaplint/pull/2815

**Comment by larshp** [comment]
@dpuerner try again, 2.94.7 published

**Comment by dpuerner** [comment]
Wonderful, issue is solved - Thanks a lot for your help!
