### ISSUE TITLE
Syntax check - Attribut KERNEL_ERRID of CX_ROOT unkown

### ISSUE THREAD

**Issue by dpuerner** [abaplint/abaplint#2814]
Hello.

I am using ABAPLINT via CI/CD job running on GitHub. After committing software changes to GitHub the ABAPLINT job will be executed automatically. I used ABAPLINT to make a syntax check on our namespace development (> 1.000 objects ; all kind of objects like classes, interface, DDIC, etc.).
Here you can find my abaplint config file (json).
![abaplint_syntax_json](https://user-images.githubusercontent.com/83902129/208944414-334307c7-656a-40f1-a240-00a78e18e195.png)

One of the syntax issues I am receiving is related to attribute KERNEL_ERRIR part of error class CX_ROOT. In our known SAP releases this attribute is part the error class.

![syntax_error_cx_root](https://user-images.githubusercontent.com/83902129/208944577-b93a61a0-da74-4b75-949d-d51496c43a50.jpg)
![syntax_error_cx_root_II](https://user-images.githubusercontent.com/83902129/208944591-0fb53f36-af37-442c-95d9-bc87f78a4a5f.jpg)
![syntax_error_cx_root_III](https://user-images.githubusercontent.com/83902129/208944600-a793189d-ee09-4f17-94a4-5b2fc07b01af.jpg)

Thanks.

Best regards,
Dominik Pürner

**Comment by larshp** [comment]
https://github.com/abaplint/deps/blob/main/src/exceptions/cx_root.clas.abap

**Comment by dpuerner** [comment]
Issue solved by adding the attribute (temporary to my fork - Will solve other issues and finally do pull-request to org. repository). Thanks a lot for your help :-)

**Comment by larshp** [comment]
with large new codebases, there are typically some false positives, feel free to open issues 😄
