### ISSUE TITLE
Syntax issue - Method importing parameter "IV_..." does not exist (check_syntax) [E]

### ISSUE THREAD

**Issue by dpuerner** [abaplint/abaplint#2826]
Hello,

I have a syntax issue which is not explainable and shouldn't be an issue in real.
![Syntax_error_import_parameter_1](https://user-images.githubusercontent.com/83902129/210570073-e352fea7-d51c-4e9f-a1a9-5f9fe8f42e2f.jpg)

Problem is, that IV_DOCID seems to be not existing.
![Syntax_error_import_parameter_2](https://user-images.githubusercontent.com/83902129/210570369-6fb00730-d5fb-4890-8563-61e7e719f2ee.jpg)

The attribute MO_SRV_DLV_INB himself is from type class /MYCOMP/CL_SRV_DLV_INB. This class himself does not include the method BO_UPDATE_BATCH because this method will be inherited from the super class which is /MYCOMP/CL_SRV_DLV_BASE. But also there the interface /MYCOMP/IF_SRV_DLV is used which includes the method interface.
![Syntax_error_import_parameter_3](https://user-images.githubusercontent.com/83902129/210571416-163110b6-9170-47a8-91d5-95f015a3c242.jpg)
![Syntax_error_import_parameter_4](https://user-images.githubusercontent.com/83902129/210571610-804e0d1a-3477-4a45-bfd7-f893c0354b96.jpg)

So for me everything looks fine and also within SAP system there is no syntax issue. I have a couple of such issues in the syntax check via abaplint (via gitlab). This is my JSON config file.

![abaplint_syntax_json](https://user-images.githubusercontent.com/83902129/210572165-a735cca5-91fb-46a1-8954-895e51ab12f8.png)

Thanks for checking.

Best regards,
Dominik

**Comment by dpuerner** [comment]
I reproduced this issue with the playground. Just add the namespace /MYCOMP/ to the error namespace and paste coding below.
![image](https://user-images.githubusercontent.com/83902129/211582546-a5b4ca48-23df-4eab-a668-061f2e3f6c06.png)

For me it seems, that abaplint will try to run BO_UPDATE_BATCH of class /MYCOMP/CL_SRV_BATCH in line 99 instead of calling method BO_UPDATE_BATCH of attribut MO_SRV_DLV_INBOUND (which is class /MYCOMP/CL_SRV_DLV_INB). So the expected result is, that BO_UPDATE_BATCH is not found because class /MYCOMP/CL_SRV_DLV_INB is unknown (not part of the playground).

To test my theory, try to comment line 101, 102 and 104 and then result set says, that IV_PRODUCTNO is expected and thats for me the indicator that abaplint is trying to run BO_UPDATE_BATCH of class /MYCOMP/CL_SRV_BATCH.

![image](https://user-images.githubusercontent.com/83902129/211582852-e5c31892-47c7-4c43-b7e4-cd7778eb1c4c.png)

Thanks a lot!

BR
Dominik

_REPORT zfoobar.

interface /MYCOMP/IF_SRV_BATCH
  public.

  methods BO_UPDATE_BATCH
    importing
      !IV_PRODUCTNO type /SCWM/DE_MATNR
      !IV_BATCHNO type /SCWM/DE_CHARG
      !IV_SLED type /SCWM/SLED optional
      !IV_REREAD_BATCH type XFELD default ABAP_FALSE
      !IV_RETRIES type I default '10'
      !IV_COMMIT type XFELD default ABAP_FALSE
      !IV_WAIT type XFELD default ABAP_FALSE
      !IV_ENTITLED type /SCWM/DE_ENTITLED optional
      !IT_VAL_NUM type TT_BAPI1003_ALLOC_VALUES_NUM optional
      !IT_VAL_CHAR type TT_BAPI1003_ALLOC_VALUES_CHAR optional
      !IT_VAL_CURR type TT_BAPI1003_ALLOC_VALUES_CURR optional
    exporting
      !EV_BATCHNO type /SCWM/DE_CHARG
      !EO_BATCH type ref to /SCWM/CL_BATCH_APPL
      !EV_NOT_EXISTS type XFELD
    raising
      /MYCOMP/CX_SRV_ROOT .
  
  methods BO_UPDATE_BATCH_ON_HU_ITEM
    importing
      !IV_BATCHID type /SCWM/DE_BATCHID optional
      !IV_BATCHNO type /SCWM/DE_CHARG optional
      !IV_PROCTY type /SCWM/DE_PROCTY
      !IV_REASON type /SCWM/DE_REASON optional
      !IV_GUID_PARENT_HU type /LIME/GUID_PARENT
      !IV_GUID_STOCK type /LIME/GUID_STOCK
      !IV_COMMIT type XFELD default ABAP_FALSE
      !IV_WAIT type XFELD default ABAP_FALSE
    exporting
      !ET_LTAP_VB type /SCWM/TT_LTAP_VB
      !ET_BAPIRET type BAPIRETTAB
    raising
      /MYCOMP/CX_SRV_ROOT .
  
  methods BO_UPDATE_BATCH_ON_DLV_ITEM
    importing
      !IV_DOCCAT type /SCDL/DL_DOCCAT
      !IV_DOCID type /SCDL/DL_DOCID
      !IV_ITEMID type /SCDL/DL_ITEMID
      !IV_BATCHNO type /SCWM/DE_CHARG
      !IV_COMMIT_WORK type XFELD default ABAP_FALSE
      !IV_WAIT type XFELD default ABAP_FALSE
    raising
      /MYCOMP/CX_SRV_ROOT .
 
endinterface.

class /MYCOMP/CL_SRV_BATCH definition
  public
  create protected

  global friends /MYCOMP/CL_SRV_FACTORY .

public section.

  interfaces /MYCOMP/IF_SRV_BATCH .

  aliases BO_UPDATE_BATCH
    for /MYCOMP/IF_SRV_BATCH~BO_UPDATE_BATCH .
  aliases BO_UPDATE_BATCH_ON_DLV_ITEM
    for /MYCOMP/IF_SRV_BATCH~BO_UPDATE_BATCH_ON_DLV_ITEM .
  aliases BO_UPDATE_BATCH_ON_HU_ITEM
    for /MYCOMP/IF_SRV_BATCH~BO_UPDATE_BATCH_ON_HU_ITEM .
  
  methods CONSTRUCTOR
    importing
      !IO_LOG type ref to /MYCOMP/CL_LOG optional
      !IV_LGNUM type /SCWM/LGNUM
      !IV_NO_LOG type XFELD default ABAP_FALSE
    raising
      /MYCOMP/CX_SRV_INPUT_INITIAL .

  PROTECTED SECTION.

  data MO_SRV_DLV_INB type ref to /MYCOMP/CL_SRV_DLV_INB .
  data MO_SRV_HU type ref to /MYCOMP/CL_SRV_HU .

  PRIVATE SECTION.

ENDCLASS.

CLASS /MYCOMP/CL_SRV_BATCH IMPLEMENTATION.

  METHOD constructor.
  ENDMETHOD.

  METHOD bo_update_batch.
  ENDMETHOD.

  METHOD bo_update_batch_on_dlv_item.

    CALL METHOD me->mo_srv_dlv_inb->bo_update_batch
      EXPORTING
        iv_docid       = iv_docid
        iv_itemid      = iv_itemid
        iv_batchno     = iv_batchno
        iv_commit_work = iv_commit_work
        iv_wait        = iv_wait.          

  ENDMETHOD.

  METHOD bo_update_batch_on_hu_item.

    CALL METHOD me->mo_srv_hu->bo_update_batch_on_hu_item(
      EXPORTING
        iv_batchid           = iv_batchid
        iv_batchno           = iv_batchno
        iv_procty            = iv_procty
        iv_reason            = iv_reason
        iv_guid_parent_hu    = iv_guid_parent_hu
        iv_guid_stock        = iv_guid_stock
        iv_commit            = iv_commit
        iv_wait              = iv_wait
      IMPORTING
        et_ltap_vb           = et_ltap_vb
        et_bapiret           = et_bapiret ).

  ENDMETHOD.

ENDCLASS._

**Comment by larshp** [comment]
so, something like the below reproduces the same issue?

```abap
INTERFACE if_srv.
  METHODS update_batch.
  METHODS update_line.
ENDINTERFACE.

CLASS cl_srv_batch DEFINITION.
  PUBLIC SECTION.
    INTERFACES if_srv.
    ALIASES update_batch FOR if_srv~update_batch.
    ALIASES update_line FOR if_srv~update_line.
  
  PROTECTED SECTION.
    DATA foobar TYPE REF TO voided.
ENDCLASS.

CLASS cl_srv_batch IMPLEMENTATION.
  METHOD update_batch.
  ENDMETHOD.

  METHOD update_line.
    CALL METHOD me->foobar->update_batch
      EXPORTING
        iv_docid = 2.
  ENDMETHOD.
ENDCLASS.
```

![image](https://user-images.githubusercontent.com/5888506/212546077-72690ce2-6076-4557-9bdb-5af550b9fd3d.png)

**Comment by dpuerner** [comment]
First thanks for analysing. Dont know what you mean?!

**Comment by dpuerner** [comment]
I doublecheck your example and yes same principle issue. Object _foobar_ is referenced to another class and abaplint seems to identify the method call (signature) in line 23 as the method which is in the interface _if_srv_, but that's not true. Because w/o assigning _iv_docid_ no syntax issue. On the other hand you can typ _foobar_ ref to any kind of z-class e.g. and there is no error shown, that class is unknown. This is the expected behavior, also in your example above.

**Comment by larshp** [comment]
if you change the code to use functional writing, I think it should work, as a workaround....  https://rules.abaplint.org/functional_writing/

**Comment by dpuerner** [comment]
You are right - It's working with the functional writing. Thank you 👍  Is it planned to provide a long term fix?

**Comment by larshp** [comment]
long term fix: yes, just takes time, and I need to concentrate for rewriting stuff 😅

**Comment by larshp** [comment]
@dpuerner try again, 2.94.25

**Comment by dpuerner** [comment]
Hello,
I have rechecked with old calling variant and with the newest abaplint version (2.9.53) and finally the issue is fixed. So thanks a lot for providing also a bugfix for that :-) It was a very short term long term fix ;-)
Best regards,
Dominik

**Comment by larshp** [comment]
yea, well, sometimes its difficult to get stuff working, ABAP is a messed up language
