### ISSUE TITLE
Syntax issue - Inline statements not possible

### ISSUE THREAD

**Issue by dpuerner** [abaplint/abaplint#2827]
Hello,

I am using abaplint via gitlab and found some syntax issue which are in real no syntax issues. Problem seems to be that inline coding is not identified correctly.
![Syntax_error_inline_coding_1](https://user-images.githubusercontent.com/83902129/210575262-ff3e8786-2a9d-45cb-87d8-8118624da7c8.jpg)

This is the coding
![Syntax_error_inline_coding_2](https://user-images.githubusercontent.com/83902129/210575320-5305053a-538d-45e9-9f4e-c2170d55373e.jpg)

Constant is available in the referenced class as public
![Syntax_error_inline_coding_3](https://user-images.githubusercontent.com/83902129/210575391-7b0fd18b-f163-429d-81d7-65ae2511e360.jpg)

The json config file looks like that (
![abaplint_syntax_json](https://user-images.githubusercontent.com/83902129/210575587-3d1f40fc-1bea-4b59-a405-c5f7410af368.png)

Also tried to change the syntax version to v756, same issue.

Thanks for checking.

Best regards,
Dominik

**Comment by larshp** [comment]
try reproducing this in the playground, https://playground.abaplint.org

might reproduce with just some local classes

**Comment by dpuerner** [comment]
Same issue via playground. In a common SAP system its running.
![Syntax_error_inline_coding_4](https://user-images.githubusercontent.com/83902129/210580236-c9f9727b-849e-4e00-badc-a22845fb743d.jpg)

**Comment by larshp** [comment]
can you help pasting the code here? then I dont need to type it again for a unit test case

**Comment by dpuerner** [comment]
REPORT zfoobar.

CLASS lcl_constant DEFINITION.
  PUBLIC SECTION.
    CONSTANTS c_header_length TYPE i VALUE 28.
ENDCLASS.

DATA:
  lv_telegram TYPE string VALUE 'ABCDEFGHIJ',
  lv_telegram2 TYPE string.

MOVE lv_telegram+0(lcl_constant=>c_header_length) TO lv_telegram2.

**Comment by larshp** [comment]
@dpuerner try again, 2.94.16 published

**Comment by larshp** [comment]
moving to #2830, the original issue for this issue is closed

please open one issue per issue, having multiple in one makes it difficult to get an overview
