### ISSUE TITLE
Syntax issue - Class ... not found

### ISSUE THREAD

**Issue by dpuerner** [abaplint/abaplint#2829]
Hello,

I have another sytax issue which is not an issue in SAP system.
![Syntax_error_class_not_found_1](https://user-images.githubusercontent.com/83902129/210597162-b61a696d-cbb2-433e-b6f7-7723ea64a61a.jpg)

This is the coding line.
![Syntax_error_class_not_found_2](https://user-images.githubusercontent.com/83902129/210597243-cc61d930-7750-4586-a8af-08b183db8c7b.jpg)

Class is existing in repository and method as well
![Syntax_error_class_not_found_3](https://user-images.githubusercontent.com/83902129/210597331-04482fa8-b867-4ebe-b941-dc265e0fd3c8.jpg)

There are no other issues in the abaplint check which are indicating an error within that class /.../cl_wplace.

Thanks a lot!

Best regards,
Dominik

**Comment by dpuerner** [comment]
I tried a couple of retests and now found the issue. Problem is, that abaplint does not show the problem in the resultset. Therefore I could find the problem only by adding logic within the methods step by step. The problem is this SELECT statement

    _SELECT 'X'
      FROM /mycomp/wplog
     WHERE lgnum      = @ms_wplace-lgnum
       AND wp_id      = @ms_wplace-wp_id
       AND uname      = @iv_uname
       AND logout_ts  = @space
      INTO @DATA(lv_exists).
    ENDSELECT._

If this SELECT is deleted, then the class will not be a problem anymore. With this coding line inside, the class will be unknown and cross references within other logic will be part of the abaplint syntax issue list. (like message above).

Thanks a lot.

Best regards,
Dominiik

**Comment by dpuerner** [comment]
Just one addition info. Syntax check is done based on version v756

**Comment by larshp** [comment]
thanks, reproduced,

![image](https://user-images.githubusercontent.com/5888506/211562256-ba47aca2-f556-425c-8f98-688bb0aaa4c1.png)

**Comment by larshp** [comment]
@dpuerner try again, 2.94.22 published
