### ISSUE TITLE
Dependencies check based on gitlab repo

### ISSUE THREAD

**Issue by dpuerner** [abaplint/abaplint#2832]
Hello,

it's still possible to maintain the repository URL for the dependencies check in the abaplint JSON config file.

![dependencies_1](https://user-images.githubusercontent.com/83902129/210811547-caeb08df-ba34-4ab6-ba55-f351f63206c6.jpg)

Based on company internal restrictions I have to put the repo to gitlab. Access to the repo is limited by user and their token. Is it possible via JSON config file as well to maintain a user and token for the repo. login? If not is it planned for the future?

Thanks for an answer.

BR
Dominik

**Comment by larshp** [comment]
I recommend using GitHub and https://abaplint.app then it will work out of the box

**Comment by dpuerner** [comment]
Thanks a lot again for  the very quick answer. Unfortunately company is using gitlab in general, so for abaplint checked abap repository (using abaplint CI via docker image) and for the dependency list. Therefore github is not possible to be use.

**Comment by larshp** [comment]
no progress, closing
