### ISSUE TITLE
Docker Linter performance went from 40s to not completing in 8h

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#2840]
With v 2.91.3, the execution of this project took 40s. Since this version (latest test with 2.94.3), it does not finish anymore in 8h.
The processing is done in a Gitlab pipeline using the docker linter image. The project has a big sap dependency project.

Ok Run:
![image](https://user-images.githubusercontent.com/53995991/211754489-ff8c92ba-4045-4eb9-adcb-4d7c72c36091.png)
Not completing Run:
![image](https://user-images.githubusercontent.com/53995991/211754807-0a61fb09-921e-4751-9fac-619a90dfb6d8.png)

I've not found the command to show the linter details while running. This might provide more intel on what has changed.

**Comment by ed-holland** [comment]
The above project results are from a medium size project. There is a daily regression test.
Even with a small project (with dependency project) it does not finish. Test was done with the new version

**Comment by larshp** [comment]
try on node 16? looking at the screenshots it was changed from 16 to 18

**Comment by ed-holland** [comment]
as this is the docker image provided, it is locked in on GitHub.

**Comment by ed-holland** [comment]
Added the "-p" to the command:
![image](https://user-images.githubusercontent.com/53995991/211855147-4304c5da-3ee3-4d7d-8c82-19cc921cfd27.png)

**Comment by ed-holland** [comment]
I've checked the docker image in the registry and it is clearly build with a newer node version.
![image](https://user-images.githubusercontent.com/53995991/212122320-531c5e7f-de9f-409f-9534-ebff65af944e.png)

Will try to build a new image using https://github.com/abaplint/abaplint-sci-server/tree/main/docker and retest

**Comment by ed-holland** [comment]
abaplint/abaplint-backend:latest is build with Node 16
abaplint/abaplint:latest is build with Node 18. It is working fine with Node 16.

Can it be changed back to use node v16?

**Comment by larshp** [comment]
@ed-holland https://github.com/abaplint/abaplint-docker/pull/8 merged

**Comment by ed-holland** [comment]
Thank Lars.

Checked the docker image. It was still on v18. Does it need to be manually triggered?

**Comment by larshp** [comment]
argh, running now https://github.com/abaplint/abaplint-docker/actions/workflows/dockerimage.yml

**Comment by ed-holland** [comment]
Thanks again.
Switched to latest and all is still working fine.

Closing Ticket

**Comment by larshp** [comment]
hmm, tho I still wonder what the problem is

**Comment by larshp** [comment]
I experienced a similar problem, on github actions it halted with node 18, but worked with 16
