### ISSUE TITLE
Syntax check - "<variable>" not found, findTop(check_syntax)

### ISSUE THREAD

**Issue by dpuerner** [abaplint/abaplint#2842]
Hello,

I have a syntax error which is not an error in SAP himself.

![Syntax_error_variable_not_found_1](https://user-images.githubusercontent.com/83902129/211800713-a42c4b4e-0abe-4d8a-804e-3ff0e30f9d74.jpg)

You can use this code in playground to reproduce.

``` abap
REPORT zfoobar.

DATA lv_source_hex TYPE xstring.
DATA lv_source TYPE char16.

GET BIT sy-index OF lv_source_hex INTO DATA(lv_res).
lv_source = lv_source && lv_res.
```

Thanks a lot!

Best regards,
Dominik

**Comment by larshp** [comment]
@dpuerner try again, 2.94.23 published

**Comment by dpuerner** [comment]
This bug is now fixed as well - fantastic :-) Thanks a lot!
