### ISSUE TITLE
idea: ast manipulation libraries

### ISSUE THREAD

**Issue by Allam76** [abaplint/abaplint#2859]
I noticed the parser outputs a CST that is fairly similar to [unist](https://github.com/syntax-tree/unist). This is a tool suite for ast manipulation. For instance, nowadays with CSS [has](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) selector and library [unist-util-select](https://github.com/syntax-tree/unist-util-select) could make your life rule building a lot easier. There is also the usual stiff like walker and ast node printing etc.

Also [esast](https://github.com/syntax-tree/esast) could be worth mentioning if you one day would like to go down the road of semantic AST. :smile: Same thing as unist but for general programming languages.

**Comment by larshp** [comment]
no, not planned
