### ISSUE TITLE
display the local implementations of classes in the vs code abaplint tab

### ISSUE THREAD

**Issue by oblomov-dev** [abaplint/abaplint#2887]
display also the local implementations of classes in the vs code abaplint tab:
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/102328295/221173473-04b2ddea-fd74-4546-8d20-dbc193802e2d.png">

**Comment by larshp** [comment]
moved to https://github.com/abaplint/vscode-abaplint/issues/142
