### ISSUE TITLE
check_syntax: Target "l_return" not found

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#2892]
node version:     v16.19.1
abaplint version: 2.95.26

Since a few weeks our regression Linter runs are creating errors (0 errors before) without any changes to to code.
There are several types of errors reported. This is the first ones but they probably will have the same cause.

Error (multiple occurrences):
`./src/bsc/#jcs#bsc.fugr.#jcs#acc_doc_create_atta.abap[46, 7]                  - "l_return" not found, Target (check_syntax) [E]`

l_return is defined in this macro, which is defined in an include.
![image](https://user-images.githubusercontent.com/53995991/222073382-47aae61a-0841-45c0-a540-d84fed72e4bd.png)

Error:  (multiple occurrences)
`./src/ecc/#jcs#fi.fugr.#jcs#fi_ff67_preparation.abap[121, 3]                  - "t012" not found, Target (check_syntax) [E]`

The SAP Table T012 is defined in another include.

Let me know if you need additional information. Thx

**Comment by larshp** [comment]
just need something that can be reproduced

**Comment by ed-holland** [comment]
will try. What areas were changed lately to reduce to context?

**Comment by larshp** [comment]
changes = https://github.com/abaplint/abaplint/commits/main, if you know a version that it worked on, its possible to do binary search for the version breaking it

**Comment by ed-holland** [comment]
The errors first occurred with abaplint version: 2.95.10
thx

**Comment by larshp** [comment]
2.95.10 = https://github.com/abaplint/abaplint/pull/2864

**Comment by ed-holland** [comment]
The changes seem minimal.  Could it be caused by the Node version change?

**Comment by ed-holland** [comment]
Ok [2.91.3](https://hub.docker.com/layers/abaplint/abaplint/2.91.3/images/sha256-2eedaf2d2a33197231781deff2c907e7b40437ddf2c6a1383ad1381722d4268f?context=explore) is the last version that worked.
After that, Node v18 broke the linter.

**Comment by ed-holland** [comment]
It was the daily regression linter run. Not a code change.

**Comment by larshp** [comment]
need something for reproducing the issue

**Comment by ed-holland** [comment]
Hi Lars,

Finally go to creating a test case that gets the errors. Attached the REPO export.
Not sure if you will get the same errors...
[AG_Tests-main.zip](https://github.com/user-attachments/files/16174296/AG_Tests-main.zip)

**Comment by larshp** [comment]
@ed-holland its a configuration error, dont set it as a `globalMacros`

![image](https://github.com/user-attachments/assets/a702b939-31ca-48d4-ac78-7fead57a8c10)

**Comment by ed-holland** [comment]
The global macros where set as they were not linted correctly. I will remove them all and test if these are now working as expected.

**Comment by ed-holland** [comment]
The new errors are like these:
```
./src/ecc/#jcs#ckml.fugr.#jcs#ckml_cp_change.abap[58, 5]                     - Statement does not exist in ABAPv700(or a parser error), "set_bapiret2" (parser_error) [E]
./src/ecc/#jcs#ckml.fugr.#jcs#ckml_cp_change.abap[86, 7]                     - Statement does not exist in ABAPv700(or a parser error), "set_bapiret2" (parser_error) [E]
./src/ecc/badi/#jcs#cl_badi_fi_acc_document.clas.abap[300, 5]                - Statement does not exist in ABAPv700(or a parser error), "do_accit" (parser_error) [E]
./src/ecc/badi/#jcs#cl_badi_fi_acc_document.clas.abap[304, 5]                - Statement does not exist in ABAPv700(or a parser error), "do_accit" (parser_error) [E]
./src/ecc/badi/#jcs#cl_badi_fi_acc_document.clas.abap[308, 5]                - Statement does not exist in ABAPv700(or a parser error), "do_accit_item" (parser_error) [E]
./src/ecc/badi/#jcs#cl_badi_fi_acc_document.clas.abap[312, 5]                - Statement does not exist in ABAPv700(or a parser error), "do_accit_item" (parser_error) [E]
```

Interestingly, not all the entries defined in the globalmacros showed up. I'll add the ones that show up again.

**Comment by ed-holland** [comment]
Happy with the result. Will close this ticket.

Thanks
