### ISSUE TITLE
Implementation of "for lock" syntax

### ISSUE THREAD

**Issue by Zeatynis** [abaplint/abaplint#2903]
Seems like there is a hole in the syntax. There is "for lock" statement that is not handled. I couldn't find any issue about it, so I create one. "For modify" and "for read" are handled.
![obraz](https://user-images.githubusercontent.com/9119187/223084755-bc2263b3-1312-4c9c-87c1-75a51ad88a9a.png)
![obraz](https://user-images.githubusercontent.com/9119187/223084899-cd60f63a-39a0-4958-8655-1dea814171f6.png)

**Comment by larshp** [comment]
`METHODS lock FOR LOCK IMPORTING keys FOR LOCK /foo/bar.`

**Comment by larshp** [comment]
https://syntax.abaplint.org/?filter=methoddef#/abap/statement/MethodDef

**Comment by larshp** [comment]
@Zeatynis try again, 2.95.32 published

**Comment by Zeatynis** [comment]
@larshp thanks for such fast response! It is working 😃
