### ISSUE TITLE
Idea: Link from syntax diagram to repo

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#2907]
It's quite tricky to find the right file in this repo esp. if one is not familiar with it. The idea is to include an "Edit on GitHub" button on the syntax diagrams. 

Example:

I found a mistake on https://syntax.abaplint.org/?filter=table#/abap/expression/TypeTable (visually):

![image](https://user-images.githubusercontent.com/59966492/223653021-463fc9b8-87dc-4d7c-9f28-967f7817153e.png)

The edit button should take me to https://github.com/abaplint/abaplint/blob/main/packages/core/src/abap/2_statements/expressions/type_table.ts

PS: I will provide fix separately

**Comment by larshp** [comment]
fixed, see lower left,
![image](https://user-images.githubusercontent.com/5888506/236454281-b0c3bc93-c677-4de0-92c1-3df95630b157.png)
