### ISSUE TITLE
check_subrc ignoring IF IS (NOT) INITIAL

### ISSUE THREAD

**Issue by jan-jezek** [abaplint/abaplint#2928]
![image](https://user-images.githubusercontent.com/17530797/227310220-342abc18-9283-4df2-8a33-865890d62f6e.png)

IMHO the check should not fire here. If I have it like a field symbol the IF ASSIGNED is enough, so I don't see a reason to fire for IS (NOT) INITIAL.

**Comment by larshp** [comment]
yea, tho I dont remember if `line_one` is cleared if index 1 is not found, eg. if running it in a loop

**Comment by jan-jezek** [comment]
true... :(
![image](https://user-images.githubusercontent.com/17530797/227313842-0f24c52d-34a0-49ed-af32-46065a1da590.png)
This completely breaks my ABAP logic :D, oh well

**Comment by jan-jezek** [comment]
What surprised me unpleasantly was that even:
![image](https://user-images.githubusercontent.com/17530797/227315169-b3278420-3525-411b-9ce4-8141e0d1fa31.png)
keeps the value, so the result is still same as in the aforementioned picture.
