### ISSUE TITLE
Return data type 

### ISSUE THREAD

**Issue by DennisLybecker-INVIXO** [abaplint/abaplint#2937]
Issue introduced this weekend. Was working on friday  (version 7.02)
-------------------
      BEGIN OF ty_data_tree_st,
        tree_node     TYPE ty_component_view_st,
        tree_tab_info TYPE ty_tree_tab_info_tt,
      END OF ty_data_tree_st .
    TYPES:
      ty_data_tree_tt TYPE SORTED TABLE OF ty_data_tree_st WITH UNIQUE KEY primary_key COMPONENTS tree_node-id
-----------------
When using a return table of this type TY_DATA_TREE_TT and a local variable LIKE LINE OF this. 

When we get a 'Not a structure, type unknown, target' error when doing a move corresponding to TREE_NODE. 
Can see you did some work on 'Return' this weekend. Think it needs to check if there is a key defined for the table, then it is Ok by SAP. 

Let me know if you need a Playground example. 

Thanks.

**Comment by larshp** [comment]
@DennisLybecker-INVIXO try again, latest version

**Comment by DennisLybecker-INVIXO** [comment]
Working, thanks.
