### ISSUE TITLE
prefer_inline: conflicting with no_inline_in_optional_branches

### ISSUE THREAD

**Issue by TheLazyHangman** [abaplint/abaplint#2949]
This is correctly throwing no_inline_in_optional_branches:
![image](https://user-images.githubusercontent.com/104131979/231478652-0b7f6158-ee7c-4e49-9a5c-5d5e38cc0a1a.png)

while this is throwing prefer_inline:
![image](https://user-images.githubusercontent.com/104131979/231479160-485f89fd-3599-4592-9694-c6c87df1a191.png)

I can see prefer_inline is marked as [experimental](https://rules.abaplint.org/prefer_inline/), but honestly I don't see how they can both be active at the same time, prefer_inline definitely needs to be more context-based.

**Comment by larshp** [comment]
Hi,
From my point of view its not a design goal that all rules can be achieved at the same time. Each team must decide their preferred style.

However, also see https://github.com/abaplint/abaplint/issues/2522 and https://github.com/SAP/styleguides/issues/272

**Comment by larshp** [comment]
@TheLazyHangman ok to close?

**Comment by larshp** [comment]
remote fs: I think there are some open issues somewhere
