### ISSUE TITLE
Class / data element etc. not found 

### ISSUE THREAD

**Issue by dominikpanzer** [abaplint/abaplint#2968]
what is a good way to solve problems while linting/downporting/unittesting when a certain class is not available?

example:
```
[E] Class cl_abap_datfm not found (check_syntax) @ .
  117 |        cl_abap_datfm=>conv_date_ext_to_int( EXPORTING im_datext = date_as_text
      |        ^
  118 |                                                       im_datfmdes = '1'
```

**Comment by larshp** [comment]
if unit testing, I guess it is setup to check depndencies against https://github.com/open-abap/open-abap-core, ie. add the class there with a PR, only add what you need

**Comment by larshp** [comment]
https://github.com/open-abap/open-abap-core/pull/658 opened

**Comment by dominikpanzer** [comment]
https://github.com/open-abap/open-abap-core/pull/661 
unit tests in the pipeline seem to take > 10 minutes and havent finished, yet.'

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/236598802-98a73687-0359-4845-be7c-89a57e2612aa.png)

**Comment by dominikpanzer** [comment]
sure
