### ISSUE TITLE
downporting: UNDEFINED not found, lookup (unknown_types) [E]

### ISSUE THREAD

**Issue by dominikpanzer** [abaplint/abaplint#2984]
Hi,
I get these errors while downporting. the line numbers(?) 298, 299 etc don't exist in the file / make no sense. Is there any way to find out whats the problem here?

> 
> 2023-05-10T20:51:11.4948171Z 	Iteration  61,   0 fixes applied,    4ms, rule unknown_types
> 2023-05-10T20:51:11.4948671Z 	Iteration  62,   0 fixes applied,    1ms, rule xml_consistency
> 2023-05-10T20:51:13.1767165Z ./downport/XXX.clas.testclasses.abap[298, 10] - Variable "TEMP12" contains unknown: UNDEFINED not found, lookup (unknown_types) [E]
> 2023-05-10T20:51:13.1773930Z ./downport/XXX.clas.testclasses.abap[299, 10] - Variable "TEMP13" contains unknown: UNDEFINED not found, lookup (unknown_types) [E]
> 2023-05-10T20:51:13.1775047Z ./downport/XXX.clas.testclasses.abap[379, 10] - Variable "TEMP17" contains unknown: UNDEFINED not found, lookup (unknown_types) [E]
> 2023-05-10T20:51:13.1776326Z ./downport/XXX.clas.testclasses.abap[380, 10] - Variable "TEMP18" contains unknown: UNDEFINED not found, lookup (unknown_types) [E]
> 2023-05-10T20:51:13.1777285Z ./downport/XXX.clas.testclasses.abap[381, 10] - Variable "TEMP19" contains unknown: UNDEFINED not found, lookup (unknown_types) [E]

Repo is not public, yet. I currently can't reproduce this, because I really don't know what the problem might actually be. Any hints? Otherwise I will link the repo here when its public.

**Comment by larshp** [comment]
yea, it happens, typically I've seen this error when types are not fully qualified

eg. change
`DATA sdf TYPE STANDARD TABLE OF i WITH DEFAULT KEY.`
to
```abap
TYPES ty TYPE STANDARD TABLE OF i WITH DEFAULT KEY. 
DATA sdf TYPE ty.
```

I would like to add more features for debugging this, but time...

**Comment by dominikpanzer** [comment]
ok, I'll have a look or get back to you when the repo is public. thx.

**Comment by dominikpanzer** [comment]
here it is. I couldn't find the error. would be great if you could have a look. thanks.
https://github.com/dominikpanzer/cacamber-BDD-for-ABAP

**Comment by dominikpanzer** [comment]
![grafik](https://github.com/abaplint/abaplint/assets/54714566/8cb7bdcf-e381-4f04-a229-23b961d97a71)

https://github.com/dominikpanzer/cacamber-BDD-for-ABAP/actions/runs/4992812508/jobs/8941031900 

the tests don't fail on BTP / on prem
