### ISSUE TITLE
unit tests fails but works fine on BTP / on prem: TypeError: Cannot read properties of undefined (reading 'set')

### ISSUE THREAD

**Issue by dominikpanzer** [abaplint/abaplint#2987]
After downporting a unit test seems to fail with the following error:
```
TypeError: Cannot read properties of undefined (reading 'set')
````
The unit tests work fine on the BTP ABAP Environment / on premise

https://github.com/dominikpanzer/cacamber-BDD-for-ABAP/actions/runs/4992812508/jobs/8941031900
![grafik](https://github.com/abaplint/abaplint/assets/54714566/79c21290-f444-4a01-8d04-c22928793827)

**Comment by larshp** [comment]
fixed in https://github.com/abaplint/transpiler/pull/1223 as part of the transpiler project

**Comment by dominikpanzer** [comment]
ok.  new error - a new issue or did I do something wrong?
https://github.com/dominikpanzer/cacamber-BDD-for-ABAP/actions/runs/4993039575/jobs/8941582995

**Comment by larshp** [comment]
I've opened that error as https://github.com/open-abap/open-abap-core/issues/674

**Comment by dominikpanzer** [comment]
I had a look at it, but I have no idea how to solve that myself. doesn't seem to be possible without knowledge of the kernel-functions?

**Comment by larshp** [comment]
I'll fix it, sometime..

close this issue and move to https://github.com/open-abap/open-abap-core/issues/674 ?

**Comment by dominikpanzer** [comment]
sure
