### ISSUE TITLE
Q: 'check_syntax' to ignore certain objects

### ISSUE THREAD

**Issue by albertmink** [abaplint/abaplint#2989]
Let's say, I like the syntax check to ignore class 'CL_ABCD'.
(I assume that will also resolve findings 'Method definition "CL_ABCD...." not found'.)

I tried
```
    "check_syntax": {
      "exclude": ["cl_abcd"]
    }
```
and
```
    "check_syntax": {
      "exclude": ["cl\\_abcd"]
    }
```
but could not succeed.

Can you point me in the right direction?

**Comment by larshp** [comment]
* ignore syntax errors in class: add it to exclude
* ignore syntax errors involving the class: exclude it from errorNamespace

**Comment by larshp** [comment]
eg `"^(Z|(?!YORG)Y|LCL_|TY_|LIF_)"`

**Comment by albertmink** [comment]
thanks
