### ISSUE TITLE
cloud_types doesn't know ATC object types 

### ISSUE THREAD

**Issue by bjoern-jueliger-sap** [abaplint/abaplint#2998]
The ATC has objects for its checks and check variants: Object types CHKC, CHKO, CHKV.

These currently produce linter errors:

> Unknown object type, currently not supported in abaplint, open issue on github (parser_error) [E]
> Object type CHKV not supported in cloud (cloud_types) [E]

But these object types are supported in ABAP Cloud (in fact, they were introduced to deal with ATC checks in a cloud context).

**Comment by larshp** [comment]
@bjoern-jueliger-sap try again, 2.101.1 published

**Comment by bjoern-jueliger-sap** [comment]
Thanks, can confirm it works!
