### ISSUE TITLE
Search on rules.abaplint.org incomplete

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#3063]
Looks like the index is not up-to-date. Doesn't find "smim_consistency" or "easy_to_find_messages" for example

![image](https://github.com/abaplint/abaplint/assets/59966492/1bf402c8-6703-44be-908d-b1dc78fcddde)

**Comment by larshp** [comment]
argh, thats annoying, tried kicking some tires

design issue = https://github.com/abaplint/abaplint/issues/1740

**Comment by larshp** [comment]
@mbtools try again, all new rewritten,

![image](https://github.com/abaplint/abaplint/assets/5888506/5012a1bd-6aaa-451b-bc87-3d978cb5a069)

**Comment by mbtools** [comment]
Nicely done! 👍
