### ISSUE TITLE
type abap_boolean - check for lower releases or not allowed function

### ISSUE THREAD

**Issue by oblomov-dev** [abaplint/abaplint#3064]
Don't now since which release abap_boolean is available, but seems to make some some problems on certain releases:
https://github.com/abap2UI5/abap2UI5/issues/428

Maybe the variable can be added to a certain "not allowed" list?

Do not use this type by myself (always use abap_bool) but it is hard to discover when it comes with a PR and abaplint is not warning. Maybe it is easy to add a check or there is still a rule for this?

**Comment by larshp** [comment]
it doesnt exist in 702, https://abapedia.org/steampunk-2305-api/abap_boolean.dtel.html

**Comment by larshp** [comment]
@oblomov-dev try checking against https://github.com/abapedia/steampunk-2305-api-intersect-702 instead

thanks to @mbtools for providing the [702 list](https://github.com/abapedia/object-existence/blob/main/json/on_prem_702.json)

**Comment by oblomov-dev** [comment]
Nice!

https://github.com/abap2UI5/abap2UI5/pull/430/checks?check_run_id=15419578445
<img width="500" alt="image" src="https://github.com/abaplint/abaplint/assets/102328295/cfcdda9b-9d8b-4521-a41a-c330f3c84abd">

Thank you and @mbtools

**Comment by larshp** [comment]
closing

**Comment by mbtools** [comment]
@larshp if you create a steampunk_2305.json (like https://github.com/abapedia/object-existence/blob/main/json/steampunk_2111.json), I can run the 702, 750, 754 extracts again.

**Comment by larshp** [comment]
I dont remember where that came from /how to generate it, anyhow, think its good for now, not much new stuff is added

**Comment by mbtools** [comment]
https://github.com/abapedia/object-existence/pull/2
