### ISSUE TITLE
Keyword STEP not detected.

### ISSUE THREAD

**Issue by albertmink** [abaplint/abaplint#3096]
We found a keyword that slipped into the repository here https://github.com/SAP/abap-file-formats-tools/blob/d7bfc9f4bffe33db2d694eba533ad7953da5005b/src/z_generate_repo.prog.abap#L566 

Should be UPPER according to abaplint.jsonc

**Comment by larshp** [comment]
generate_repo is excluded from linting, https://github.com/SAP/abap-file-formats-tools/blob/main/abaplint.jsonc#L4

but there is still a bug in abaplint, https://syntax.abaplint.org/?filter=loop#/abap/statement/Loop

**Comment by larshp** [comment]
757 feature, https://help.sap.com/doc/abapdocu_757_index_htm/7.57/en-US/abennews-757-itab.htm#!ABAP_MODIFICATION_1@1@

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/pull/3094

**Comment by albertmink** [comment]
I guess it is solved.
