### ISSUE TITLE
method_length rule firing even if class is abstract

### ISSUE THREAD

**Issue by jan-jezek** [abaplint/abaplint#3103]
If I have abstract class that has empty implementation of method, the method_length rule is firing (if set to check for empty methods).

IMHO this should not be the case, as it is okay to have abstract class with empty method implementations.

![image](https://github.com/abaplint/abaplint/assets/17530797/a99b3701-68ed-4b55-a91c-9242b8e85123)

**Comment by larshp** [comment]
yea, I aggree

**Comment by larshp** [comment]
reproduced as 

```abap
CLASS lcl DEFINITION ABSTRACT.
  PUBLIC SECTION.
    METHODS foo.
ENDCLASS.

CLASS lcl IMPLEMENTATION.
  METHOD foo.
  ENDMETHOD.
ENDCLASS.
```

**Comment by larshp** [comment]
@jan-jezek try again, 2.102.42 published

**Comment by jan-jezek** [comment]
Fixed, thanks 👍🏻
