### ISSUE TITLE
/ui2/cl_json inheritance issue

### ISSUE THREAD

**Issue by antilla1** [abaplint/abaplint#3107]
I'm getting errors when trying to inherit the standard JSON class /ui2/cl_json:
<img width="525" alt="image" src="https://github.com/abaplint/abaplint/assets/83271110/87f23c17-9a6e-4ccf-a97c-a6ca20739695">

```abap
CLASS lcl_json_custom DEFINITION FINAL INHERITING FROM /ui2/cl_json.
  PUBLIC SECTION.

  PROTECTED SECTION.
ENDCLASS.
CLASS lcl_json_custom IMPLEMENTATION.

ENDCLASS.
```

But there are no errors, when I'm using this standard class in my code:
<img width="781" alt="image" src="https://github.com/abaplint/abaplint/assets/83271110/933d2d04-a56e-44c6-a249-71355352b743">

```abap
DATA ls_body TYPE sflight.

DATA(lv_json) = /ui2/cl_json=>serialize(
                                data           = ls_body
                                pretty_name    = /ui2/cl_json=>pretty_mode-low_case
                                numc_as_string = abap_true ).
WRITE lv_json.
```

**Comment by larshp** [comment]
yea, its not in the playground

when inheriting, abaplint needs to know the super class to do a proper syntax check. But it doesn't need it for a method call

dependencies can be added in abaplint.jsonc, either with a url or local to the repo,

![image](https://github.com/abaplint/abaplint/assets/5888506/ab2f5669-f8f4-4d52-8309-d627ade3c0f7)

**Comment by DennisLybecker-INVIXO** [comment]
We have added it to the dependencies and it works, thanks. @larshp you can just close this.
