### ISSUE TITLE
Assign - static variant - check_subrc

### ISSUE THREAD

**Issue by DGRHicron** [abaplint/abaplint#3114]
```
DATA foo TYPE i.
DATA bar TYPE i.

FIELD-SYMBOLS <foo> TYPE i.
FIELD-SYMBOLS <bar> TYPE string.

ASSIGN foo TO <foo>.
ASSIGN bar TO <bar>.
```

These FSs and variables are declared statically. They are checked by syntax check nevertheless abaplint's rule _check_subrc_ raises an issue here. This is pointless,especially since there is no subrc change for these statements. The subrc is changed only in dynamic variants.

**Comment by larshp** [comment]
#2707
#1863

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/pull/3115

**Comment by larshp** [comment]
@DGRHicron try again, 2.102.48 published

**Comment by DGRHicron** [comment]
In my code these issues are gone. I didn't check the demo code from this issue as Playground is not yet in the newest version.
