### ISSUE TITLE
Too many `unnecessary_return` messages

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#3141]
There are a lot of `unnecessary_return` messages related to something like this:

```abap
  METHOD zif_abapgit_background~get_settings.
    RETURN.
  ENDMETHOD.
```

```jsonc
  "unnecessary_return": true,
  "method_length": true, //   "errorWhenEmpty": true is the default
```

It's common also to prevent `method_length` errors.

Maybe add a parameter to skip these.

**Comment by larshp** [comment]
@mbtools try again, 2.108.9

https://rules.abaplint.org/unnecessary_return/

**Comment by mbtools** [comment]
👍
