### ISSUE TITLE
2.102.68 - unknown_types occurred

### ISSUE THREAD

**Issue by DGRHicron** [abaplint/abaplint#3151]
Hi,
after publishing new version (2.102.68) - https://github.com/abaplint/abaplint/pull/3149 there is a problem with dependencies. I have a dependency from folder. It works on 2.102.67 and on new version abaplint tells me that my dependency object is uknown (unknown_types)

**Comment by larshp** [comment]
try running the linter on just the dependencies to check they are okay

I had to do https://github.com/abaplint/deps/commit/5b0a0e5aafa01fc48babc344b6387d52b4410a3a and https://github.com/open-abap/open-abap-core/commit/ba36bf2e777fa84002640953689d5b8c4c334a47 to fix similar bugs

**Comment by DGRHicron** [comment]
Yes they are ok. No syntax_check issues. Only abapdoc 😆

**Comment by DGRHicron** [comment]
I resolved my issue. It was connected to dependencies of my project.
