### ISSUE TITLE
Request: Support for object type `.oa2p.xml`

### ISSUE THREAD

**Issue by HOUNDmx** [abaplint/abaplint#3162]
Hello 😄 

OAuth 2.0 Client Profiles not supported by abaplint, currently raising a parser error? 

![image](https://github.com/abaplint/abaplint/assets/41452634/aa50eb2f-6ee8-4d21-b988-d1c4c33797a8)

**Comment by larshp** [comment]
@HOUNDmx try again, latest version

**Comment by HOUNDmx** [comment]
seems okay, thanks 😄 
![image](https://github.com/abaplint/abaplint/assets/41452634/7e9aecbf-5283-455a-a624-ffbcdb211ac3)
