### ISSUE TITLE
forbidden_pseudo_and_pragma: invalid json in default config

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#3164]
guess the leading quote is too much:

![image](https://github.com/abaplint/abaplint/assets/59966492/cc3ff7a3-6c5c-4718-b9e7-e1c96bb95b8d)

https://github.com/abaplint/abaplint/blob/195b76310ab196249279d1a2181c9eae5bea07b5/packages/core/src/rules/forbidden_pseudo_and_pragma.ts#L13

Also odd that rules doesn't show in search for "pragma" but does show for "forbidden":

![image](https://github.com/abaplint/abaplint/assets/59966492/62918ba4-b58d-4cb4-9deb-fe50ac004991)

![image](https://github.com/abaplint/abaplint/assets/59966492/3f563893-76aa-4d01-97c8-86d08e63754e)

**Comment by larshp** [comment]
oh, on https://rules.abaplint.org/forbidden_pseudo_and_pragma/

**Comment by larshp** [comment]
@mbtools try again, fuzziness adjusted, and escaping fixed

**Comment by mbtools** [comment]
works 👍
