### ISSUE TITLE
Turn off dependency check or use regex patterns

### ISSUE THREAD

**Issue by mraht** [abaplint/abaplint#3179]
I use abapLint in combination with repositories for SAP EWM. Thus I have many dependencies the abapLint exporting report (`zabaplint_dependencies`) would have to export and isn't exporting currently.

It would be nice, if one could turn off abapLint rules considering dependencies (e.g. `check_syntax` or `unknown_types`):
1) Turn off dependency-based checks or parts of the related checks (e.g. `check_syntax` only checks for non-dependency related issues)
2) Use regex patterns for dependency-related object names to be recognized during the checks as fulfilled (e.g. pattern `*/scwm/*` would fulfill all dependencies matching the pattern)

**Comment by larshp** [comment]
hi, 
In general I dont recommend using `zabaplint_dependencies`, SAP standard is typically not designed in layers, ie. one class will end up pulling in all the system, or limiting to some depth has the tendency to give strange and difficult errors.

syntax_check and unknown_types: the 2 rules would not be able to give any results if not considering dependencies, ie. same as switching off these rules

**Comment by mraht** [comment]
Ok, thanks for the clarification :)
