### ISSUE TITLE
Handle pseudo-comments in avoid_use rule

### ISSUE THREAD

**Issue by jan-jezek** [abaplint/abaplint#3195]
I suggest that the **avoid_use** rule should ignore those instances where these pseudo-comments are used:

"#EC DEFAULT_KEY for option defaultKey
 "#EC TEST_SEAM_USAGE for option testSeams

It would also be nice to disable exportToMemory and exportToDatabase with a pseudo-comment or pragma, but there is no standard way to do this as these statements are neither obsolete nor discouraged by Clean Code or Code Pal.

**Comment by larshp** [comment]
```abap
TEST-SEAM seam_name.    "#EC TEST_SEAM_USAGE
END-TEST-SEAM.
```

**Comment by larshp** [comment]
@jan-jezek try again, 2.105.17 released

**Comment by jan-jezek** [comment]
👍🏻
