### ISSUE TITLE
Downport - Not checking for ENUMS when using ABAP version v.7.02

### ISSUE THREAD

**Issue by oblomov-dev** [abaplint/abaplint#3203]
Hi,

created a downport repository of S-RTTI with the abaplint downport, everything works great, so big thank you first!

But when i use abap version 7.02 in the abaplint settings: 
https://github.com/abap2UI5/S-RTTI-downport/blob/998c4dc7b135cc5da9d61fef7b5d7a988df5e9e8/abaplint.jsonc#L13

I would expect that using the API of for example cl_abap_enumdescr is not allowed, because it exists since 7.51:
https://help.sap.com/doc/abapdocu_752_index_htm/7.52/de-de/abaptypes_enum.htm

It is done here:
https://github.com/abap2UI5/S-RTTI-downport/blob/998c4dc7b135cc5da9d61fef7b5d7a988df5e9e8/src/zcl_srtti_enumdescr.clas.abap#L9
<img width="500" alt="image" src="https://github.com/abaplint/abaplint/assets/102328295/4551d77c-02a9-4469-95a9-0a63935fb04d">

But the abaplint status is green:
<img width="1223" alt="image" src="https://github.com/abaplint/abaplint/assets/102328295/8a3bb1a6-703d-4a63-93d4-d242ffc5248e">

Best regards.

**Comment by larshp** [comment]
for `cl_abap_enumdescr` its a question of input to the linter more than the functionality

it exists in https://github.com/open-abap/open-abap-core/blob/main/src/rtti/cl_abap_enumdescr.clas.abap, thus abaplint expects it to be okay

its a compromise, I'd like not to maintain 100s of open-abap-core versions, plus I dont have any possibility to check they are okay

**Comment by oblomov-dev** [comment]
ok understand, thank you for the information.
yes deleted the dependency, so no problem on my side, just was not sure if this is a "known" feature or not ;)

**Comment by larshp** [comment]
downport only downports the language syntax

and the syntax check checks against the dependencies provided

it would be nice if SAP did provide information as to when/what something is changed, its really difficult to figure out when only having access to a few running versions

**Comment by oblomov-dev** [comment]
ah ok everything works fine! i just understood what you mean with dependency wrong. i changed it now to:
https://github.com/abap2UI5/S-RTTI-downport/blob/1f53287944cd2d103d7dbe1242cdccb29e03631c/abaplint.jsonc#L7

And now i get the error which i expected:
<img width="500" alt="image" src="https://github.com/abaplint/abaplint/assets/102328295/f3714e09-4c17-4058-ae24-0806e61bfc65">

```
it would be nice if SAP did provide information as to when/what something is changed, its really difficult to figure out when only having access to a few running versions
```
yes exactly, first step having running system from SAP for all diffenerent versions would be nice, i do everything blind and trust your tools (which is fun, but which should not be needed in professional business contexts). luckily having a (1) v.7.02, (2) on-premise 7.50 and a (3) cloud stack will cover most use cases.

```
you can do a fork of any dependency repository, and maintain it if you like
```
yes slowly i understand how it all works, whenever i notice something unexpected, i will create an issue or try to fix it by myself
