### ISSUE TITLE
support Eclipse ADT file format

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#321]
support Eclipse ADT file format

**Comment by FreHu** [comment]
do you plan on eclipse integration anytime soon? i am trying to turn eclipse into a decent editor and if doing quickfixes with abaplint was possible it would be amazing

**Comment by larshp** [comment]
planning to convert ADT file format to abapGit format via https://github.com/larshp/abap-transmogrify

integration/plugin will be at https://github.com/abaplint/abaplint-eclipse

suggest using an approach like https://github.com/angelozerr/tern.java

I dont plan looking into it anytime soon, but pull requests welcome

**Comment by FreHu** [comment]
You can also put vscode into eclipse:
![eclipse_omepeurynw](https://user-images.githubusercontent.com/5097067/52505830-01dcc580-2bed-11e9-832e-4a9dbd231b5e.png)

https://marketplace.eclipse.org/content/codemix
This allows you to install vscode extensions from vsix packages. I installed abaplint, vscode-abap and abap snippets and they all seem to work.

This is for local files only, but possibly it's just a matter of vscode-abap not recognizing the .aclass extension.

**Comment by larshp** [comment]
uh, cool, looks promising

**Comment by FreHu** [comment]
Tried to modify the extensions to support .aclass, unfortunately this also only works only on local aclass files. You can at least have a vscode scratchpad in ADT I guess.

Also you have to do this first:
![image](https://user-images.githubusercontent.com/5097067/52518651-48164100-2c4e-11e9-99ff-3c9c2c9844b7.png)

**Comment by larshp** [comment]
eclipse integration via https://github.com/abaplint/abaplint-abap-backend, closing
