### ISSUE TITLE
abaplint CLI freezes when using custom dependency repository

### ISSUE THREAD

**Issue by sz3lbi** [abaplint/abaplint#3228]
Hello everyone,

I have a Z package in the system that uses quite a lot of objects, even standard ones, that abaplint shows as non-existent - which is true, as they come from other packages. So I wanted to solve this problem somehow. I've come across the option to [export dependencies for a specific package from the system using the abaplint SCI client](https://github.com/abaplint/abaplint-sci-client/blob/main/docs/export_dependencies.md). I've installed it in the system, exported dependencies from the system to a repository. It exported all the dependencies that my package uses, which is intended. I don't need all of them, but I can easily remove some of the dependencies from the repo manually.
However, now when I try to run abaplint locally after adding the dependency repo to the config, it freezes on the `Global OO types` step as shown below. If I remove my repo with custom deps, it works fine. I even left it for about 1 hour to check, but it didn't proceed at all.
```
abaplint 2.105.16
Using config: C:\Users\username\some-directory\my-repo-name\abaplint.json
100% - 0.2s - Reading files - z_rf_production_rack.para.xml
Clone: https://github.com/abaplint/deps
100% - 0.0s - Reading files - cl_workflow_general_task_def.clas.xml
Clone: https://github.com/my-organization/my-repo-name
Username for 'https://github.com': my-github-usernmae
Password for 'https://my-github-usernmae@github.com':
100% - 1.1s - Reading files - zcs_fleet.dtel.xml
100% - 3.0s - Lexing and parsing(v757) - PARA Z_RF_PRODUCTION_RACK
        Total lexing:     736ms
        Total statements: 1503ms
        Total structure:  294ms
1% - 0.1s - Global OO types(pass 1), next pass: 22
```
`abaplint.json`:
```json
{
  "global": {
    "files": "/src/**/*.*",
    "exclude": [],
    "noIssues": [],
    "skipGeneratedBOPFInterfaces": false,
    "skipGeneratedFunctionGroups": true,
    "skipGeneratedGatewayClasses": true,
    "skipGeneratedPersistentClasses": true,
    "skipGeneratedProxyClasses": false,
    "skipGeneratedProxyInterfaces": false,
    "useApackDependencies": false,
    "skipIncludesWithoutMain": false
  },
  "dependencies": [
    {
      "url": "https://github.com/abaplint/deps",
      "folder": "/deps",
      "files": "/src/**/*.*"
    },
    {
      "url": "https://github.com/my-organization/my-repo-name",
      "folder": "/my-repo-name",
      "files": "/src/**/*.*"
    }
  ],
  //...
}
```
The problem is the same when I replace the URL with the SSH one. It just asks me for a passphrase instead of the username and token.

**Comment by larshp** [comment]
thanks

I've not seen that error before, we need a way to reproduce it, need more information to debug it

SCI client: not sure I'd recommend using it that way

**Comment by larshp** [comment]
thanks, I can confirm the issue, it freezes, hmm

also when running on just https://gitlab.com/sz3lbi/abaplint_cli_freeze_deps, its a smaller MRE

**Comment by larshp** [comment]
@sz3lbi try again, 2.105.18 published
