### ISSUE TITLE
long strings in one line, expect syntax errors

### ISSUE THREAD

**Issue by oblomov-dev** [abaplint/abaplint#3235]
https://github.com/abap2UI5/abap2UI5/issues/879#issuecomment-1937456053 reproduces as:
```abap
REPORT zfoobar.

CLASS lcl DEFINITION.
  PUBLIC SECTION.
    METHODS my_method
      IMPORTING
        val TYPE data.
ENDCLASS.

CLASS lcl IMPLEMENTATION.
  METHOD my_method.

    data(lv_string) = `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.` && `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.` && `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, seddiamnonumyeirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.` && `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.` && `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.` && `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna` && `aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.`.
 
  ENDMETHOD.
ENDCLASS.
```

expect syntax error on lower release, because the line length is restricted.

Additionally the dowmported seems to miss adding a line break after &&, orginal source code before downportimg for example:
```abap
REPORT zfoobar.

CLASS lcl DEFINITION.
  PUBLIC SECTION.
    METHODS my_method
      IMPORTING
        val TYPE data.
ENDCLASS.

CLASS lcl IMPLEMENTATION.
  METHOD my_method.

   data(lv_string) = `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.` && `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.` && `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, seddiamnonumyeirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.` && `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.` && `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.` && `Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna` && `aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.`.
 
  ENDMETHOD.
ENDCLASS.
```

**Comment by larshp** [comment]
https://rules.abaplint.org/line_length/ can be used to check for line length

plus there is a bug in downport

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/pull/3233

**Comment by larshp** [comment]
downport fix is part of https://github.com/abaplint/abaplint/pull/3233, which I'll probably release later today

**Comment by oblomov-dev** [comment]
nice thank you!

**Comment by larshp** [comment]
@oblomov-dev try again, 2.105.17 released

**Comment by larshp** [comment]
@oblomov-dev try updating the package.json + package lock file? I'm not exactly sure which are used for the samples downport

**Comment by oblomov-dev** [comment]
the samples does not have a package.json, i do it manually in a github codespace with:
```
npm install @abaplint/cli -g
abaplint --fix
```
but,i have in mind to try to setup also an autodownport repo for the samples soon, then i will check it again.

**Comment by larshp** [comment]
repository = https://github.com/abap2UI5/abap2UI5-samples

**Comment by oblomov-dev** [comment]
yes i tried to setup the samples-downport here and have in mind to do it excactly for the samples like i do with the main repository. therefore i copied 1:1 everything from abap2UI5 and just changed the names but unfortunately it does not work.

when i downport the samples manually in github codespace, it runs without problems. what do you mean exactly, adjust something here?
https://github.com/abap2UI5/abap2UI5-samples/blob/ee1054fe08d32a2ecf6ec9eb09ba84d56732375e/package.json#L7

**Comment by larshp** [comment]
it was notes for myself, will release 2.105.18 later today, then we can try again

**Comment by larshp** [comment]
@oblomov-dev try again, latest version

![image](https://github.com/abaplint/abaplint/assets/5888506/4136ae72-d52f-45b6-bd11-b084aaa2b2e1)

**Comment by oblomov-dev** [comment]
Looks good also on my side now:
<img width="800" alt="image" src="https://github.com/abaplint/abaplint/assets/102328295/01f34167-cef2-484b-8d5d-5781236e0c7c">

Thank you!

But it seems that abap2UI5-samples does not see the abap2UI5 repository, get these issues when downporting, because types can not be found:
<img width="800" alt="image" src="https://github.com/abaplint/abaplint/assets/102328295/cdb23107-ca38-4049-b7dd-c2bda10ffaf3">

Set up the dependency here:
<img width="955600" alt="image" src="https://github.com/abaplint/abaplint/assets/102328295/2b777c57-ead8-4bd6-929b-dff04f5490af">
<img width="600" alt="image" src="https://github.com/abaplint/abaplint/assets/102328295/8998cb4e-3fc9-470c-8694-3435f59179af">
But yes maybe this problem does not belong to this issue here. so we can close this one for now.
