### ISSUE TITLE
wrong finding, variable not used

### ISSUE THREAD

**Issue by oblomov-dev** [abaplint/abaplint#3236]
found this in a more complex situation but simplified and reproduced as:
```abap
REPORT zfoobar.

CLASS lcl DEFINITION.
  PUBLIC SECTION.
    METHODS my_method.
ENDCLASS.

CLASS lcl IMPLEMENTATION.

  METHOD my_method.

    DATA(lt_tab) = VALUE string_table( ).

    LOOP AT lt_tab REFERENCE INTO DATA(lr_row).

      DATA(lv_test) = COND #( WHEN `test` = `test` THEN `test` ) && lr_row->*.

    ENDLOOP.

  ENDMETHOD.
ENDCLASS.
```

Seems when the row is behind && abaplint does not see that it is used inside the loop:
<img width="896" alt="image" src="https://github.com/abaplint/abaplint/assets/102328295/66487db4-23b5-4b3f-be10-7aa68c59c32e">

**Comment by larshp** [comment]
```abap
CLASS lcl DEFINITION.
  PUBLIC SECTION.
    METHODS my_method.
ENDCLASS.

CLASS lcl IMPLEMENTATION.

  METHOD my_method.
    DATA(lt_tab) = VALUE string_table( ).
    LOOP AT lt_tab REFERENCE INTO DATA(lr_row).
      DATA(lv_test) = COND #( WHEN `test` = `test` THEN `test` ) && lr_row->*.
      WRITE lv_test.
    ENDLOOP.
  ENDMETHOD.
ENDCLASS.
```

**Comment by larshp** [comment]
@oblomov-dev try again, 2.105.18 published

**Comment by oblomov-dev** [comment]
i mean this bug is completely not crucial, because I can do a workaround easily, but my quick check says that it is still there:
https://github.com/abap2UI5/abap2UI5/runs/21699445112
Code Position:
https://github.com/abap2UI5/abap2UI5/blob/1875e1826d7e96170ef12162b5b9b351674ffa71/src/01/02/01/z2ui5_cl_core_dissolve_srv.clas.abap#L119

**Comment by larshp** [comment]
@oblomov-dev try again, abaplint.app updated to latest abaplint
