### ISSUE TITLE
JUnit format issues when checking naming for field-symbols

### ISSUE THREAD

**Issue by fidley** [abaplint/abaplint#3250]
Not sure why it happens as in the code it seems to be escaped for '<' and '>'. But seems it does not work as the failure message attribute contains still <>.

![image](https://github.com/abaplint/abaplint/assets/7912195/2cb90857-716a-425b-9b49-849607f9300b)

https://github.com/abaplint/abaplint/blob/352cd63c02bef6da20f736246feda8514dd2b82b/packages/cli/src/formatters/junit.ts#L44C1-L44C15

**Comment by fidley** [comment]
I know I can deactivate the rule and this will be a workaround for me, but would be nice  to correct this small problem. I'd do myself but I have no clue about TS .

**Comment by larshp** [comment]
Hi, I recommend using https://github.com/marketplace/abaplint it works out of the box

**Comment by fidley** [comment]
Not possible for me, but I think I know what the issue is. I'm almost sure it replace only the first finding and you have < and > two times in the message, once in the patter and once in the FS name. Not sure if you have replaceAll in TS :)

**Comment by fidley** [comment]
according to google something like this should make it work :)
`  private formatFailureMessage(message: string): string {
    const reg_lt = </gm;
    const reg_gt = >/gm; 
    return message.replace(reg_lt, "").replace(reg_gt, "");
  }`

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/issues/2582

https://github.com/abaplint/abaplint/issues/2833

**Comment by larshp** [comment]
@fidley thanks for your contributions to the open source community, I'll have a look at this issue, hopefully later today

**Comment by fidley** [comment]
Thanks @larshp , really appreciating it and your work for the community !

**Comment by larshp** [comment]
@fidley try again, 2.105.23 published

**Comment by fidley** [comment]
Works good, no more issue. 
![image](https://github.com/abaplint/abaplint/assets/7912195/356bef98-f430-49c7-83bb-cd31f183cdc9)

Thanks a lot!
