### ISSUE TITLE
unused_methods - supress by pseudo comment

### ISSUE THREAD

**Issue by DGRHicron** [abaplint/abaplint#3276]
According to https://github.com/abaplint/abaplint/issues/1847, the rule `unused_methods` should also support pseudo comment `"#EC CALLED`. Seems like this has been forgotten.

**Comment by larshp** [comment]
try pragma `##CALLED`?

**Comment by DGRHicron** [comment]
@larshp, I wouldn't raise an issue if that was the solution 😉 
For systems older than 740 pragmas are not possible, right?
