### ISSUE TITLE
Some issues while renaming abap2UI5 from `z2ui5` to `z3ui5`

### ISSUE THREAD

**Issue by christianguenter2** [abaplint/abaplint#3291]
I tried to use abaplint to automagically rename [abap2UI5](https://github.com/abap2UI5/abap2UI5) into our namespace. In that process some issues arised and luckily I'm able to reproduce them in a public [demo repo](https://github.com/christianguenter2/demo_rename).

In this repo I setup abaplint to rename `z2ui5` to `z3ui5`. I'm not sure whether I did everything right, but at least I got some results with this configuration:
https://github.com/christianguenter2/demo_rename/blob/main/abaplint_rename.json#L13-L22
and these scripts
https://github.com/christianguenter2/demo_rename/blob/main/package.json#L14-L18
and running `npm run mirror`.

But it seems that some occurrences of classes and interfaces aren't renamed properly. I'm not sure whether these are known issues or not or if I did something wrong.

That's what `SYNTAX_CHECK` shows after I installed the repo into NW 752 dev.
![grafik](https://github.com/abaplint/abaplint/assets/17437789/5bffed6e-fe89-45dd-a262-11772f99c4b6)
![grafik](https://github.com/abaplint/abaplint/assets/17437789/fd29e9a6-6b89-4c02-bb86-fc5d4aed8cd7)

**Comment by larshp** [comment]
first bugfix in https://github.com/abaplint/abaplint/pull/3290, there might be more bugs tho

**Comment by larshp** [comment]
@christianguenter2 update to latest and try again

![image](https://github.com/abaplint/abaplint/assets/5888506/4038ae1d-3bac-45fb-af6f-37a14669850c)

**Comment by christianguenter2** [comment]
Amazing! Thx a lot.
![grafik](https://github.com/abaplint/abaplint/assets/17437789/47866383-1986-4fcc-a79f-7acd63e5d3fd)

**Comment by christianguenter2** [comment]
One static reference left to rename
https://github.com/christianguenter2/demo_rename/blob/03479fdece6d09f23f71bcf66696f705a47e629f/src/01/02/z3ui5_cl_core_app.clas.abap#L150

And for this I think we need search and replace?
https://github.com/christianguenter2/demo_rename/blob/03479fdece6d09f23f71bcf66696f705a47e629f/src/01/03/z3ui5_cl_core_app_search.clas.abap#L349

**Comment by larshp** [comment]
search and replace: I'd recommend trying to refactor the code so it doesnt have magic constants

`DATA foo TYPE REF TO Z2UI5_IF_APP.` then use RTTI to get the absolute name for the type of foo

**Comment by larshp** [comment]
@christianguenter2 update to latest and try again, 

![image](https://github.com/abaplint/abaplint/assets/5888506/773fae89-c31a-4b75-8687-9626817171cb)

**Comment by christianguenter2** [comment]
One unit test is failing, but that is also due to hard coded text.
![grafik](https://github.com/abaplint/abaplint/assets/17437789/2f063ce3-e0f5-458f-931f-a8d961f26026)

**Comment by oblomov-dev** [comment]
the first bugs are fixed now: https://github.com/abap2UI5/abap2UI5/pull/1078

**Comment by larshp** [comment]
this is running, so closing
