### ISSUE TITLE
Fix All fixes all issues instead of just all issues of this type

### ISSUE THREAD

**Issue by cawoodmonads** [abaplint/abaplint#3331]
When selecting quick fix -> Fix all omit_parameter_name I would expect it to fix all issues of this type. 

![image](https://github.com/abaplint/abaplint/assets/163100156/3f9edc10-e271-4ec5-a73b-0e409eeb78ff)

However it fixes all issues of any type i.e. line 38 (commented_code) is deleted as well!
![image](https://github.com/abaplint/abaplint/assets/163100156/48e2f625-a018-45e4-8b60-b2e1a32e157e)

**Comment by larshp** [comment]
I have been messing with this recently, can you check if "Experimental formatting" is enabled? It auto fixes everything automatically, which might cause problems if there is a lot of issues in the starting file

![image](https://github.com/abaplint/abaplint/assets/5888506/bdf6f3c7-7d33-4cd2-ae0e-8c06cd66f84e)

**Comment by cawoodmonads** [comment]
This is not enabled in my setup:
![image](https://github.com/abaplint/abaplint/assets/163100156/20e24cfb-b2cc-49db-8f66-2fab03eb2f0f)

**Comment by larshp** [comment]
reproduced with following code on https://playground.abaplint.org

```abap
CLASS lcl DEFINITION.
  PUBLIC SECTION.
    METHODS foo IMPORTING val TYPE i.
ENDCLASS.

CLASS lcl IMPLEMENTATION.

  METHOD foo.
    DATA unused TYPE i.

    foo( val = 2 ).
    foo( val = 3 ).
  ENDMETHOD.

ENDCLASS.
```

**Comment by larshp** [comment]
:hides: perhaps it has never worked, it didnt check the issue type

**Comment by larshp** [comment]
try again, new version of vscode extension = v0.6.389 published

**Comment by cawoodmonads** [comment]
Thanks, it works fine now!
