### ISSUE TITLE
7.50 syntax check - dereferencing a reference in a method call on 7.50 not found

### ISSUE THREAD

**Issue by oblomov-dev** [abaplint/abaplint#3336]
On ABAP Dev 2022 this works fine:
```
DATA foo TYPE REF TO data.
my_object->meth( foo->* ).
```
But it is not found when abaplint checks for 7.50 syntax:
https://github.com/abap2UI5/abap2UI5/issues/1168

**Comment by larshp** [comment]
do you know from which ABAP version this is allowed?

**Comment by oblomov-dev** [comment]
unfortunately not exactly, switched from ABAP Dev Edition 7.52 (there it does not work) to ABAP Cloud 2022 (there it works), so somewhere in between this two releases.

maybe we can make it more exact:
https://github.com/abap2UI5/abap2UI5/issues/1168

**Comment by choper725** [comment]
on 7.52 it doesnt work

**Comment by larshp** [comment]
https://github.com/abap2UI5/abap2UI5/pull/1246

**Comment by larshp** [comment]
https://github.com/abapGit/abapGit/pull/6984

**Comment by mbtools** [comment]
I think this is it:

https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abennews-756-dref.htm

**Comment by larshp** [comment]
merged, closing

**Comment by oblomov-dev** [comment]
Nice, thank you! Now is working with abap dev 2022 edition even more fun :)
