### ISSUE TITLE
ADT doesn't indent selection screen blocks

### ISSUE THREAD

**Issue by pokrakam** [abaplint/abaplint#3349]
abaplint expects: 
```abap
SELECTION-SCREEN BEGIN OF BLOCK b.
  PARAMETERS p_foo TYPE string.
  PARAMETERS p_bar TYPE string.
SELECTION-SCREEN END OF BLOCK b.
```
Unfortunately ADT pretty printer will reformat it to
```abap
SELECTION-SCREEN BEGIN OF BLOCK b.
PARAMETERS p_foo TYPE string.
PARAMETERS p_bar TYPE string.
SELECTION-SCREEN END OF BLOCK b.
```
abaplint is the better formatting, but it means manually rearranging after every `<shift>-<f1>`. It would be better if this check could be switched off separately from other indenting.

**Comment by larshp** [comment]
check the configuration, https://rules.abaplint.org/indentation/, `selectionScreenBlockIndentation`

on some versions the built-in pretty printer does indentation for select blocks
