### ISSUE TITLE
CDS Parser - extend view

### ISSUE THREAD

**Issue by DGRHicron** [abaplint/abaplint#3381]
If I'm not mistaken, the CDS Parser doesn't support _Extend view_ yet. Is it in the near future work scope?

**Comment by larshp** [comment]
can you help by providing a code example?

**Comment by larshp** [comment]
are these DDLX or DDLS objects?

**Comment by DGRHicron** [comment]
> can you help by providing a code example?

Sure, but I have a very basic one.

```
@AbapCatalog.sqlViewAppendName: 'ZESLSDCITM'
@EndUserText.label: 'Sales document item addit. fields'
extend view I_SalesDocumentItem with ZE_SalesDocItem
  {
    vbkd.bstdk as PurchaseOrderByCustomerDate,
    vbak.bstnk as PurchaseOrderByCustomer2
  }
```

**Comment by larshp** [comment]
@DGRHicron try again, 2.112.8

**Comment by DGRHicron** [comment]
No issues now. Thanks!
