### ISSUE TITLE
Provide inlay hints for inline data declarations

### ISSUE THREAD

**Issue by marcellourbani** [abaplint/abaplint#3428]
This is for abaplint/vscode-abaplint/issues/146

**Comment by marcellourbani** [comment]
The naive way of doing this is adding value assignment to the inlay filter, but in the references we don't distinguish declarations from assignments, so we have a  questionable side effect:

![image](https://github.com/user-attachments/assets/5f6fb179-92e5-440b-98c6-8cad9eed4ce3)

Not sure if it's a bug or a feature :P 
The best way I found to check this is by only keeping the DataWriteReference references if their token matches a  VARS declaration, and it's quite clunky to check

**Comment by larshp** [comment]
I think its fine for now, I typically switch the inlay hints off, and then use the keyboard shortcut for showing them if needed

**Comment by marcellourbani** [comment]
here's the results catalog from current tests: 
![image](https://github.com/user-attachments/assets/4fab63c9-7f13-4f33-bed0-6b0ce36b0c6d)
