### ISSUE TITLE
Downport -> `|{ x ALPHA = IN }|` having some trouble? 

### ISSUE THREAD

**Issue by HOUNDmx** [abaplint/abaplint#3438]
abaplint version 2.110.1 .
Might be related to #3007 ? 🤔 

Given:

```abap 
DATA(objname) = CONV tdobname( |{ sy-mandt }{ iv_aufnr ALPHA = IN }| ) 
```
`tdobname` being CHAR70.
`iv_aufnr` being type `afko-aufnr`, CHAR12.

Downport output is: 

```abap
DATA temp5 TYPE tdobname.
temp5 = |{ sy-mandt }{ iv_aufnr ALPHA = IN }|.
DATA lv_name LIKE temp5.
lv_name = temp5.
```

Second line being flagged as non-existing statement in open-abap by abaplint:
![image](https://github.com/user-attachments/assets/87ed886a-0f3b-471e-920f-720d40951e06)

**Comment by larshp** [comment]
reproduced as

```abap
TYPES ty_char TYPE c LENGTH 24.
DATA iv_aufnr TYPE c LENGTH 12.
DATA temp1 TYPE ty_char.
temp1 = |{ sy-mandt }{ iv_aufnr ALPHA = IN }|.
DATA objname LIKE temp1.
objname = temp1.
```

**Comment by larshp** [comment]
@HOUNDmx try again, 2.113.25 published

**Comment by HOUNDmx** [comment]
Working now, thanks for the fast hand! 😄 
might be ready to close
