### ISSUE TITLE
METHODS ... FOR TABLE FUNCTION does not allow namespace character "/"

### ISSUE THREAD

**Issue by jkadw** [abaplint/abaplint#3485]
In packages/core/src/abap/2_statements/statements/method_def.ts  the table function name is represented by regex /^\w+?$/. This does not take into consideration that the function name can be part of a namespace, e.g. /ABC/CL_CLASSNAME.

The regex should be changed to /^[\w\/]+?$/.

Regards,
   Jan

**Comment by larshp** [comment]
thanks, can you help providing a full statement, which I can add to the unit tests? dummy names are okay

**Comment by jkadw** [comment]
Please keep in mind that this example might show other linter errors according to this issue: [https://github.com/abaplint/abaplint/issues/3486](https://github.com/abaplint/abaplint/issues/3486)

**Comment by larshp** [comment]
@jkadw try again, 2.113.68 published

**Comment by larshp** [comment]
closing, no reply
