### ISSUE TITLE
Flow logic

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#3492]
Ref https://github.com/abapGit/abapGit/pull/7066 

When splitting it into separate files, I didn't take abaplint into consideration. I can exclude these with `.prog.screen.*.abap` but it would be nice to check the ABAP because usually there's more code than my example:

![image](https://github.com/user-attachments/assets/657e7012-0f28-4eaa-ac19-937410af33bd)

https://github.com/Marc-Bernard-Tools/MBT-Logical-Object-Lister/pull/4/files

**Comment by larshp** [comment]
yea, I need to get it done sometime soon

also see #3477

**Comment by mbtools** [comment]
Thx. Closing in fav of #3477

**Comment by larshp** [comment]
@mbtools try again, latest version

**Comment by mbtools** [comment]
It worked. Excellent!
