### ISSUE TITLE
Downport doesn't remove all SQL commas

### ISSUE THREAD

**Issue by pokrakam** [abaplint/abaplint#3501]
Downporting an SQL with a field list is fine, but if another list is added such as an `order by` clause, the commas remain causing a syntax error. This may be a distant cousin of #2902 
Example: 
```abap
    SELECT devclass, object, obj_name 
      FROM tadir
      INTO TABLE @DATA(itab)
      WHERE object = 'PROG'.
```
Downport OK:
```abap
    SELECT devclass object obj_name
      FROM tadir
      INTO TABLE itab
      WHERE object = 'PROG'.
```
But add a clause with commas (I'm guessing `group by` and such may do same): 
```abap
    SELECT devclass, object, obj_name
      FROM tadir
      INTO TABLE @DATA(itab)
      WHERE object = 'PROG'
      ORDER BY devclass, object.
```
Downport has a syntax error:
```abap
    SELECT devclass object obj_name
      FROM tadir
      INTO TABLE itab
      WHERE object = 'PROG'
      ORDER BY devclass, object.
```

**Comment by larshp** [comment]
@pokrakam try again, latest version

**Comment by pokrakam** [comment]
It does what's needed, but now I get an error `The elements in the "SELECT LIST" list must be separated using commas.` on 7.58. Argh! I think we're good to close this and I can raise another one just to keep things separate.

**Comment by pokrakam** [comment]
Just for completion: the subsequent error was due to unrelated issue #3505
