### ISSUE TITLE
dynpro checks: statement syntax

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#3510]
`MODULE` and `FIELD` need some updates:

- `MODULE ... AT ... ON ... SWITCH`

https://syntax.abaplint.org/?filter=module#/abap/statement/Module
https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=dynpmodule.htm

- `FIELD ... ON *-INPUT ... ON CHAIN-... AT CURSOR-SELECTION`

https://syntax.abaplint.org/?filter=field#/abap/statement/Field
https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=dynpfield_module.htm

There's also a `FIELD ... VALUES (BETWEEN x AND y).` which seems to be undocumented (copy from SAP code) 🤷 

![image](https://github.com/user-attachments/assets/11bfa23b-6a8d-4ca5-8b99-a944b7e779cd)

**Comment by larshp** [comment]
I've added a few bits, but it helps if you can add examples, then I'll add those to the unit tests, SAP help is messed up

**Comment by larshp** [comment]
screen example added to playground, 
![image](https://github.com/user-attachments/assets/4af1d2b7-378c-4db7-a2a9-04f0f7d9a6db)

**Comment by mbtools** [comment]
```abap
PROCESS BEFORE OUTPUT.
  MODULE pbo_1001.

PROCESS AFTER INPUT.
  MODULE pai_exit AT EXIT-COMMAND.
  FIELD trc_level VALUES (BETWEEN '0' AND '3').
```

```
/zfoo.prog.screen_0100.abap[5, 3]: Statement does not exist in ABAPv758(or a parser error), "MODULE"(parser_error)
/zfoo.prog.screen_0100.abap[6, 3]: Statement does not exist in ABAPv758(or a parser error), "FIELD"(parser_error)
```

**Comment by larshp** [comment]
@mbtools try again, 2.113.85 published
