### ISSUE TITLE
local class naming for exceptions

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint#400]
Got this message
```
src/zmockup_loader_switch_source.prog.abap[44, 7]     - Local class naming, expected ^LCL_.*$
```
On this
```
class lcx_error definition
  inheriting from cx_static_check ...
```
Is there any proper workaround except renaming the exception class ?

**Comment by larshp** [comment]
for now suggest allowing `^LC(X|L)_.*`

**Comment by sbcgua** [comment]
indeed, maybe the fastest way. Thanks !

**Comment by larshp** [comment]
but there should be an option for local exception classes
