### ISSUE TITLE
Parser errors on +=, -=...

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#458]
This kind of arithmetic causes parser errors:

`level += 1.`

**Comment by larshp** [comment]
should work on Cloud language version,
https://syntax.abaplint.org/?filter=move#/statement/Move

**Comment by FreHu** [comment]
Is Cloud supposed to be Cloud ABAP or S4HANA Cloud?

**Comment by larshp** [comment]
try again, version 1.7.11 released, set language version to v755
