### ISSUE TITLE
Parser error(Unknown statement)

### ISSUE THREAD

**Issue by flaiker** [abaplint/abaplint#466]
I enabled abaplint for a new repo... sorry in advance

Parser error(Unknown statement), ABAP version v740sp08
```abap
ls_extension = CORRESPONDING #( ls_line_item MAPPING /abc/comp_a = comp_a
                                                     /abc/comp_b = comp_b
                                                     /abc/comp_c = comp_c ).
```

Parser error(Unknown statement), ABAP version v740sp08
```abap
MODIFY /abc/tablea FROM @is_tablea.
```

Parser error(Unknown statement), ABAP version v740sp08
```abap
MODIFY /abc/tableb FROM TABLE @it_tableb.
```

Parser error(Unknown statement), ABAP version v740sp08
```abap
BEGIN_DATA OBJECT. " Do not change.. DATA is generated
```

Parser error(Unknown statement), ABAP version v740sp08
```abap
END_DATA OBJECT. " Do not change.. DATA is generated
```

I assume the first 3 errors are because of the namespace.

The other ones are classic business objects with macros. I can easily add these few objects to the ignore list so they are not really a problem to me.

**Comment by larshp** [comment]
more testing is good 😄 

yea, the last 2 is macros, so its difficult

**Comment by larshp** [comment]
first 3 fixed in https://github.com/abaplint/abaplint/commit/92e665a358ad0aa3b9f89b8cf729090cfb6d4ff6, I will publish a new version tomorrow

**Comment by larshp** [comment]
try again, 1.7.18 released

**Comment by larshp** [comment]
the globalMacros feature moved to https://github.com/abaplint/abaplint/issues/467

closing, other stuff fixed(?)

**Comment by flaiker** [comment]
Thanks! I'll restart the pipeline tomorrow and report back.

By the way: Is there a smart way to manage the abaplint.json across multiple repositories? Currently it's a bit painful for me to update 10+ repositories each time there is a new config option. And of course the exclude blocks are repo specific while the rule settings _should_ be in sync in this case.

**Comment by larshp** [comment]
minimize the use of exclude, this will make it eaiser

feel free open issues for false postives and suggestions to avoid excludes

**Comment by flaiker** [comment]
It's fixed!
