### ISSUE TITLE
Parser error - assignment beginning with CAST

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#470]
Lines like this cause parser errors:

`CAST cl_class( x->y->z )->property-component  = cl_other_class=>constant.`

**Comment by larshp** [comment]
CAST on the left side, nice

**Comment by FreHu** [comment]
Also possible with NEW

**Comment by larshp** [comment]
hmm, but it must have a property, ie. `NEW zcl_foo( )->prop = bar.` ?

**Comment by FreHu** [comment]
yeah

**Comment by larshp** [comment]
try again, 1.7.19 published
