### ISSUE TITLE
Errors from test include are reported at the end of main class

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#472]
After fixing the errors in the in the include, they don't go away instantly from the main class. You also need to change the main class and save.

They are also reported in the test include, so they shouldn't be here as well.

![image](https://user-images.githubusercontent.com/5097067/62784900-cb123a00-babf-11e9-92d2-bb31f8b000d6.png)

**Comment by larshp** [comment]
I cannot reproduce this, are you running the latest version? Or something special like https://marketplace.visualstudio.com/items?itemName=murbani.vscode-abap-remote-fs ?

**Comment by larshp** [comment]
think it has something to do with some exceptions that are thrown

**Comment by FreHu** [comment]
Latest version, looking at local files serialized with abapgit, using the vscode extension.

**Comment by larshp** [comment]
will try releasing a new version later today

**Comment by FreHu** [comment]
but i checked my jenkins build and it also reports the errors. this one should be up to date as it's doing npm install abaplint every time

**Comment by larshp** [comment]
does the jenkins build also report errors for the wrong files?

**Comment by FreHu** [comment]
Actually no, I seem to be blind. Jenkins is correct, vscode isn't. Let's try with the updated extension

**Comment by larshp** [comment]
try again, new vscode extension released

**Comment by larshp** [comment]
fixed in vscode extension 0.2.27

**Comment by FreHu** [comment]
It's working, nice!
