### ISSUE TITLE
Naming local class incorrectly will report a problem with global class name as well

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#473]
If I have a local class which fails the check `CLASS cl_unit_test DEFINITION FOR TESTING` 
then the global class name will get reported as a failure incorrectly
![image](https://user-images.githubusercontent.com/5097067/62785173-65727d80-bac0-11e9-8bf6-72aa6d650f24.png)

**Comment by larshp** [comment]
guess this is connected to https://github.com/abaplint/abaplint/issues/472

**Comment by FreHu** [comment]
Working now as well, closing.
