### ISSUE TITLE
generate json schema for configuration file

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#487]

**Comment by larshp** [comment]
looks like there are multiple options:
https://github.com/vega/ts-json-schema-generator
https://github.com/YousefED/typescript-json-schema

**Comment by larshp** [comment]
and then add to the abaplint vscode extension, https://code.visualstudio.com/api/references/contribution-points#contributes.jsonValidation

**Comment by larshp** [comment]
auto generate and put in git, add one schema per version of abaplint?

**Comment by FreHu** [comment]
You only need to version if you add or change a rule.

**Comment by larshp** [comment]
I do that all the time 😁

**Comment by larshp** [comment]
something like this? I've not tested the JsDoc support

![image](https://user-images.githubusercontent.com/5888506/63154890-dc080180-c011-11e9-9d53-bd7200a8ef1e.png)

**Comment by FreHu** [comment]
That should work. There is a description field on each object in the schema you can fill.

**Comment by larshp** [comment]
used https://github.com/vega/ts-json-schema-generator, I guess the description can be added to the json spec by having JsDoc annotations in the code, but have not tested it

**Comment by larshp** [comment]
jsdoc also works, 
![image](https://user-images.githubusercontent.com/5888506/63419755-a1350d80-c405-11e9-8f72-800cf9f59b28.png)

**Comment by larshp** [comment]
run with `npm run schema`

todo: setup CI, via new GitHub actions?

**Comment by FreHu** [comment]
Nice, I will contribute some docstrings

**Comment by larshp** [comment]
now automatically pushed to https://schema.abaplint.org/schema.json from master, using GitHub Actions, closing
