### ISSUE TITLE
New rule: no empty methods

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#488]
I think this rule about empty teardown can be extended to the other methods as well:

https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#dont-add-a-teardown-unless-you-really-need-it

**Comment by FreHu** [comment]
Actually, no empty methods at all. We have the same check in the S4HANA pilot. You mark an intentionally empty method with a `RETURN.`

**Comment by g-back** [comment]
I'll take a crack at this one.

**Comment by larshp** [comment]
into method_length: yes, think it would be nice
