### ISSUE TITLE
New cases for avoid_use

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#489]
https://github.com/SAP/styleguides/blob/master/clean-abap/CleanABAP.md#avoid-default-key

the breakpoint rule can be merged into this rule

**Comment by larshp** [comment]
yea, I also have this in abapOpenChecks, https://docs.abapopenchecks.org/checks/48/

Sometimes I end up adding DEFAULT KEY for internal tables during function module calls

**Comment by g-back** [comment]
Working on this - can I actually just delete the `breakpoint` rule and merge it into `avoid_use`? It's simple enough, but is there anything I have to consider?
