### ISSUE TITLE
support for APACK dependencies

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#491]

**Comment by larshp** [comment]
current workaround: manually add the git repos under `dependencies`

**Comment by FreHu** [comment]
- Add config option to use apack dependencies
- If apack manifest is present, extract repo links from here as well:
https://github.com/SAP-samples/abap-platform-jak/blob/c51f630dc78cc2d67c5aca3b660736eab3d5d099/.apack-manifest.xml#L14

**Comment by larshp** [comment]
suggest it to be on by default
