### ISSUE TITLE
abaplint.json and defaults

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint#500]
Seems like set of rules is applied even if a limited set defined in abaplint.json.

I mean I have a abaplint.json with several explicit rules with, say, does not include `avoid_use`. And still `avoid_use` is applied. This is unexpected.

Would be nice to have this logic:
1. if no rules specified - use default set
2. if rules specified - use just them
3. probably it would be good to have a template set like in eslint and then re-define specific rules. So that I define in abaplint.json that I want to use "default set" but certain rules are redefined in addition.

**Comment by larshp** [comment]
what is the value of `applyUnspecifiedRules` in your example? https://github.com/larshp/abapGit/blob/master/abaplint.json#L7

**Comment by sbcgua** [comment]
you're right, I forgot about this feature. Sorry. 
Closing.
