### ISSUE TITLE
abaplint.json, allow comments, jsonc? json5? yaml?

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#507]
?

https://www.npmjs.com/package/jsonc-parser

**Comment by larshp** [comment]
not needed, the reason field added for free text, closing

**Comment by larshp** [comment]
or json5, but it has a strong dependency to minimist, https://github.com/json5/json5/issues/205

**Comment by sbcgua** [comment]
or JSON5 - https://github.com/json5/json5

Quick comaparison:

- weekly downloads: json5 = 23m (!), jsonc = 311k
- dependencies: json5 = 1 (minimist), jsonc = 0
- licence - both MIT
- features:
  - json5 supports additional features, most relevant (imho) are: allow trailing commas in array and obj, allow attribute names without quotes (less useful, but nice)
- performance: unknown, but probably not relevant for the task

**Comment by sbcgua** [comment]
or/and YAML: https://www.npmjs.com/package/js-yaml

which would be very convenient but potentially increase doc maintenance

**Comment by larshp** [comment]
I think JSON5 or JSONc would be okay, just make sure the browser stuff still works if minimist is added as dependency to core

**Comment by larshp** [comment]
hmm, there is something strange happening when webpack'ing the cli,

![image](https://user-images.githubusercontent.com/5888506/87218793-4fb3ab00-c356-11ea-8a7b-06e64f5663d9.png)

**Comment by larshp** [comment]
added in cli:

```
  // evil hack to get JSON5 working
  // @ts-ignore
  JSON5.parse = JSON5.default.parse;
  // @ts-ignore
  JSON5.stringify = JSON5.default.stringify;
```
