### ISSUE TITLE
Respect pragmas in abap code

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#512]
Some checks might overlap with existing or new backend checks which can be suppressed by pragmas. If I run abaplint, it will report these suppressed errors again as exclusions work differently here.

For compatibility we need
- a general mechanism for pragma-based suppression
- a list of overlapping checks and their pragmas

**Comment by larshp** [comment]
call new method `getPragmas` on `StatementNode` to get pragmas

**Comment by larshp** [comment]
@FreHu any specific rules in mind? If not I think we can close the issue and open issues for each case

**Comment by FreHu** [comment]
Yeah, I forgot what this was about.
