### ISSUE TITLE
skipGeneratedGatewayClasses does not work anymore with partner namespaces

### ISSUE THREAD

**Issue by flaiker** [abaplint/abaplint#513]
See https://github.com/flaiker/IWPR/runs/206481843

Results were as expected before renaming the classes https://github.com/flaiker/IWPR/runs/206030331

This did work on 1.7.23: https://travis-ci.com/flaiker/IWPR/builds/125022263

**Comment by larshp** [comment]
fixed in abaplint@2.0.1

**Comment by flaiker** [comment]
Thanks! I'll migrate to 2.0.1 on monday.

**Comment by flaiker** [comment]
It works!

**Comment by larshp** [comment]
this time I also added a real life unit test 😁
