### ISSUE TITLE
New playground

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#524]
new

**Comment by larshp** [comment]
hmm, Theia looks very flexible, with lots of dependency injection, but feels monolithic?


https://cdnjs.com/libraries/monaco-editor

**Comment by larshp** [comment]
follow progress at https://github.com/abaplint/playground_test

**Comment by larshp** [comment]
theme from https://microsoft.github.io/monaco-editor/monarch.html

**Comment by larshp** [comment]
some screenshots of "old" functions:
![image](https://user-images.githubusercontent.com/5888506/65382916-ce7b2100-dd0d-11e9-9ee0-4db047514c17.png)
![image](https://user-images.githubusercontent.com/5888506/65382919-d33fd500-dd0d-11e9-8e94-c29a085f016b.png)
![image](https://user-images.githubusercontent.com/5888506/65382921-d6d35c00-dd0d-11e9-8021-4f97276a784e.png)
![image](https://user-images.githubusercontent.com/5888506/65382922-da66e300-dd0d-11e9-8c30-a7df2bffb5b4.png)

**Comment by larshp** [comment]
move to webpack instead of the top level browserify?

**Comment by larshp** [comment]
* show version number on playground
* respond to changes in abaplint.json on playground
* navigate from file to editor
* navigate from problems to editor

**Comment by larshp** [comment]
add direct links to source code, both playground and abaplint itself

**Comment by FreHu** [comment]
Schema doesn't work, but it seems to be supported:
![image](https://user-images.githubusercontent.com/5097067/65409556-4289f780-dde8-11e9-9bc8-1c73961c4189.png)

https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-configure-json-defaults

**Comment by larshp** [comment]
yea, it might just get into some CORS issues, but it should be okay since its *.abaplint.org

**Comment by sbcgua** [comment]
comments (ctrl+/) does work properly - probably worth changing comment to `"`
![image](https://user-images.githubusercontent.com/15635498/65545868-f1305400-df1e-11e9-863b-5d4c27992346.png)

**Comment by larshp** [comment]
F1 help now with some "useful" information,
![image](https://user-images.githubusercontent.com/5888506/65660367-caf9d980-e02e-11e9-9879-67ac00bd4de3.png)

**Comment by larshp** [comment]
schema validation, see https://github.com/microsoft/monaco-editor/issues/365

**Comment by sbcgua** [comment]
F1: maybe change to another key? F1 is the alternative one-key for command palette (it did work - i tried). Which was quite convenient.

**Comment by larshp** [comment]
As an ABAP developer, apart from saving/editing/activating/checking, I think F1 is the shortcut I use the most. It doesnt really fit with vscode and all, and will probably end up making this a user setting.

**Comment by FreHu** [comment]
I can only get the validation to work if I both copy the schema and link to it in the abaplint.json as well. Funnily enough, the schema does not specify that `$schema` is an allowed attribute in abaplint.json, which makes the file invalid :)

![image](https://user-images.githubusercontent.com/5097067/65682247-d662fa00-e05a-11e9-9e32-dd5c36085c72.png)

**Comment by larshp** [comment]
we just need to fetch the schema via http, might take a bit of startup time, but guess its okay

**Comment by larshp** [comment]
local testing: consider using https://webpack.js.org/configuration/dev-server/ https://github.com/webpack/webpack-dev-server instead of `local-web-server`

**Comment by larshp** [comment]
closing, moving stuff to https://github.com/abaplint/abaplint/issues/562 instead to get a overview
