### ISSUE TITLE
Release management

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint#533]
First thoughts:

Found a couple of articles on the subject. [This one](https://medium.com/@kevinkreuzer/the-way-to-fully-automated-releases-in-open-source-projects-44c015f38fd6) has a good overview.

Looks like there are 2 popular libraries to manage the process:
1. https://github.com/semantic-release/semantic-release
2. https://github.com/release-it/release-it

The first one look like more mainstream for CI releases. But also required more discipline and setup. Like separate branch for development and releases (master), conventional commits (e.g. feat(config): new format of config - would trigger automatic minor release on push to master)

The second one, although can do similar things completely detached, also provide a nice cli for a manual release, also pushing the tags and changelog and npm release.

Imho: release-it looks more flexible, semantic-release is for bigger projects with large teams

**Comment by sbcgua** [comment]
@larshp 

Made some drafts on auto docker build - [script](https://github.com/sbcgua/ci-js-versioning-test/blob/master/.github/workflows/docker.yml), [log](https://github.com/sbcgua/ci-js-versioning-test/runs/368140708)

But there are 2 points: 

- in order to publish the image there should be credentials. To the dockerhub. Would you add them to the secrets ? **OR** alternatively we can publish it to github registry (https://github.com/features/packages) which should be also fine since I don't think docker image is used a lot currently ... then the existing token may work if you granted package management within it. What do you think ?
- a more tricky point - how to trigger the build ? I mean that the true trigger event should be publishing to npm, and not on a new tag directly (like in the example). Options are: auto npm publishing on new tag **or**, if you always publish after version bump, the script can actually build abaplint from source ignoring the npm and `link` it. Any thoughts ?

**Comment by larshp** [comment]
I can add the secret, no problem

triggering build: 🤷‍♂

**Comment by sbcgua** [comment]
OK, I'll do some more test during the weekend then and open a PR. triggering the build ... I think probably I'll try to compile it right in the container without npm publishing ... let's have a look how this works

**Comment by larshp** [comment]
what does the docker container do? it can just do `npm install abaplint@new_tag_version` ?

**Comment by sbcgua** [comment]
yes ... but then it does not make much sense to use docker ... point is that all the dependencies are packed inside

**Comment by larshp** [comment]
no progress
