### ISSUE TITLE
Default rules format: boolean form

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint#534]
Following #528 and https://github.com/larshp/abapGit/pull/2915/files

It is imho of course but the following looks quite dirty for me:

```
    "7bit_ascii": { },
    "avoid_use": {
    },
    "short_case": {
      enabled: false,
    },
```

Why leave brackets ? As far as all inside is defaulted ? I'd propose pushing this a bit further to:

```
    "7bit_ascii": true,
    "avoid_use": false,
    "short_case": {
      enabled: false,
    },
```
the semantics would be much cleaner:
- "rule": false, means force disable (e.g. if global enable is set)
- "rule": true, means enable and accept default

Looking at https://github.com/larshp/abapGit/pull/2915/files - this would be the majority of a typical rule set

**Comment by larshp** [comment]
guess this can be closed?

**Comment by sbcgua** [comment]
yes, closing.
