### ISSUE TITLE
Report name wrong error

### ISSUE THREAD

**Issue by christianguenter2** [abaplint/abaplint#549]
Something seems odd here
![image](https://user-images.githubusercontent.com/17437789/65314790-470ba180-db97-11e9-973d-568a493173d5.png)
https://github.com/christianguenter2/test_hamburg/blob/master/src/ztest_hamburg.prog.abap

**Comment by larshp** [comment]
think its the error description, in this example it should say that "ZTEST_HAMBURG" should be lower case

**Comment by christianguenter2** [comment]
Right, and it's not a really keyword?

**Comment by larshp** [comment]
its not, the error message is misleading

**Comment by larshp** [comment]
try again, npm and vscode updated

**Comment by christianguenter2** [comment]
Looks good, thanks
![image](https://user-images.githubusercontent.com/17437789/65385197-f4afb980-dd2b-11e9-8f78-4e098b69a5a1.png)
