### ISSUE TITLE
Lowercase keyword 'type' not recognized

### ISSUE THREAD

**Issue by christianguenter2** [abaplint/abaplint#552]
![image](https://user-images.githubusercontent.com/17437789/65392535-4b41e580-dd76-11e9-8f88-cdec2dfbae14.png)

REPORT zfoobar.
WRITE 'Hello World'.

DATA: lt_foo type stringtab.

LOOP AT lt_foo ASSIGNING FIELD-SYMBOL(<ls_foo>).
  WRITE 'bar'.
ENDLOOP.

**Comment by larshp** [comment]
yea, hmm, but pretty printer(shift + F1) knows to upper case it

**Comment by larshp** [comment]
fixed in https://github.com/abaplint/abaplint/commit/7ba16c2a35622f2ad25abf266a536244947c83f9, I'll release a new version on Friday

**Comment by larshp** [comment]
2.1.4 released
