### ISSUE TITLE
Playground: Monarch bugs / highlighting

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#554]
These are gonna come up often:
![image](https://user-images.githubusercontent.com/5097067/65447926-ef3f9580-de37-11e9-9096-0038a3e514f5.png)

Backticks look like they are invalid characters:
![image](https://user-images.githubusercontent.com/5097067/65448003-19915300-de38-11e9-8495-10ae80fd1e09.png)

**Comment by larshp** [comment]
yea, lets collect the highlighting bugs here. I'm pretty sure there is also some issues regarding string templates, and nesting of string templates

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/65831695-f265d600-e2bc-11e9-8c0c-c651fdb43600.png)

**Comment by FreHu** [comment]
Not a bug, but migh as well add stuff from the vscode plugin's language configuration. Note that the autoclosing pairs `(` and `[` have an extra trailing space which makes them more abap friendly.

https://github.com/larshp/vscode-abap/pull/6

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/66389152-ffbf4680-e9c7-11e9-8eb2-4dd6d15cf9a1.png)

**Comment by larshp** [comment]
the "#",

![image](https://user-images.githubusercontent.com/5888506/66391968-d0600800-e9ce-11e9-8b66-11a698a2aa5e.png)

**Comment by larshp** [comment]
pragmas, 

![image](https://user-images.githubusercontent.com/5888506/66455618-93961e80-ea6b-11e9-8731-264958573586.png)

**Comment by larshp** [comment]
"PARTIALLY IMPLEMENTED", 

![image](https://user-images.githubusercontent.com/5888506/66891309-14639600-efe9-11e9-90b0-b379a9eda788.png)

**Comment by larshp** [comment]
"AND", "@",

![image](https://user-images.githubusercontent.com/5888506/67192639-39467780-f3f4-11e9-9960-2574f4a2e7d4.png)

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/67209827-5bea8780-f418-11e9-8569-82b7361b9021.png)

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/71617800-fe637b80-2bbc-11ea-9dce-62896bd09abd.png)

**Comment by mbtools** [comment]
CONSTANT
LOG-POINT

![image](https://user-images.githubusercontent.com/59966492/92520869-4aee6480-f1ea-11ea-92aa-337099660de2.png)

**Comment by mbtools** [comment]
Some more for a later time...

- Any term with hyphen like
- AT... VALUE-REQUEST
- DATA ... READ-ONLY
- SELECTION-SCREEN COMMENT, PUSHBUTTON
- RADIOBUTTON GROUP
- MEMORY
- SUBMIT ... VIA ... AND RETURN
- IF ... CA ... CP ... BETWEEN (+other C/Nx operators)
- IF ... NOT / OR / AND 
- SORT ... AS TEXT
- TYPE-POOLS
- METHOD ... PREFERRED PARAMETER
- WRITE ... AS ICON

![image](https://user-images.githubusercontent.com/59966492/92524987-0b774680-f1f1-11ea-8e7b-dca394f50725.png)

![image](https://user-images.githubusercontent.com/59966492/92525105-3f526c00-f1f1-11ea-9db5-c2babb338f5f.png)

![image](https://user-images.githubusercontent.com/59966492/92525143-4f6a4b80-f1f1-11ea-8372-423775c93131.png)

![image](https://user-images.githubusercontent.com/59966492/92525239-79237280-f1f1-11ea-9711-9502f998e3df.png)

![image](https://user-images.githubusercontent.com/59966492/92525383-bc7de100-f1f1-11ea-8853-c74fb8aa60bd.png)

![image](https://user-images.githubusercontent.com/59966492/92525584-1d0d1e00-f1f2-11ea-88fa-a3deeb77e5f8.png)

![image](https://user-images.githubusercontent.com/59966492/92525855-90af2b00-f1f2-11ea-9c38-f5c11c8662fd.png)

![image](https://user-images.githubusercontent.com/59966492/92525948-b5a39e00-f1f2-11ea-8624-d7161b414607.png)

![image](https://user-images.githubusercontent.com/59966492/92526003-c81dd780-f1f2-11ea-9682-aee757b47978.png)

**Comment by larshp** [comment]
@mbtools thanks, can you help moving the 2 above issues to https://github.com/abaplint/abaplint/issues/1292

when semantic highlighting is part of LSP, most of it should be fixed, the highlighiting is currently not context based, it just looks at words

**Comment by larshp** [comment]
🎉 https://www.npmjs.com/package/monaco-editor 0.21.0 published
