### ISSUE TITLE
"Report must begin with REPORT" when it is started with PROGRAM

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint#557]
![image](https://user-images.githubusercontent.com/15635498/65768697-57dd8980-e13a-11e9-9229-6fcb603b7dae.png)
![2019-09-24_23h00_59](https://user-images.githubusercontent.com/15635498/65768700-58762000-e13a-11e9-91ed-7db601e6ac0f.png)

**Comment by larshp** [comment]
abaplint@2.1.5 released
