### ISSUE TITLE
pretty printer adds newlines

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#564]
place cursor like this, and trigger pretty print multiple times, adds newlines

![image](https://user-images.githubusercontent.com/5888506/65953725-d8ef9600-e444-11e9-84a9-35f16034ab69.png)

**Comment by g-back** [comment]
I've tried to fix this (remove all trailing blank lines) - it works in the pretty-printer unit test but not in the playground. Is this a problem with the playground itself?

**Comment by larshp** [comment]
it might have been fixed in the recent pretty printer changes
