### ISSUE TITLE
Playground: abaplint.json schema validation

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#565]
See https://github.com/abaplint/abaplint/issues/524#issuecomment-534010186 @FreHu 

I guess $schema should be allowed no matter what the schema says, another example http://json.schemastore.org/coffeelint, need to find the json RFC/specification

The schema is not applied automatically, I think this is due to bad uri setup in the playground

**Comment by larshp** [comment]
same in just vscode,
![image](https://user-images.githubusercontent.com/5888506/66019791-0ab83980-e4e5-11e9-9f2e-e2e6ce118fce.png)

**Comment by FreHu** [comment]
https://github.com/json-schema/json-schema/issues/220 `$schema` is not allowed by default, it should be stated in the abaplint schema as one of the properties. It will also allow other editors to pick it up.

**Comment by larshp** [comment]
cool, we should add the "$schma" attribute to the generated schema then

**Comment by larshp** [comment]
here we go, now works on playground,
![image](https://user-images.githubusercontent.com/5888506/66021150-e4e16380-e4e9-11e9-8310-e2a6159de95e.png)

**Comment by larshp** [comment]
done, closing
