### ISSUE TITLE
prefixes

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#576]
@FreHu running the new code on abapGit gives so many errors that the terminal cannot really display it

https://github.com/abaplint/abaplint/pull/574

**Comment by larshp** [comment]
8344 issues, does patternKind default to the wrong value if it is not specified in the config?

**Comment by FreHu** [comment]
hmm, it's supposed to default to required which is the old behavior

**Comment by FreHu** [comment]
I think I found the bug, there needs to be a check for falsy `patternKind`
```typescript
    return params.patternKind === "required" ?
      pattern.test(name) === false :
      pattern.test(name) === true;
```
to
```typescript
    return !params.patternKind || params.patternKind === "required" ?
      pattern.test(name) === false :
      pattern.test(name) === true;
```
