### ISSUE TITLE
playground: changing abaplint.json has no effect

### ISSUE THREAD

**Issue by g-back** [abaplint/abaplint#584]
(tested with chrome and edge)

**Comment by larshp** [comment]
thanks

though it worked, but I've probably broken it again, started setting up some scaffolding for automatic testing last week 😄

**Comment by larshp** [comment]
![payconfig](https://user-images.githubusercontent.com/5888506/79112689-68281f80-7d7f-11ea-9f9e-37b721fd070b.gif)
