### ISSUE TITLE
abapdoc check: local classes and interfaces

### ISSUE THREAD

**Issue by g-back** [abaplint/abaplint#593]
Remove check for local classes and interfaces? Create a setting that regulates its requirement?
(Currently abapdoc is required for local classes and interfaces)

**Comment by larshp** [comment]
create a setting that regulates it, default to not require abapdoc for local classes

**Comment by larshp** [comment]
class_definition.ts have methods:   public isLocal(): public isGlobal(): 

Suggest we add similar methods in interface_definition.ts, the heuristic can be added in the method, note the filename was added yesterday, which can be used to determine if it is global

**Comment by larshp** [comment]
actually interfaces work the same way as classes, "INTERFACE zif_test PUBLIC."
