### ISSUE TITLE
New feature: pretty print multiple files

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#614]
Add a commandline option which would run the pretty printer on multiple files. This will allow you to reformat all your code at once. 

`abaplint -pretty_print [file_pattern]`(`-format` is already taken). , Take pattern from `abaplint.json` if not specified.

**Comment by larshp** [comment]
yea, would like to implement the feature

but on the other hand also keep the number of parameters small for the cli, a different approach could be adding multiple executeables, eg `abaplint-pretty`, but this is also not great

**Comment by FreHu** [comment]
so this is --fix, closing
