### ISSUE TITLE
754 adjustments

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#626]
special moves is 754
https://syntax.abaplint.org/?filter=move#/statement/Move
and add concat operator

https://help.sap.com/doc/abapdocu_754_index_htm/7.54/en-US/index.htm?file=abennews-754.htm

**Comment by FreHu** [comment]
Rename version to 754 in config?

**Comment by larshp** [comment]
yea

**Comment by larshp** [comment]
fixed in https://github.com/abaplint/abaplint/commit/73db565f40be3f375039f7f2a9708940eac32d3e
