### ISSUE TITLE
Pretty printer does not capitalize `like line of`

### ISSUE THREAD

**Issue by FreHu** [abaplint/abaplint#628]
Try running pretty printer on 
```abap
FIELD-SYMBOLS:
      <lv_file> like line of it_files.
```

the keywords will not be capitalized.

**Comment by larshp** [comment]
yea, most of the field-symbols syntax is todo, https://syntax.abaplint.org/?filter=field#/statement/FieldSymbol

**Comment by larshp** [comment]
fixing, but might run into some evil parser error bugs on the way, this is the only statement that had not had any attention

**Comment by larshp** [comment]
fixed in 2.9.1
