### ISSUE TITLE
Add possibility to run pretty printer from Eclipse/ADT

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#629]
this would be pretty easy, as its per file, and only requires the text

**Comment by AlexandreHT** [comment]
I have dreamed about this feature for some time now. Now I can't wait. Thanks in advance!

Alexandre

**Comment by larshp** [comment]
pull requests are welcome 😄 

The code is under https://github.com/abaplint/abaplint/tree/master/src/pretty_printer

and you can try it out in the https://playground.abaplint.org by pressing shift+F1

Tricky part here is making the ADT plugin and having it run under Nashorn(the Javascript engine in Java)

**Comment by larshp** [comment]
As suggested by FreHu on Slack, just run a local service on some port which then can be called by Eclipse?

**Comment by larshp** [comment]
alternatively run abaplint on the ABAP application server, https://github.com/larshp/abap-wasm

**Comment by larshp** [comment]
Nashorn will be deprecated, http://openjdk.java.net/jeps/335

**Comment by larshp** [comment]
see https://github.com/abaplint/abaplint-cloud-foundry and https://github.com/abaplint/abaplint-abap-backend

**Comment by larshp** [comment]
out of scope, closing
