### ISSUE TITLE
method_length rule: add exception for test classes

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint#631]
A proposal: maybe add a flag to disable the rule for test classes where there might be multiple case checks in a row so the method is long while the semantics is ok.

e.g. https://github.com/sbcgua/mockup_loader/blob/master/src/zcl_mockup_loader_stub_factory.clas.testclasses.abap#L188

**Comment by larshp** [comment]
yea 👍 configuration options are good

method length is not a super great measure, hoping to implement #387 and #287 sometime in the future
