### ISSUE TITLE
Error: Unknown object type: PNG (registry_add)

### ISSUE THREAD

**Issue by jrodriguez-rc** [abaplint/abaplint#651]
I'm checking a repository with a dependency and checks fails because in dependency repository there are a file that throw an error:
![image](https://user-images.githubusercontent.com/56556686/69568003-037c4c00-0fbb-11ea-9717-a9360e80b68f.png)

In original repository checks are executed without problem

**Comment by larshp** [comment]
yea, it looks like a bug, thanks

might have time to look at it tomorrow, it should categorize as a W3MI object

**Comment by larshp** [comment]
the example in https://github.com/abapGit-tests/W3MI/tree/master/src seems okay

**Comment by larshp** [comment]
See https://github.com/larshp/abapGit/issues/3092

**Comment by jrodriguez-rc** [comment]
It is right, name of file is BACKGROUND.PNG, I remove extension and it works

**Comment by larshp** [comment]
its the easiest fix if its possible for you, I'll probably change abapGit to throw an error if the name contains "."

**Comment by jrodriguez-rc** [comment]
To me has a easy solution, but could cause problems if someone needs to rename it and uses in many places

It seems that name in Git is not correctly built because for .data file is setting extension twice:
background**.png**.w3mi.data**.png**
It is correct?

**Comment by larshp** [comment]
the "data.png" is okay, see working example in https://github.com/abapGit-tests/W3MI/tree/master/src

just the characters after the first "." in the filename must be the object type

**Comment by larshp** [comment]
I guess this can be closed
