### ISSUE TITLE
add icons for abaplint.json and .abapgit.xml

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#668]
https://code.visualstudio.com/api/extension-guides/icon-theme

perhaps as part of the abap highlighting extension instead?

**Comment by sbcgua** [comment]
![image](https://user-images.githubusercontent.com/15635498/71170000-f4f41e00-2262-11ea-9837-6083fbcc8edb.png)

smaller scale for preview
![image](https://user-images.githubusercontent.com/15635498/71170024-02110d00-2263-11ea-9af4-d81c728d52b5.png)

in fact there is regular abap file too ... so may be not that easy

P.S. is there "official" abaplint image ?

**Comment by sbcgua** [comment]
hmm images are re-sampled on upload for some unknown reason ... attaching as zip
[code-icons.zip](https://github.com/abaplint/abaplint/files/3983340/code-icons.zip)

**Comment by sbcgua** [comment]
personally like 3.2 with probably different colors for abap file and .abapgit.xml. The rest would be cluttered in so small res.

The best is 2.1 but proportions are unfortunate. And 5.3 is cool imho but also in a larger res

**Comment by sbcgua** [comment]
Also nice option with mirroring ... mind the hidden arrows in the high res -the're cool ;)

![image](https://user-images.githubusercontent.com/15635498/71171026-72209280-2265-11ea-842e-34cda97d58d9.png)

![image](https://user-images.githubusercontent.com/15635498/71171035-777ddd00-2265-11ea-8c8c-dc617c91d20d.png)

**Comment by sbcgua** [comment]
![image](https://user-images.githubusercontent.com/15635498/71171620-e445a700-2266-11ea-8e8a-bda4eee5ca02.png)

End of creativity. :)

**Comment by larshp** [comment]
for `.abapgit.xml`, I guess this one will work
![image](https://user-images.githubusercontent.com/5888506/71176199-98483180-2269-11ea-968b-be5e30df9e28.png)

for `*.abap`, one of:
![image](https://user-images.githubusercontent.com/5888506/71176250-bb72e100-2269-11ea-9c15-51659541c06c.png)

for `abaplint.json` see https://github.com/abaplint/img, it might need a different colour to be visible

**Comment by sbcgua** [comment]
attached.

[svg-icons.zip](https://github.com/abaplint/abaplint/files/3992267/svg-icons.zip)

**Comment by larshp** [comment]
hmm, looks like it should go into https://github.com/jesseweed/seti-ui to go into the default theme

**Comment by larshp** [comment]
I dont think this is possible as of now, closing
