### ISSUE TITLE
PARAMETERS and SELECT-OPTIONS naming conventions

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#675]
default to 'p_' and 's_', so it matches abapOpenChecks,

![image](https://user-images.githubusercontent.com/5888506/70608214-0d7b8d00-1c00-11ea-80d9-abbd8d13d7dc.png)

**Comment by g-back** [comment]
duplicate of #358 ?
Also: should we also add a check for the length of the variable names here? As we all know and "appreciate" both can be a maximum of 8 chars.

**Comment by larshp** [comment]
yea, closing
