### ISSUE TITLE
Unknown object type: SFBF/SFSW/SHI8 (registry_add)

### ISSUE THREAD

**Issue by jrodriguez-rc** [abaplint/abaplint#684]
I have two projects, A and B, and I set A as dependency in abaplint config for B.

Project A has some object types (SFBF/SFSW/SHI8) that returns an error when abaplint is executed for B, but runs correctly for A:
![image](https://user-images.githubusercontent.com/56556686/71165722-a8ecad80-2251-11ea-96f8-39944c971f72.png)

**Comment by larshp** [comment]
then I'd guess there is something wrong in the setup for A

SFBF + SFBS + SFSW + SHI8 should give errors, as its not implemented yet

implementing....

**Comment by larshp** [comment]
try again, 2.17.0 released

**Comment by jrodriguez-rc** [comment]
Perfect now, thank you.
