### ISSUE TITLE
implement_methods for interfaces without methods

### ISSUE THREAD

**Issue by jrodriguez-rc** [abaplint/abaplint#690]
I'm creating BAdI implementations that have implemented interface IF_BADI_INTERFACE, but it hasn't any method.

An error is thrown by abaplint checks:
`./src/#rslt#cl_fb_ui5_base_address.clas.abap[1, 7]  - Implemented interface "IF_BADI_INTERFACE" not found (implement_methods)`

**Comment by larshp** [comment]
should go into https://github.com/abaplint/deps

or alternatively you can add your own dependencies

**Comment by larshp** [comment]
@jrodriguez-rc try again, added in https://github.com/abaplint/deps/commit/cae0356ae6cabc1edeed86ccc142c18f0d18bc13

**Comment by jrodriguez-rc** [comment]
No errors now, thank you
