### ISSUE TITLE
method_parameter_names in exceptions

### ISSUE THREAD

**Issue by jrodriguez-rc** [abaplint/abaplint#698]
I created an exception inherit from another own exception.

In abaplint config I set ignore exception for method_parameter_names, but it checks for that specific exception:
![image](https://user-images.githubusercontent.com/56556686/71578973-a6644080-2afa-11ea-8829-7d8a224c9142.png)

`CLASS /rslt/cx_bs_not_found DEFINITION`
`  PUBLIC`
`  INHERITING FROM /rslt/cx_bs_static_check`
`  CREATE PUBLIC .`

Both are in same package

**Comment by larshp** [comment]
thanks, its a bug, fixing

**Comment by larshp** [comment]
2.20.1 released, try again, the code for determining if its an exception is a workaround, https://github.com/abaplint/abaplint/commit/b19e9980ad86e5b14bad1932fcf23aeb70ff7f52#diff-05346174a87b732059231e09b320d31fR44

There is a lot of things breaking, but its all work in progress, just keep opening issues 😄 🚢

**Comment by jrodriguez-rc** [comment]
Checked and working, thank you!
I have some things prepared and I am trying to help with all I can
