### ISSUE TITLE
ABAP doc for method redefinitions

### ISSUE THREAD

**Issue by hhelibeb** [abaplint/abaplint#719]
abaplint hints 'Missing ABAP Doc for method get_source_position' as below,
![图片](https://user-images.githubusercontent.com/16676760/71801557-42abbb80-3096-11ea-99fa-dc539b596094.png)

But while adding ABAP Doc, ADT hints another warning 'ABAP Doc comments are not allowed for method redefinitions'.

![图片](https://user-images.githubusercontent.com/16676760/71801639-77b80e00-3096-11ea-803d-594663e5d900.png)

**Comment by larshp** [comment]
thanks, looks like a bug

👍

**Comment by hhelibeb** [comment]
@larshp Give me a chance to fix it. I am interested in typescript, but don't have an opportunity to practice... May need more time, but I get some clues now.

**Comment by g-back** [comment]
let us know if you need any pointers 👍

**Comment by hhelibeb** [comment]
> 
> 
> let us know if you need any pointers 👍

Thanks for your support~
I created a pr and waiting for review.
