### ISSUE TITLE
Refactoring: PrefixIsCurrentClass

### ISSUE THREAD

**Issue by g-back** [abaplint/abaplint#721]
Technically, the referenced styleguide section recommends to omit the "me" when calling instance methods, they don't specifically talk about the usage for types/static methods.
To add the "me->" part to this rule, perhaps rename the rule to "references_current_class" or something so it's a bit less specific and make options for what is currently implemented as the default and additionally another option to check "me->" references?

**Comment by larshp** [comment]
yea 👍

**Comment by g-back** [comment]
False positives when used in strings:
![image](https://user-images.githubusercontent.com/27279305/71887213-f3b96100-313d-11ea-9092-bbd7123fe546.png)

**Comment by larshp** [comment]
quick and dirty implementation 😄
