### ISSUE TITLE
may need a basic introduction

### ISSUE THREAD

**Issue by hhelibeb** [abaplint/abaplint#724]
Maybe most visitors can understand [syntax.abaplint.org](https://syntax.abaplint.org/) easily. But to a newbie like me there are some difficulties. 
If it is possible, a legend or a link to some related information will be helpful.

**Comment by larshp** [comment]
moved to "abaplint" instead of "syntax.abaplint.org" repo, syntax is in context of this repo

**Comment by FreHu** [comment]
Can you specify more concretely what is difficult to understand in the diagrams?

**Comment by hhelibeb** [comment]
@FreHu For example, the '1+'.
![图片](https://user-images.githubusercontent.com/16676760/71893823-a06c0080-3187-11ea-98ac-a6275d612a13.png)
And an important issue is that I understand the diagrams intuitively, I believe the diagrams is clear and follow some rules. But I'm not sure if my understand is correctly. For example, at first glance, I understand the symbol below represents the start of a statement,
![图片](https://user-images.githubusercontent.com/16676760/71894183-8848b100-3188-11ea-863b-afc155f88cd0.png)
and then I find another similar thing, I guess it represents the start of a part of a statement,
![图片](https://user-images.githubusercontent.com/16676760/71894292-ca71f280-3188-11ea-9999-1b7370e982f9.png)
But I can't make sure...:sweat_smile: . 
This is just my personal feeling and I don't want you to explain every detail to me. It is not worth.
But I think if there are some explicit introductions or links on related background knowledge to the diagrams will has a positive influence to the visitors like me to understand them easier.

**Comment by FreHu** [comment]
`1+`:
![image](https://user-images.githubusercontent.com/5097067/71895377-37699600-3151-11ea-9a40-ae5b57ac8006.png)

This would mean that you can choose multiple of the options
```
CALL FUNCTION `BLAH` 
    IN BACKGROUND TASK
    IN UPDATE TASK 
    AS SEPARATE UNIT.
```
but in practice not all of the possibilities will compile (like the one above) because the parser is not 100% correct.

**Comment by FreHu** [comment]
And I fully agree that projects should strive to be understandable to newcomers. This is pretty much what try to do around here - improve docs and create simple issues for them to pick up.

**Comment by larshp** [comment]
yea, need to improve(read create) documentation for the overall structure and how `abaplint` works. Its very much work in progress, but some parts have matured enough to build some documentation(but I'm lazy).

For http://syntax.abaplint.org, note that there are 3 categories of diagrams: Structures, Statements and Expressions.

Structures: are made up of other Structures or Statements, example: https://syntax.abaplint.org/#/structure/Case, note the square and rounded edges

Statements: Can contain tokens(terminals) or expressions, https://syntax.abaplint.org/?filter=case#/statement/When

Expressions: Can contain tokens or other expressions, https://syntax.abaplint.org/?filter=case#/expression/InlineData

The remaining boxes is Tokens: contains regex or fixed values, "SOMETHING"

**Comment by hhelibeb** [comment]
Thank you for your helpful replies. I think now it is clear enough to me : )

**Comment by larshp** [comment]
closing, feel free to open new issues with questions and bugs, or alternatively ask in the #abaplint channel on https://abapgit-slackinviter.herokuapp.com/

**Comment by hhelibeb** [comment]
supplement: [railroad diagrams or syntax diagrams.](https://softwareengineering.stackexchange.com/questions/378211/is-there-a-name-for-these-diagrams-that-show-the-flow-of-a-valid-value/378218)
