### ISSUE TITLE
parser_error: string template, alpha

### ISSUE THREAD

**Issue by g-back** [abaplint/abaplint#734]
```abap
m_material = |{ i_material ALPHA = IN }|.
```

**Comment by larshp** [comment]
add in https://syntax.abaplint.org/?filter=string#/expression/StringTemplate, https://github.com/abaplint/abaplint/blob/master/src/abap/expressions/string_template.ts

**Comment by g-back** [comment]
a few other things missing, see: https://help.sap.com/doc/abapdocu_752_index_htm/7.52/en-us/abapcompute_string_format_options.htm

**Comment by FreHu** [comment]
The original reported example was fixed, I suggest updating the description to what is still missing from string templates.

**Comment by larshp** [comment]
yea, or closing this one and opening a new

**Comment by g-back** [comment]
yeah, i'll compile the missing parts sometime in the next few days, closing this one
