### ISSUE TITLE
Generated function groups

### ISSUE THREAD

**Issue by jrodriguez-rc** [abaplint/abaplint#742]
I created new change documents and lock objects, which have generated function groups.

In abaplint.json I set skipGeneratedFunctionGroups and exclude parameter in specific rules:
```json
            "exclude":[
                ".*WRITE*.DOC*",
                "^/RSLT/F.*CD.*$"
            ]
```

But they are checked
![image](https://user-images.githubusercontent.com/56556686/72259884-cb37d800-3611-11ea-80e6-8ba8a789ad9d.png)

**Comment by larshp** [comment]
@jrodriguez-rc sorry, I totally missed this issue, currently the logic checks for a TOBJ object so not function groups generated for change documents

any way to identify this is a function group that is generated?

**Comment by jrodriguez-rc** [comment]
@larshp I also completely forgot it.

This issue can be closed. Since CHDO is supported (https://github.com/larshp/abapGit/pull/3207) those objects are not serialized, only the main CHDO object and others are automatically generated.
