### ISSUE TITLE
keyword_case rule: add option to ignore list of words

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#745]
keyword_case rule: add option to ignore list of words

**Comment by FreHu** [comment]
Do you have a use case for wanting certain keywords in a different case? This is like the one thing people are consistent about.

**Comment by larshp** [comment]
should have added that, sorry

somewhere around ~v750, `TEXT-001` is upper cased by the pretty printer

and on 740 its `text-001`

**Comment by g-back** [comment]
Do you remember the context in which it was shown as an error? Was it in a `SELECTION-SCREEN` statement?

**Comment by larshp** [comment]
yes, it was
