### ISSUE TITLE
bug? "enabled" is not respected anymore

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint#749]
v2.23.2

![image](https://user-images.githubusercontent.com/15635498/72755291-d0c58d00-3bd2-11ea-8787-3719d7c0d23d.png)

abaplint.json
![image](https://user-images.githubusercontent.com/15635498/72755301-da4ef500-3bd2-11ea-9a95-617d65e3fdfd.png)

**Comment by larshp** [comment]
removed in https://github.com/abaplint/abaplint/pull/736

**Comment by sbcgua** [comment]
ah ok ...

P.S. mmm, just a side-thought, guess it would be nice to have some warnings for such cases. To be honest this makes abaplint very unpredictable as a tool. I tend to fix the versions in my projects to avoid constant config issue solving e.g. 2.14 and 2.19 - the ones I'm using. Just a comment ...

**Comment by larshp** [comment]
yea, also noted in the readme, "Regarding versioning: semantic versioning is currently not followed, recommend fixing usage to a specific version"
