### ISSUE TITLE
Unknown object type: CHDO (registry_add)

### ISSUE THREAD

**Issue by jrodriguez-rc** [abaplint/abaplint#758]
CHDO is in a repository used as a dependency (repository A), in the reporitory where the object is (A) linter doesn't raise any error, the error appears in other repository (B) that use it as dependency
`/tmp/abaplint-zxg3bP/src/params/#rslt#bs_0000.chdo.xml[1, 1] - Error: Unknown object type: CHDO (registry_add)`

**Comment by larshp** [comment]
abaplint@2.23.3 published
