### ISSUE TITLE
String Templates: Missing format options

### ISSUE THREAD

**Issue by g-back** [abaplint/abaplint#765]
Missing entirely:
 - [ ] PAD
 - [ ] EXPONENT
 - [ ] DECIMALS
 - [ ] ZERO
 - [ ] XSD
 - [ ] STYLE
 - [ ] CURRENCY
 - [ ] TIMEZONE
 - [ ] COUNTRY

Missing dynamic element( dobj/expr):
 - [ ] ALIGN
 - [ ] SIGN
 - [ ] NUMBER
 - [ ] CASE
 - [ ] ALPHA
 - [ ] DATE
 - [ ] TIME
 - [ ] TIMESTAMP

[Reference Sheet](https://help.sap.com/doc/abapdocu_752_index_htm/7.52/en-us/abapcompute_string_format_options.htm)

**Comment by g-back** [comment]
What's the best way to implement the dynamic part? Just let it take a `Source`? Technically each formatting option has a subset of allowed values (integers for the most part), but I'm not sure how to do this.

**Comment by larshp** [comment]
yea, Source, 

currently there is no approach for implementing type checking

**Comment by g-back** [comment]
Alright, you can assign this to me then!
