### ISSUE TITLE
Misleading message  when "patternkind" is empty

### ISSUE THREAD

**Issue by g-back** [abaplint/abaplint#776]
see https://github.com/larshp/abapOpenChecks/pull/917
I have an idea how to fix, will take a look

**Comment by larshp** [comment]
think I fixed this in one of the checks

**Comment by g-back** [comment]
Yeah I saw, I'm trying to find a more generic approach to avoid it, but unfortunately the rules themselves are mixed in their implementation (some implement IRule, some extend ABAPRule).
Think I'll just quick fix all naming confs and refactor later
