### ISSUE TITLE
parse_error in COND inside LET

### ISSUE THREAD

**Issue by jrodriguez-rc** [abaplint/abaplint#831]
This code raises a parse_error, caused by COND inside the LET statement:

```
rv_info = CONV string(
        LET height_dec  = COND #( WHEN lv_height_unit = 'M'  THEN 2 ELSE 0 )
            weight_dec  = COND #( WHEN lv_weight_unit = 'KG' THEN 1 ELSE 0 )
            height_unit = to_lower( lv_height_unit )
            weight_unit = to_lower( lv_weight_unit )
            height = COND #( WHEN lv_height <> 0
                         THEN |{ 'Height'(001) }: { lv_height NUMBER = USER DECIMALS = height_dec } { height_unit }| )
            weight = COND #( WHEN lv_weight <> 0
                         THEN |{ 'Weight'(002) }: { lv_weight NUMBER = USER DECIMALS = weight_dec } { weight_unit }| )
            IN COND #( WHEN height IS NOT INITIAL AND weight IS NOT INITIAL
                           THEN |{ height } \| { weight }|
                       WHEN height IS NOT INITIAL
                           THEN |{ height }|
                       WHEN weight IS NOT INITIAL
                           THEN |{ weight }| ) ).
```

> Statement does not exist in ABAPv754(or a parser error), "rv_info"(parser_error)

**Comment by larshp** [comment]
reduced to

```abap
data(sdf) = |sdf{ lv_height NUMBER = USER DECIMALS = height_dec }sdf|.
```

in
https://syntax.abaplint.org/?filter=templ#/expression/StringTemplateFormatting
only Integer is currently allowed after DECIMALS

**Comment by g-back** [comment]
could be fixed by adding `Source` to the parameter list, but this can cause errors not to be found (say if the variable contains a string), since we don't have type checks (... or do we?)

**Comment by larshp** [comment]
we dont have type checks as part of the current syntax diagrams

**Comment by jrodriguez-rc** [comment]
> reduced to
> 
> ```abap
> data(sdf) = |sdf{ lv_height NUMBER = USER DECIMALS = height_dec }sdf|.
> ```
> 
> in
> https://syntax.abaplint.org/?filter=templ#/expression/StringTemplateFormatting
> only Integer is currently allowed after DECIMALS

Do you mean this `|{ 'Height'(001) }: { lv_height NUMBER = USER DECIMALS = height_dec } { height_unit }|`?

I'm using text pool `{ 'Height'(001) }` to use translations from the text pool

**Comment by larshp** [comment]
@jrodriguez-rc the ABAP code is okay, there is a bug in abaplint

**Comment by larshp** [comment]
regarding types, note that ABAP has a lot of implicit conversions, following runs without problems

```abap
  DATA(lv_height) = 2.
  DATA(sdf1) = |{ lv_height NUMBER = USER DECIMALS = '2' }|.
  DATA(sdf2) = |{ lv_height NUMBER = USER DECIMALS = `2` }|.
  DATA(sdf3) = |{ lv_height NUMBER = USER DECIMALS = '2' + 1 }|.
```

only something like
```abap
DATA(sdf4) = |{ lv_height NUMBER = USER DECIMALS = 'A' }|.
```
dumps, but it dumps at runtime, no syntax errors or warnings

**Comment by larshp** [comment]
@jrodriguez-rc try again, 2.32.1 released

**Comment by jrodriguez-rc** [comment]
[Playground](https://playground.abaplint.org/) is ok, but GitLab pipeline still fails
![image](https://user-images.githubusercontent.com/56556686/79240279-dc42f000-7e71-11ea-9ece-092762626a9e.png)

**Comment by larshp** [comment]
did it install version 2.32.1? should say somewhere higher in the log

**Comment by jrodriguez-rc** [comment]
Right, I was using an old version from npmjs. Changed not works ok. Thanks!
