### ISSUE TITLE
Class implementation for "lcx_error" not found (implement_methods)

### ISSUE THREAD

**Issue by flaiker** [abaplint/abaplint#843]
```abap
CLASS lcx_error DEFINITION INHERITING FROM /abc/cx_local_error.
ENDCLASS.
```

An implementation is not needed as there is no changed behaviour or to be implemented abstract methods of the super class. The super class is abstract to prevent reuse or global use of the exception class intended for reports and UI.

**Comment by flaiker** [comment]
Looking at the next message I'll probably disable the rule altogether as I don't intend to use the dependency feature. "Implemented interface "IF_F4CALLBACK_VALUE_REQUEST" not found (implement_methods)"

**Comment by larshp** [comment]
try again, 2.76.6

**Comment by flaiker** [comment]
Seems to be fixed, thanks!
