### ISSUE TITLE
Parser error for SELECT statements with CASE

### ISSUE THREAD

**Issue by flaiker** [abaplint/abaplint#855]
Updated to 2.32.8

> Statement does not exist in ABAPv740sp08(or a parser error), "SELECT" (parser_error)

```abap
      SELECT mwskz AS tax_code,
             CASE shkzg
               WHEN 'H' THEN ABS( fwste )
               WHEN 'S' THEN ABS( fwste ) * -1
             END AS tax_amount_dc,
             CASE shkzg
               WHEN 'H' THEN ABS( hwste )
               WHEN 'S' THEN ABS( hwste ) * -1
             END AS tax_amount_lc,
             CASE shkzg
               WHEN 'H' THEN ABS( fwbas )
               WHEN 'S' THEN ABS( fwbas ) * -1
             END AS tax_base_amount_dc,
             CASE shkzg
               WHEN 'H' THEN ABS( hwbas )
               WHEN 'S' THEN ABS( hwbas ) * -1
             END AS tax_base_amount_lc
        FROM bset
        WHERE bukrs = @is_doc_key-company_code
          AND gjahr = @is_doc_key-fiscal_year
          AND belnr = @is_doc_key-document_number
        ORDER BY tax_code
        INTO CORRESPONDING FIELDS OF TABLE @lt_document_tax_data.
```

**Comment by flaiker** [comment]
Also got `Identifiers should be lower case: "CASE" (keyword_case)` for a simliar SELECT statement with CASE.

**Comment by larshp** [comment]
yea, it probably guesses CASE is a table column name

**Comment by larshp** [comment]
simple CASE added in https://github.com/abaplint/abaplint/pull/1520,
abs() added in https://github.com/abaplint/abaplint/pull/1520

still need a few updates for above example to work

**Comment by larshp** [comment]
now parses, but false positive "ABS" should be lower case...

**Comment by larshp** [comment]
@flaiker try again, latest version

**Comment by flaiker** [comment]
Hmm, I don't think this works yet. Only tested in playground so far. With target 755 I get `/zfoobar.prog.abap[1, 1]: Expected ENDCLASS(structure)`. With target 740sp08 I also get `/zfoobar.prog.abap[20, 29]: Identifiers should be lower case: "ABS"(keyword_case)`.

Dummy report that doesn't compile but should be fine for the test case I think?

```abap
REPORT zfoobar.

CLASS lcl_main DEFINITION.
  TYPES:
    BEGIN OF ty_doc_key,
      company_code    TYPE bukrs,
      document_number TYPE belnr_d,
      fiscal_year     TYPE gjahr_d,
    END OF ty_doc_key.
  METHODS:
    run IMPORTING is_doc_key TYPE ty_doc_key OPTIONAL.
ENDCLASS.

CLASS lcl_main IMPLEMENTATION.
  METHOD run.
    DATA: lt_document_tax_data TYPE STANDARD TABLE OF dummy.

    SELECT mwskz AS tax_code,
            CASE shkzg
              WHEN 'H' THEN ABS( fwste )
              WHEN 'S' THEN ABS( fwste ) * -1
            END AS tax_amount_dc,
            CASE shkzg
              WHEN 'H' THEN ABS( hwste )
              WHEN 'S' THEN ABS( hwste ) * -1
            END AS tax_amount_lc,
            CASE shkzg
              WHEN 'H' THEN ABS( fwbas )
              WHEN 'S' THEN ABS( fwbas ) * -1
            END AS tax_base_amount_dc,
            CASE shkzg
              WHEN 'H' THEN ABS( hwbas )
              WHEN 'S' THEN ABS( hwbas ) * -1
            END AS tax_base_amount_lc
      FROM bset
      WHERE bukrs = @is_doc_key-company_code
        AND gjahr = @is_doc_key-fiscal_year
        AND belnr = @is_doc_key-document_number
      ORDER BY tax_code
      INTO CORRESPONDING FIELDS OF TABLE @lt_document_tax_data.
    IF sy-subrc <> 0.
      WRITE 'Error'.
    ENDIF.
  ENDMETHOD.
ENDCLASS.

START-OF-SELECTION.
  NEW lcl_main( )->run( ).
```

**Comment by larshp** [comment]
@flaiker `PUBLIC SECTION.` missing in the example

**Comment by flaiker** [comment]
Thanks, now it works with target 755. On 740sp08 I get:
```
/zfoobar.prog.abap[19, 5]: "fwste" not found, findTop(check_syntax)
/zfoobar.prog.abap[21, 28]: Identifiers should be lower case: "ABS"(keyword_case)
```

**Comment by larshp** [comment]
`ABS` was introduced in 751 AFAIK

**Comment by flaiker** [comment]
I'll have to disagree on that, the example in the opening post compiles on 740sp20. ABS is found in the 740 keyword documentation: https://help.sap.com/doc/abapdocu_740_index_htm/7.40/en-US/abensql_arith_func.htm

**Comment by larshp** [comment]
okay, then I need to get https://syntax.abaplint.org/?filter=sql#/expression/SQLFunction updated, help.sap.com is down at the moment :(

**Comment by larshp** [comment]
https://blogs.sap.com/2014/02/06/abap-news-for-release-740-sp05/ ?

in the above comment did you mean "740sp02" instead of "740sp20"?

**Comment by flaiker** [comment]
I cannot narrow down the version all that much, the system with the example is on 740sp20. I cannot recall if that feature worked on sp05 but according to the blog you linked it looks like it did.

**Comment by larshp** [comment]
@flaiker try again 2.80.10,

![image](https://user-images.githubusercontent.com/5888506/141927741-44155f99-f98a-4260-b83b-923c30c4c7e6.png)

**Comment by flaiker** [comment]
That works, thanks!
