### ISSUE TITLE
prefer_returning_to_exporting: Does it make sense for generic types?

### ISSUE THREAD

**Issue by flaiker** [abaplint/abaplint#869]
I have this method:
```abap
  METHODS:
    get_next_single IMPORTING iv_number_range TYPE nrnr
                              iv_subobject    TYPE nrsobj OPTIONAL
                    EXPORTING eg_number       TYPE clike
                    RAISING   /abc/cx_some_exception_class.
...
  METHOD get_next_single.
    CALL FUNCTION 'NUMBER_GET_NEXT'
      EXPORTING
        nr_range_nr             = iv_number_range
        object                  = mv_number_range_obj_name
        quantity                = '1'
        subobject               = iv_subobject
      IMPORTING
        number                  = eg_number
      EXCEPTIONS
        interval_not_found      = 1
        number_range_not_intern = 2
        object_not_found        = 3
        quantity_is_0           = 4
        quantity_is_not_1       = 5
        interval_overflow       = 6
        buffer_overflow         = 7
        OTHERS                  = 8.
    IF sy-subrc <> 0.
      RAISE EXCEPTION TYPE /abc/cx_some_exception_class
        EXPORTING
          is_msg                 = /abc/cl_some_tool=>get_msg_from_sy( )
          iv_number_range_object = mv_number_range_obj_name
          iv_number_range        = iv_number_range.
    ENDIF.
  ENDMETHOD.
```

which gets reported by prefer_returning_to_exporting. I would like to keep the exporting parameter since it allows the actual type of the result variable to be defined by the caller and use CLIKE in the interface. Otherwise I would have to return a string (since RETURNING does not allow generic types) and hope there is no conversion edge case.

But maybe I am also a bit paranoid in regards to implicit type conversions.

**Comment by larshp** [comment]
no it doesnt, should skip if its a generic type

https://github.com/abaplint/abaplint/blob/dca5fd629c71b8dea3349d36b894796b159122ab/packages/core/src/rules/prefer_returning_to_exporting.ts#L63

**Comment by larshp** [comment]
plus XSEQUENCE

**Comment by flaiker** [comment]
> plus XSEQUENCE

I'd say any of these:

https://help.sap.com/doc/abapdocu_754_index_htm/7.54/en-US/index.htm?file=abenbuilt_in_types_generic.htm

**Comment by larshp** [comment]
2.32.10 published
