### ISSUE TITLE
Parse error Statement does not exist

### ISSUE THREAD

**Issue by jrodriguez-rc** [abaplint/abaplint#883]
Hi, I'm getting a parse error with this sentence:
```
        ri_entity_object = CAST #( LET collectors = get_collectors( )
                                        IN collectors[ type = iv_type ]-collector ).
```
![image](https://user-images.githubusercontent.com/56556686/82320658-eeb1cb80-99d3-11ea-919a-1d24278dd967.png)

**Comment by larshp** [comment]
thanks 👍

**Comment by larshp** [comment]
starting this

**Comment by larshp** [comment]
@jrodriguez-rc try again, 2.32.24 released

fixed with https://github.com/abaplint/abaplint/commit/afddc6a795ef916e56d012ae9626b9be0c100f1c#diff-638b20b877914b83f98e03a1f880d093R15

**Comment by jrodriguez-rc** [comment]
Worked fine, thanks!
