### ISSUE TITLE
rule contains_tab: report correct position instead of remaining line

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#936]
rule contains_tab: report correct position instead of remaining line

very change similar to https://github.com/abaplint/abaplint/pull/900

**Comment by g-back** [comment]
For the quick fix, just remove the tab?
There's a max of one reported finding per line - would have to run a quick fix multiple times. Leave it as is or report all findings?

**Comment by larshp** [comment]
quick fix: suggest replacing the tab with space, or else it might become a syntax error

report only one finding per line, perhaps add so if there are more sequential tabs that they are reported in the same issue
