### ISSUE TITLE
rule: don't overwrite built-in SAP functions in classes

### ISSUE THREAD

**Issue by g-back** [abaplint/abaplint#944]
Defining a method with the same name as a predefined function overwrites it in the class scope

see for overview:
https://help.sap.com/doc/abapdocu_752_index_htm/7.52/en-us/abenbuilt_in_functions_overview.htm

**Comment by larshp** [comment]
started listing some of the builtin functions in https://github.com/abaplint/abaplint/blob/cd66c3d72e4d2ca24af5cec1ff190c8956769255/packages/core/src/abap/5_syntax/_builtin.ts#L76

**Comment by larshp** [comment]
this should be pretty easy, for each object get the `ABAPFile->getInfo()` it contains the class and interface definitions with method names
