### ISSUE TITLE
Code Inspector ignore  pragma comments

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#961]
Noticed that the pragma comments for Code Inspector generate warnings.

![image](https://user-images.githubusercontent.com/53995991/84498162-65c74080-acb0-11ea-8620-353374a368b2.png)

The comments need to be on the line of the statement to exclude if from certain checks.

There are several prefixes to trigger this behavior:

- #EC <topic>  - Extended Check
- ##<topic> - [Pragmas](https://help.sap.com/doc/abapdocu_751_index_htm/7.51/en-US/index.htm?file=abenpragma.htm)

**Comment by larshp** [comment]
yea, looks like a bug, thanks

**Comment by larshp** [comment]
hmm, but above `"##MG_MISSING` is a commented pragma? `##MG_MISSING` is a pragma

EC ok,
![image](https://user-images.githubusercontent.com/5888506/84503103-d9ba1680-acb9-11ea-8a2c-da8d8a861d17.png)

**Comment by ed-holland** [comment]
In 700 the pragma are limited. SAP wanted me to follow a certain ATC specification for which the newer Pragma's are required. So i needed to add the newer once as comments which still works fine for ATC

**Comment by larshp** [comment]
any official or semi-official documentation on this approach?

**Comment by larshp** [comment]
its no trouble adding it as an exception in this rule, just some of the other stuff will need to know the real pragmas

**Comment by larshp** [comment]
@ed-holland try again, latest version

**Comment by ed-holland** [comment]
Working nicely. Thanks.

**Comment by ed-holland** [comment]
Does abapLint have it's own Pragma's?

As to the official Pragma's and their positioning:

`A pragma applies to the current statement, that is, for the statement that ends at the next "." or ",". Pragmas in front of the ":" of a chained statement apply to the whole chained statement. Pragmas that occur when calling a macro apply to all statements of the macro.

Pragmas must only occur at certain positions in the source code for reasons of readability:

at the start of a line, after any number of blanks
at the end of a line, at the most followed by ".", ",", or ":".
but not after ".", ",", or ":".
Multiple pragmas may be entered one after another (separated by blanks) at permitted positions.
Unknown pragmas or pragmas with formal errors or pragmas in the wrong position or with incorrect parameters themselves produce syntax warnings. Pragmas in the wrong position for syntax check warnings are ignored.
`

[751](https://help.sap.com/doc/abapdocu_751_index_htm/7.51/de-DE/abenpragma.htm)

**Comment by larshp** [comment]
no, no custom abaplint pragmas for now, I'm trying to have few false positives which will remove the need for pragmas

and abaplint will use the pragmas already defined by SAP, eg.

`DATA foo TYPE i ##NEEDED.`

But as far as I understand, for it to work on 700 you have this:
`DATA foo TYPE i. "##NEEDED`
which is not a real pragma according to the documentation you've linked above?

**Comment by ed-holland** [comment]
Yes, the pragma will not work in 700 (requiring it to be comment). But it will work if the code is checked in a newer release. Showing a clean bill when the company is doing ATC checks.

Found this Abap: ABAP_SLIN_PRAGMAS (it shows all the pragma's)
