### ISSUE TITLE
Checking namespace objects

### ISSUE THREAD

**Issue by ed-holland** [abaplint/abaplint#963]
We use two namespaces and i've added them to the config file in this way

"^(\/JCS\/|\/REDWOOD\/|LT?CL_|TY_|LIF_)

Visual code still thinks it is bad
![image](https://user-images.githubusercontent.com/53995991/84520504-f8c5a200-acd3-11ea-9a25-cdbbf2900ae4.png)

Did i use the wrong specification?

**Comment by larshp** [comment]
try escaping the "/"'es, its a javascipt regex

https://regex101.com
![image](https://user-images.githubusercontent.com/5888506/84521068-ca949200-acd4-11ea-9dff-a4915135f6cc.png)

**Comment by ed-holland** [comment]
I escaped it already (using the same online test... but somehow in here it was removed.

![image](https://user-images.githubusercontent.com/53995991/84523544-c2d6ec80-acd8-11ea-90fa-9109b81f9115.png)

Tried also the // escaping. Still the same result.
![image](https://user-images.githubusercontent.com/53995991/84523763-30831880-acd9-11ea-82f7-0650dd511657.png)

**Comment by larshp** [comment]
try double escaping, `\\/` since its a javascript string

**Comment by ed-holland** [comment]
Nope, same result.

**Comment by larshp** [comment]
okay, the top error is from the https://rules.abaplint.org/object_naming/ rule, which has its own settings, not related to the `errorNamespace`

**Comment by ed-holland** [comment]
Worked nicely using `"prog": "^\/JCS\/",`
