### ISSUE TITLE
How to add dependencies to repo

### ISSUE THREAD

**Issue by mbtools** [abaplint/abaplint#972]
I have generated deps using ZABAPGIT_DEPS into repo 2. My main repo 1 is private so using the abaplint.json "dependencies" > "url" setting does not work (unless I make repo 2 public, I guess).

I'm trying to use "dependencies" > "folder". I copied the generated files from repo2/src to repo1/deps. However, my abaplint action does not seem to find the dependencies. Is my setup correct?

**Comment by larshp** [comment]
in the `repo1/` folder do "git clone http://repo2 repo2"

you can also test it locally

depending on the CI setup, there are multiple ways to clone a private repo

**Comment by mbtools** [comment]
Always helps to read the code... /packages/cli/src/cli.ts

Now I see that the "dependencies" > "files" is also appended to the local "dependencies" > "folder" settings (not just the remote url). I had my files directly in /deps but abaplint is looking for files with /deps/src/**/*.* 

On my dream list is to integrate it into abapGit out of the box:
- UI to maintain the abaplint.json settings
- Menu item to generate the dependencies into the same repo on demand

**Comment by larshp** [comment]
also make sure to try https://github.com/abaplint/abaplint-abap-backend

maintain: I'd recommend using vscode to edit the abaplint.json files, it knows about the schema, https://schema.abaplint.org/schema.json, alternatively build a web based editor, much like editing settings in vscode works
