### ISSUE TITLE
Comments in abaplint config (json5?)

### ISSUE THREAD

**Issue by sbcgua** [abaplint/abaplint#999]
What about allowing comments in abaplint.json.

E.g. switching to this for the parsing: https://github.com/json5/json5

P.S. or even yaml ... though it is a more revolutionary change

**Comment by larshp** [comment]
there is a `reason` field for each rule which can contain free text,
![image](https://user-images.githubusercontent.com/5888506/85941743-f777b480-b924-11ea-8f14-e57d20f3544c.png)

also considered adding jsonc parsing, https://github.com/abaplint/abaplint/issues/507

**Comment by sbcgua** [comment]
Hmm. Is the `reason` used anyhow else ? I mean this is more readable

```json
"avoid_use": false, // according to our corporate coding style ...
```

than leaving the whole object in place. Imho.



jsonc vs json5: yeah I guess both will do. But json5 also have some extra features e.g. allow array trailing comma, which is very convenient

P.S. shell I close the issue as a duplicate ? or let it hang here for the "reason" matter ?

**Comment by sbcgua** [comment]
... and filling the reason does not disable the rule by the way. Was "enable" deprecated ?

**Comment by larshp** [comment]
yea, enable was deprecated

guess there is no way to fill the reason while leaving the rule disabled :(

**Comment by sbcgua** [comment]
:)) OK ... I'll close this one and move the comments to #507 . Would you mind adding json5 to the #507 description too ? (I don't have rights)

**Comment by larshp** [comment]
@sbcgua try again, you should have more access now :)

**Comment by sbcgua** [comment]
yeah, thanks ! fixes the description, added a comment
